function initstacks_unet_b(c1, c2, c3, c_in)
    xpad0_stack = Vector{Float64}(undef, (div(n_xpad0 - 1, 1) + 1) + (div(c_in * hw - 1, 1) + 1))
    t_e1_stack = Vector{Float64}(undef, (div(c1 * hw - 1, 1) + 1) + (div(n_e1_mid - 1, 1) + 1))
    t_e1pad_stack = Vector{Float64}(undef, (div(n_e1_midpad - 1, 1) + 1) + (div(c1 * hw - 1, 1) + 1))
    skip1_stack = Vector{Float64}(undef, (div(c1 * hw - 1, 1) + 1) + (div(n_e1_out - 1, 1) + 1))
    a11_stack = Vector{Float64}(undef, ((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1)
    a12_stack = Vector{Float64}(undef, ((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1)
    a21_stack = Vector{Float64}(undef, ((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1)
    a22_stack = Vector{Float64}(undef, ((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1)
    m1_stack = Vector{Float64}(undef, ((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1)
    m2_stack = Vector{Float64}(undef, ((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1)
    p1pad_stack = Vector{Float64}(undef, (div(n_p1pad - 1, 1) + 1) + (div(c1 * hw2 - 1, 1) + 1))
    t_e2_stack = Vector{Float64}(undef, (div(c2 * hw2 - 1, 1) + 1) + (div(n_e2_mid - 1, 1) + 1))
    t_e2pad_stack = Vector{Float64}(undef, (div(n_e2_midpad - 1, 1) + 1) + (div(c2 * hw2 - 1, 1) + 1))
    skip2_stack = Vector{Float64}(undef, (div(c2 * hw2 - 1, 1) + 1) + (div(n_e2_out - 1, 1) + 1))
    p2pad_stack = Vector{Float64}(undef, (div(n_p2pad - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1))
    t_b_stack = Vector{Float64}(undef, (div(c3 * hw4 - 1, 1) + 1) + (div(n_b_mid - 1, 1) + 1))
    t_bpad_stack = Vector{Float64}(undef, (div(n_b_midpad - 1, 1) + 1) + (div(c3 * hw4 - 1, 1) + 1))
    bott_stack = Vector{Float64}(undef, (div(c3 * hw4 - 1, 1) + 1) + (div(n_b_out - 1, 1) + 1))
    cat2pad_stack = Vector{Float64}(undef, (div(n_cat2pad - 1, 1) + 1) + (div(c32 * hw2 - 1, 1) + 1))
    t_d2_stack = Vector{Float64}(undef, (div(c2 * hw2 - 1, 1) + 1) + (div(n_d2_mid - 1, 1) + 1))
    t_d2pad_stack = Vector{Float64}(undef, (div(n_d2_midpad - 1, 1) + 1) + (div(c2 * hw2 - 1, 1) + 1))
    dec2out_stack = Vector{Float64}(undef, (div(c2 * hw2 - 1, 1) + 1) + (div(n_d2_out - 1, 1) + 1))
    cat1pad_stack = Vector{Float64}(undef, (div(n_cat1pad - 1, 1) + 1) + (div(c21 * hw - 1, 1) + 1))
    t_d1_stack = Vector{Float64}(undef, (div(c1 * hw - 1, 1) + 1) + (div(n_d1_mid - 1, 1) + 1))
    t_d1pad_stack = Vector{Float64}(undef, (div(n_d1_midpad - 1, 1) + 1) + (div(c1 * hw - 1, 1) + 1))
    dec1out_stack = Vector{Float64}(undef, (div(c1 * hw - 1, 1) + 1) + (div(n_d1_out - 1, 1) + 1))
    return (xpad0_stack, t_e1_stack, t_e1pad_stack, skip1_stack, a11_stack, a12_stack, a21_stack, a22_stack, m1_stack, m2_stack, p1pad_stack, t_e2_stack, t_e2pad_stack, skip2_stack, p2pad_stack, t_b_stack, t_bpad_stack, bott_stack, cat2pad_stack, t_d2_stack, t_d2pad_stack, dec2out_stack, cat1pad_stack, t_d1_stack, t_d1pad_stack, dec1out_stack)
end

function unet_hv(x, xb, h, w, c_in, c1, c2, c3, c_out, w_e1a, w_e1ab, b_e1a, b_e1ab, w_e1b, w_e1bb, b_e1b, b_e1bb, w_e2a, w_e2ab, b_e2a, b_e2ab, w_e2b, w_e2bb, b_e2b, b_e2bb, w_ba, w_bab, b_ba, b_bab, w_bb, w_bbb, b_bb, b_bbb, w_d2a, w_d2ab, b_d2a, b_d2ab, w_d2b, w_d2bb, b_d2b, b_d2bb, w_d1a, w_d1ab, b_d1a, b_d1ab, w_d1b, w_d1bb, b_d1b, b_d1bb, w_out, w_outb, b_out, b_outb, xpad0, xpad0b, t_e1, t_e1b, t_e1pad, t_e1padb, skip1, skip1b, p1, p1b, p1pad, p1padb, t_e2, t_e2b, t_e2pad, t_e2padb, skip2, skip2b, p2, p2b, p2pad, p2padb, t_b, t_bb, t_bpad, t_bpadb, bott, bottb, u2, u2b, cat2, cat2b, cat2pad, cat2padb, t_d2, t_d2b, t_d2pad, t_d2padb, dec2out, dec2outb, u1, u1b, cat1, cat1b, cat1pad, cat1padb, t_d1, t_d1b, t_d1pad, t_d1padb, dec1out, dec1outb, y, yb, xd, xbd, w_e1ad, w_e1abd, b_e1ad, b_e1abd, w_e1bd, w_e1bbd, b_e1bd, b_e1bbd, w_e2ad, w_e2abd, b_e2ad, b_e2abd, w_e2bd, w_e2bbd, b_e2bd, b_e2bbd, w_bad, w_babd, b_bad, b_babd, w_bbd, w_bbbd, b_bbd, b_bbbd, w_d2ad, w_d2abd, b_d2ad, b_d2abd, w_d2bd, w_d2bbd, b_d2bd, b_d2bbd, w_d1ad, w_d1abd, b_d1ad, b_d1abd, w_d1bd, w_d1bbd, b_d1bd, b_d1bbd, w_outd, w_outbd, b_outd, b_outbd, xpad0d, xpad0bd, t_e1d, t_e1bd, t_e1padd, t_e1padbd, skip1d, skip1bd, p1d, p1bd, p1padd, p1padbd, t_e2d, t_e2bd, t_e2padd, t_e2padbd, skip2d, skip2bd, p2d, p2bd, p2padd, p2padbd, t_bd, t_bbd, t_bpadd, t_bpadbd, bottd, bottbd, u2d, u2bd, cat2d, cat2bd, cat2padd, cat2padbd, t_d2d, t_d2bd, t_d2padd, t_d2padbd, dec2outd, dec2outbd, u1d, u1bd, cat1d, cat1bd, cat1padd, cat1padbd, t_d1d, t_d1bd, t_d1padd, t_d1padbd, dec1outd, dec1outbd, yd, ybd, xpad0_stack, t_e1_stack, t_e1pad_stack, skip1_stack, a11_stack, a12_stack, a21_stack, a22_stack, m1_stack, m2_stack, p1pad_stack, t_e2_stack, t_e2pad_stack, skip2_stack, p2pad_stack, t_b_stack, t_bpad_stack, bott_stack, cat2pad_stack, t_d2_stack, t_d2pad_stack, dec2out_stack, cat1pad_stack, t_d1_stack, t_d1pad_stack, dec1out_stack)
    xpad0_stack_d = Vector{Float64}(undef, length(xpad0_stack))
    t_e1_stack_d = Vector{Float64}(undef, length(t_e1_stack))
    t_e1pad_stack_d = Vector{Float64}(undef, length(t_e1pad_stack))
    skip1_stack_d = Vector{Float64}(undef, length(skip1_stack))
    a11_stack_d = Vector{Float64}(undef, length(a11_stack))
    a12_stack_d = Vector{Float64}(undef, length(a12_stack))
    a21_stack_d = Vector{Float64}(undef, length(a21_stack))
    a22_stack_d = Vector{Float64}(undef, length(a22_stack))
    m1_stack_d = Vector{Float64}(undef, length(m1_stack))
    m2_stack_d = Vector{Float64}(undef, length(m2_stack))
    p1pad_stack_d = Vector{Float64}(undef, length(p1pad_stack))
    t_e2_stack_d = Vector{Float64}(undef, length(t_e2_stack))
    t_e2pad_stack_d = Vector{Float64}(undef, length(t_e2pad_stack))
    skip2_stack_d = Vector{Float64}(undef, length(skip2_stack))
    p2pad_stack_d = Vector{Float64}(undef, length(p2pad_stack))
    t_b_stack_d = Vector{Float64}(undef, length(t_b_stack))
    t_bpad_stack_d = Vector{Float64}(undef, length(t_bpad_stack))
    bott_stack_d = Vector{Float64}(undef, length(bott_stack))
    cat2pad_stack_d = Vector{Float64}(undef, length(cat2pad_stack))
    t_d2_stack_d = Vector{Float64}(undef, length(t_d2_stack))
    t_d2pad_stack_d = Vector{Float64}(undef, length(t_d2pad_stack))
    dec2out_stack_d = Vector{Float64}(undef, length(dec2out_stack))
    cat1pad_stack_d = Vector{Float64}(undef, length(cat1pad_stack))
    t_d1_stack_d = Vector{Float64}(undef, length(t_d1_stack))
    t_d1pad_stack_d = Vector{Float64}(undef, length(t_d1pad_stack))
    dec1out_stack_d = Vector{Float64}(undef, length(dec1out_stack))
    a11 = 0.0
    a12 = 0.0
    a21 = 0.0
    a22 = 0.0
    m1 = 0.0
    m2 = 0.0
    s = 0.0
    a11b = 0.0
    a12b = 0.0
    a21b = 0.0
    a22b = 0.0
    m1b = 0.0
    m2b = 0.0
    sb = 0.0
    a11d = 0.0
    a11bd = 0.0
    a12d = 0.0
    a12bd = 0.0
    a21d = 0.0
    a21bd = 0.0
    a22d = 0.0
    a22bd = 0.0
    m1d = 0.0
    m1bd = 0.0
    m2d = 0.0
    m2bd = 0.0
    sd = 0.0
    sbd = 0.0
    zero_vald = 0.0
    zero_valbd = 0.0
    two = 2
    four = 4
    h2 = div(h, two)
    w2 = div(w, two)
    h4 = div(h, four)
    w4 = div(w, four)
    hp1 = h + 2
    wp1 = w + 2
    hp2 = h2 + 2
    wp2 = w2 + 2
    hp4 = h4 + 2
    wp4 = w4 + 2
    pad = 1
    kh = 3
    kw = 3
    khkw = kh * kw
    kh_out = 1
    kw_out = 1
    khkw_out = kh_out * kw_out
    scale = 2
    zero_vald = 0.0
    zero_val = 0.0
    c32 = c3 + c2
    c21 = c2 + c1
    hw = h * w
    hw2 = h2 * w2
    hw4 = h4 * w4
    n_xpad0 = c_in * hp1 * wp1
    n_e1_mid = c1 * hw
    n_e1_midpad = c1 * hp1 * wp1
    n_e1_out = c1 * hw
    n_p1pad = c1 * hp2 * wp2
    n_e2_mid = c2 * hw2
    n_e2_midpad = c2 * hp2 * wp2
    n_e2_out = c2 * hw2
    n_p2pad = c2 * hp4 * wp4
    n_b_mid = c3 * hw4
    n_b_midpad = c3 * hp4 * wp4
    n_b_out = c3 * hw4
    n_cat2pad = c32 * hp2 * wp2
    n_d2_mid = c2 * hw2
    n_d2_midpad = c2 * hp2 * wp2
    n_d2_out = c2 * hw2
    n_cat1pad = c21 * hp1 * wp1
    n_d1_mid = c1 * hw
    n_d1_midpad = c1 * hp1 * wp1
    n_d1_out = c1 * hw
    for i = 1:n_xpad0
        xpad0_stack_d[(i - 1) + 1] = xpad0d[i]
        xpad0_stack[(i - 1) + 1] = xpad0[i]
        xpad0d[i] = zero_vald
        xpad0[i] = zero_val
    end
    for idx = 1:c_in * hw
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        yi = (ci - 1) * hp1 * wp1 + ((i + pad) - 1) * wp1 + (j + pad)
        xpad0_stack_d[(div(n_xpad0 - 1, 1) + 1) + ((idx - 1) + 1)] = xpad0d[yi]
        xpad0_stack[(div(n_xpad0 - 1, 1) + 1) + ((idx - 1) + 1)] = xpad0[yi]
        xpad0d[yi] = xd[idx]
        xpad0[yi] = x[idx]
    end
    for idx = 1:c1 * hw
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        sd = 0.0
        s = 0.0
        for i_seq_k = 1:c_in * khkw
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp1 * wp1 + (row - 1) * wp1 + col
            wi = (((co - 1) * c_in + (ci - 1)) * kh + (ki - 1)) * kw + kj
            sd = sd + (w_e1a[wi] * xpad0d[xi] + xpad0[xi] * w_e1ad[wi])
            s = s + xpad0[xi] * w_e1a[wi]
        end
        t_e1_stack_d[(idx - 1) + 1] = t_e1d[idx]
        t_e1_stack[(idx - 1) + 1] = t_e1[idx]
        t_e1d[idx] = sd + b_e1ad[co]
        t_e1[idx] = s + b_e1a[co]
    end
    for i = 1:n_e1_mid
        t_e1_stack_d[(div(c1 * hw - 1, 1) + 1) + ((i - 1) + 1)] = t_e1d[i]
        t_e1_stack[(div(c1 * hw - 1, 1) + 1) + ((i - 1) + 1)] = t_e1[i]
        t_e1d[i] = (0.5 * (1.0 + sign(t_e1[i] - zero_val))) * t_e1d[i] + (0.5 * (1.0 + sign(zero_val - t_e1[i]))) * zero_vald
        t_e1[i] = max(t_e1[i], zero_val)
    end
    for i = 1:n_e1_midpad
        t_e1pad_stack_d[(i - 1) + 1] = t_e1padd[i]
        t_e1pad_stack[(i - 1) + 1] = t_e1pad[i]
        t_e1padd[i] = zero_vald
        t_e1pad[i] = zero_val
    end
    for idx = 1:c1 * hw
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        yi = (ci - 1) * hp1 * wp1 + ((i + pad) - 1) * wp1 + (j + pad)
        t_e1pad_stack_d[(div(n_e1_midpad - 1, 1) + 1) + ((idx - 1) + 1)] = t_e1padd[yi]
        t_e1pad_stack[(div(n_e1_midpad - 1, 1) + 1) + ((idx - 1) + 1)] = t_e1pad[yi]
        t_e1padd[yi] = t_e1d[idx]
        t_e1pad[yi] = t_e1[idx]
    end
    for idx = 1:c1 * hw
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        sd = 0.0
        s = 0.0
        for i_seq_k = 1:c1 * khkw
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp1 * wp1 + (row - 1) * wp1 + col
            wi = (((co - 1) * c1 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            sd = sd + (w_e1b[wi] * t_e1padd[xi] + t_e1pad[xi] * w_e1bd[wi])
            s = s + t_e1pad[xi] * w_e1b[wi]
        end
        skip1_stack_d[(idx - 1) + 1] = skip1d[idx]
        skip1_stack[(idx - 1) + 1] = skip1[idx]
        skip1d[idx] = sd + b_e1bd[co]
        skip1[idx] = s + b_e1b[co]
    end
    for i = 1:n_e1_out
        skip1_stack_d[(div(c1 * hw - 1, 1) + 1) + ((i - 1) + 1)] = skip1d[i]
        skip1_stack[(div(c1 * hw - 1, 1) + 1) + ((i - 1) + 1)] = skip1[i]
        skip1d[i] = (0.5 * (1.0 + sign(skip1[i] - zero_val))) * skip1d[i] + (0.5 * (1.0 + sign(zero_val - skip1[i]))) * zero_vald
        skip1[i] = max(skip1[i], zero_val)
    end
    for idx = 1:c1 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        oi = div(rem, w2) + 1
        oj = mod(rem, w2) + 1
        i0 = 2oi - 1
        j0 = 2oj - 1
        a11_stack_d[(idx - 1) + 1] = a11d
        a11_stack[(idx - 1) + 1] = a11
        a11d = skip1d[(ci - 1) * hw + (i0 - 1) * w + j0]
        a11 = skip1[(ci - 1) * hw + (i0 - 1) * w + j0]
        a12_stack_d[(idx - 1) + 1] = a12d
        a12_stack[(idx - 1) + 1] = a12
        a12d = skip1d[(ci - 1) * hw + (i0 - 1) * w + j0 + 1]
        a12 = skip1[(ci - 1) * hw + (i0 - 1) * w + j0 + 1]
        a21_stack_d[(idx - 1) + 1] = a21d
        a21_stack[(idx - 1) + 1] = a21
        a21d = skip1d[(ci - 1) * hw + i0 * w + j0]
        a21 = skip1[(ci - 1) * hw + i0 * w + j0]
        a22_stack_d[(idx - 1) + 1] = a22d
        a22_stack[(idx - 1) + 1] = a22
        a22d = skip1d[(ci - 1) * hw + i0 * w + j0 + 1]
        a22 = skip1[(ci - 1) * hw + i0 * w + j0 + 1]
        m1_stack_d[(idx - 1) + 1] = m1d
        m1_stack[(idx - 1) + 1] = m1
        m1d = (0.5 * (1.0 + sign(a11 - a12))) * a11d + (0.5 * (1.0 + sign(a12 - a11))) * a12d
        m1 = max(a11, a12)
        m2_stack_d[(idx - 1) + 1] = m2d
        m2_stack[(idx - 1) + 1] = m2
        m2d = (0.5 * (1.0 + sign(a21 - a22))) * a21d + (0.5 * (1.0 + sign(a22 - a21))) * a22d
        m2 = max(a21, a22)
        p1d[idx] = (0.5 * (1.0 + sign(m1 - m2))) * m1d + (0.5 * (1.0 + sign(m2 - m1))) * m2d
        p1[idx] = max(m1, m2)
    end
    for i = 1:n_p1pad
        p1pad_stack_d[(i - 1) + 1] = p1padd[i]
        p1pad_stack[(i - 1) + 1] = p1pad[i]
        p1padd[i] = zero_vald
        p1pad[i] = zero_val
    end
    for idx = 1:c1 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        yi = (ci - 1) * hp2 * wp2 + ((i + pad) - 1) * wp2 + (j + pad)
        p1pad_stack_d[(div(n_p1pad - 1, 1) + 1) + ((idx - 1) + 1)] = p1padd[yi]
        p1pad_stack[(div(n_p1pad - 1, 1) + 1) + ((idx - 1) + 1)] = p1pad[yi]
        p1padd[yi] = p1d[idx]
        p1pad[yi] = p1[idx]
    end
    for idx = 1:c2 * hw2
        idxm1 = idx - 1
        co = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        sd = 0.0
        s = 0.0
        for i_seq_k = 1:c1 * khkw
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp2 * wp2 + (row - 1) * wp2 + col
            wi = (((co - 1) * c1 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            sd = sd + (w_e2a[wi] * p1padd[xi] + p1pad[xi] * w_e2ad[wi])
            s = s + p1pad[xi] * w_e2a[wi]
        end
        t_e2_stack_d[(idx - 1) + 1] = t_e2d[idx]
        t_e2_stack[(idx - 1) + 1] = t_e2[idx]
        t_e2d[idx] = sd + b_e2ad[co]
        t_e2[idx] = s + b_e2a[co]
    end
    for i = 1:n_e2_mid
        t_e2_stack_d[(div(c2 * hw2 - 1, 1) + 1) + ((i - 1) + 1)] = t_e2d[i]
        t_e2_stack[(div(c2 * hw2 - 1, 1) + 1) + ((i - 1) + 1)] = t_e2[i]
        t_e2d[i] = (0.5 * (1.0 + sign(t_e2[i] - zero_val))) * t_e2d[i] + (0.5 * (1.0 + sign(zero_val - t_e2[i]))) * zero_vald
        t_e2[i] = max(t_e2[i], zero_val)
    end
    for i = 1:n_e2_midpad
        t_e2pad_stack_d[(i - 1) + 1] = t_e2padd[i]
        t_e2pad_stack[(i - 1) + 1] = t_e2pad[i]
        t_e2padd[i] = zero_vald
        t_e2pad[i] = zero_val
    end
    for idx = 1:c2 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        yi = (ci - 1) * hp2 * wp2 + ((i + pad) - 1) * wp2 + (j + pad)
        t_e2pad_stack_d[(div(n_e2_midpad - 1, 1) + 1) + ((idx - 1) + 1)] = t_e2padd[yi]
        t_e2pad_stack[(div(n_e2_midpad - 1, 1) + 1) + ((idx - 1) + 1)] = t_e2pad[yi]
        t_e2padd[yi] = t_e2d[idx]
        t_e2pad[yi] = t_e2[idx]
    end
    for idx = 1:c2 * hw2
        idxm1 = idx - 1
        co = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        sd = 0.0
        s = 0.0
        for i_seq_k = 1:c2 * khkw
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp2 * wp2 + (row - 1) * wp2 + col
            wi = (((co - 1) * c2 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            sd = sd + (w_e2b[wi] * t_e2padd[xi] + t_e2pad[xi] * w_e2bd[wi])
            s = s + t_e2pad[xi] * w_e2b[wi]
        end
        skip2_stack_d[(idx - 1) + 1] = skip2d[idx]
        skip2_stack[(idx - 1) + 1] = skip2[idx]
        skip2d[idx] = sd + b_e2bd[co]
        skip2[idx] = s + b_e2b[co]
    end
    for i = 1:n_e2_out
        skip2_stack_d[(div(c2 * hw2 - 1, 1) + 1) + ((i - 1) + 1)] = skip2d[i]
        skip2_stack[(div(c2 * hw2 - 1, 1) + 1) + ((i - 1) + 1)] = skip2[i]
        skip2d[i] = (0.5 * (1.0 + sign(skip2[i] - zero_val))) * skip2d[i] + (0.5 * (1.0 + sign(zero_val - skip2[i]))) * zero_vald
        skip2[i] = max(skip2[i], zero_val)
    end
    for idx = 1:c2 * hw4
        idxm1 = idx - 1
        ci = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        oi = div(rem, w4) + 1
        oj = mod(rem, w4) + 1
        i0 = 2oi - 1
        j0 = 2oj - 1
        a11_stack_d[(div(c1 * hw2 - 1, 1) + 1) + ((idx - 1) + 1)] = a11d
        a11_stack[(div(c1 * hw2 - 1, 1) + 1) + ((idx - 1) + 1)] = a11
        a11d = skip2d[(ci - 1) * hw2 + (i0 - 1) * w2 + j0]
        a11 = skip2[(ci - 1) * hw2 + (i0 - 1) * w2 + j0]
        a12_stack_d[(div(c1 * hw2 - 1, 1) + 1) + ((idx - 1) + 1)] = a12d
        a12_stack[(div(c1 * hw2 - 1, 1) + 1) + ((idx - 1) + 1)] = a12
        a12d = skip2d[(ci - 1) * hw2 + (i0 - 1) * w2 + j0 + 1]
        a12 = skip2[(ci - 1) * hw2 + (i0 - 1) * w2 + j0 + 1]
        a21_stack_d[(div(c1 * hw2 - 1, 1) + 1) + ((idx - 1) + 1)] = a21d
        a21_stack[(div(c1 * hw2 - 1, 1) + 1) + ((idx - 1) + 1)] = a21
        a21d = skip2d[(ci - 1) * hw2 + i0 * w2 + j0]
        a21 = skip2[(ci - 1) * hw2 + i0 * w2 + j0]
        a22_stack_d[(div(c1 * hw2 - 1, 1) + 1) + ((idx - 1) + 1)] = a22d
        a22_stack[(div(c1 * hw2 - 1, 1) + 1) + ((idx - 1) + 1)] = a22
        a22d = skip2d[(ci - 1) * hw2 + i0 * w2 + j0 + 1]
        a22 = skip2[(ci - 1) * hw2 + i0 * w2 + j0 + 1]
        m1_stack_d[(div(c1 * hw2 - 1, 1) + 1) + ((idx - 1) + 1)] = m1d
        m1_stack[(div(c1 * hw2 - 1, 1) + 1) + ((idx - 1) + 1)] = m1
        m1d = (0.5 * (1.0 + sign(a11 - a12))) * a11d + (0.5 * (1.0 + sign(a12 - a11))) * a12d
        m1 = max(a11, a12)
        m2_stack_d[(div(c1 * hw2 - 1, 1) + 1) + ((idx - 1) + 1)] = m2d
        m2_stack[(div(c1 * hw2 - 1, 1) + 1) + ((idx - 1) + 1)] = m2
        m2d = (0.5 * (1.0 + sign(a21 - a22))) * a21d + (0.5 * (1.0 + sign(a22 - a21))) * a22d
        m2 = max(a21, a22)
        p2d[idx] = (0.5 * (1.0 + sign(m1 - m2))) * m1d + (0.5 * (1.0 + sign(m2 - m1))) * m2d
        p2[idx] = max(m1, m2)
    end
    for i = 1:n_p2pad
        p2pad_stack_d[(i - 1) + 1] = p2padd[i]
        p2pad_stack[(i - 1) + 1] = p2pad[i]
        p2padd[i] = zero_vald
        p2pad[i] = zero_val
    end
    for idx = 1:c2 * hw4
        idxm1 = idx - 1
        ci = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        i = div(rem, w4) + 1
        j = mod(rem, w4) + 1
        yi = (ci - 1) * hp4 * wp4 + ((i + pad) - 1) * wp4 + (j + pad)
        p2pad_stack_d[(div(n_p2pad - 1, 1) + 1) + ((idx - 1) + 1)] = p2padd[yi]
        p2pad_stack[(div(n_p2pad - 1, 1) + 1) + ((idx - 1) + 1)] = p2pad[yi]
        p2padd[yi] = p2d[idx]
        p2pad[yi] = p2[idx]
    end
    for idx = 1:c3 * hw4
        idxm1 = idx - 1
        co = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        i = div(rem, w4) + 1
        j = mod(rem, w4) + 1
        sd = 0.0
        s = 0.0
        for i_seq_k = 1:c2 * khkw
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp4 * wp4 + (row - 1) * wp4 + col
            wi = (((co - 1) * c2 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            sd = sd + (w_ba[wi] * p2padd[xi] + p2pad[xi] * w_bad[wi])
            s = s + p2pad[xi] * w_ba[wi]
        end
        t_b_stack_d[(idx - 1) + 1] = t_bd[idx]
        t_b_stack[(idx - 1) + 1] = t_b[idx]
        t_bd[idx] = sd + b_bad[co]
        t_b[idx] = s + b_ba[co]
    end
    for i = 1:n_b_mid
        t_b_stack_d[(div(c3 * hw4 - 1, 1) + 1) + ((i - 1) + 1)] = t_bd[i]
        t_b_stack[(div(c3 * hw4 - 1, 1) + 1) + ((i - 1) + 1)] = t_b[i]
        t_bd[i] = (0.5 * (1.0 + sign(t_b[i] - zero_val))) * t_bd[i] + (0.5 * (1.0 + sign(zero_val - t_b[i]))) * zero_vald
        t_b[i] = max(t_b[i], zero_val)
    end
    for i = 1:n_b_midpad
        t_bpad_stack_d[(i - 1) + 1] = t_bpadd[i]
        t_bpad_stack[(i - 1) + 1] = t_bpad[i]
        t_bpadd[i] = zero_vald
        t_bpad[i] = zero_val
    end
    for idx = 1:c3 * hw4
        idxm1 = idx - 1
        ci = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        i = div(rem, w4) + 1
        j = mod(rem, w4) + 1
        yi = (ci - 1) * hp4 * wp4 + ((i + pad) - 1) * wp4 + (j + pad)
        t_bpad_stack_d[(div(n_b_midpad - 1, 1) + 1) + ((idx - 1) + 1)] = t_bpadd[yi]
        t_bpad_stack[(div(n_b_midpad - 1, 1) + 1) + ((idx - 1) + 1)] = t_bpad[yi]
        t_bpadd[yi] = t_bd[idx]
        t_bpad[yi] = t_b[idx]
    end
    for idx = 1:c3 * hw4
        idxm1 = idx - 1
        co = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        i = div(rem, w4) + 1
        j = mod(rem, w4) + 1
        sd = 0.0
        s = 0.0
        for i_seq_k = 1:c3 * khkw
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp4 * wp4 + (row - 1) * wp4 + col
            wi = (((co - 1) * c3 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            sd = sd + (w_bb[wi] * t_bpadd[xi] + t_bpad[xi] * w_bbd[wi])
            s = s + t_bpad[xi] * w_bb[wi]
        end
        bott_stack_d[(idx - 1) + 1] = bottd[idx]
        bott_stack[(idx - 1) + 1] = bott[idx]
        bottd[idx] = sd + b_bbd[co]
        bott[idx] = s + b_bb[co]
    end
    for i = 1:n_b_out
        bott_stack_d[(div(c3 * hw4 - 1, 1) + 1) + ((i - 1) + 1)] = bottd[i]
        bott_stack[(div(c3 * hw4 - 1, 1) + 1) + ((i - 1) + 1)] = bott[i]
        bottd[i] = (0.5 * (1.0 + sign(bott[i] - zero_val))) * bottd[i] + (0.5 * (1.0 + sign(zero_val - bott[i]))) * zero_vald
        bott[i] = max(bott[i], zero_val)
    end
    for idx = 1:c3 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        oi = div(rem, w2) + 1
        oj = mod(rem, w2) + 1
        oim1 = oi - 1
        ojm1 = oj - 1
        i = div(oim1, scale) + 1
        j = div(ojm1, scale) + 1
        xi = (ci - 1) * hw4 + (i - 1) * w4 + j
        u2d[idx] = bottd[xi]
        u2[idx] = bott[xi]
    end
    for idx = 1:c3 * hw2
        cat2d[idx] = u2d[idx]
        cat2[idx] = u2[idx]
    end
    for idx = 1:c2 * hw2
        cat2d[c3 * hw2 + idx] = skip2d[idx]
        cat2[c3 * hw2 + idx] = skip2[idx]
    end
    for i = 1:n_cat2pad
        cat2pad_stack_d[(i - 1) + 1] = cat2padd[i]
        cat2pad_stack[(i - 1) + 1] = cat2pad[i]
        cat2padd[i] = zero_vald
        cat2pad[i] = zero_val
    end
    for idx = 1:c32 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        yi = (ci - 1) * hp2 * wp2 + ((i + pad) - 1) * wp2 + (j + pad)
        cat2pad_stack_d[(div(n_cat2pad - 1, 1) + 1) + ((idx - 1) + 1)] = cat2padd[yi]
        cat2pad_stack[(div(n_cat2pad - 1, 1) + 1) + ((idx - 1) + 1)] = cat2pad[yi]
        cat2padd[yi] = cat2d[idx]
        cat2pad[yi] = cat2[idx]
    end
    for idx = 1:c2 * hw2
        idxm1 = idx - 1
        co = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        sd = 0.0
        s = 0.0
        for i_seq_k = 1:c32 * khkw
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp2 * wp2 + (row - 1) * wp2 + col
            wi = (((co - 1) * c32 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            sd = sd + (w_d2a[wi] * cat2padd[xi] + cat2pad[xi] * w_d2ad[wi])
            s = s + cat2pad[xi] * w_d2a[wi]
        end
        t_d2_stack_d[(idx - 1) + 1] = t_d2d[idx]
        t_d2_stack[(idx - 1) + 1] = t_d2[idx]
        t_d2d[idx] = sd + b_d2ad[co]
        t_d2[idx] = s + b_d2a[co]
    end
    for i = 1:n_d2_mid
        t_d2_stack_d[(div(c2 * hw2 - 1, 1) + 1) + ((i - 1) + 1)] = t_d2d[i]
        t_d2_stack[(div(c2 * hw2 - 1, 1) + 1) + ((i - 1) + 1)] = t_d2[i]
        t_d2d[i] = (0.5 * (1.0 + sign(t_d2[i] - zero_val))) * t_d2d[i] + (0.5 * (1.0 + sign(zero_val - t_d2[i]))) * zero_vald
        t_d2[i] = max(t_d2[i], zero_val)
    end
    for i = 1:n_d2_midpad
        t_d2pad_stack_d[(i - 1) + 1] = t_d2padd[i]
        t_d2pad_stack[(i - 1) + 1] = t_d2pad[i]
        t_d2padd[i] = zero_vald
        t_d2pad[i] = zero_val
    end
    for idx = 1:c2 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        yi = (ci - 1) * hp2 * wp2 + ((i + pad) - 1) * wp2 + (j + pad)
        t_d2pad_stack_d[(div(n_d2_midpad - 1, 1) + 1) + ((idx - 1) + 1)] = t_d2padd[yi]
        t_d2pad_stack[(div(n_d2_midpad - 1, 1) + 1) + ((idx - 1) + 1)] = t_d2pad[yi]
        t_d2padd[yi] = t_d2d[idx]
        t_d2pad[yi] = t_d2[idx]
    end
    for idx = 1:c2 * hw2
        idxm1 = idx - 1
        co = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        sd = 0.0
        s = 0.0
        for i_seq_k = 1:c2 * khkw
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp2 * wp2 + (row - 1) * wp2 + col
            wi = (((co - 1) * c2 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            sd = sd + (w_d2b[wi] * t_d2padd[xi] + t_d2pad[xi] * w_d2bd[wi])
            s = s + t_d2pad[xi] * w_d2b[wi]
        end
        dec2out_stack_d[(idx - 1) + 1] = dec2outd[idx]
        dec2out_stack[(idx - 1) + 1] = dec2out[idx]
        dec2outd[idx] = sd + b_d2bd[co]
        dec2out[idx] = s + b_d2b[co]
    end
    for i = 1:n_d2_out
        dec2out_stack_d[(div(c2 * hw2 - 1, 1) + 1) + ((i - 1) + 1)] = dec2outd[i]
        dec2out_stack[(div(c2 * hw2 - 1, 1) + 1) + ((i - 1) + 1)] = dec2out[i]
        dec2outd[i] = (0.5 * (1.0 + sign(dec2out[i] - zero_val))) * dec2outd[i] + (0.5 * (1.0 + sign(zero_val - dec2out[i]))) * zero_vald
        dec2out[i] = max(dec2out[i], zero_val)
    end
    for idx = 1:c2 * hw
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        oi = div(rem, w) + 1
        oj = mod(rem, w) + 1
        oim1 = oi - 1
        ojm1 = oj - 1
        i = div(oim1, scale) + 1
        j = div(ojm1, scale) + 1
        xi = (ci - 1) * hw2 + (i - 1) * w2 + j
        u1d[idx] = dec2outd[xi]
        u1[idx] = dec2out[xi]
    end
    for idx = 1:c2 * hw
        cat1d[idx] = u1d[idx]
        cat1[idx] = u1[idx]
    end
    for idx = 1:c1 * hw
        cat1d[c2 * hw + idx] = skip1d[idx]
        cat1[c2 * hw + idx] = skip1[idx]
    end
    for i = 1:n_cat1pad
        cat1pad_stack_d[(i - 1) + 1] = cat1padd[i]
        cat1pad_stack[(i - 1) + 1] = cat1pad[i]
        cat1padd[i] = zero_vald
        cat1pad[i] = zero_val
    end
    for idx = 1:c21 * hw
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        yi = (ci - 1) * hp1 * wp1 + ((i + pad) - 1) * wp1 + (j + pad)
        cat1pad_stack_d[(div(n_cat1pad - 1, 1) + 1) + ((idx - 1) + 1)] = cat1padd[yi]
        cat1pad_stack[(div(n_cat1pad - 1, 1) + 1) + ((idx - 1) + 1)] = cat1pad[yi]
        cat1padd[yi] = cat1d[idx]
        cat1pad[yi] = cat1[idx]
    end
    for idx = 1:c1 * hw
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        sd = 0.0
        s = 0.0
        for i_seq_k = 1:c21 * khkw
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp1 * wp1 + (row - 1) * wp1 + col
            wi = (((co - 1) * c21 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            sd = sd + (w_d1a[wi] * cat1padd[xi] + cat1pad[xi] * w_d1ad[wi])
            s = s + cat1pad[xi] * w_d1a[wi]
        end
        t_d1_stack_d[(idx - 1) + 1] = t_d1d[idx]
        t_d1_stack[(idx - 1) + 1] = t_d1[idx]
        t_d1d[idx] = sd + b_d1ad[co]
        t_d1[idx] = s + b_d1a[co]
    end
    for i = 1:n_d1_mid
        t_d1_stack_d[(div(c1 * hw - 1, 1) + 1) + ((i - 1) + 1)] = t_d1d[i]
        t_d1_stack[(div(c1 * hw - 1, 1) + 1) + ((i - 1) + 1)] = t_d1[i]
        t_d1d[i] = (0.5 * (1.0 + sign(t_d1[i] - zero_val))) * t_d1d[i] + (0.5 * (1.0 + sign(zero_val - t_d1[i]))) * zero_vald
        t_d1[i] = max(t_d1[i], zero_val)
    end
    for i = 1:n_d1_midpad
        t_d1pad_stack_d[(i - 1) + 1] = t_d1padd[i]
        t_d1pad_stack[(i - 1) + 1] = t_d1pad[i]
        t_d1padd[i] = zero_vald
        t_d1pad[i] = zero_val
    end
    for idx = 1:c1 * hw
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        yi = (ci - 1) * hp1 * wp1 + ((i + pad) - 1) * wp1 + (j + pad)
        t_d1pad_stack_d[(div(n_d1_midpad - 1, 1) + 1) + ((idx - 1) + 1)] = t_d1padd[yi]
        t_d1pad_stack[(div(n_d1_midpad - 1, 1) + 1) + ((idx - 1) + 1)] = t_d1pad[yi]
        t_d1padd[yi] = t_d1d[idx]
        t_d1pad[yi] = t_d1[idx]
    end
    for idx = 1:c1 * hw
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        sd = 0.0
        s = 0.0
        for i_seq_k = 1:c1 * khkw
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp1 * wp1 + (row - 1) * wp1 + col
            wi = (((co - 1) * c1 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            sd = sd + (w_d1b[wi] * t_d1padd[xi] + t_d1pad[xi] * w_d1bd[wi])
            s = s + t_d1pad[xi] * w_d1b[wi]
        end
        dec1out_stack_d[(idx - 1) + 1] = dec1outd[idx]
        dec1out_stack[(idx - 1) + 1] = dec1out[idx]
        dec1outd[idx] = sd + b_d1bd[co]
        dec1out[idx] = s + b_d1b[co]
    end
    for i = 1:n_d1_out
        dec1out_stack_d[(div(c1 * hw - 1, 1) + 1) + ((i - 1) + 1)] = dec1outd[i]
        dec1out_stack[(div(c1 * hw - 1, 1) + 1) + ((i - 1) + 1)] = dec1out[i]
        dec1outd[i] = (0.5 * (1.0 + sign(dec1out[i] - zero_val))) * dec1outd[i] + (0.5 * (1.0 + sign(zero_val - dec1out[i]))) * zero_vald
        dec1out[i] = max(dec1out[i], zero_val)
    end
    for idx = 1:c_out * hw
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        sd = 0.0
        s = 0.0
        for i_seq_k = 1:c1 * khkw_out
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw_out) + 1
            rem2 = mod(kseqm1, khkw_out)
            ki = div(rem2, kw_out) + 1
            kj = mod(rem2, kw_out) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hw + (row - 1) * w + col
            wi = (((co - 1) * c1 + (ci - 1)) * kh_out + (ki - 1)) * kw_out + kj
            sd = sd + (w_out[wi] * dec1outd[xi] + dec1out[xi] * w_outd[wi])
            s = s + dec1out[xi] * w_out[wi]
        end
        yd[idx] = sd + b_outd[co]
        y[idx] = s + b_out[co]
    end
    a11_stack_d[((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1] = a11d
    a11_stack[((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1] = a11
    a12_stack_d[((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1] = a12d
    a12_stack[((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1] = a12
    a21_stack_d[((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1] = a21d
    a21_stack[((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1] = a21
    a22_stack_d[((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1] = a22d
    a22_stack[((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1] = a22
    m1_stack_d[((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1] = m1d
    m1_stack[((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1] = m1
    m2_stack_d[((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1] = m2d
    m2_stack[((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1] = m2
    a11d = a11_stack_d[((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1]
    a11 = a11_stack[((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1]
    a12d = a12_stack_d[((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1]
    a12 = a12_stack[((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1]
    a21d = a21_stack_d[((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1]
    a21 = a21_stack[((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1]
    a22d = a22_stack_d[((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1]
    a22 = a22_stack[((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1]
    m1d = m1_stack_d[((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1]
    m1 = m1_stack[((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1]
    m2d = m2_stack_d[((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1]
    m2 = m2_stack[((div(c1 * hw2 - 1, 1) + 1) + (div(c2 * hw4 - 1, 1) + 1)) + 1]
    two = 2
    four = 4
    h2 = div(h, two)
    w2 = div(w, two)
    h4 = div(h, four)
    w4 = div(w, four)
    hp1 = h + 2
    wp1 = w + 2
    hp2 = h2 + 2
    wp2 = w2 + 2
    hp4 = h4 + 2
    wp4 = w4 + 2
    pad = 1
    kh = 3
    kw = 3
    khkw = kh * kw
    kh_out = 1
    kw_out = 1
    khkw_out = kh_out * kw_out
    scale = 2
    c32 = c3 + c2
    c21 = c2 + c1
    hw = h * w
    hw2 = h2 * w2
    hw4 = h4 * w4
    n_xpad0 = c_in * hp1 * wp1
    n_e1_mid = c1 * hw
    n_e1_midpad = c1 * hp1 * wp1
    n_e1_out = c1 * hw
    n_p1pad = c1 * hp2 * wp2
    n_e2_mid = c2 * hw2
    n_e2_midpad = c2 * hp2 * wp2
    n_e2_out = c2 * hw2
    n_p2pad = c2 * hp4 * wp4
    n_b_mid = c3 * hw4
    n_b_midpad = c3 * hp4 * wp4
    n_b_out = c3 * hw4
    n_cat2pad = c32 * hp2 * wp2
    n_d2_mid = c2 * hw2
    n_d2_midpad = c2 * hp2 * wp2
    n_d2_out = c2 * hw2
    n_cat1pad = c21 * hp1 * wp1
    n_d1_mid = c1 * hw
    n_d1_midpad = c1 * hp1 * wp1
    n_d1_out = c1 * hw
    for idx = 1:c_out * hw
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        sbd = sbd + ybd[idx]
        sb = sb + yb[idx]
        b_outbd[co] = b_outbd[co] + ybd[idx]
        b_outb[co] = b_outb[co] + yb[idx]
        ybd[idx] = 0.0
        yb[idx] = 0.0
        for i_seq_k = c1 * khkw_out:-1:1
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw_out) + 1
            rem2 = mod(kseqm1, khkw_out)
            ki = div(rem2, kw_out) + 1
            kj = mod(rem2, kw_out) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hw + (row - 1) * w + col
            wi = (((co - 1) * c1 + (ci - 1)) * kh_out + (ki - 1)) * kw_out + kj
            dec1outbd[xi] = dec1outbd[xi] + (sb * w_outd[wi] + w_out[wi] * sbd)
            dec1outb[xi] = dec1outb[xi] + w_out[wi] * sb
            w_outbd[wi] = w_outbd[wi] + (sb * dec1outd[xi] + dec1out[xi] * sbd)
            w_outb[wi] = w_outb[wi] + dec1out[xi] * sb
        end
        sbd = 0.0
        sb = 0.0
    end
    for i = n_d1_out:-1:1
        dec1outd[i] = dec1out_stack_d[(div(c1 * hw - 1, 1) + 1) + ((i - 1) + 1)]
        dec1out[i] = dec1out_stack[(div(c1 * hw - 1, 1) + 1) + ((i - 1) + 1)]
        dec1outbd[i] = (0.5 * (1.0 + sign(dec1out[i] - zero_val))) * dec1outbd[i]
        dec1outb[i] = (0.5 * (1.0 + sign(dec1out[i] - zero_val))) * dec1outb[i]
    end
    for idx = c1 * hw:-1:1
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        dec1outd[idx] = dec1out_stack_d[(idx - 1) + 1]
        dec1out[idx] = dec1out_stack[(idx - 1) + 1]
        sbd = sbd + dec1outbd[idx]
        sb = sb + dec1outb[idx]
        b_d1bbd[co] = b_d1bbd[co] + dec1outbd[idx]
        b_d1bb[co] = b_d1bb[co] + dec1outb[idx]
        dec1outbd[idx] = 0.0
        dec1outb[idx] = 0.0
        for i_seq_k = c1 * khkw:-1:1
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp1 * wp1 + (row - 1) * wp1 + col
            wi = (((co - 1) * c1 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            t_d1padbd[xi] = t_d1padbd[xi] + (sb * w_d1bd[wi] + w_d1b[wi] * sbd)
            t_d1padb[xi] = t_d1padb[xi] + w_d1b[wi] * sb
            w_d1bbd[wi] = w_d1bbd[wi] + (sb * t_d1padd[xi] + t_d1pad[xi] * sbd)
            w_d1bb[wi] = w_d1bb[wi] + t_d1pad[xi] * sb
        end
        sbd = 0.0
        sb = 0.0
    end
    for idx = c1 * hw:-1:1
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        yi = (ci - 1) * hp1 * wp1 + ((i + pad) - 1) * wp1 + (j + pad)
        t_d1padd[yi] = t_d1pad_stack_d[(div(n_d1_midpad - 1, 1) + 1) + ((idx - 1) + 1)]
        t_d1pad[yi] = t_d1pad_stack[(div(n_d1_midpad - 1, 1) + 1) + ((idx - 1) + 1)]
        t_d1bd[idx] = t_d1bd[idx] + t_d1padbd[yi]
        t_d1b[idx] = t_d1b[idx] + t_d1padb[yi]
        t_d1padbd[yi] = 0.0
        t_d1padb[yi] = 0.0
    end
    for i = n_d1_midpad:-1:1
        t_d1padd[i] = t_d1pad_stack_d[(i - 1) + 1]
        t_d1pad[i] = t_d1pad_stack[(i - 1) + 1]
        t_d1padbd[i] = 0.0
        t_d1padb[i] = 0.0
    end
    for i = n_d1_mid:-1:1
        t_d1d[i] = t_d1_stack_d[(div(c1 * hw - 1, 1) + 1) + ((i - 1) + 1)]
        t_d1[i] = t_d1_stack[(div(c1 * hw - 1, 1) + 1) + ((i - 1) + 1)]
        t_d1bd[i] = (0.5 * (1.0 + sign(t_d1[i] - zero_val))) * t_d1bd[i]
        t_d1b[i] = (0.5 * (1.0 + sign(t_d1[i] - zero_val))) * t_d1b[i]
    end
    for idx = c1 * hw:-1:1
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        t_d1d[idx] = t_d1_stack_d[(idx - 1) + 1]
        t_d1[idx] = t_d1_stack[(idx - 1) + 1]
        sbd = sbd + t_d1bd[idx]
        sb = sb + t_d1b[idx]
        b_d1abd[co] = b_d1abd[co] + t_d1bd[idx]
        b_d1ab[co] = b_d1ab[co] + t_d1b[idx]
        t_d1bd[idx] = 0.0
        t_d1b[idx] = 0.0
        for i_seq_k = c21 * khkw:-1:1
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp1 * wp1 + (row - 1) * wp1 + col
            wi = (((co - 1) * c21 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            cat1padbd[xi] = cat1padbd[xi] + (sb * w_d1ad[wi] + w_d1a[wi] * sbd)
            cat1padb[xi] = cat1padb[xi] + w_d1a[wi] * sb
            w_d1abd[wi] = w_d1abd[wi] + (sb * cat1padd[xi] + cat1pad[xi] * sbd)
            w_d1ab[wi] = w_d1ab[wi] + cat1pad[xi] * sb
        end
        sbd = 0.0
        sb = 0.0
    end
    for idx = c21 * hw:-1:1
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        yi = (ci - 1) * hp1 * wp1 + ((i + pad) - 1) * wp1 + (j + pad)
        cat1padd[yi] = cat1pad_stack_d[(div(n_cat1pad - 1, 1) + 1) + ((idx - 1) + 1)]
        cat1pad[yi] = cat1pad_stack[(div(n_cat1pad - 1, 1) + 1) + ((idx - 1) + 1)]
        cat1bd[idx] = cat1bd[idx] + cat1padbd[yi]
        cat1b[idx] = cat1b[idx] + cat1padb[yi]
        cat1padbd[yi] = 0.0
        cat1padb[yi] = 0.0
    end
    for i = n_cat1pad:-1:1
        cat1padd[i] = cat1pad_stack_d[(i - 1) + 1]
        cat1pad[i] = cat1pad_stack[(i - 1) + 1]
        cat1padbd[i] = 0.0
        cat1padb[i] = 0.0
    end
    for idx = 1:c1 * hw
        skip1bd[idx] = skip1bd[idx] + cat1bd[c2 * hw + idx]
        skip1b[idx] = skip1b[idx] + cat1b[c2 * hw + idx]
        cat1bd[c2 * hw + idx] = 0.0
        cat1b[c2 * hw + idx] = 0.0
    end
    for idx = 1:c2 * hw
        u1bd[idx] = u1bd[idx] + cat1bd[idx]
        u1b[idx] = u1b[idx] + cat1b[idx]
        cat1bd[idx] = 0.0
        cat1b[idx] = 0.0
    end
    for idx = 1:c2 * hw
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        oi = div(rem, w) + 1
        oj = mod(rem, w) + 1
        oim1 = oi - 1
        ojm1 = oj - 1
        i = div(oim1, scale) + 1
        j = div(ojm1, scale) + 1
        xi = (ci - 1) * hw2 + (i - 1) * w2 + j
        dec2outbd[xi] = dec2outbd[xi] + u1bd[idx]
        dec2outb[xi] = dec2outb[xi] + u1b[idx]
        u1bd[idx] = 0.0
        u1b[idx] = 0.0
    end
    for i = n_d2_out:-1:1
        dec2outd[i] = dec2out_stack_d[(div(c2 * hw2 - 1, 1) + 1) + ((i - 1) + 1)]
        dec2out[i] = dec2out_stack[(div(c2 * hw2 - 1, 1) + 1) + ((i - 1) + 1)]
        dec2outbd[i] = (0.5 * (1.0 + sign(dec2out[i] - zero_val))) * dec2outbd[i]
        dec2outb[i] = (0.5 * (1.0 + sign(dec2out[i] - zero_val))) * dec2outb[i]
    end
    for idx = c2 * hw2:-1:1
        idxm1 = idx - 1
        co = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        dec2outd[idx] = dec2out_stack_d[(idx - 1) + 1]
        dec2out[idx] = dec2out_stack[(idx - 1) + 1]
        sbd = sbd + dec2outbd[idx]
        sb = sb + dec2outb[idx]
        b_d2bbd[co] = b_d2bbd[co] + dec2outbd[idx]
        b_d2bb[co] = b_d2bb[co] + dec2outb[idx]
        dec2outbd[idx] = 0.0
        dec2outb[idx] = 0.0
        for i_seq_k = c2 * khkw:-1:1
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp2 * wp2 + (row - 1) * wp2 + col
            wi = (((co - 1) * c2 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            t_d2padbd[xi] = t_d2padbd[xi] + (sb * w_d2bd[wi] + w_d2b[wi] * sbd)
            t_d2padb[xi] = t_d2padb[xi] + w_d2b[wi] * sb
            w_d2bbd[wi] = w_d2bbd[wi] + (sb * t_d2padd[xi] + t_d2pad[xi] * sbd)
            w_d2bb[wi] = w_d2bb[wi] + t_d2pad[xi] * sb
        end
        sbd = 0.0
        sb = 0.0
    end
    for idx = c2 * hw2:-1:1
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        yi = (ci - 1) * hp2 * wp2 + ((i + pad) - 1) * wp2 + (j + pad)
        t_d2padd[yi] = t_d2pad_stack_d[(div(n_d2_midpad - 1, 1) + 1) + ((idx - 1) + 1)]
        t_d2pad[yi] = t_d2pad_stack[(div(n_d2_midpad - 1, 1) + 1) + ((idx - 1) + 1)]
        t_d2bd[idx] = t_d2bd[idx] + t_d2padbd[yi]
        t_d2b[idx] = t_d2b[idx] + t_d2padb[yi]
        t_d2padbd[yi] = 0.0
        t_d2padb[yi] = 0.0
    end
    for i = n_d2_midpad:-1:1
        t_d2padd[i] = t_d2pad_stack_d[(i - 1) + 1]
        t_d2pad[i] = t_d2pad_stack[(i - 1) + 1]
        t_d2padbd[i] = 0.0
        t_d2padb[i] = 0.0
    end
    for i = n_d2_mid:-1:1
        t_d2d[i] = t_d2_stack_d[(div(c2 * hw2 - 1, 1) + 1) + ((i - 1) + 1)]
        t_d2[i] = t_d2_stack[(div(c2 * hw2 - 1, 1) + 1) + ((i - 1) + 1)]
        t_d2bd[i] = (0.5 * (1.0 + sign(t_d2[i] - zero_val))) * t_d2bd[i]
        t_d2b[i] = (0.5 * (1.0 + sign(t_d2[i] - zero_val))) * t_d2b[i]
    end
    for idx = c2 * hw2:-1:1
        idxm1 = idx - 1
        co = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        t_d2d[idx] = t_d2_stack_d[(idx - 1) + 1]
        t_d2[idx] = t_d2_stack[(idx - 1) + 1]
        sbd = sbd + t_d2bd[idx]
        sb = sb + t_d2b[idx]
        b_d2abd[co] = b_d2abd[co] + t_d2bd[idx]
        b_d2ab[co] = b_d2ab[co] + t_d2b[idx]
        t_d2bd[idx] = 0.0
        t_d2b[idx] = 0.0
        for i_seq_k = c32 * khkw:-1:1
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp2 * wp2 + (row - 1) * wp2 + col
            wi = (((co - 1) * c32 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            cat2padbd[xi] = cat2padbd[xi] + (sb * w_d2ad[wi] + w_d2a[wi] * sbd)
            cat2padb[xi] = cat2padb[xi] + w_d2a[wi] * sb
            w_d2abd[wi] = w_d2abd[wi] + (sb * cat2padd[xi] + cat2pad[xi] * sbd)
            w_d2ab[wi] = w_d2ab[wi] + cat2pad[xi] * sb
        end
        sbd = 0.0
        sb = 0.0
    end
    for idx = c32 * hw2:-1:1
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        yi = (ci - 1) * hp2 * wp2 + ((i + pad) - 1) * wp2 + (j + pad)
        cat2padd[yi] = cat2pad_stack_d[(div(n_cat2pad - 1, 1) + 1) + ((idx - 1) + 1)]
        cat2pad[yi] = cat2pad_stack[(div(n_cat2pad - 1, 1) + 1) + ((idx - 1) + 1)]
        cat2bd[idx] = cat2bd[idx] + cat2padbd[yi]
        cat2b[idx] = cat2b[idx] + cat2padb[yi]
        cat2padbd[yi] = 0.0
        cat2padb[yi] = 0.0
    end
    for i = n_cat2pad:-1:1
        cat2padd[i] = cat2pad_stack_d[(i - 1) + 1]
        cat2pad[i] = cat2pad_stack[(i - 1) + 1]
        cat2padbd[i] = 0.0
        cat2padb[i] = 0.0
    end
    for idx = 1:c2 * hw2
        skip2bd[idx] = skip2bd[idx] + cat2bd[c3 * hw2 + idx]
        skip2b[idx] = skip2b[idx] + cat2b[c3 * hw2 + idx]
        cat2bd[c3 * hw2 + idx] = 0.0
        cat2b[c3 * hw2 + idx] = 0.0
    end
    for idx = 1:c3 * hw2
        u2bd[idx] = u2bd[idx] + cat2bd[idx]
        u2b[idx] = u2b[idx] + cat2b[idx]
        cat2bd[idx] = 0.0
        cat2b[idx] = 0.0
    end
    for idx = 1:c3 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        oi = div(rem, w2) + 1
        oj = mod(rem, w2) + 1
        oim1 = oi - 1
        ojm1 = oj - 1
        i = div(oim1, scale) + 1
        j = div(ojm1, scale) + 1
        xi = (ci - 1) * hw4 + (i - 1) * w4 + j
        bottbd[xi] = bottbd[xi] + u2bd[idx]
        bottb[xi] = bottb[xi] + u2b[idx]
        u2bd[idx] = 0.0
        u2b[idx] = 0.0
    end
    for i = n_b_out:-1:1
        bottd[i] = bott_stack_d[(div(c3 * hw4 - 1, 1) + 1) + ((i - 1) + 1)]
        bott[i] = bott_stack[(div(c3 * hw4 - 1, 1) + 1) + ((i - 1) + 1)]
        bottbd[i] = (0.5 * (1.0 + sign(bott[i] - zero_val))) * bottbd[i]
        bottb[i] = (0.5 * (1.0 + sign(bott[i] - zero_val))) * bottb[i]
    end
    for idx = c3 * hw4:-1:1
        idxm1 = idx - 1
        co = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        i = div(rem, w4) + 1
        j = mod(rem, w4) + 1
        bottd[idx] = bott_stack_d[(idx - 1) + 1]
        bott[idx] = bott_stack[(idx - 1) + 1]
        sbd = sbd + bottbd[idx]
        sb = sb + bottb[idx]
        b_bbbd[co] = b_bbbd[co] + bottbd[idx]
        b_bbb[co] = b_bbb[co] + bottb[idx]
        bottbd[idx] = 0.0
        bottb[idx] = 0.0
        for i_seq_k = c3 * khkw:-1:1
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp4 * wp4 + (row - 1) * wp4 + col
            wi = (((co - 1) * c3 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            t_bpadbd[xi] = t_bpadbd[xi] + (sb * w_bbd[wi] + w_bb[wi] * sbd)
            t_bpadb[xi] = t_bpadb[xi] + w_bb[wi] * sb
            w_bbbd[wi] = w_bbbd[wi] + (sb * t_bpadd[xi] + t_bpad[xi] * sbd)
            w_bbb[wi] = w_bbb[wi] + t_bpad[xi] * sb
        end
        sbd = 0.0
        sb = 0.0
    end
    for idx = c3 * hw4:-1:1
        idxm1 = idx - 1
        ci = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        i = div(rem, w4) + 1
        j = mod(rem, w4) + 1
        yi = (ci - 1) * hp4 * wp4 + ((i + pad) - 1) * wp4 + (j + pad)
        t_bpadd[yi] = t_bpad_stack_d[(div(n_b_midpad - 1, 1) + 1) + ((idx - 1) + 1)]
        t_bpad[yi] = t_bpad_stack[(div(n_b_midpad - 1, 1) + 1) + ((idx - 1) + 1)]
        t_bbd[idx] = t_bbd[idx] + t_bpadbd[yi]
        t_bb[idx] = t_bb[idx] + t_bpadb[yi]
        t_bpadbd[yi] = 0.0
        t_bpadb[yi] = 0.0
    end
    for i = n_b_midpad:-1:1
        t_bpadd[i] = t_bpad_stack_d[(i - 1) + 1]
        t_bpad[i] = t_bpad_stack[(i - 1) + 1]
        t_bpadbd[i] = 0.0
        t_bpadb[i] = 0.0
    end
    for i = n_b_mid:-1:1
        t_bd[i] = t_b_stack_d[(div(c3 * hw4 - 1, 1) + 1) + ((i - 1) + 1)]
        t_b[i] = t_b_stack[(div(c3 * hw4 - 1, 1) + 1) + ((i - 1) + 1)]
        t_bbd[i] = (0.5 * (1.0 + sign(t_b[i] - zero_val))) * t_bbd[i]
        t_bb[i] = (0.5 * (1.0 + sign(t_b[i] - zero_val))) * t_bb[i]
    end
    for idx = c3 * hw4:-1:1
        idxm1 = idx - 1
        co = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        i = div(rem, w4) + 1
        j = mod(rem, w4) + 1
        t_bd[idx] = t_b_stack_d[(idx - 1) + 1]
        t_b[idx] = t_b_stack[(idx - 1) + 1]
        sbd = sbd + t_bbd[idx]
        sb = sb + t_bb[idx]
        b_babd[co] = b_babd[co] + t_bbd[idx]
        b_bab[co] = b_bab[co] + t_bb[idx]
        t_bbd[idx] = 0.0
        t_bb[idx] = 0.0
        for i_seq_k = c2 * khkw:-1:1
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp4 * wp4 + (row - 1) * wp4 + col
            wi = (((co - 1) * c2 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            p2padbd[xi] = p2padbd[xi] + (sb * w_bad[wi] + w_ba[wi] * sbd)
            p2padb[xi] = p2padb[xi] + w_ba[wi] * sb
            w_babd[wi] = w_babd[wi] + (sb * p2padd[xi] + p2pad[xi] * sbd)
            w_bab[wi] = w_bab[wi] + p2pad[xi] * sb
        end
        sbd = 0.0
        sb = 0.0
    end
    for idx = c2 * hw4:-1:1
        idxm1 = idx - 1
        ci = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        i = div(rem, w4) + 1
        j = mod(rem, w4) + 1
        yi = (ci - 1) * hp4 * wp4 + ((i + pad) - 1) * wp4 + (j + pad)
        p2padd[yi] = p2pad_stack_d[(div(n_p2pad - 1, 1) + 1) + ((idx - 1) + 1)]
        p2pad[yi] = p2pad_stack[(div(n_p2pad - 1, 1) + 1) + ((idx - 1) + 1)]
        p2bd[idx] = p2bd[idx] + p2padbd[yi]
        p2b[idx] = p2b[idx] + p2padb[yi]
        p2padbd[yi] = 0.0
        p2padb[yi] = 0.0
    end
    for i = n_p2pad:-1:1
        p2padd[i] = p2pad_stack_d[(i - 1) + 1]
        p2pad[i] = p2pad_stack[(i - 1) + 1]
        p2padbd[i] = 0.0
        p2padb[i] = 0.0
    end
    for idx = c2 * hw4:-1:1
        idxm1 = idx - 1
        ci = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        oi = div(rem, w4) + 1
        oj = mod(rem, w4) + 1
        i0 = 2oi - 1
        j0 = 2oj - 1
        m1bd = m1bd + (0.5 * (1.0 + sign(m1 - m2))) * p2bd[idx]
        m1b = m1b + (0.5 * (1.0 + sign(m1 - m2))) * p2b[idx]
        m2bd = m2bd + (0.5 * (1.0 + sign(m2 - m1))) * p2bd[idx]
        m2b = m2b + (0.5 * (1.0 + sign(m2 - m1))) * p2b[idx]
        p2bd[idx] = 0.0
        p2b[idx] = 0.0
        m2d = m2_stack_d[(div(c1 * hw2 - 1, 1) + 1) + ((idx - 1) + 1)]
        m2 = m2_stack[(div(c1 * hw2 - 1, 1) + 1) + ((idx - 1) + 1)]
        a21bd = a21bd + (0.5 * (1.0 + sign(a21 - a22))) * m2bd
        a21b = a21b + (0.5 * (1.0 + sign(a21 - a22))) * m2b
        a22bd = a22bd + (0.5 * (1.0 + sign(a22 - a21))) * m2bd
        a22b = a22b + (0.5 * (1.0 + sign(a22 - a21))) * m2b
        m2bd = 0.0
        m2b = 0.0
        m1d = m1_stack_d[(div(c1 * hw2 - 1, 1) + 1) + ((idx - 1) + 1)]
        m1 = m1_stack[(div(c1 * hw2 - 1, 1) + 1) + ((idx - 1) + 1)]
        a11bd = a11bd + (0.5 * (1.0 + sign(a11 - a12))) * m1bd
        a11b = a11b + (0.5 * (1.0 + sign(a11 - a12))) * m1b
        a12bd = a12bd + (0.5 * (1.0 + sign(a12 - a11))) * m1bd
        a12b = a12b + (0.5 * (1.0 + sign(a12 - a11))) * m1b
        m1bd = 0.0
        m1b = 0.0
        a22d = a22_stack_d[(div(c1 * hw2 - 1, 1) + 1) + ((idx - 1) + 1)]
        a22 = a22_stack[(div(c1 * hw2 - 1, 1) + 1) + ((idx - 1) + 1)]
        skip2bd[(ci - 1) * hw2 + i0 * w2 + j0 + 1] = skip2bd[(ci - 1) * hw2 + i0 * w2 + j0 + 1] + a22bd
        skip2b[(ci - 1) * hw2 + i0 * w2 + j0 + 1] = skip2b[(ci - 1) * hw2 + i0 * w2 + j0 + 1] + a22b
        a22bd = 0.0
        a22b = 0.0
        a21d = a21_stack_d[(div(c1 * hw2 - 1, 1) + 1) + ((idx - 1) + 1)]
        a21 = a21_stack[(div(c1 * hw2 - 1, 1) + 1) + ((idx - 1) + 1)]
        skip2bd[(ci - 1) * hw2 + i0 * w2 + j0] = skip2bd[(ci - 1) * hw2 + i0 * w2 + j0] + a21bd
        skip2b[(ci - 1) * hw2 + i0 * w2 + j0] = skip2b[(ci - 1) * hw2 + i0 * w2 + j0] + a21b
        a21bd = 0.0
        a21b = 0.0
        a12d = a12_stack_d[(div(c1 * hw2 - 1, 1) + 1) + ((idx - 1) + 1)]
        a12 = a12_stack[(div(c1 * hw2 - 1, 1) + 1) + ((idx - 1) + 1)]
        skip2bd[(ci - 1) * hw2 + (i0 - 1) * w2 + j0 + 1] = skip2bd[(ci - 1) * hw2 + (i0 - 1) * w2 + j0 + 1] + a12bd
        skip2b[(ci - 1) * hw2 + (i0 - 1) * w2 + j0 + 1] = skip2b[(ci - 1) * hw2 + (i0 - 1) * w2 + j0 + 1] + a12b
        a12bd = 0.0
        a12b = 0.0
        a11d = a11_stack_d[(div(c1 * hw2 - 1, 1) + 1) + ((idx - 1) + 1)]
        a11 = a11_stack[(div(c1 * hw2 - 1, 1) + 1) + ((idx - 1) + 1)]
        skip2bd[(ci - 1) * hw2 + (i0 - 1) * w2 + j0] = skip2bd[(ci - 1) * hw2 + (i0 - 1) * w2 + j0] + a11bd
        skip2b[(ci - 1) * hw2 + (i0 - 1) * w2 + j0] = skip2b[(ci - 1) * hw2 + (i0 - 1) * w2 + j0] + a11b
        a11bd = 0.0
        a11b = 0.0
    end
    for i = n_e2_out:-1:1
        skip2d[i] = skip2_stack_d[(div(c2 * hw2 - 1, 1) + 1) + ((i - 1) + 1)]
        skip2[i] = skip2_stack[(div(c2 * hw2 - 1, 1) + 1) + ((i - 1) + 1)]
        skip2bd[i] = (0.5 * (1.0 + sign(skip2[i] - zero_val))) * skip2bd[i]
        skip2b[i] = (0.5 * (1.0 + sign(skip2[i] - zero_val))) * skip2b[i]
    end
    for idx = c2 * hw2:-1:1
        idxm1 = idx - 1
        co = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        skip2d[idx] = skip2_stack_d[(idx - 1) + 1]
        skip2[idx] = skip2_stack[(idx - 1) + 1]
        sbd = sbd + skip2bd[idx]
        sb = sb + skip2b[idx]
        b_e2bbd[co] = b_e2bbd[co] + skip2bd[idx]
        b_e2bb[co] = b_e2bb[co] + skip2b[idx]
        skip2bd[idx] = 0.0
        skip2b[idx] = 0.0
        for i_seq_k = c2 * khkw:-1:1
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp2 * wp2 + (row - 1) * wp2 + col
            wi = (((co - 1) * c2 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            t_e2padbd[xi] = t_e2padbd[xi] + (sb * w_e2bd[wi] + w_e2b[wi] * sbd)
            t_e2padb[xi] = t_e2padb[xi] + w_e2b[wi] * sb
            w_e2bbd[wi] = w_e2bbd[wi] + (sb * t_e2padd[xi] + t_e2pad[xi] * sbd)
            w_e2bb[wi] = w_e2bb[wi] + t_e2pad[xi] * sb
        end
        sbd = 0.0
        sb = 0.0
    end
    for idx = c2 * hw2:-1:1
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        yi = (ci - 1) * hp2 * wp2 + ((i + pad) - 1) * wp2 + (j + pad)
        t_e2padd[yi] = t_e2pad_stack_d[(div(n_e2_midpad - 1, 1) + 1) + ((idx - 1) + 1)]
        t_e2pad[yi] = t_e2pad_stack[(div(n_e2_midpad - 1, 1) + 1) + ((idx - 1) + 1)]
        t_e2bd[idx] = t_e2bd[idx] + t_e2padbd[yi]
        t_e2b[idx] = t_e2b[idx] + t_e2padb[yi]
        t_e2padbd[yi] = 0.0
        t_e2padb[yi] = 0.0
    end
    for i = n_e2_midpad:-1:1
        t_e2padd[i] = t_e2pad_stack_d[(i - 1) + 1]
        t_e2pad[i] = t_e2pad_stack[(i - 1) + 1]
        t_e2padbd[i] = 0.0
        t_e2padb[i] = 0.0
    end
    for i = n_e2_mid:-1:1
        t_e2d[i] = t_e2_stack_d[(div(c2 * hw2 - 1, 1) + 1) + ((i - 1) + 1)]
        t_e2[i] = t_e2_stack[(div(c2 * hw2 - 1, 1) + 1) + ((i - 1) + 1)]
        t_e2bd[i] = (0.5 * (1.0 + sign(t_e2[i] - zero_val))) * t_e2bd[i]
        t_e2b[i] = (0.5 * (1.0 + sign(t_e2[i] - zero_val))) * t_e2b[i]
    end
    for idx = c2 * hw2:-1:1
        idxm1 = idx - 1
        co = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        t_e2d[idx] = t_e2_stack_d[(idx - 1) + 1]
        t_e2[idx] = t_e2_stack[(idx - 1) + 1]
        sbd = sbd + t_e2bd[idx]
        sb = sb + t_e2b[idx]
        b_e2abd[co] = b_e2abd[co] + t_e2bd[idx]
        b_e2ab[co] = b_e2ab[co] + t_e2b[idx]
        t_e2bd[idx] = 0.0
        t_e2b[idx] = 0.0
        for i_seq_k = c1 * khkw:-1:1
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp2 * wp2 + (row - 1) * wp2 + col
            wi = (((co - 1) * c1 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            p1padbd[xi] = p1padbd[xi] + (sb * w_e2ad[wi] + w_e2a[wi] * sbd)
            p1padb[xi] = p1padb[xi] + w_e2a[wi] * sb
            w_e2abd[wi] = w_e2abd[wi] + (sb * p1padd[xi] + p1pad[xi] * sbd)
            w_e2ab[wi] = w_e2ab[wi] + p1pad[xi] * sb
        end
        sbd = 0.0
        sb = 0.0
    end
    for idx = c1 * hw2:-1:1
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        yi = (ci - 1) * hp2 * wp2 + ((i + pad) - 1) * wp2 + (j + pad)
        p1padd[yi] = p1pad_stack_d[(div(n_p1pad - 1, 1) + 1) + ((idx - 1) + 1)]
        p1pad[yi] = p1pad_stack[(div(n_p1pad - 1, 1) + 1) + ((idx - 1) + 1)]
        p1bd[idx] = p1bd[idx] + p1padbd[yi]
        p1b[idx] = p1b[idx] + p1padb[yi]
        p1padbd[yi] = 0.0
        p1padb[yi] = 0.0
    end
    for i = n_p1pad:-1:1
        p1padd[i] = p1pad_stack_d[(i - 1) + 1]
        p1pad[i] = p1pad_stack[(i - 1) + 1]
        p1padbd[i] = 0.0
        p1padb[i] = 0.0
    end
    for idx = c1 * hw2:-1:1
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        oi = div(rem, w2) + 1
        oj = mod(rem, w2) + 1
        i0 = 2oi - 1
        j0 = 2oj - 1
        m1bd = m1bd + (0.5 * (1.0 + sign(m1 - m2))) * p1bd[idx]
        m1b = m1b + (0.5 * (1.0 + sign(m1 - m2))) * p1b[idx]
        m2bd = m2bd + (0.5 * (1.0 + sign(m2 - m1))) * p1bd[idx]
        m2b = m2b + (0.5 * (1.0 + sign(m2 - m1))) * p1b[idx]
        p1bd[idx] = 0.0
        p1b[idx] = 0.0
        m2d = m2_stack_d[(idx - 1) + 1]
        m2 = m2_stack[(idx - 1) + 1]
        a21bd = a21bd + (0.5 * (1.0 + sign(a21 - a22))) * m2bd
        a21b = a21b + (0.5 * (1.0 + sign(a21 - a22))) * m2b
        a22bd = a22bd + (0.5 * (1.0 + sign(a22 - a21))) * m2bd
        a22b = a22b + (0.5 * (1.0 + sign(a22 - a21))) * m2b
        m2bd = 0.0
        m2b = 0.0
        m1d = m1_stack_d[(idx - 1) + 1]
        m1 = m1_stack[(idx - 1) + 1]
        a11bd = a11bd + (0.5 * (1.0 + sign(a11 - a12))) * m1bd
        a11b = a11b + (0.5 * (1.0 + sign(a11 - a12))) * m1b
        a12bd = a12bd + (0.5 * (1.0 + sign(a12 - a11))) * m1bd
        a12b = a12b + (0.5 * (1.0 + sign(a12 - a11))) * m1b
        m1bd = 0.0
        m1b = 0.0
        a22d = a22_stack_d[(idx - 1) + 1]
        a22 = a22_stack[(idx - 1) + 1]
        skip1bd[(ci - 1) * hw + i0 * w + j0 + 1] = skip1bd[(ci - 1) * hw + i0 * w + j0 + 1] + a22bd
        skip1b[(ci - 1) * hw + i0 * w + j0 + 1] = skip1b[(ci - 1) * hw + i0 * w + j0 + 1] + a22b
        a22bd = 0.0
        a22b = 0.0
        a21d = a21_stack_d[(idx - 1) + 1]
        a21 = a21_stack[(idx - 1) + 1]
        skip1bd[(ci - 1) * hw + i0 * w + j0] = skip1bd[(ci - 1) * hw + i0 * w + j0] + a21bd
        skip1b[(ci - 1) * hw + i0 * w + j0] = skip1b[(ci - 1) * hw + i0 * w + j0] + a21b
        a21bd = 0.0
        a21b = 0.0
        a12d = a12_stack_d[(idx - 1) + 1]
        a12 = a12_stack[(idx - 1) + 1]
        skip1bd[(ci - 1) * hw + (i0 - 1) * w + j0 + 1] = skip1bd[(ci - 1) * hw + (i0 - 1) * w + j0 + 1] + a12bd
        skip1b[(ci - 1) * hw + (i0 - 1) * w + j0 + 1] = skip1b[(ci - 1) * hw + (i0 - 1) * w + j0 + 1] + a12b
        a12bd = 0.0
        a12b = 0.0
        a11d = a11_stack_d[(idx - 1) + 1]
        a11 = a11_stack[(idx - 1) + 1]
        skip1bd[(ci - 1) * hw + (i0 - 1) * w + j0] = skip1bd[(ci - 1) * hw + (i0 - 1) * w + j0] + a11bd
        skip1b[(ci - 1) * hw + (i0 - 1) * w + j0] = skip1b[(ci - 1) * hw + (i0 - 1) * w + j0] + a11b
        a11bd = 0.0
        a11b = 0.0
    end
    for i = n_e1_out:-1:1
        skip1d[i] = skip1_stack_d[(div(c1 * hw - 1, 1) + 1) + ((i - 1) + 1)]
        skip1[i] = skip1_stack[(div(c1 * hw - 1, 1) + 1) + ((i - 1) + 1)]
        skip1bd[i] = (0.5 * (1.0 + sign(skip1[i] - zero_val))) * skip1bd[i]
        skip1b[i] = (0.5 * (1.0 + sign(skip1[i] - zero_val))) * skip1b[i]
    end
    for idx = c1 * hw:-1:1
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        skip1d[idx] = skip1_stack_d[(idx - 1) + 1]
        skip1[idx] = skip1_stack[(idx - 1) + 1]
        sbd = sbd + skip1bd[idx]
        sb = sb + skip1b[idx]
        b_e1bbd[co] = b_e1bbd[co] + skip1bd[idx]
        b_e1bb[co] = b_e1bb[co] + skip1b[idx]
        skip1bd[idx] = 0.0
        skip1b[idx] = 0.0
        for i_seq_k = c1 * khkw:-1:1
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp1 * wp1 + (row - 1) * wp1 + col
            wi = (((co - 1) * c1 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            t_e1padbd[xi] = t_e1padbd[xi] + (sb * w_e1bd[wi] + w_e1b[wi] * sbd)
            t_e1padb[xi] = t_e1padb[xi] + w_e1b[wi] * sb
            w_e1bbd[wi] = w_e1bbd[wi] + (sb * t_e1padd[xi] + t_e1pad[xi] * sbd)
            w_e1bb[wi] = w_e1bb[wi] + t_e1pad[xi] * sb
        end
        sbd = 0.0
        sb = 0.0
    end
    for idx = c1 * hw:-1:1
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        yi = (ci - 1) * hp1 * wp1 + ((i + pad) - 1) * wp1 + (j + pad)
        t_e1padd[yi] = t_e1pad_stack_d[(div(n_e1_midpad - 1, 1) + 1) + ((idx - 1) + 1)]
        t_e1pad[yi] = t_e1pad_stack[(div(n_e1_midpad - 1, 1) + 1) + ((idx - 1) + 1)]
        t_e1bd[idx] = t_e1bd[idx] + t_e1padbd[yi]
        t_e1b[idx] = t_e1b[idx] + t_e1padb[yi]
        t_e1padbd[yi] = 0.0
        t_e1padb[yi] = 0.0
    end
    for i = n_e1_midpad:-1:1
        t_e1padd[i] = t_e1pad_stack_d[(i - 1) + 1]
        t_e1pad[i] = t_e1pad_stack[(i - 1) + 1]
        t_e1padbd[i] = 0.0
        t_e1padb[i] = 0.0
    end
    for i = n_e1_mid:-1:1
        t_e1d[i] = t_e1_stack_d[(div(c1 * hw - 1, 1) + 1) + ((i - 1) + 1)]
        t_e1[i] = t_e1_stack[(div(c1 * hw - 1, 1) + 1) + ((i - 1) + 1)]
        t_e1bd[i] = (0.5 * (1.0 + sign(t_e1[i] - zero_val))) * t_e1bd[i]
        t_e1b[i] = (0.5 * (1.0 + sign(t_e1[i] - zero_val))) * t_e1b[i]
    end
    for idx = c1 * hw:-1:1
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        t_e1d[idx] = t_e1_stack_d[(idx - 1) + 1]
        t_e1[idx] = t_e1_stack[(idx - 1) + 1]
        sbd = sbd + t_e1bd[idx]
        sb = sb + t_e1b[idx]
        b_e1abd[co] = b_e1abd[co] + t_e1bd[idx]
        b_e1ab[co] = b_e1ab[co] + t_e1b[idx]
        t_e1bd[idx] = 0.0
        t_e1b[idx] = 0.0
        for i_seq_k = c_in * khkw:-1:1
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp1 * wp1 + (row - 1) * wp1 + col
            wi = (((co - 1) * c_in + (ci - 1)) * kh + (ki - 1)) * kw + kj
            xpad0bd[xi] = xpad0bd[xi] + (sb * w_e1ad[wi] + w_e1a[wi] * sbd)
            xpad0b[xi] = xpad0b[xi] + w_e1a[wi] * sb
            w_e1abd[wi] = w_e1abd[wi] + (sb * xpad0d[xi] + xpad0[xi] * sbd)
            w_e1ab[wi] = w_e1ab[wi] + xpad0[xi] * sb
        end
        sbd = 0.0
        sb = 0.0
    end
    for idx = c_in * hw:-1:1
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        yi = (ci - 1) * hp1 * wp1 + ((i + pad) - 1) * wp1 + (j + pad)
        xpad0d[yi] = xpad0_stack_d[(div(n_xpad0 - 1, 1) + 1) + ((idx - 1) + 1)]
        xpad0[yi] = xpad0_stack[(div(n_xpad0 - 1, 1) + 1) + ((idx - 1) + 1)]
        xbd[idx] = xbd[idx] + xpad0bd[yi]
        xb[idx] = xb[idx] + xpad0b[yi]
        xpad0bd[yi] = 0.0
        xpad0b[yi] = 0.0
    end
    for i = n_xpad0:-1:1
        xpad0d[i] = xpad0_stack_d[(i - 1) + 1]
        xpad0[i] = xpad0_stack[(i - 1) + 1]
        xpad0bd[i] = 0.0
        xpad0b[i] = 0.0
    end
    zero_valbd = 0.0
    zero_valb = 0.0
    return nothing
end

function unet(x, h, w, c_in, c1, c2, c3, c_out, w_e1a, b_e1a, w_e1b, b_e1b, w_e2a, b_e2a, w_e2b, b_e2b, w_ba, b_ba, w_bb, b_bb, w_d2a, b_d2a, w_d2b, b_d2b, w_d1a, b_d1a, w_d1b, b_d1b, w_out, b_out, xpad0, t_e1, t_e1pad, skip1, p1, p1pad, t_e2, t_e2pad, skip2, p2, p2pad, t_b, t_bpad, bott, u2, cat2, cat2pad, t_d2, t_d2pad, dec2out, u1, cat1, cat1pad, t_d1, t_d1pad, dec1out, y)
    two = 2
    four = 4
    h2 = div(h, two)
    w2 = div(w, two)
    h4 = div(h, four)
    w4 = div(w, four)
    hp1 = h + 2
    wp1 = w + 2
    hp2 = h2 + 2
    wp2 = w2 + 2
    hp4 = h4 + 2
    wp4 = w4 + 2
    pad = 1
    kh = 3
    kw = 3
    khkw = kh * kw
    kh_out = 1
    kw_out = 1
    khkw_out = kh_out * kw_out
    scale = 2
    zero_val = 0.0
    c32 = c3 + c2
    c21 = c2 + c1
    hw = h * w
    hw2 = h2 * w2
    hw4 = h4 * w4
    n_xpad0 = c_in * hp1 * wp1
    n_e1_mid = c1 * hw
    n_e1_midpad = c1 * hp1 * wp1
    n_e1_out = c1 * hw
    n_p1pad = c1 * hp2 * wp2
    n_e2_mid = c2 * hw2
    n_e2_midpad = c2 * hp2 * wp2
    n_e2_out = c2 * hw2
    n_p2pad = c2 * hp4 * wp4
    n_b_mid = c3 * hw4
    n_b_midpad = c3 * hp4 * wp4
    n_b_out = c3 * hw4
    n_cat2pad = c32 * hp2 * wp2
    n_d2_mid = c2 * hw2
    n_d2_midpad = c2 * hp2 * wp2
    n_d2_out = c2 * hw2
    n_cat1pad = c21 * hp1 * wp1
    n_d1_mid = c1 * hw
    n_d1_midpad = c1 * hp1 * wp1
    n_d1_out = c1 * hw
    for i = 1:n_xpad0
        xpad0[i] = zero_val
    end
    for idx = 1:c_in * hw
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        yi = (ci - 1) * hp1 * wp1 + ((i + pad) - 1) * wp1 + (j + pad)
        xpad0[yi] = x[idx]
    end
    for idx = 1:c1 * hw
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        s = 0.0
        for i_seq_k = 1:c_in * khkw
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp1 * wp1 + (row - 1) * wp1 + col
            wi = (((co - 1) * c_in + (ci - 1)) * kh + (ki - 1)) * kw + kj
            s = s + xpad0[xi] * w_e1a[wi]
        end
        t_e1[idx] = s + b_e1a[co]
    end
    for i = 1:n_e1_mid
        t_e1[i] = max(t_e1[i], zero_val)
    end
    for i = 1:n_e1_midpad
        t_e1pad[i] = zero_val
    end
    for idx = 1:c1 * hw
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        yi = (ci - 1) * hp1 * wp1 + ((i + pad) - 1) * wp1 + (j + pad)
        t_e1pad[yi] = t_e1[idx]
    end
    for idx = 1:c1 * hw
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        s = 0.0
        for i_seq_k = 1:c1 * khkw
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp1 * wp1 + (row - 1) * wp1 + col
            wi = (((co - 1) * c1 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            s = s + t_e1pad[xi] * w_e1b[wi]
        end
        skip1[idx] = s + b_e1b[co]
    end
    for i = 1:n_e1_out
        skip1[i] = max(skip1[i], zero_val)
    end
    for idx = 1:c1 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        oi = div(rem, w2) + 1
        oj = mod(rem, w2) + 1
        i0 = 2oi - 1
        j0 = 2oj - 1
        a11 = skip1[(ci - 1) * hw + (i0 - 1) * w + j0]
        a12 = skip1[(ci - 1) * hw + (i0 - 1) * w + j0 + 1]
        a21 = skip1[(ci - 1) * hw + i0 * w + j0]
        a22 = skip1[(ci - 1) * hw + i0 * w + j0 + 1]
        m1 = max(a11, a12)
        m2 = max(a21, a22)
        p1[idx] = max(m1, m2)
    end
    for i = 1:n_p1pad
        p1pad[i] = zero_val
    end
    for idx = 1:c1 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        yi = (ci - 1) * hp2 * wp2 + ((i + pad) - 1) * wp2 + (j + pad)
        p1pad[yi] = p1[idx]
    end
    for idx = 1:c2 * hw2
        idxm1 = idx - 1
        co = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        s = 0.0
        for i_seq_k = 1:c1 * khkw
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp2 * wp2 + (row - 1) * wp2 + col
            wi = (((co - 1) * c1 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            s = s + p1pad[xi] * w_e2a[wi]
        end
        t_e2[idx] = s + b_e2a[co]
    end
    for i = 1:n_e2_mid
        t_e2[i] = max(t_e2[i], zero_val)
    end
    for i = 1:n_e2_midpad
        t_e2pad[i] = zero_val
    end
    for idx = 1:c2 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        yi = (ci - 1) * hp2 * wp2 + ((i + pad) - 1) * wp2 + (j + pad)
        t_e2pad[yi] = t_e2[idx]
    end
    for idx = 1:c2 * hw2
        idxm1 = idx - 1
        co = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        s = 0.0
        for i_seq_k = 1:c2 * khkw
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp2 * wp2 + (row - 1) * wp2 + col
            wi = (((co - 1) * c2 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            s = s + t_e2pad[xi] * w_e2b[wi]
        end
        skip2[idx] = s + b_e2b[co]
    end
    for i = 1:n_e2_out
        skip2[i] = max(skip2[i], zero_val)
    end
    for idx = 1:c2 * hw4
        idxm1 = idx - 1
        ci = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        oi = div(rem, w4) + 1
        oj = mod(rem, w4) + 1
        i0 = 2oi - 1
        j0 = 2oj - 1
        a11 = skip2[(ci - 1) * hw2 + (i0 - 1) * w2 + j0]
        a12 = skip2[(ci - 1) * hw2 + (i0 - 1) * w2 + j0 + 1]
        a21 = skip2[(ci - 1) * hw2 + i0 * w2 + j0]
        a22 = skip2[(ci - 1) * hw2 + i0 * w2 + j0 + 1]
        m1 = max(a11, a12)
        m2 = max(a21, a22)
        p2[idx] = max(m1, m2)
    end
    for i = 1:n_p2pad
        p2pad[i] = zero_val
    end
    for idx = 1:c2 * hw4
        idxm1 = idx - 1
        ci = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        i = div(rem, w4) + 1
        j = mod(rem, w4) + 1
        yi = (ci - 1) * hp4 * wp4 + ((i + pad) - 1) * wp4 + (j + pad)
        p2pad[yi] = p2[idx]
    end
    for idx = 1:c3 * hw4
        idxm1 = idx - 1
        co = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        i = div(rem, w4) + 1
        j = mod(rem, w4) + 1
        s = 0.0
        for i_seq_k = 1:c2 * khkw
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp4 * wp4 + (row - 1) * wp4 + col
            wi = (((co - 1) * c2 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            s = s + p2pad[xi] * w_ba[wi]
        end
        t_b[idx] = s + b_ba[co]
    end
    for i = 1:n_b_mid
        t_b[i] = max(t_b[i], zero_val)
    end
    for i = 1:n_b_midpad
        t_bpad[i] = zero_val
    end
    for idx = 1:c3 * hw4
        idxm1 = idx - 1
        ci = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        i = div(rem, w4) + 1
        j = mod(rem, w4) + 1
        yi = (ci - 1) * hp4 * wp4 + ((i + pad) - 1) * wp4 + (j + pad)
        t_bpad[yi] = t_b[idx]
    end
    for idx = 1:c3 * hw4
        idxm1 = idx - 1
        co = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        i = div(rem, w4) + 1
        j = mod(rem, w4) + 1
        s = 0.0
        for i_seq_k = 1:c3 * khkw
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp4 * wp4 + (row - 1) * wp4 + col
            wi = (((co - 1) * c3 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            s = s + t_bpad[xi] * w_bb[wi]
        end
        bott[idx] = s + b_bb[co]
    end
    for i = 1:n_b_out
        bott[i] = max(bott[i], zero_val)
    end
    for idx = 1:c3 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        oi = div(rem, w2) + 1
        oj = mod(rem, w2) + 1
        oim1 = oi - 1
        ojm1 = oj - 1
        i = div(oim1, scale) + 1
        j = div(ojm1, scale) + 1
        xi = (ci - 1) * hw4 + (i - 1) * w4 + j
        u2[idx] = bott[xi]
    end
    for idx = 1:c3 * hw2
        cat2[idx] = u2[idx]
    end
    for idx = 1:c2 * hw2
        cat2[c3 * hw2 + idx] = skip2[idx]
    end
    for i = 1:n_cat2pad
        cat2pad[i] = zero_val
    end
    for idx = 1:c32 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        yi = (ci - 1) * hp2 * wp2 + ((i + pad) - 1) * wp2 + (j + pad)
        cat2pad[yi] = cat2[idx]
    end
    for idx = 1:c2 * hw2
        idxm1 = idx - 1
        co = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        s = 0.0
        for i_seq_k = 1:c32 * khkw
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp2 * wp2 + (row - 1) * wp2 + col
            wi = (((co - 1) * c32 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            s = s + cat2pad[xi] * w_d2a[wi]
        end
        t_d2[idx] = s + b_d2a[co]
    end
    for i = 1:n_d2_mid
        t_d2[i] = max(t_d2[i], zero_val)
    end
    for i = 1:n_d2_midpad
        t_d2pad[i] = zero_val
    end
    for idx = 1:c2 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        yi = (ci - 1) * hp2 * wp2 + ((i + pad) - 1) * wp2 + (j + pad)
        t_d2pad[yi] = t_d2[idx]
    end
    for idx = 1:c2 * hw2
        idxm1 = idx - 1
        co = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        s = 0.0
        for i_seq_k = 1:c2 * khkw
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp2 * wp2 + (row - 1) * wp2 + col
            wi = (((co - 1) * c2 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            s = s + t_d2pad[xi] * w_d2b[wi]
        end
        dec2out[idx] = s + b_d2b[co]
    end
    for i = 1:n_d2_out
        dec2out[i] = max(dec2out[i], zero_val)
    end
    for idx = 1:c2 * hw
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        oi = div(rem, w) + 1
        oj = mod(rem, w) + 1
        oim1 = oi - 1
        ojm1 = oj - 1
        i = div(oim1, scale) + 1
        j = div(ojm1, scale) + 1
        xi = (ci - 1) * hw2 + (i - 1) * w2 + j
        u1[idx] = dec2out[xi]
    end
    for idx = 1:c2 * hw
        cat1[idx] = u1[idx]
    end
    for idx = 1:c1 * hw
        cat1[c2 * hw + idx] = skip1[idx]
    end
    for i = 1:n_cat1pad
        cat1pad[i] = zero_val
    end
    for idx = 1:c21 * hw
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        yi = (ci - 1) * hp1 * wp1 + ((i + pad) - 1) * wp1 + (j + pad)
        cat1pad[yi] = cat1[idx]
    end
    for idx = 1:c1 * hw
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        s = 0.0
        for i_seq_k = 1:c21 * khkw
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp1 * wp1 + (row - 1) * wp1 + col
            wi = (((co - 1) * c21 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            s = s + cat1pad[xi] * w_d1a[wi]
        end
        t_d1[idx] = s + b_d1a[co]
    end
    for i = 1:n_d1_mid
        t_d1[i] = max(t_d1[i], zero_val)
    end
    for i = 1:n_d1_midpad
        t_d1pad[i] = zero_val
    end
    for idx = 1:c1 * hw
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        yi = (ci - 1) * hp1 * wp1 + ((i + pad) - 1) * wp1 + (j + pad)
        t_d1pad[yi] = t_d1[idx]
    end
    for idx = 1:c1 * hw
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        s = 0.0
        for i_seq_k = 1:c1 * khkw
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp1 * wp1 + (row - 1) * wp1 + col
            wi = (((co - 1) * c1 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            s = s + t_d1pad[xi] * w_d1b[wi]
        end
        dec1out[idx] = s + b_d1b[co]
    end
    for i = 1:n_d1_out
        dec1out[i] = max(dec1out[i], zero_val)
    end
    for idx = 1:c_out * hw
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        s = 0.0
        for i_seq_k = 1:c1 * khkw_out
            kseqm1 = i_seq_k - 1
            ci = div(kseqm1, khkw_out) + 1
            rem2 = mod(kseqm1, khkw_out)
            ki = div(rem2, kw_out) + 1
            kj = mod(rem2, kw_out) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hw + (row - 1) * w + col
            wi = (((co - 1) * c1 + (ci - 1)) * kh_out + (ki - 1)) * kw_out + kj
            s = s + dec1out[xi] * w_out[wi]
        end
        y[idx] = s + b_out[co]
    end
end
