function initstacks_transformer_b(dff, dk, h, n, n_layers)
    d = h * dk
    n_d = n * d
    n_dff = n * dff
    q_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1))
    k_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1))
    v_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1))
    scores_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * n - 1, 1) + 1))
    row_max_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) * max(0, div(n - 2, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n - 1, 1) + 1))
    probs_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) * max(0, div(n - 1, 1) + 1))
    ctx_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * dk - 1, 1) + 1))
    resid1_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1))
    row_mean_stack = Vector{Float64}(undef, ((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1)) + 1)
    row_var_stack = Vector{Float64}(undef, ((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1)) + 1)
    denom_stack = Vector{Float64}(undef, ((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1)) + 1)
    normed1_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) * max(0, div(d - 1, 1) + 1))
    ff_hidden_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_dff - 1, 1) + 1))
    resid2_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1))
    x_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1))
    row_sum_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n - 1, 1) + 1))
    s_stack = Vector{Float64}(undef, ((((((((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * dk - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_dff - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1))
    s2_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1))
    return (q_stack, k_stack, v_stack, scores_stack, row_max_stack, probs_stack, ctx_stack, resid1_stack, row_mean_stack, row_var_stack, denom_stack, normed1_stack, ff_hidden_stack, resid2_stack, x_stack, row_sum_stack, s_stack, s2_stack)
end

function transformer_hv(x, xb, wq, wqb, bq, bqb, wk, wkb, bk, bkb, wv, wvb, bv, bvb, wo, wob, bo, bob, ln1_gain, ln1_gainb, ln1_bias, ln1_biasb, w1, w1b, b1, b1b, w2, w2b, b2, b2b, ln2_gain, ln2_gainb, ln2_bias, ln2_biasb, q, qb, k, kb, v, vb, scores, scoresb, probs, probsb, ctx, ctxb, attn_out, attn_outb, resid1, resid1b, normed1, normed1b, ff_hidden, ff_hiddenb, ff_out, ff_outb, resid2, resid2b, x_next, x_nextb, n, dk, h, dff, n_layers, eps, epsb, xd, xbd, wqd, wqbd, bqd, bqbd, wkd, wkbd, bkd, bkbd, wvd, wvbd, bvd, bvbd, wod, wobd, bod, bobd, ln1_gaind, ln1_gainbd, ln1_biasd, ln1_biasbd, w1d, w1bd, b1d, b1bd, w2d, w2bd, b2d, b2bd, ln2_gaind, ln2_gainbd, ln2_biasd, ln2_biasbd, qd, qbd, kd, kbd, vd, vbd, scoresd, scoresbd, probsd, probsbd, ctxd, ctxbd, attn_outd, attn_outbd, resid1d, resid1bd, normed1d, normed1bd, ff_hiddend, ff_hiddenbd, ff_outd, ff_outbd, resid2d, resid2bd, x_nextd, x_nextbd, epsd, epsbd, q_stack, k_stack, v_stack, scores_stack, row_max_stack, probs_stack, ctx_stack, resid1_stack, row_mean_stack, row_var_stack, denom_stack, normed1_stack, ff_hidden_stack, resid2_stack, x_stack, row_sum_stack, s_stack, s2_stack)
    q_stack_d = Vector{Float64}(undef, length(q_stack))
    k_stack_d = Vector{Float64}(undef, length(k_stack))
    v_stack_d = Vector{Float64}(undef, length(v_stack))
    scores_stack_d = Vector{Float64}(undef, length(scores_stack))
    row_max_stack_d = Vector{Float64}(undef, length(row_max_stack))
    probs_stack_d = Vector{Float64}(undef, length(probs_stack))
    ctx_stack_d = Vector{Float64}(undef, length(ctx_stack))
    resid1_stack_d = Vector{Float64}(undef, length(resid1_stack))
    row_mean_stack_d = Vector{Float64}(undef, length(row_mean_stack))
    row_var_stack_d = Vector{Float64}(undef, length(row_var_stack))
    denom_stack_d = Vector{Float64}(undef, length(denom_stack))
    normed1_stack_d = Vector{Float64}(undef, length(normed1_stack))
    ff_hidden_stack_d = Vector{Float64}(undef, length(ff_hidden_stack))
    resid2_stack_d = Vector{Float64}(undef, length(resid2_stack))
    x_stack_d = Vector{Float64}(undef, length(x_stack))
    row_sum_stack_d = Vector{Float64}(undef, length(row_sum_stack))
    s_stack_d = Vector{Float64}(undef, length(s_stack))
    s2_stack_d = Vector{Float64}(undef, length(s2_stack))
    denom = 0.0
    diff = 0.0
    row_max = 0.0
    row_mean = 0.0
    row_sum = 0.0
    row_var = 0.0
    s = 0.0
    s2 = 0.0
    denomb = 0.0
    diffb = 0.0
    row_maxb = 0.0
    row_meanb = 0.0
    row_sumb = 0.0
    row_varb = 0.0
    sb = 0.0
    s2b = 0.0
    denomd = 0.0
    denombd = 0.0
    diffd = 0.0
    diffbd = 0.0
    inv_sqrt_dkd = 0.0
    inv_sqrt_dkbd = 0.0
    row_maxd = 0.0
    row_maxbd = 0.0
    row_meand = 0.0
    row_meanbd = 0.0
    row_sumd = 0.0
    row_sumbd = 0.0
    row_vard = 0.0
    row_varbd = 0.0
    sd = 0.0
    sbd = 0.0
    s2d = 0.0
    s2bd = 0.0
    d = h * dk
    inv_sqrt_dkd = 0.0
    inv_sqrt_dk = 1.0 / sqrt(dk)
    n_d = n * d
    n_dff = n * dff
    for i_l = 1:n_layers
        __icse_0 = i_l - 1
        w_offset = __icse_0 * d * d
        __icse_1 = __icse_0 * d
        b_offset = __icse_1
        ln_offset = __icse_1
        w1_offset = __icse_0 * d * dff
        b1_offset = __icse_0 * dff
        w2_offset = __icse_0 * dff * d
        b2_offset = __icse_1
        ln2_offset = __icse_1
        for idx = 1:n_d
            __icse_2 = idx - 1
            i = div(__icse_2, d) + 1
            j = mod(__icse_2, d) + 1
            sd = 0.0
            s = 0.0
            for i_p = 1:d
                __hcse_0 = wq[w_offset + (i_p - 1) * d + j]
                __hcse_1 = x[(i - 1) * d + i_p]
                sd = sd + (__hcse_0 * xd[(i - 1) * d + i_p] + __hcse_1 * wqd[w_offset + (i_p - 1) * d + j])
                s = s + __hcse_1 * __hcse_0
            end
            __icse_3 = ((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1
            __idx_q_stack_4 = __icse_3
            q_stack_d[__idx_q_stack_4] = qd[(i - 1) * d + j]
            q_stack[__idx_q_stack_4] = q[(i - 1) * d + j]
            qd[(i - 1) * d + j] = sd + bqd[b_offset + j]
            q[(i - 1) * d + j] = s + bq[b_offset + j]
            __idx_s_stack_7 = __icse_3
            s_stack_d[__idx_s_stack_7] = sd
            s_stack[__idx_s_stack_7] = s
        end
        for idx = 1:n_d
            __icse_4 = idx - 1
            i = div(__icse_4, d) + 1
            j = mod(__icse_4, d) + 1
            sd = 0.0
            s = 0.0
            for i_p = 1:d
                __hcse_2 = wk[w_offset + (i_p - 1) * d + j]
                __hcse_3 = x[(i - 1) * d + i_p]
                sd = sd + (__hcse_2 * xd[(i - 1) * d + i_p] + __hcse_3 * wkd[w_offset + (i_p - 1) * d + j])
                s = s + __hcse_3 * __hcse_2
            end
            __icse_5 = div(n_d - 1, 1) + 1
            __icse_6 = ((i_l - 1) * __icse_5 + (idx - 1)) + 1
            __idx_k_stack_4 = __icse_6
            k_stack_d[__idx_k_stack_4] = kd[(i - 1) * d + j]
            k_stack[__idx_k_stack_4] = k[(i - 1) * d + j]
            kd[(i - 1) * d + j] = sd + bkd[b_offset + j]
            k[(i - 1) * d + j] = s + bk[b_offset + j]
            __idx_s_stack_7 = max(0, div(n_layers - 1, 1) + 1) * max(0, __icse_5) + __icse_6
            s_stack_d[__idx_s_stack_7] = sd
            s_stack[__idx_s_stack_7] = s
        end
        for idx = 1:n_d
            __icse_7 = idx - 1
            i = div(__icse_7, d) + 1
            j = mod(__icse_7, d) + 1
            sd = 0.0
            s = 0.0
            for i_p = 1:d
                __hcse_4 = wv[w_offset + (i_p - 1) * d + j]
                __hcse_5 = x[(i - 1) * d + i_p]
                sd = sd + (__hcse_4 * xd[(i - 1) * d + i_p] + __hcse_5 * wvd[w_offset + (i_p - 1) * d + j])
                s = s + __hcse_5 * __hcse_4
            end
            __icse_8 = div(n_d - 1, 1) + 1
            __icse_9 = ((i_l - 1) * __icse_8 + (idx - 1)) + 1
            __idx_v_stack_4 = __icse_9
            v_stack_d[__idx_v_stack_4] = vd[(i - 1) * d + j]
            v_stack[__idx_v_stack_4] = v[(i - 1) * d + j]
            vd[(i - 1) * d + j] = sd + bvd[b_offset + j]
            v[(i - 1) * d + j] = s + bv[b_offset + j]
            __icse_10 = max(0, div(n_layers - 1, 1) + 1) * max(0, __icse_8)
            __idx_s_stack_7 = (__icse_10 + __icse_10) + __icse_9
            s_stack_d[__idx_s_stack_7] = sd
            s_stack[__idx_s_stack_7] = s
        end
        for hh = 1:h
            __icse_11 = hh - 1
            head_offset = __icse_11 * dk
            score_off = __icse_11 * n * n
            for idx2 = 1:n * n
                __icse_12 = idx2 - 1
                i = div(__icse_12, n) + 1
                j = mod(__icse_12, n) + 1
                sd = 0.0
                s = 0.0
                for i_p = 1:dk
                    __hcse_6 = k[(j - 1) * d + head_offset + i_p]
                    __hcse_7 = q[(i - 1) * d + head_offset + i_p]
                    sd = sd + (__hcse_6 * qd[(i - 1) * d + head_offset + i_p] + __hcse_7 * kd[(j - 1) * d + head_offset + i_p])
                    s = s + __hcse_7 * __hcse_6
                end
                __icse_13 = div(n * n - 1, 1) + 1
                __icse_14 = ((i_l - 1) * ((div(h - 1, 1) + 1) * __icse_13) + (hh - 1) * __icse_13 + (idx2 - 1)) + 1
                __idx_scores_stack_4 = __icse_14
                scores_stack_d[__idx_scores_stack_4] = scoresd[score_off + (i - 1) * n + j]
                scores_stack[__idx_scores_stack_4] = scores[score_off + (i - 1) * n + j]
                scoresd[score_off + (i - 1) * n + j] = inv_sqrt_dk * sd + s * inv_sqrt_dkd
                scores[score_off + (i - 1) * n + j] = s * inv_sqrt_dk
                __icse_15 = max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)
                __idx_s_stack_7 = ((__icse_15 + __icse_15) + __icse_15) + __icse_14
                s_stack_d[__idx_s_stack_7] = sd
                s_stack[__idx_s_stack_7] = s
            end
            for i = 1:n
                row_maxd = scoresd[score_off + (i - 1) * n + 1]
                row_max = scores[score_off + (i - 1) * n + 1]
                for i_j = 2:n
                    __icse_16 = div(n - 1, 1) + 1
                    __icse_17 = div(n - 2, 1) + 1
                    __idx_row_max_stack_0 = ((i_l - 1) * ((div(h - 1, 1) + 1) * __icse_16 * __icse_17) + (hh - 1) * (__icse_16 * __icse_17) + (i - 1) * __icse_17 + (i_j - 2)) + 1
                    row_max_stack_d[__idx_row_max_stack_0] = row_maxd
                    row_max_stack[__idx_row_max_stack_0] = row_max
                    __hcse_8 = scores[score_off + (i - 1) * n + i_j]
                    row_maxd = (0.5 * (1.0 + sign(row_max - __hcse_8))) * row_maxd + (0.5 * (1.0 + sign(__hcse_8 - row_max))) * scoresd[score_off + (i - 1) * n + i_j]
                    row_max = max(row_max, __hcse_8)
                end
                for j = 1:n
                    __icse_18 = i - 1
                    kk = score_off + __icse_18 * n + j
                    __icse_19 = div(n - 1, 1) + 1
                    __idx_probs_stack_1 = ((i_l - 1) * ((div(h - 1, 1) + 1) * __icse_19 * __icse_19) + (hh - 1) * (__icse_19 * __icse_19) + __icse_18 * __icse_19 + (j - 1)) + 1
                    probs_stack_d[__idx_probs_stack_1] = probsd[kk]
                    probs_stack[__idx_probs_stack_1] = probs[kk]
                    __hcse_9 = exp(scores[kk] - row_max)
                    probsd[kk] = __hcse_9 * (scoresd[kk] + -row_maxd)
                    probs[kk] = __hcse_9
                end
                row_sumd = 0.0
                row_sum = 0.0
                for i_j = 1:n
                    row_sumd = row_sumd + probsd[score_off + (i - 1) * n + i_j]
                    row_sum = row_sum + probs[score_off + (i - 1) * n + i_j]
                end
                for j = 1:n
                    __icse_20 = i - 1
                    kk = score_off + __icse_20 * n + j
                    __icse_21 = div(h - 1, 1) + 1
                    __icse_22 = div(n - 1, 1) + 1
                    __icse_23 = max(0, __icse_22)
                    __idx_probs_stack_1 = max(0, div(n_layers - 1, 1) + 1) * max(0, __icse_21) * __icse_23 * __icse_23 + (((i_l - 1) * (__icse_21 * __icse_22 * __icse_22) + (hh - 1) * (__icse_22 * __icse_22) + __icse_20 * __icse_22 + (j - 1)) + 1)
                    __cse_24d = probsd[kk]
                    __cse_24 = probs[kk]
                    probs_stack_d[__idx_probs_stack_1] = __cse_24d
                    probs_stack[__idx_probs_stack_1] = __cse_24
                    probsd[kk] = (1.0 / row_sum) * __cse_24d + -(__cse_24 / row_sum ^ 2) * row_sumd
                    probs[kk] = __cse_24 / row_sum
                end
                __icse_25 = div(h - 1, 1) + 1
                __icse_26 = div(n - 1, 1) + 1
                __icse_27 = ((i_l - 1) * (__icse_25 * __icse_26) + (hh - 1) * __icse_26 + (i - 1)) + 1
                __idx_row_max_stack_6 = max(0, div(n_layers - 1, 1) + 1) * max(0, __icse_25) * max(0, __icse_26) * max(0, div(n - 2, 1) + 1) + __icse_27
                row_max_stack_d[__idx_row_max_stack_6] = row_maxd
                row_max_stack[__idx_row_max_stack_6] = row_max
                __idx_row_sum_stack_8 = __icse_27
                row_sum_stack_d[__idx_row_sum_stack_8] = row_sumd
                row_sum_stack[__idx_row_sum_stack_8] = row_sum
            end
            for idx3 = 1:n * dk
                __icse_28 = idx3 - 1
                i = div(__icse_28, dk) + 1
                p = mod(__icse_28, dk) + 1
                sd = 0.0
                s = 0.0
                for i_j = 1:n
                    __hcse_10 = v[(i_j - 1) * d + head_offset + p]
                    __hcse_11 = probs[score_off + (i - 1) * n + i_j]
                    sd = sd + (__hcse_10 * probsd[score_off + (i - 1) * n + i_j] + __hcse_11 * vd[(i_j - 1) * d + head_offset + p])
                    s = s + __hcse_11 * __hcse_10
                end
                __icse_29 = div(h - 1, 1) + 1
                __icse_30 = div(n * dk - 1, 1) + 1
                __icse_31 = ((i_l - 1) * (__icse_29 * __icse_30) + (hh - 1) * __icse_30 + (idx3 - 1)) + 1
                __idx_ctx_stack_4 = __icse_31
                ctx_stack_d[__idx_ctx_stack_4] = ctxd[(i - 1) * d + head_offset + p]
                ctx_stack[__idx_ctx_stack_4] = ctx[(i - 1) * d + head_offset + p]
                ctxd[(i - 1) * d + head_offset + p] = sd
                ctx[(i - 1) * d + head_offset + p] = s
                __icse_32 = max(0, div(n_layers - 1, 1) + 1)
                __icse_33 = __icse_32 * max(0, div(n_d - 1, 1) + 1)
                __idx_s_stack_7 = (((__icse_33 + __icse_33) + __icse_33) + __icse_32 * max(0, __icse_29) * max(0, div(n * n - 1, 1) + 1)) + __icse_31
                s_stack_d[__idx_s_stack_7] = sd
                s_stack[__idx_s_stack_7] = s
            end
        end
        for idx = 1:n_d
            __icse_34 = idx - 1
            i = div(__icse_34, d) + 1
            j = mod(__icse_34, d) + 1
            sd = 0.0
            s = 0.0
            for i_p = 1:d
                __hcse_12 = wo[w_offset + (i_p - 1) * d + j]
                __hcse_13 = ctx[(i - 1) * d + i_p]
                sd = sd + (__hcse_12 * ctxd[(i - 1) * d + i_p] + __hcse_13 * wod[w_offset + (i_p - 1) * d + j])
                s = s + __hcse_13 * __hcse_12
            end
            attn_outd[(i - 1) * d + j] = sd + bod[b_offset + j]
            attn_out[(i - 1) * d + j] = s + bo[b_offset + j]
            __icse_35 = max(0, div(n_layers - 1, 1) + 1)
            __icse_36 = div(n_d - 1, 1) + 1
            __icse_37 = __icse_35 * max(0, __icse_36)
            __icse_38 = max(0, div(h - 1, 1) + 1)
            __idx_s_stack_5 = ((((__icse_37 + __icse_37) + __icse_37) + __icse_35 * __icse_38 * max(0, div(n * n - 1, 1) + 1)) + __icse_35 * __icse_38 * max(0, div(n * dk - 1, 1) + 1)) + (((i_l - 1) * __icse_36 + (idx - 1)) + 1)
            s_stack_d[__idx_s_stack_5] = sd
            s_stack[__idx_s_stack_5] = s
        end
        for idx = 1:n_d
            __idx_resid1_stack_0 = ((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1
            resid1_stack_d[__idx_resid1_stack_0] = resid1d[idx]
            resid1_stack[__idx_resid1_stack_0] = resid1[idx]
            resid1d[idx] = xd[idx] + attn_outd[idx]
            resid1[idx] = x[idx] + attn_out[idx]
        end
        for i = 1:n
            sd = 0.0
            s = 0.0
            for i_j = 1:d
                sd = sd + resid1d[(i - 1) * d + i_j]
                s = s + resid1[(i - 1) * d + i_j]
            end
            __idx_row_mean_stack_2 = ((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1
            row_mean_stack_d[__idx_row_mean_stack_2] = row_meand
            row_mean_stack[__idx_row_mean_stack_2] = row_mean
            row_meand = (1.0 / d) * sd
            row_mean = s / d
            s2d = 0.0
            s2 = 0.0
            for i_j = 1:d
                diffd = resid1d[(i - 1) * d + i_j] + -row_meand
                diff = resid1[(i - 1) * d + i_j] - row_mean
                __hcse_14 = diff * diffd
                s2d = s2d + (__hcse_14 + __hcse_14)
                s2 = s2 + diff * diff
            end
            __icse_39 = ((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1
            __idx_row_var_stack_7 = __icse_39
            row_var_stack_d[__idx_row_var_stack_7] = row_vard
            row_var_stack[__idx_row_var_stack_7] = row_var
            row_vard = (1.0 / d) * s2d
            row_var = s2 / d
            __idx_denom_stack_10 = __icse_39
            denom_stack_d[__idx_denom_stack_10] = denomd
            denom_stack[__idx_denom_stack_10] = denom
            __hcse_15 = sqrt(row_var + eps)
            denomd = (1.0 / (2.0__hcse_15)) * (row_vard + epsd)
            denom = __hcse_15
            for j = 1:d
                __icse_40 = i - 1
                kk = __icse_40 * d + j
                __icse_41 = div(d - 1, 1) + 1
                __idx_normed1_stack_1 = ((i_l - 1) * ((div(n - 1, 1) + 1) * __icse_41) + __icse_40 * __icse_41 + (j - 1)) + 1
                normed1_stack_d[__idx_normed1_stack_1] = normed1d[kk]
                normed1_stack[__idx_normed1_stack_1] = normed1[kk]
                __hcse_16 = ln1_gain[ln_offset + j]
                __hcse_17 = resid1[kk] - row_mean
                __hcse_18 = __hcse_17 / denom
                normed1d[kk] = (__hcse_16 * ((1.0 / denom) * (resid1d[kk] + -row_meand) + -(__hcse_17 / denom ^ 2) * denomd) + __hcse_18 * ln1_gaind[ln_offset + j]) + ln1_biasd[ln_offset + j]
                normed1[kk] = __hcse_18 * __hcse_16 + ln1_bias[ln_offset + j]
            end
            __icse_42 = max(0, div(n_layers - 1, 1) + 1)
            __icse_43 = __icse_42 * max(0, div(n_d - 1, 1) + 1)
            __icse_44 = max(0, div(h - 1, 1) + 1)
            __icse_45 = ((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1
            __idx_s_stack_14 = (((((__icse_43 + __icse_43) + __icse_43) + __icse_42 * __icse_44 * max(0, div(n * n - 1, 1) + 1)) + __icse_42 * __icse_44 * max(0, div(n * dk - 1, 1) + 1)) + __icse_43) + __icse_45
            s_stack_d[__idx_s_stack_14] = sd
            s_stack[__idx_s_stack_14] = s
            __idx_s2_stack_16 = __icse_45
            s2_stack_d[__idx_s2_stack_16] = s2d
            s2_stack[__idx_s2_stack_16] = s2
        end
        for idx = 1:n_dff
            __icse_46 = idx - 1
            i = div(__icse_46, dff) + 1
            j = mod(__icse_46, dff) + 1
            sd = 0.0
            s = 0.0
            for i_p = 1:d
                __hcse_19 = w1[w1_offset + (i_p - 1) * dff + j]
                __hcse_20 = normed1[(i - 1) * d + i_p]
                sd = sd + (__hcse_19 * normed1d[(i - 1) * d + i_p] + __hcse_20 * w1d[w1_offset + (i_p - 1) * dff + j])
                s = s + __hcse_20 * __hcse_19
            end
            __icse_47 = ((i_l - 1) * (div(n_dff - 1, 1) + 1) + (idx - 1)) + 1
            __idx_ff_hidden_stack_4 = __icse_47
            ff_hidden_stack_d[__idx_ff_hidden_stack_4] = ff_hiddend[(i - 1) * dff + j]
            ff_hidden_stack[__idx_ff_hidden_stack_4] = ff_hidden[(i - 1) * dff + j]
            __hcse_21 = s + b1[b1_offset + j]
            ff_hiddend[(i - 1) * dff + j] = (0.5 * (1.0 + sign(__hcse_21))) * (sd + b1d[b1_offset + j])
            ff_hidden[(i - 1) * dff + j] = max(__hcse_21, 0.0)
            __icse_48 = max(0, div(n_layers - 1, 1) + 1)
            __icse_49 = __icse_48 * max(0, div(n_d - 1, 1) + 1)
            __icse_50 = max(0, div(h - 1, 1) + 1)
            __idx_s_stack_7 = ((((((__icse_49 + __icse_49) + __icse_49) + __icse_48 * __icse_50 * max(0, div(n * n - 1, 1) + 1)) + __icse_48 * __icse_50 * max(0, div(n * dk - 1, 1) + 1)) + __icse_49) + __icse_48 * max(0, div(n - 1, 1) + 1)) + __icse_47
            s_stack_d[__idx_s_stack_7] = sd
            s_stack[__idx_s_stack_7] = s
        end
        for idx = 1:n_d
            __icse_51 = idx - 1
            i = div(__icse_51, d) + 1
            j = mod(__icse_51, d) + 1
            sd = 0.0
            s = 0.0
            for i_p = 1:dff
                __hcse_22 = w2[w2_offset + (i_p - 1) * d + j]
                __hcse_23 = ff_hidden[(i - 1) * dff + i_p]
                sd = sd + (__hcse_22 * ff_hiddend[(i - 1) * dff + i_p] + __hcse_23 * w2d[w2_offset + (i_p - 1) * d + j])
                s = s + __hcse_23 * __hcse_22
            end
            ff_outd[(i - 1) * d + j] = sd + b2d[b2_offset + j]
            ff_out[(i - 1) * d + j] = s + b2[b2_offset + j]
            __icse_52 = max(0, div(n_layers - 1, 1) + 1)
            __icse_53 = div(n_d - 1, 1) + 1
            __icse_54 = __icse_52 * max(0, __icse_53)
            __icse_55 = max(0, div(h - 1, 1) + 1)
            __idx_s_stack_5 = (((((((__icse_54 + __icse_54) + __icse_54) + __icse_52 * __icse_55 * max(0, div(n * n - 1, 1) + 1)) + __icse_52 * __icse_55 * max(0, div(n * dk - 1, 1) + 1)) + __icse_54) + __icse_52 * max(0, div(n - 1, 1) + 1)) + __icse_52 * max(0, div(n_dff - 1, 1) + 1)) + (((i_l - 1) * __icse_53 + (idx - 1)) + 1)
            s_stack_d[__idx_s_stack_5] = sd
            s_stack[__idx_s_stack_5] = s
        end
        for idx = 1:n_d
            __idx_resid2_stack_0 = ((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1
            resid2_stack_d[__idx_resid2_stack_0] = resid2d[idx]
            resid2_stack[__idx_resid2_stack_0] = resid2[idx]
            resid2d[idx] = normed1d[idx] + ff_outd[idx]
            resid2[idx] = normed1[idx] + ff_out[idx]
        end
        for i = 1:n
            sd = 0.0
            s = 0.0
            for i_j = 1:d
                sd = sd + resid2d[(i - 1) * d + i_j]
                s = s + resid2[(i - 1) * d + i_j]
            end
            __icse_56 = div(n - 1, 1) + 1
            __idx_row_mean_stack_2 = max(0, div(n_layers - 1, 1) + 1) * max(0, __icse_56) + (((i_l - 1) * __icse_56 + (i - 1)) + 1)
            row_mean_stack_d[__idx_row_mean_stack_2] = row_meand
            row_mean_stack[__idx_row_mean_stack_2] = row_mean
            row_meand = (1.0 / d) * sd
            row_mean = s / d
            s2d = 0.0
            s2 = 0.0
            for i_j = 1:d
                diffd = resid2d[(i - 1) * d + i_j] + -row_meand
                diff = resid2[(i - 1) * d + i_j] - row_mean
                __hcse_24 = diff * diffd
                s2d = s2d + (__hcse_24 + __hcse_24)
                s2 = s2 + diff * diff
            end
            __icse_57 = div(n - 1, 1) + 1
            __icse_58 = max(0, div(n_layers - 1, 1) + 1) * max(0, __icse_57) + (((i_l - 1) * __icse_57 + (i - 1)) + 1)
            __idx_row_var_stack_7 = __icse_58
            row_var_stack_d[__idx_row_var_stack_7] = row_vard
            row_var_stack[__idx_row_var_stack_7] = row_var
            row_vard = (1.0 / d) * s2d
            row_var = s2 / d
            __idx_denom_stack_10 = __icse_58
            denom_stack_d[__idx_denom_stack_10] = denomd
            denom_stack[__idx_denom_stack_10] = denom
            __hcse_25 = sqrt(row_var + eps)
            denomd = (1.0 / (2.0__hcse_25)) * (row_vard + epsd)
            denom = __hcse_25
            for j = 1:d
                kk = (i - 1) * d + j
                __hcse_26 = ln2_gain[ln2_offset + j]
                __hcse_27 = resid2[kk] - row_mean
                __hcse_28 = __hcse_27 / denom
                x_nextd[kk] = (__hcse_26 * ((1.0 / denom) * (resid2d[kk] + -row_meand) + -(__hcse_27 / denom ^ 2) * denomd) + __hcse_28 * ln2_gaind[ln2_offset + j]) + ln2_biasd[ln2_offset + j]
                x_next[kk] = __hcse_28 * __hcse_26 + ln2_bias[ln2_offset + j]
            end
            __icse_59 = max(0, div(n_layers - 1, 1) + 1)
            __icse_60 = __icse_59 * max(0, div(n_d - 1, 1) + 1)
            __icse_61 = max(0, div(h - 1, 1) + 1)
            __icse_62 = div(n - 1, 1) + 1
            __icse_63 = __icse_59 * max(0, __icse_62)
            __icse_64 = ((i_l - 1) * __icse_62 + (i - 1)) + 1
            __idx_s_stack_14 = ((((((((__icse_60 + __icse_60) + __icse_60) + __icse_59 * __icse_61 * max(0, div(n * n - 1, 1) + 1)) + __icse_59 * __icse_61 * max(0, div(n * dk - 1, 1) + 1)) + __icse_60) + __icse_63) + __icse_59 * max(0, div(n_dff - 1, 1) + 1)) + __icse_60) + __icse_64
            s_stack_d[__idx_s_stack_14] = sd
            s_stack[__idx_s_stack_14] = s
            __idx_s2_stack_16 = __icse_63 + __icse_64
            s2_stack_d[__idx_s2_stack_16] = s2d
            s2_stack[__idx_s2_stack_16] = s2
        end
        for idx = 1:n_d
            __idx_x_stack_0 = ((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1
            x_stack_d[__idx_x_stack_0] = xd[idx]
            x_stack[__idx_x_stack_0] = x[idx]
            xd[idx] = x_nextd[idx]
            x[idx] = x_next[idx]
        end
        __icse_65 = max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)
        __icse_66 = (__icse_65 + __icse_65) + ((i_l - 1) + 1)
        __idx_denom_stack_20 = __icse_66
        denom_stack_d[__idx_denom_stack_20] = denomd
        denom_stack[__idx_denom_stack_20] = denom
        __idx_row_mean_stack_22 = __icse_66
        row_mean_stack_d[__idx_row_mean_stack_22] = row_meand
        row_mean_stack[__idx_row_mean_stack_22] = row_mean
        __idx_row_var_stack_24 = __icse_66
        row_var_stack_d[__idx_row_var_stack_24] = row_vard
        row_var_stack[__idx_row_var_stack_24] = row_var
    end
    __ihcse_29 = max(0, div(n_layers - 1, 1) + 1)
    __icse_67 = __ihcse_29
    __ihcse_30 = max(0, div(n - 1, 1) + 1)
    __icse_68 = __icse_67 * __ihcse_30
    __icse_69 = ((__icse_68 + __icse_68) + __icse_67) + 1
    __idx_denom_stack_5 = __icse_69
    denom_stack_d[__idx_denom_stack_5] = denomd
    denom_stack[__idx_denom_stack_5] = denom
    __idx_row_mean_stack_7 = __icse_69
    row_mean_stack_d[__idx_row_mean_stack_7] = row_meand
    row_mean_stack[__idx_row_mean_stack_7] = row_mean
    __idx_row_var_stack_9 = __icse_69
    row_var_stack_d[__idx_row_var_stack_9] = row_vard
    row_var_stack[__idx_row_var_stack_9] = row_var
    __icse_70 = __ihcse_29
    __icse_71 = __icse_70 * __ihcse_30
    __icse_72 = ((__icse_71 + __icse_71) + __icse_70) + 1
    __idx_denom_stack_0 = __icse_72
    denomd = denom_stack_d[__idx_denom_stack_0]
    denom = denom_stack[__idx_denom_stack_0]
    __idx_row_mean_stack_2 = __icse_72
    row_meand = row_mean_stack_d[__idx_row_mean_stack_2]
    row_mean = row_mean_stack[__idx_row_mean_stack_2]
    __idx_row_var_stack_4 = __icse_72
    row_vard = row_var_stack_d[__idx_row_var_stack_4]
    row_var = row_var_stack[__idx_row_var_stack_4]
    d = h * dk
    n_d = n * d
    n_dff = n * dff
    for i_l = n_layers:-1:1
        __icse_73 = max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)
        __icse_74 = i_l - 1
        __icse_75 = (__icse_73 + __icse_73) + (__icse_74 + 1)
        __idx_denom_stack_0 = __icse_75
        denomd = denom_stack_d[__idx_denom_stack_0]
        denom = denom_stack[__idx_denom_stack_0]
        __idx_row_mean_stack_2 = __icse_75
        row_meand = row_mean_stack_d[__idx_row_mean_stack_2]
        row_mean = row_mean_stack[__idx_row_mean_stack_2]
        __idx_row_var_stack_4 = __icse_75
        row_vard = row_var_stack_d[__idx_row_var_stack_4]
        row_var = row_var_stack[__idx_row_var_stack_4]
        w_offset = __icse_74 * d * d
        __icse_76 = __icse_74 * d
        b_offset = __icse_76
        ln_offset = __icse_76
        w1_offset = __icse_74 * d * dff
        b1_offset = __icse_74 * dff
        w2_offset = __icse_74 * dff * d
        b2_offset = __icse_76
        ln2_offset = __icse_76
        for idx = n_d:-1:1
            __idx_x_stack_0 = ((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1
            xd[idx] = x_stack_d[__idx_x_stack_0]
            x[idx] = x_stack[__idx_x_stack_0]
            __oldb_2d = xbd[idx]
            __oldb_2 = xb[idx]
            xbd[idx] = 0.0
            xb[idx] = 0.0
            x_nextbd[idx] = x_nextbd[idx] + __oldb_2d
            x_nextb[idx] = x_nextb[idx] + __oldb_2
        end
        for i = n:-1:1
            __icse_77 = max(0, div(n_layers - 1, 1) + 1)
            __icse_78 = __icse_77 * max(0, div(n_d - 1, 1) + 1)
            __icse_79 = max(0, div(h - 1, 1) + 1)
            __icse_80 = div(n - 1, 1) + 1
            __icse_81 = __icse_77 * max(0, __icse_80)
            __icse_82 = ((i_l - 1) * __icse_80 + (i - 1)) + 1
            __idx_s_stack_0 = ((((((((__icse_78 + __icse_78) + __icse_78) + __icse_77 * __icse_79 * max(0, div(n * n - 1, 1) + 1)) + __icse_77 * __icse_79 * max(0, div(n * dk - 1, 1) + 1)) + __icse_78) + __icse_81) + __icse_77 * max(0, div(n_dff - 1, 1) + 1)) + __icse_78) + __icse_82
            sd = s_stack_d[__idx_s_stack_0]
            s = s_stack[__idx_s_stack_0]
            __idx_s2_stack_2 = __icse_81 + __icse_82
            s2d = s2_stack_d[__idx_s2_stack_2]
            s2 = s2_stack[__idx_s2_stack_2]
            for j = d:-1:1
                kk = (i - 1) * d + j
                __oldb_0d = x_nextbd[kk]
                __oldb_0 = x_nextb[kk]
                x_nextbd[kk] = 0.0
                x_nextb[kk] = 0.0
                __hcse_31 = ln2_gain[ln2_offset + j]
                __cse_83d = __oldb_0 * ln2_gaind[ln2_offset + j] + __hcse_31 * __oldb_0d
                __cse_83 = __hcse_31 * __oldb_0
                __hcse_32 = denom ^ 2
                __hcse_33 = 1.0 / __hcse_32
                __hcse_34 = 1.0 / denom
                __cse_84d = __cse_83 * (-__hcse_33 * denomd) + __hcse_34 * __cse_83d
                __cse_84 = __hcse_34 * __cse_83
                resid2bd[kk] = resid2bd[kk] + __cse_84d
                resid2b[kk] = resid2b[kk] + __cse_84
                row_meanbd = row_meanbd + -__cse_84d
                row_meanb = row_meanb + -__cse_84
                __cse_85d = resid2d[kk] + -row_meand
                __cse_85 = resid2[kk] - row_mean
                __hcse_35 = -(__cse_85 / __hcse_32)
                denombd = denombd + (__cse_83 * -((__hcse_33 * __cse_85d + -(__cse_85 / __hcse_32 ^ 2) * ((2denom) * denomd))) + __hcse_35 * __cse_83d)
                denomb = denomb + __hcse_35 * __cse_83
                __hcse_36 = __cse_85 / denom
                ln2_gainbd[ln2_offset + j] = ln2_gainbd[ln2_offset + j] + (__oldb_0 * (__hcse_34 * __cse_85d + __hcse_35 * denomd) + __hcse_36 * __oldb_0d)
                ln2_gainb[ln2_offset + j] = ln2_gainb[ln2_offset + j] + __hcse_36 * __oldb_0
                ln2_biasbd[ln2_offset + j] = ln2_biasbd[ln2_offset + j] + __oldb_0d
                ln2_biasb[ln2_offset + j] = ln2_biasb[ln2_offset + j] + __oldb_0
            end
            __icse_86 = div(n - 1, 1) + 1
            __icse_87 = max(0, div(n_layers - 1, 1) + 1) * max(0, __icse_86) + (((i_l - 1) * __icse_86 + (i - 1)) + 1)
            __idx_denom_stack_0 = __icse_87
            denomd = denom_stack_d[__idx_denom_stack_0]
            denom = denom_stack[__idx_denom_stack_0]
            __oldb_2d = denombd
            __oldb_2 = denomb
            denombd = 0.0
            denomb = 0.0
            __hcse_37 = 2.0 * sqrt(row_var + eps)
            __hcse_38 = 1.0 / __hcse_37
            __cse_88d = __oldb_2 * (-(1.0 / __hcse_37 ^ 2) * (2.0 * (__hcse_38 * (row_vard + epsd)))) + __hcse_38 * __oldb_2d
            __cse_88 = __hcse_38 * __oldb_2
            row_varbd = row_varbd + __cse_88d
            row_varb = row_varb + __cse_88
            epsbd = epsbd + __cse_88d
            epsb = epsb + __cse_88
            __idx_row_var_stack_0 = __icse_87
            row_vard = row_var_stack_d[__idx_row_var_stack_0]
            row_var = row_var_stack[__idx_row_var_stack_0]
            __oldb_2d = row_varbd
            __oldb_2 = row_varb
            row_varbd = 0.0
            row_varb = 0.0
            __ihcse_39 = 1.0 / d
            s2bd = s2bd + __ihcse_39 * __oldb_2d
            s2b = s2b + __ihcse_39 * __oldb_2
            for i_j = 1:d
                diffd = resid2d[(i - 1) * d + i_j] + -row_meand
                diff = resid2[(i - 1) * d + i_j] - row_mean
                __hcse_40 = diff * diffd
                s2d = s2d + (__hcse_40 + __hcse_40)
                s2 = s2 + diff * diff
                __cse_89d = s2b * diffd + diff * s2bd
                __cse_89 = diff * s2b
                diffbd = diffbd + __cse_89d
                diffb = diffb + __cse_89
                diffbd = diffbd + __cse_89d
                diffb = diffb + __cse_89
                __oldb_0d = diffbd
                __oldb_0 = diffb
                diffbd = 0.0
                diffb = 0.0
                resid2bd[(i - 1) * d + i_j] = resid2bd[(i - 1) * d + i_j] + __oldb_0d
                resid2b[(i - 1) * d + i_j] = resid2b[(i - 1) * d + i_j] + __oldb_0
                row_meanbd = row_meanbd + -__oldb_0d
                row_meanb = row_meanb + -__oldb_0
            end
            s2bd = 0.0
            s2b = 0.0
            __icse_90 = div(n - 1, 1) + 1
            __idx_row_mean_stack_0 = max(0, div(n_layers - 1, 1) + 1) * max(0, __icse_90) + (((i_l - 1) * __icse_90 + (i - 1)) + 1)
            row_meand = row_mean_stack_d[__idx_row_mean_stack_0]
            row_mean = row_mean_stack[__idx_row_mean_stack_0]
            __oldb_2d = row_meanbd
            __oldb_2 = row_meanb
            row_meanbd = 0.0
            row_meanb = 0.0
            __ihcse_41 = 1.0 / d
            sbd = sbd + __ihcse_41 * __oldb_2d
            sb = sb + __ihcse_41 * __oldb_2
            for i_j = 1:d
                sd = sd + resid2d[(i - 1) * d + i_j]
                s = s + resid2[(i - 1) * d + i_j]
                resid2bd[(i - 1) * d + i_j] = resid2bd[(i - 1) * d + i_j] + sbd
                resid2b[(i - 1) * d + i_j] = resid2b[(i - 1) * d + i_j] + sb
            end
            sbd = 0.0
            sb = 0.0
        end
        for idx = n_d:-1:1
            __idx_resid2_stack_0 = ((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1
            resid2d[idx] = resid2_stack_d[__idx_resid2_stack_0]
            resid2[idx] = resid2_stack[__idx_resid2_stack_0]
            __oldb_2d = resid2bd[idx]
            __oldb_2 = resid2b[idx]
            resid2bd[idx] = 0.0
            resid2b[idx] = 0.0
            normed1bd[idx] = normed1bd[idx] + __oldb_2d
            normed1b[idx] = normed1b[idx] + __oldb_2
            ff_outbd[idx] = ff_outbd[idx] + __oldb_2d
            ff_outb[idx] = ff_outb[idx] + __oldb_2
        end
        for idx = n_d:-1:1
            __icse_91 = max(0, div(n_layers - 1, 1) + 1)
            __icse_92 = div(n_d - 1, 1) + 1
            __icse_93 = __icse_91 * max(0, __icse_92)
            __icse_94 = max(0, div(h - 1, 1) + 1)
            __icse_95 = idx - 1
            __idx_s_stack_0 = (((((((__icse_93 + __icse_93) + __icse_93) + __icse_91 * __icse_94 * max(0, div(n * n - 1, 1) + 1)) + __icse_91 * __icse_94 * max(0, div(n * dk - 1, 1) + 1)) + __icse_93) + __icse_91 * max(0, div(n - 1, 1) + 1)) + __icse_91 * max(0, div(n_dff - 1, 1) + 1)) + (((i_l - 1) * __icse_92 + __icse_95) + 1)
            sd = s_stack_d[__idx_s_stack_0]
            s = s_stack[__idx_s_stack_0]
            i = div(__icse_95, d) + 1
            j = mod(__icse_95, d) + 1
            __oldb_0d = ff_outbd[(i - 1) * d + j]
            __oldb_0 = ff_outb[(i - 1) * d + j]
            ff_outbd[(i - 1) * d + j] = 0.0
            ff_outb[(i - 1) * d + j] = 0.0
            sbd = sbd + __oldb_0d
            sb = sb + __oldb_0
            b2bd[b2_offset + j] = b2bd[b2_offset + j] + __oldb_0d
            b2b[b2_offset + j] = b2b[b2_offset + j] + __oldb_0
            for i_p = 1:dff
                __cse_96d = ff_hiddend[(i - 1) * dff + i_p]
                __cse_96 = ff_hidden[(i - 1) * dff + i_p]
                __cse_97d = w2d[w2_offset + (i_p - 1) * d + j]
                __cse_97 = w2[w2_offset + (i_p - 1) * d + j]
                sd = sd + (__cse_97 * __cse_96d + __cse_96 * __cse_97d)
                s = s + __cse_96 * __cse_97
                ff_hiddenbd[(i - 1) * dff + i_p] = ff_hiddenbd[(i - 1) * dff + i_p] + (sb * __cse_97d + __cse_97 * sbd)
                ff_hiddenb[(i - 1) * dff + i_p] = ff_hiddenb[(i - 1) * dff + i_p] + __cse_97 * sb
                w2bd[w2_offset + (i_p - 1) * d + j] = w2bd[w2_offset + (i_p - 1) * d + j] + (sb * __cse_96d + __cse_96 * sbd)
                w2b[w2_offset + (i_p - 1) * d + j] = w2b[w2_offset + (i_p - 1) * d + j] + __cse_96 * sb
            end
            sbd = 0.0
            sb = 0.0
        end
        for idx = n_dff:-1:1
            __icse_98 = max(0, div(n_layers - 1, 1) + 1)
            __icse_99 = __icse_98 * max(0, div(n_d - 1, 1) + 1)
            __icse_100 = max(0, div(h - 1, 1) + 1)
            __icse_101 = idx - 1
            __icse_102 = ((i_l - 1) * (div(n_dff - 1, 1) + 1) + __icse_101) + 1
            __idx_s_stack_0 = ((((((__icse_99 + __icse_99) + __icse_99) + __icse_98 * __icse_100 * max(0, div(n * n - 1, 1) + 1)) + __icse_98 * __icse_100 * max(0, div(n * dk - 1, 1) + 1)) + __icse_99) + __icse_98 * max(0, div(n - 1, 1) + 1)) + __icse_102
            sd = s_stack_d[__idx_s_stack_0]
            s = s_stack[__idx_s_stack_0]
            i = div(__icse_101, dff) + 1
            j = mod(__icse_101, dff) + 1
            __idx_ff_hidden_stack_0 = __icse_102
            ff_hiddend[(i - 1) * dff + j] = ff_hidden_stack_d[__idx_ff_hidden_stack_0]
            ff_hidden[(i - 1) * dff + j] = ff_hidden_stack[__idx_ff_hidden_stack_0]
            __oldb_2d = ff_hiddenbd[(i - 1) * dff + j]
            __oldb_2 = ff_hiddenb[(i - 1) * dff + j]
            ff_hiddenbd[(i - 1) * dff + j] = 0.0
            ff_hiddenb[(i - 1) * dff + j] = 0.0
            __hcse_42 = 0.5 * (1.0 + sign(s + b1[b1_offset + j]))
            __cse_103d = __hcse_42 * __oldb_2d
            __cse_103 = __hcse_42 * __oldb_2
            sbd = sbd + __cse_103d
            sb = sb + __cse_103
            b1bd[b1_offset + j] = b1bd[b1_offset + j] + __cse_103d
            b1b[b1_offset + j] = b1b[b1_offset + j] + __cse_103
            for i_p = 1:d
                __cse_104d = normed1d[(i - 1) * d + i_p]
                __cse_104 = normed1[(i - 1) * d + i_p]
                __cse_105d = w1d[w1_offset + (i_p - 1) * dff + j]
                __cse_105 = w1[w1_offset + (i_p - 1) * dff + j]
                sd = sd + (__cse_105 * __cse_104d + __cse_104 * __cse_105d)
                s = s + __cse_104 * __cse_105
                normed1bd[(i - 1) * d + i_p] = normed1bd[(i - 1) * d + i_p] + (sb * __cse_105d + __cse_105 * sbd)
                normed1b[(i - 1) * d + i_p] = normed1b[(i - 1) * d + i_p] + __cse_105 * sb
                w1bd[w1_offset + (i_p - 1) * dff + j] = w1bd[w1_offset + (i_p - 1) * dff + j] + (sb * __cse_104d + __cse_104 * sbd)
                w1b[w1_offset + (i_p - 1) * dff + j] = w1b[w1_offset + (i_p - 1) * dff + j] + __cse_104 * sb
            end
            sbd = 0.0
            sb = 0.0
        end
        for i = n:-1:1
            __icse_106 = max(0, div(n_layers - 1, 1) + 1)
            __icse_107 = __icse_106 * max(0, div(n_d - 1, 1) + 1)
            __icse_108 = max(0, div(h - 1, 1) + 1)
            __icse_109 = ((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1
            __idx_s_stack_0 = (((((__icse_107 + __icse_107) + __icse_107) + __icse_106 * __icse_108 * max(0, div(n * n - 1, 1) + 1)) + __icse_106 * __icse_108 * max(0, div(n * dk - 1, 1) + 1)) + __icse_107) + __icse_109
            sd = s_stack_d[__idx_s_stack_0]
            s = s_stack[__idx_s_stack_0]
            __idx_s2_stack_2 = __icse_109
            s2d = s2_stack_d[__idx_s2_stack_2]
            s2 = s2_stack[__idx_s2_stack_2]
            for j = d:-1:1
                __icse_110 = i - 1
                kk = __icse_110 * d + j
                __icse_111 = div(d - 1, 1) + 1
                __idx_normed1_stack_0 = ((i_l - 1) * ((div(n - 1, 1) + 1) * __icse_111) + __icse_110 * __icse_111 + (j - 1)) + 1
                normed1d[kk] = normed1_stack_d[__idx_normed1_stack_0]
                normed1[kk] = normed1_stack[__idx_normed1_stack_0]
                __oldb_2d = normed1bd[kk]
                __oldb_2 = normed1b[kk]
                normed1bd[kk] = 0.0
                normed1b[kk] = 0.0
                __hcse_43 = ln1_gain[ln_offset + j]
                __cse_112d = __oldb_2 * ln1_gaind[ln_offset + j] + __hcse_43 * __oldb_2d
                __cse_112 = __hcse_43 * __oldb_2
                __hcse_44 = denom ^ 2
                __hcse_45 = 1.0 / __hcse_44
                __hcse_46 = 1.0 / denom
                __cse_113d = __cse_112 * (-__hcse_45 * denomd) + __hcse_46 * __cse_112d
                __cse_113 = __hcse_46 * __cse_112
                resid1bd[kk] = resid1bd[kk] + __cse_113d
                resid1b[kk] = resid1b[kk] + __cse_113
                row_meanbd = row_meanbd + -__cse_113d
                row_meanb = row_meanb + -__cse_113
                __cse_114d = resid1d[kk] + -row_meand
                __cse_114 = resid1[kk] - row_mean
                __hcse_47 = -(__cse_114 / __hcse_44)
                denombd = denombd + (__cse_112 * -((__hcse_45 * __cse_114d + -(__cse_114 / __hcse_44 ^ 2) * ((2denom) * denomd))) + __hcse_47 * __cse_112d)
                denomb = denomb + __hcse_47 * __cse_112
                __hcse_48 = __cse_114 / denom
                ln1_gainbd[ln_offset + j] = ln1_gainbd[ln_offset + j] + (__oldb_2 * (__hcse_46 * __cse_114d + __hcse_47 * denomd) + __hcse_48 * __oldb_2d)
                ln1_gainb[ln_offset + j] = ln1_gainb[ln_offset + j] + __hcse_48 * __oldb_2
                ln1_biasbd[ln_offset + j] = ln1_biasbd[ln_offset + j] + __oldb_2d
                ln1_biasb[ln_offset + j] = ln1_biasb[ln_offset + j] + __oldb_2
            end
            __icse_115 = ((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1
            __idx_denom_stack_0 = __icse_115
            denomd = denom_stack_d[__idx_denom_stack_0]
            denom = denom_stack[__idx_denom_stack_0]
            __oldb_2d = denombd
            __oldb_2 = denomb
            denombd = 0.0
            denomb = 0.0
            __hcse_49 = 2.0 * sqrt(row_var + eps)
            __hcse_50 = 1.0 / __hcse_49
            __cse_116d = __oldb_2 * (-(1.0 / __hcse_49 ^ 2) * (2.0 * (__hcse_50 * (row_vard + epsd)))) + __hcse_50 * __oldb_2d
            __cse_116 = __hcse_50 * __oldb_2
            row_varbd = row_varbd + __cse_116d
            row_varb = row_varb + __cse_116
            epsbd = epsbd + __cse_116d
            epsb = epsb + __cse_116
            __idx_row_var_stack_0 = __icse_115
            row_vard = row_var_stack_d[__idx_row_var_stack_0]
            row_var = row_var_stack[__idx_row_var_stack_0]
            __oldb_2d = row_varbd
            __oldb_2 = row_varb
            row_varbd = 0.0
            row_varb = 0.0
            __ihcse_51 = 1.0 / d
            s2bd = s2bd + __ihcse_51 * __oldb_2d
            s2b = s2b + __ihcse_51 * __oldb_2
            for i_j = 1:d
                diffd = resid1d[(i - 1) * d + i_j] + -row_meand
                diff = resid1[(i - 1) * d + i_j] - row_mean
                __hcse_52 = diff * diffd
                s2d = s2d + (__hcse_52 + __hcse_52)
                s2 = s2 + diff * diff
                __cse_117d = s2b * diffd + diff * s2bd
                __cse_117 = diff * s2b
                diffbd = diffbd + __cse_117d
                diffb = diffb + __cse_117
                diffbd = diffbd + __cse_117d
                diffb = diffb + __cse_117
                __oldb_0d = diffbd
                __oldb_0 = diffb
                diffbd = 0.0
                diffb = 0.0
                resid1bd[(i - 1) * d + i_j] = resid1bd[(i - 1) * d + i_j] + __oldb_0d
                resid1b[(i - 1) * d + i_j] = resid1b[(i - 1) * d + i_j] + __oldb_0
                row_meanbd = row_meanbd + -__oldb_0d
                row_meanb = row_meanb + -__oldb_0
            end
            s2bd = 0.0
            s2b = 0.0
            __idx_row_mean_stack_0 = ((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1
            row_meand = row_mean_stack_d[__idx_row_mean_stack_0]
            row_mean = row_mean_stack[__idx_row_mean_stack_0]
            __oldb_2d = row_meanbd
            __oldb_2 = row_meanb
            row_meanbd = 0.0
            row_meanb = 0.0
            __ihcse_53 = 1.0 / d
            sbd = sbd + __ihcse_53 * __oldb_2d
            sb = sb + __ihcse_53 * __oldb_2
            for i_j = 1:d
                sd = sd + resid1d[(i - 1) * d + i_j]
                s = s + resid1[(i - 1) * d + i_j]
                resid1bd[(i - 1) * d + i_j] = resid1bd[(i - 1) * d + i_j] + sbd
                resid1b[(i - 1) * d + i_j] = resid1b[(i - 1) * d + i_j] + sb
            end
            sbd = 0.0
            sb = 0.0
        end
        for idx = n_d:-1:1
            __idx_resid1_stack_0 = ((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1
            resid1d[idx] = resid1_stack_d[__idx_resid1_stack_0]
            resid1[idx] = resid1_stack[__idx_resid1_stack_0]
            __oldb_2d = resid1bd[idx]
            __oldb_2 = resid1b[idx]
            resid1bd[idx] = 0.0
            resid1b[idx] = 0.0
            xbd[idx] = xbd[idx] + __oldb_2d
            xb[idx] = xb[idx] + __oldb_2
            attn_outbd[idx] = attn_outbd[idx] + __oldb_2d
            attn_outb[idx] = attn_outb[idx] + __oldb_2
        end
        for idx = n_d:-1:1
            __icse_118 = max(0, div(n_layers - 1, 1) + 1)
            __icse_119 = div(n_d - 1, 1) + 1
            __icse_120 = __icse_118 * max(0, __icse_119)
            __icse_121 = max(0, div(h - 1, 1) + 1)
            __icse_122 = idx - 1
            __idx_s_stack_0 = ((((__icse_120 + __icse_120) + __icse_120) + __icse_118 * __icse_121 * max(0, div(n * n - 1, 1) + 1)) + __icse_118 * __icse_121 * max(0, div(n * dk - 1, 1) + 1)) + (((i_l - 1) * __icse_119 + __icse_122) + 1)
            sd = s_stack_d[__idx_s_stack_0]
            s = s_stack[__idx_s_stack_0]
            i = div(__icse_122, d) + 1
            j = mod(__icse_122, d) + 1
            __oldb_0d = attn_outbd[(i - 1) * d + j]
            __oldb_0 = attn_outb[(i - 1) * d + j]
            attn_outbd[(i - 1) * d + j] = 0.0
            attn_outb[(i - 1) * d + j] = 0.0
            sbd = sbd + __oldb_0d
            sb = sb + __oldb_0
            bobd[b_offset + j] = bobd[b_offset + j] + __oldb_0d
            bob[b_offset + j] = bob[b_offset + j] + __oldb_0
            for i_p = 1:d
                __cse_123d = ctxd[(i - 1) * d + i_p]
                __cse_123 = ctx[(i - 1) * d + i_p]
                __cse_124d = wod[w_offset + (i_p - 1) * d + j]
                __cse_124 = wo[w_offset + (i_p - 1) * d + j]
                sd = sd + (__cse_124 * __cse_123d + __cse_123 * __cse_124d)
                s = s + __cse_123 * __cse_124
                ctxbd[(i - 1) * d + i_p] = ctxbd[(i - 1) * d + i_p] + (sb * __cse_124d + __cse_124 * sbd)
                ctxb[(i - 1) * d + i_p] = ctxb[(i - 1) * d + i_p] + __cse_124 * sb
                wobd[w_offset + (i_p - 1) * d + j] = wobd[w_offset + (i_p - 1) * d + j] + (sb * __cse_123d + __cse_123 * sbd)
                wob[w_offset + (i_p - 1) * d + j] = wob[w_offset + (i_p - 1) * d + j] + __cse_123 * sb
            end
            sbd = 0.0
            sb = 0.0
        end
        for hh = h:-1:1
            __icse_125 = hh - 1
            head_offset = __icse_125 * dk
            score_off = __icse_125 * n * n
            for idx3 = n * dk:-1:1
                __icse_126 = max(0, div(n_layers - 1, 1) + 1)
                __icse_127 = __icse_126 * max(0, div(n_d - 1, 1) + 1)
                __icse_128 = div(h - 1, 1) + 1
                __icse_129 = div(n * dk - 1, 1) + 1
                __icse_130 = idx3 - 1
                __icse_131 = ((i_l - 1) * (__icse_128 * __icse_129) + (hh - 1) * __icse_129 + __icse_130) + 1
                __idx_s_stack_0 = (((__icse_127 + __icse_127) + __icse_127) + __icse_126 * max(0, __icse_128) * max(0, div(n * n - 1, 1) + 1)) + __icse_131
                sd = s_stack_d[__idx_s_stack_0]
                s = s_stack[__idx_s_stack_0]
                i = div(__icse_130, dk) + 1
                p = mod(__icse_130, dk) + 1
                __idx_ctx_stack_0 = __icse_131
                ctxd[(i - 1) * d + head_offset + p] = ctx_stack_d[__idx_ctx_stack_0]
                ctx[(i - 1) * d + head_offset + p] = ctx_stack[__idx_ctx_stack_0]
                __oldb_2d = ctxbd[(i - 1) * d + head_offset + p]
                __oldb_2 = ctxb[(i - 1) * d + head_offset + p]
                ctxbd[(i - 1) * d + head_offset + p] = 0.0
                ctxb[(i - 1) * d + head_offset + p] = 0.0
                sbd = sbd + __oldb_2d
                sb = sb + __oldb_2
                for i_j = 1:n
                    __cse_132d = probsd[score_off + (i - 1) * n + i_j]
                    __cse_132 = probs[score_off + (i - 1) * n + i_j]
                    __cse_133d = vd[(i_j - 1) * d + head_offset + p]
                    __cse_133 = v[(i_j - 1) * d + head_offset + p]
                    sd = sd + (__cse_133 * __cse_132d + __cse_132 * __cse_133d)
                    s = s + __cse_132 * __cse_133
                    probsbd[score_off + (i - 1) * n + i_j] = probsbd[score_off + (i - 1) * n + i_j] + (sb * __cse_133d + __cse_133 * sbd)
                    probsb[score_off + (i - 1) * n + i_j] = probsb[score_off + (i - 1) * n + i_j] + __cse_133 * sb
                    vbd[(i_j - 1) * d + head_offset + p] = vbd[(i_j - 1) * d + head_offset + p] + (sb * __cse_132d + __cse_132 * sbd)
                    vb[(i_j - 1) * d + head_offset + p] = vb[(i_j - 1) * d + head_offset + p] + __cse_132 * sb
                end
                sbd = 0.0
                sb = 0.0
            end
            for i = n:-1:1
                __icse_134 = div(h - 1, 1) + 1
                __icse_135 = div(n - 1, 1) + 1
                __icse_136 = ((i_l - 1) * (__icse_134 * __icse_135) + (hh - 1) * __icse_135 + (i - 1)) + 1
                __idx_row_max_stack_0 = max(0, div(n_layers - 1, 1) + 1) * max(0, __icse_134) * max(0, __icse_135) * max(0, div(n - 2, 1) + 1) + __icse_136
                row_maxd = row_max_stack_d[__idx_row_max_stack_0]
                row_max = row_max_stack[__idx_row_max_stack_0]
                __idx_row_sum_stack_2 = __icse_136
                row_sumd = row_sum_stack_d[__idx_row_sum_stack_2]
                row_sum = row_sum_stack[__idx_row_sum_stack_2]
                for j = n:-1:1
                    __icse_137 = i - 1
                    kk = score_off + __icse_137 * n + j
                    __icse_138 = div(h - 1, 1) + 1
                    __icse_139 = div(n - 1, 1) + 1
                    __icse_140 = max(0, __icse_139)
                    __idx_probs_stack_0 = max(0, div(n_layers - 1, 1) + 1) * max(0, __icse_138) * __icse_140 * __icse_140 + (((i_l - 1) * (__icse_138 * __icse_139 * __icse_139) + (hh - 1) * (__icse_139 * __icse_139) + __icse_137 * __icse_139 + (j - 1)) + 1)
                    probsd[kk] = probs_stack_d[__idx_probs_stack_0]
                    probs[kk] = probs_stack[__idx_probs_stack_0]
                    __oldb_2d = probsbd[kk]
                    __oldb_2 = probsb[kk]
                    probsbd[kk] = 0.0
                    probsb[kk] = 0.0
                    __hcse_54 = row_sum ^ 2
                    __hcse_55 = 1.0 / __hcse_54
                    __hcse_56 = 1.0 / row_sum
                    probsbd[kk] = probsbd[kk] + (__oldb_2 * (-__hcse_55 * row_sumd) + __hcse_56 * __oldb_2d)
                    probsb[kk] = probsb[kk] + __hcse_56 * __oldb_2
                    __hcse_57 = probs[kk]
                    __hcse_58 = -(__hcse_57 / __hcse_54)
                    row_sumbd = row_sumbd + (__oldb_2 * -((__hcse_55 * probsd[kk] + -(__hcse_57 / __hcse_54 ^ 2) * ((2row_sum) * row_sumd))) + __hcse_58 * __oldb_2d)
                    row_sumb = row_sumb + __hcse_58 * __oldb_2
                end
                for i_j = 1:n
                    row_sumd = row_sumd + probsd[score_off + (i - 1) * n + i_j]
                    row_sum = row_sum + probs[score_off + (i - 1) * n + i_j]
                    probsbd[score_off + (i - 1) * n + i_j] = probsbd[score_off + (i - 1) * n + i_j] + row_sumbd
                    probsb[score_off + (i - 1) * n + i_j] = probsb[score_off + (i - 1) * n + i_j] + row_sumb
                end
                row_sumbd = 0.0
                row_sumb = 0.0
                for j = n:-1:1
                    __icse_141 = i - 1
                    kk = score_off + __icse_141 * n + j
                    __icse_142 = div(n - 1, 1) + 1
                    __idx_probs_stack_0 = ((i_l - 1) * ((div(h - 1, 1) + 1) * __icse_142 * __icse_142) + (hh - 1) * (__icse_142 * __icse_142) + __icse_141 * __icse_142 + (j - 1)) + 1
                    probsd[kk] = probs_stack_d[__idx_probs_stack_0]
                    probs[kk] = probs_stack[__idx_probs_stack_0]
                    __oldb_2d = probsbd[kk]
                    __oldb_2 = probsb[kk]
                    probsbd[kk] = 0.0
                    probsb[kk] = 0.0
                    __hcse_59 = exp(scores[kk] - row_max)
                    __cse_143d = __oldb_2 * (__hcse_59 * (scoresd[kk] + -row_maxd)) + __hcse_59 * __oldb_2d
                    __cse_143 = __hcse_59 * __oldb_2
                    scoresbd[kk] = scoresbd[kk] + __cse_143d
                    scoresb[kk] = scoresb[kk] + __cse_143
                    row_maxbd = row_maxbd + -__cse_143d
                    row_maxb = row_maxb + -__cse_143
                end
                for i_j = n:-1:2
                    __icse_144 = div(n - 1, 1) + 1
                    __icse_145 = div(n - 2, 1) + 1
                    __idx_row_max_stack_0 = ((i_l - 1) * ((div(h - 1, 1) + 1) * __icse_144 * __icse_145) + (hh - 1) * (__icse_144 * __icse_145) + (i - 1) * __icse_145 + (i_j - 2)) + 1
                    row_maxd = row_max_stack_d[__idx_row_max_stack_0]
                    row_max = row_max_stack[__idx_row_max_stack_0]
                    __oldb_2d = row_maxbd
                    __oldb_2 = row_maxb
                    row_maxbd = 0.0
                    row_maxb = 0.0
                    __cse_146d = scoresd[score_off + (i - 1) * n + i_j]
                    __cse_146 = scores[score_off + (i - 1) * n + i_j]
                    __hcse_60 = 0.5 * (1.0 + sign(row_max - __cse_146))
                    row_maxbd = row_maxbd + __hcse_60 * __oldb_2d
                    row_maxb = row_maxb + __hcse_60 * __oldb_2
                    __hcse_61 = 0.5 * (1.0 + sign(__cse_146 - row_max))
                    scoresbd[score_off + (i - 1) * n + i_j] = scoresbd[score_off + (i - 1) * n + i_j] + __hcse_61 * __oldb_2d
                    scoresb[score_off + (i - 1) * n + i_j] = scoresb[score_off + (i - 1) * n + i_j] + __hcse_61 * __oldb_2
                end
                __oldb_0d = row_maxbd
                __oldb_0 = row_maxb
                row_maxbd = 0.0
                row_maxb = 0.0
                scoresbd[score_off + (i - 1) * n + 1] = scoresbd[score_off + (i - 1) * n + 1] + __oldb_0d
                scoresb[score_off + (i - 1) * n + 1] = scoresb[score_off + (i - 1) * n + 1] + __oldb_0
            end
            for idx2 = n * n:-1:1
                __icse_147 = max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)
                __icse_148 = div(n * n - 1, 1) + 1
                __icse_149 = idx2 - 1
                __icse_150 = ((i_l - 1) * ((div(h - 1, 1) + 1) * __icse_148) + (hh - 1) * __icse_148 + __icse_149) + 1
                __idx_s_stack_0 = ((__icse_147 + __icse_147) + __icse_147) + __icse_150
                sd = s_stack_d[__idx_s_stack_0]
                s = s_stack[__idx_s_stack_0]
                i = div(__icse_149, n) + 1
                j = mod(__icse_149, n) + 1
                __idx_scores_stack_0 = __icse_150
                scoresd[score_off + (i - 1) * n + j] = scores_stack_d[__idx_scores_stack_0]
                scores[score_off + (i - 1) * n + j] = scores_stack[__idx_scores_stack_0]
                __oldb_2d = scoresbd[score_off + (i - 1) * n + j]
                __oldb_2 = scoresb[score_off + (i - 1) * n + j]
                scoresbd[score_off + (i - 1) * n + j] = 0.0
                scoresb[score_off + (i - 1) * n + j] = 0.0
                sbd = sbd + (__oldb_2 * inv_sqrt_dkd + inv_sqrt_dk * __oldb_2d)
                sb = sb + inv_sqrt_dk * __oldb_2
                for i_p = 1:dk
                    __cse_151d = qd[(i - 1) * d + head_offset + i_p]
                    __cse_151 = q[(i - 1) * d + head_offset + i_p]
                    __cse_152d = kd[(j - 1) * d + head_offset + i_p]
                    __cse_152 = k[(j - 1) * d + head_offset + i_p]
                    sd = sd + (__cse_152 * __cse_151d + __cse_151 * __cse_152d)
                    s = s + __cse_151 * __cse_152
                    qbd[(i - 1) * d + head_offset + i_p] = qbd[(i - 1) * d + head_offset + i_p] + (sb * __cse_152d + __cse_152 * sbd)
                    qb[(i - 1) * d + head_offset + i_p] = qb[(i - 1) * d + head_offset + i_p] + __cse_152 * sb
                    kbd[(j - 1) * d + head_offset + i_p] = kbd[(j - 1) * d + head_offset + i_p] + (sb * __cse_151d + __cse_151 * sbd)
                    kb[(j - 1) * d + head_offset + i_p] = kb[(j - 1) * d + head_offset + i_p] + __cse_151 * sb
                end
                sbd = 0.0
                sb = 0.0
            end
        end
        for idx = n_d:-1:1
            __icse_153 = div(n_d - 1, 1) + 1
            __icse_154 = max(0, div(n_layers - 1, 1) + 1) * max(0, __icse_153)
            __icse_155 = idx - 1
            __icse_156 = ((i_l - 1) * __icse_153 + __icse_155) + 1
            __idx_s_stack_0 = (__icse_154 + __icse_154) + __icse_156
            sd = s_stack_d[__idx_s_stack_0]
            s = s_stack[__idx_s_stack_0]
            i = div(__icse_155, d) + 1
            j = mod(__icse_155, d) + 1
            __idx_v_stack_0 = __icse_156
            vd[(i - 1) * d + j] = v_stack_d[__idx_v_stack_0]
            v[(i - 1) * d + j] = v_stack[__idx_v_stack_0]
            __oldb_2d = vbd[(i - 1) * d + j]
            __oldb_2 = vb[(i - 1) * d + j]
            vbd[(i - 1) * d + j] = 0.0
            vb[(i - 1) * d + j] = 0.0
            sbd = sbd + __oldb_2d
            sb = sb + __oldb_2
            bvbd[b_offset + j] = bvbd[b_offset + j] + __oldb_2d
            bvb[b_offset + j] = bvb[b_offset + j] + __oldb_2
            for i_p = 1:d
                __cse_157d = xd[(i - 1) * d + i_p]
                __cse_157 = x[(i - 1) * d + i_p]
                __cse_158d = wvd[w_offset + (i_p - 1) * d + j]
                __cse_158 = wv[w_offset + (i_p - 1) * d + j]
                sd = sd + (__cse_158 * __cse_157d + __cse_157 * __cse_158d)
                s = s + __cse_157 * __cse_158
                xbd[(i - 1) * d + i_p] = xbd[(i - 1) * d + i_p] + (sb * __cse_158d + __cse_158 * sbd)
                xb[(i - 1) * d + i_p] = xb[(i - 1) * d + i_p] + __cse_158 * sb
                wvbd[w_offset + (i_p - 1) * d + j] = wvbd[w_offset + (i_p - 1) * d + j] + (sb * __cse_157d + __cse_157 * sbd)
                wvb[w_offset + (i_p - 1) * d + j] = wvb[w_offset + (i_p - 1) * d + j] + __cse_157 * sb
            end
            sbd = 0.0
            sb = 0.0
        end
        for idx = n_d:-1:1
            __icse_159 = div(n_d - 1, 1) + 1
            __icse_160 = idx - 1
            __icse_161 = ((i_l - 1) * __icse_159 + __icse_160) + 1
            __idx_s_stack_0 = max(0, div(n_layers - 1, 1) + 1) * max(0, __icse_159) + __icse_161
            sd = s_stack_d[__idx_s_stack_0]
            s = s_stack[__idx_s_stack_0]
            i = div(__icse_160, d) + 1
            j = mod(__icse_160, d) + 1
            __idx_k_stack_0 = __icse_161
            kd[(i - 1) * d + j] = k_stack_d[__idx_k_stack_0]
            k[(i - 1) * d + j] = k_stack[__idx_k_stack_0]
            __oldb_2d = kbd[(i - 1) * d + j]
            __oldb_2 = kb[(i - 1) * d + j]
            kbd[(i - 1) * d + j] = 0.0
            kb[(i - 1) * d + j] = 0.0
            sbd = sbd + __oldb_2d
            sb = sb + __oldb_2
            bkbd[b_offset + j] = bkbd[b_offset + j] + __oldb_2d
            bkb[b_offset + j] = bkb[b_offset + j] + __oldb_2
            for i_p = 1:d
                __cse_162d = xd[(i - 1) * d + i_p]
                __cse_162 = x[(i - 1) * d + i_p]
                __cse_163d = wkd[w_offset + (i_p - 1) * d + j]
                __cse_163 = wk[w_offset + (i_p - 1) * d + j]
                sd = sd + (__cse_163 * __cse_162d + __cse_162 * __cse_163d)
                s = s + __cse_162 * __cse_163
                xbd[(i - 1) * d + i_p] = xbd[(i - 1) * d + i_p] + (sb * __cse_163d + __cse_163 * sbd)
                xb[(i - 1) * d + i_p] = xb[(i - 1) * d + i_p] + __cse_163 * sb
                wkbd[w_offset + (i_p - 1) * d + j] = wkbd[w_offset + (i_p - 1) * d + j] + (sb * __cse_162d + __cse_162 * sbd)
                wkb[w_offset + (i_p - 1) * d + j] = wkb[w_offset + (i_p - 1) * d + j] + __cse_162 * sb
            end
            sbd = 0.0
            sb = 0.0
        end
        for idx = n_d:-1:1
            __icse_164 = idx - 1
            __icse_165 = ((i_l - 1) * (div(n_d - 1, 1) + 1) + __icse_164) + 1
            __idx_s_stack_0 = __icse_165
            sd = s_stack_d[__idx_s_stack_0]
            s = s_stack[__idx_s_stack_0]
            i = div(__icse_164, d) + 1
            j = mod(__icse_164, d) + 1
            __idx_q_stack_0 = __icse_165
            qd[(i - 1) * d + j] = q_stack_d[__idx_q_stack_0]
            q[(i - 1) * d + j] = q_stack[__idx_q_stack_0]
            __oldb_2d = qbd[(i - 1) * d + j]
            __oldb_2 = qb[(i - 1) * d + j]
            qbd[(i - 1) * d + j] = 0.0
            qb[(i - 1) * d + j] = 0.0
            sbd = sbd + __oldb_2d
            sb = sb + __oldb_2
            bqbd[b_offset + j] = bqbd[b_offset + j] + __oldb_2d
            bqb[b_offset + j] = bqb[b_offset + j] + __oldb_2
            for i_p = 1:d
                __cse_166d = xd[(i - 1) * d + i_p]
                __cse_166 = x[(i - 1) * d + i_p]
                __cse_167d = wqd[w_offset + (i_p - 1) * d + j]
                __cse_167 = wq[w_offset + (i_p - 1) * d + j]
                sd = sd + (__cse_167 * __cse_166d + __cse_166 * __cse_167d)
                s = s + __cse_166 * __cse_167
                xbd[(i - 1) * d + i_p] = xbd[(i - 1) * d + i_p] + (sb * __cse_167d + __cse_167 * sbd)
                xb[(i - 1) * d + i_p] = xb[(i - 1) * d + i_p] + __cse_167 * sb
                wqbd[w_offset + (i_p - 1) * d + j] = wqbd[w_offset + (i_p - 1) * d + j] + (sb * __cse_166d + __cse_166 * sbd)
                wqb[w_offset + (i_p - 1) * d + j] = wqb[w_offset + (i_p - 1) * d + j] + __cse_166 * sb
            end
            sbd = 0.0
            sb = 0.0
        end
    end
    inv_sqrt_dkbd = 0.0
    inv_sqrt_dkb = 0.0
    return (epsb, epsbd)
end

function transformer(x, wq, bq, wk, bk, wv, bv, wo, bo, ln1_gain, ln1_bias, w1, b1, w2, b2, ln2_gain, ln2_bias, q, k, v, scores, probs, ctx, attn_out, resid1, normed1, ff_hidden, ff_out, resid2, x_next, n, dk, h, dff, n_layers, eps)
    d = h * dk
    inv_sqrt_dk = 1.0 / sqrt(dk)
    n_d = n * d
    n_dff = n * dff
    for i_l = 1:n_layers
        w_offset = (i_l - 1) * d * d
        b_offset = (i_l - 1) * d
        ln_offset = (i_l - 1) * d
        w1_offset = (i_l - 1) * d * dff
        b1_offset = (i_l - 1) * dff
        w2_offset = (i_l - 1) * dff * d
        b2_offset = (i_l - 1) * d
        ln2_offset = (i_l - 1) * d
        for idx = 1:n_d
            i = div(idx - 1, d) + 1
            j = mod(idx - 1, d) + 1
            s = 0.0
            for i_p = 1:d
                s = s + x[(i - 1) * d + i_p] * wq[w_offset + (i_p - 1) * d + j]
            end
            q[(i - 1) * d + j] = s + bq[b_offset + j]
        end
        for idx = 1:n_d
            i = div(idx - 1, d) + 1
            j = mod(idx - 1, d) + 1
            s = 0.0
            for i_p = 1:d
                s = s + x[(i - 1) * d + i_p] * wk[w_offset + (i_p - 1) * d + j]
            end
            k[(i - 1) * d + j] = s + bk[b_offset + j]
        end
        for idx = 1:n_d
            i = div(idx - 1, d) + 1
            j = mod(idx - 1, d) + 1
            s = 0.0
            for i_p = 1:d
                s = s + x[(i - 1) * d + i_p] * wv[w_offset + (i_p - 1) * d + j]
            end
            v[(i - 1) * d + j] = s + bv[b_offset + j]
        end
        for hh = 1:h
            head_offset = (hh - 1) * dk
            score_off = (hh - 1) * n * n
            for idx2 = 1:n * n
                i = div(idx2 - 1, n) + 1
                j = mod(idx2 - 1, n) + 1
                s = 0.0
                for i_p = 1:dk
                    s = s + q[(i - 1) * d + head_offset + i_p] * k[(j - 1) * d + head_offset + i_p]
                end
                scores[score_off + (i - 1) * n + j] = s * inv_sqrt_dk
            end
            for i = 1:n
                row_max = scores[score_off + (i - 1) * n + 1]
                for i_j = 2:n
                    row_max = max(row_max, scores[score_off + (i - 1) * n + i_j])
                end
                for j = 1:n
                    kk = score_off + (i - 1) * n + j
                    probs[kk] = exp(scores[kk] - row_max)
                end
                row_sum = 0.0
                for i_j = 1:n
                    row_sum = row_sum + probs[score_off + (i - 1) * n + i_j]
                end
                for j = 1:n
                    kk = score_off + (i - 1) * n + j
                    probs[kk] = probs[kk] / row_sum
                end
            end
            for idx3 = 1:n * dk
                i = div(idx3 - 1, dk) + 1
                p = mod(idx3 - 1, dk) + 1
                s = 0.0
                for i_j = 1:n
                    s = s + probs[score_off + (i - 1) * n + i_j] * v[(i_j - 1) * d + head_offset + p]
                end
                ctx[(i - 1) * d + head_offset + p] = s
            end
        end
        for idx = 1:n_d
            i = div(idx - 1, d) + 1
            j = mod(idx - 1, d) + 1
            s = 0.0
            for i_p = 1:d
                s = s + ctx[(i - 1) * d + i_p] * wo[w_offset + (i_p - 1) * d + j]
            end
            attn_out[(i - 1) * d + j] = s + bo[b_offset + j]
        end
        for idx = 1:n_d
            resid1[idx] = x[idx] + attn_out[idx]
        end
        for i = 1:n
            s = 0.0
            for i_j = 1:d
                s = s + resid1[(i - 1) * d + i_j]
            end
            row_mean = s / d
            s2 = 0.0
            for i_j = 1:d
                diff = resid1[(i - 1) * d + i_j] - row_mean
                s2 = s2 + diff * diff
            end
            row_var = s2 / d
            denom = sqrt(row_var + eps)
            for j = 1:d
                kk = (i - 1) * d + j
                normed1[kk] = ((resid1[kk] - row_mean) / denom) * ln1_gain[ln_offset + j] + ln1_bias[ln_offset + j]
            end
        end
        for idx = 1:n_dff
            i = div(idx - 1, dff) + 1
            j = mod(idx - 1, dff) + 1
            s = 0.0
            for i_p = 1:d
                s = s + normed1[(i - 1) * d + i_p] * w1[w1_offset + (i_p - 1) * dff + j]
            end
            ff_hidden[(i - 1) * dff + j] = max(s + b1[b1_offset + j], 0.0)
        end
        for idx = 1:n_d
            i = div(idx - 1, d) + 1
            j = mod(idx - 1, d) + 1
            s = 0.0
            for i_p = 1:dff
                s = s + ff_hidden[(i - 1) * dff + i_p] * w2[w2_offset + (i_p - 1) * d + j]
            end
            ff_out[(i - 1) * d + j] = s + b2[b2_offset + j]
        end
        for idx = 1:n_d
            resid2[idx] = normed1[idx] + ff_out[idx]
        end
        for i = 1:n
            s = 0.0
            for i_j = 1:d
                s = s + resid2[(i - 1) * d + i_j]
            end
            row_mean = s / d
            s2 = 0.0
            for i_j = 1:d
                diff = resid2[(i - 1) * d + i_j] - row_mean
                s2 = s2 + diff * diff
            end
            row_var = s2 / d
            denom = sqrt(row_var + eps)
            for j = 1:d
                kk = (i - 1) * d + j
                x_next[kk] = ((resid2[kk] - row_mean) / denom) * ln2_gain[ln2_offset + j] + ln2_bias[ln2_offset + j]
            end
        end
        for idx = 1:n_d
            x[idx] = x_next[idx]
        end
    end
end
