function initstacks_transformer_b(dff, dk, h, n, n_layers)
    d = h * dk
    n_d = n * d
    n_dff = n * dff
    q_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1))
    k_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1))
    v_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1))
    scores_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * n - 1, 1) + 1))
    row_max_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) * max(0, div(n - 2, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n - 1, 1) + 1))
    probs_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) * max(0, div(n - 1, 1) + 1))
    ctx_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * dk - 1, 1) + 1))
    resid1_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1))
    row_mean_stack = Vector{Float64}(undef, ((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1)) + 1)
    row_var_stack = Vector{Float64}(undef, ((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1)) + 1)
    denom_stack = Vector{Float64}(undef, ((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1)) + 1)
    normed1_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) * max(0, div(d - 1, 1) + 1))
    ff_hidden_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_dff - 1, 1) + 1))
    resid2_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1))
    x_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1))
    row_sum_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n - 1, 1) + 1))
    s_stack = Vector{Float64}(undef, ((((((((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * dk - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_dff - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1))
    s2_stack = Vector{Float64}(undef, max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1))
    return (q_stack, k_stack, v_stack, scores_stack, row_max_stack, probs_stack, ctx_stack, resid1_stack, row_mean_stack, row_var_stack, denom_stack, normed1_stack, ff_hidden_stack, resid2_stack, x_stack, row_sum_stack, s_stack, s2_stack)
end

function transformer_hv(x, xb, wq, wqb, bq, bqb, wk, wkb, bk, bkb, wv, wvb, bv, bvb, wo, wob, bo, bob, ln1_gain, ln1_gainb, ln1_bias, ln1_biasb, w1, w1b, b1, b1b, w2, w2b, b2, b2b, ln2_gain, ln2_gainb, ln2_bias, ln2_biasb, q, qb, k, kb, v, vb, scores, scoresb, probs, probsb, ctx, ctxb, attn_out, attn_outb, resid1, resid1b, normed1, normed1b, ff_hidden, ff_hiddenb, ff_out, ff_outb, resid2, resid2b, x_next, x_nextb, n, dk, h, dff, n_layers, eps, epsb, xd, xbd, wqd, wqbd, bqd, bqbd, wkd, wkbd, bkd, bkbd, wvd, wvbd, bvd, bvbd, wod, wobd, bod, bobd, ln1_gaind, ln1_gainbd, ln1_biasd, ln1_biasbd, w1d, w1bd, b1d, b1bd, w2d, w2bd, b2d, b2bd, ln2_gaind, ln2_gainbd, ln2_biasd, ln2_biasbd, qd, qbd, kd, kbd, vd, vbd, scoresd, scoresbd, probsd, probsbd, ctxd, ctxbd, attn_outd, attn_outbd, resid1d, resid1bd, normed1d, normed1bd, ff_hiddend, ff_hiddenbd, ff_outd, ff_outbd, resid2d, resid2bd, x_nextd, x_nextbd, epsd, epsbd, q_stack, k_stack, v_stack, scores_stack, row_max_stack, probs_stack, ctx_stack, resid1_stack, row_mean_stack, row_var_stack, denom_stack, normed1_stack, ff_hidden_stack, resid2_stack, x_stack, row_sum_stack, s_stack, s2_stack)
    q_stack_d = Vector{Float64}(undef, length(q_stack))
    k_stack_d = Vector{Float64}(undef, length(k_stack))
    v_stack_d = Vector{Float64}(undef, length(v_stack))
    scores_stack_d = Vector{Float64}(undef, length(scores_stack))
    row_max_stack_d = Vector{Float64}(undef, length(row_max_stack))
    probs_stack_d = Vector{Float64}(undef, length(probs_stack))
    ctx_stack_d = Vector{Float64}(undef, length(ctx_stack))
    resid1_stack_d = Vector{Float64}(undef, length(resid1_stack))
    row_mean_stack_d = Vector{Float64}(undef, length(row_mean_stack))
    row_var_stack_d = Vector{Float64}(undef, length(row_var_stack))
    denom_stack_d = Vector{Float64}(undef, length(denom_stack))
    normed1_stack_d = Vector{Float64}(undef, length(normed1_stack))
    ff_hidden_stack_d = Vector{Float64}(undef, length(ff_hidden_stack))
    resid2_stack_d = Vector{Float64}(undef, length(resid2_stack))
    x_stack_d = Vector{Float64}(undef, length(x_stack))
    row_sum_stack_d = Vector{Float64}(undef, length(row_sum_stack))
    s_stack_d = Vector{Float64}(undef, length(s_stack))
    s2_stack_d = Vector{Float64}(undef, length(s2_stack))
    denom = 0.0
    diff = 0.0
    row_max = 0.0
    row_mean = 0.0
    row_sum = 0.0
    row_var = 0.0
    s = 0.0
    s2 = 0.0
    denomb = 0.0
    diffb = 0.0
    row_maxb = 0.0
    row_meanb = 0.0
    row_sumb = 0.0
    row_varb = 0.0
    sb = 0.0
    s2b = 0.0
    denomd = 0.0
    denombd = 0.0
    diffd = 0.0
    diffbd = 0.0
    inv_sqrt_dkd = 0.0
    inv_sqrt_dkbd = 0.0
    row_maxd = 0.0
    row_maxbd = 0.0
    row_meand = 0.0
    row_meanbd = 0.0
    row_sumd = 0.0
    row_sumbd = 0.0
    row_vard = 0.0
    row_varbd = 0.0
    sd = 0.0
    sbd = 0.0
    s2d = 0.0
    s2bd = 0.0
    d = h * dk
    inv_sqrt_dkd = 0.0
    inv_sqrt_dk = 1.0 / sqrt(dk)
    n_d = n * d
    n_dff = n * dff
    for i_l = 1:n_layers
        w_offset = (i_l - 1) * d * d
        b_offset = (i_l - 1) * d
        ln_offset = (i_l - 1) * d
        w1_offset = (i_l - 1) * d * dff
        b1_offset = (i_l - 1) * dff
        w2_offset = (i_l - 1) * dff * d
        b2_offset = (i_l - 1) * d
        ln2_offset = (i_l - 1) * d
        for idx = 1:n_d
            i = div(idx - 1, d) + 1
            j = mod(idx - 1, d) + 1
            sd = 0.0
            s = 0.0
            for i_p = 1:d
                __cse_40 = wq[w_offset + (i_p - 1) * d + j]
                __cse_41 = x[(i - 1) * d + i_p]
                sd = sd + (__cse_40 * xd[(i - 1) * d + i_p] + __cse_41 * wqd[w_offset + (i_p - 1) * d + j])
                s = s + __cse_41 * __cse_40
            end
            __idx_q_stack_4 = ((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1
            q_stack_d[__idx_q_stack_4] = qd[(i - 1) * d + j]
            q_stack[__idx_q_stack_4] = q[(i - 1) * d + j]
            qd[(i - 1) * d + j] = sd + bqd[b_offset + j]
            q[(i - 1) * d + j] = s + bq[b_offset + j]
            __idx_s_stack_7 = ((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1
            s_stack_d[__idx_s_stack_7] = sd
            s_stack[__idx_s_stack_7] = s
        end
        for idx = 1:n_d
            i = div(idx - 1, d) + 1
            j = mod(idx - 1, d) + 1
            sd = 0.0
            s = 0.0
            for i_p = 1:d
                __cse_42 = wk[w_offset + (i_p - 1) * d + j]
                __cse_43 = x[(i - 1) * d + i_p]
                sd = sd + (__cse_42 * xd[(i - 1) * d + i_p] + __cse_43 * wkd[w_offset + (i_p - 1) * d + j])
                s = s + __cse_43 * __cse_42
            end
            __idx_k_stack_4 = ((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1
            k_stack_d[__idx_k_stack_4] = kd[(i - 1) * d + j]
            k_stack[__idx_k_stack_4] = k[(i - 1) * d + j]
            kd[(i - 1) * d + j] = sd + bkd[b_offset + j]
            k[(i - 1) * d + j] = s + bk[b_offset + j]
            __idx_s_stack_7 = max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1) + (((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1)
            s_stack_d[__idx_s_stack_7] = sd
            s_stack[__idx_s_stack_7] = s
        end
        for idx = 1:n_d
            i = div(idx - 1, d) + 1
            j = mod(idx - 1, d) + 1
            sd = 0.0
            s = 0.0
            for i_p = 1:d
                __cse_44 = wv[w_offset + (i_p - 1) * d + j]
                __cse_45 = x[(i - 1) * d + i_p]
                sd = sd + (__cse_44 * xd[(i - 1) * d + i_p] + __cse_45 * wvd[w_offset + (i_p - 1) * d + j])
                s = s + __cse_45 * __cse_44
            end
            __idx_v_stack_4 = ((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1
            v_stack_d[__idx_v_stack_4] = vd[(i - 1) * d + j]
            v_stack[__idx_v_stack_4] = v[(i - 1) * d + j]
            vd[(i - 1) * d + j] = sd + bvd[b_offset + j]
            v[(i - 1) * d + j] = s + bv[b_offset + j]
            __idx_s_stack_7 = (max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + (((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1)
            s_stack_d[__idx_s_stack_7] = sd
            s_stack[__idx_s_stack_7] = s
        end
        for hh = 1:h
            head_offset = (hh - 1) * dk
            score_off = (hh - 1) * n * n
            for idx2 = 1:n * n
                i = div(idx2 - 1, n) + 1
                j = mod(idx2 - 1, n) + 1
                sd = 0.0
                s = 0.0
                for i_p = 1:dk
                    __cse_46 = k[(j - 1) * d + head_offset + i_p]
                    __cse_47 = q[(i - 1) * d + head_offset + i_p]
                    sd = sd + (__cse_46 * qd[(i - 1) * d + head_offset + i_p] + __cse_47 * kd[(j - 1) * d + head_offset + i_p])
                    s = s + __cse_47 * __cse_46
                end
                __idx_scores_stack_4 = ((i_l - 1) * ((div(h - 1, 1) + 1) * (div(n * n - 1, 1) + 1)) + (hh - 1) * (div(n * n - 1, 1) + 1) + (idx2 - 1)) + 1
                scores_stack_d[__idx_scores_stack_4] = scoresd[score_off + (i - 1) * n + j]
                scores_stack[__idx_scores_stack_4] = scores[score_off + (i - 1) * n + j]
                scoresd[score_off + (i - 1) * n + j] = inv_sqrt_dk * sd + s * inv_sqrt_dkd
                scores[score_off + (i - 1) * n + j] = s * inv_sqrt_dk
                __idx_s_stack_7 = ((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + (((i_l - 1) * ((div(h - 1, 1) + 1) * (div(n * n - 1, 1) + 1)) + (hh - 1) * (div(n * n - 1, 1) + 1) + (idx2 - 1)) + 1)
                s_stack_d[__idx_s_stack_7] = sd
                s_stack[__idx_s_stack_7] = s
            end
            for i = 1:n
                row_maxd = scoresd[score_off + (i - 1) * n + 1]
                row_max = scores[score_off + (i - 1) * n + 1]
                for i_j = 2:n
                    __idx_row_max_stack_0 = ((i_l - 1) * ((div(h - 1, 1) + 1) * (div(n - 1, 1) + 1) * (div(n - 2, 1) + 1)) + (hh - 1) * ((div(n - 1, 1) + 1) * (div(n - 2, 1) + 1)) + (i - 1) * (div(n - 2, 1) + 1) + (i_j - 2)) + 1
                    row_max_stack_d[__idx_row_max_stack_0] = row_maxd
                    row_max_stack[__idx_row_max_stack_0] = row_max
                    __cse_48 = scores[score_off + (i - 1) * n + i_j]
                    row_maxd = (0.5 * (1.0 + sign(row_max - __cse_48))) * row_maxd + (0.5 * (1.0 + sign(__cse_48 - row_max))) * scoresd[score_off + (i - 1) * n + i_j]
                    row_max = max(row_max, __cse_48)
                end
                for j = 1:n
                    kk = score_off + (i - 1) * n + j
                    __idx_probs_stack_1 = ((i_l - 1) * ((div(h - 1, 1) + 1) * (div(n - 1, 1) + 1) * (div(n - 1, 1) + 1)) + (hh - 1) * ((div(n - 1, 1) + 1) * (div(n - 1, 1) + 1)) + (i - 1) * (div(n - 1, 1) + 1) + (j - 1)) + 1
                    probs_stack_d[__idx_probs_stack_1] = probsd[kk]
                    probs_stack[__idx_probs_stack_1] = probs[kk]
                    __cse_49 = exp(scores[kk] - row_max)
                    probsd[kk] = __cse_49 * (scoresd[kk] + -row_maxd)
                    probs[kk] = __cse_49
                end
                row_sumd = 0.0
                row_sum = 0.0
                for i_j = 1:n
                    row_sumd = row_sumd + probsd[score_off + (i - 1) * n + i_j]
                    row_sum = row_sum + probs[score_off + (i - 1) * n + i_j]
                end
                for j = 1:n
                    kk = score_off + (i - 1) * n + j
                    __idx_probs_stack_1 = max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + (((i_l - 1) * ((div(h - 1, 1) + 1) * (div(n - 1, 1) + 1) * (div(n - 1, 1) + 1)) + (hh - 1) * ((div(n - 1, 1) + 1) * (div(n - 1, 1) + 1)) + (i - 1) * (div(n - 1, 1) + 1) + (j - 1)) + 1)
                    __cse_0d = probsd[kk]
                    __cse_0 = probs[kk]
                    probs_stack_d[__idx_probs_stack_1] = __cse_0d
                    probs_stack[__idx_probs_stack_1] = __cse_0
                    probsd[kk] = (1.0 / row_sum) * __cse_0d + -(__cse_0 / row_sum ^ 2) * row_sumd
                    probs[kk] = __cse_0 / row_sum
                end
                __idx_row_max_stack_6 = max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) * max(0, div(n - 2, 1) + 1) + (((i_l - 1) * ((div(h - 1, 1) + 1) * (div(n - 1, 1) + 1)) + (hh - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1)
                row_max_stack_d[__idx_row_max_stack_6] = row_maxd
                row_max_stack[__idx_row_max_stack_6] = row_max
                __idx_row_sum_stack_8 = ((i_l - 1) * ((div(h - 1, 1) + 1) * (div(n - 1, 1) + 1)) + (hh - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1
                row_sum_stack_d[__idx_row_sum_stack_8] = row_sumd
                row_sum_stack[__idx_row_sum_stack_8] = row_sum
            end
            for idx3 = 1:n * dk
                i = div(idx3 - 1, dk) + 1
                p = mod(idx3 - 1, dk) + 1
                sd = 0.0
                s = 0.0
                for i_j = 1:n
                    __cse_50 = v[(i_j - 1) * d + head_offset + p]
                    __cse_51 = probs[score_off + (i - 1) * n + i_j]
                    sd = sd + (__cse_50 * probsd[score_off + (i - 1) * n + i_j] + __cse_51 * vd[(i_j - 1) * d + head_offset + p])
                    s = s + __cse_51 * __cse_50
                end
                __idx_ctx_stack_4 = ((i_l - 1) * ((div(h - 1, 1) + 1) * (div(n * dk - 1, 1) + 1)) + (hh - 1) * (div(n * dk - 1, 1) + 1) + (idx3 - 1)) + 1
                ctx_stack_d[__idx_ctx_stack_4] = ctxd[(i - 1) * d + head_offset + p]
                ctx_stack[__idx_ctx_stack_4] = ctx[(i - 1) * d + head_offset + p]
                ctxd[(i - 1) * d + head_offset + p] = sd
                ctx[(i - 1) * d + head_offset + p] = s
                __idx_s_stack_7 = (((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * n - 1, 1) + 1)) + (((i_l - 1) * ((div(h - 1, 1) + 1) * (div(n * dk - 1, 1) + 1)) + (hh - 1) * (div(n * dk - 1, 1) + 1) + (idx3 - 1)) + 1)
                s_stack_d[__idx_s_stack_7] = sd
                s_stack[__idx_s_stack_7] = s
            end
        end
        for idx = 1:n_d
            i = div(idx - 1, d) + 1
            j = mod(idx - 1, d) + 1
            sd = 0.0
            s = 0.0
            for i_p = 1:d
                __cse_52 = wo[w_offset + (i_p - 1) * d + j]
                __cse_53 = ctx[(i - 1) * d + i_p]
                sd = sd + (__cse_52 * ctxd[(i - 1) * d + i_p] + __cse_53 * wod[w_offset + (i_p - 1) * d + j])
                s = s + __cse_53 * __cse_52
            end
            attn_outd[(i - 1) * d + j] = sd + bod[b_offset + j]
            attn_out[(i - 1) * d + j] = s + bo[b_offset + j]
            __idx_s_stack_5 = ((((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * dk - 1, 1) + 1)) + (((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1)
            s_stack_d[__idx_s_stack_5] = sd
            s_stack[__idx_s_stack_5] = s
        end
        for idx = 1:n_d
            __idx_resid1_stack_0 = ((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1
            resid1_stack_d[__idx_resid1_stack_0] = resid1d[idx]
            resid1_stack[__idx_resid1_stack_0] = resid1[idx]
            resid1d[idx] = xd[idx] + attn_outd[idx]
            resid1[idx] = x[idx] + attn_out[idx]
        end
        for i = 1:n
            sd = 0.0
            s = 0.0
            for i_j = 1:d
                sd = sd + resid1d[(i - 1) * d + i_j]
                s = s + resid1[(i - 1) * d + i_j]
            end
            __idx_row_mean_stack_2 = ((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1
            row_mean_stack_d[__idx_row_mean_stack_2] = row_meand
            row_mean_stack[__idx_row_mean_stack_2] = row_mean
            row_meand = (1.0 / d) * sd
            row_mean = s / d
            s2d = 0.0
            s2 = 0.0
            for i_j = 1:d
                diffd = resid1d[(i - 1) * d + i_j] + -row_meand
                diff = resid1[(i - 1) * d + i_j] - row_mean
                __cse_54 = diff * diffd
                s2d = s2d + (__cse_54 + __cse_54)
                s2 = s2 + diff * diff
            end
            __idx_row_var_stack_7 = ((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1
            row_var_stack_d[__idx_row_var_stack_7] = row_vard
            row_var_stack[__idx_row_var_stack_7] = row_var
            row_vard = (1.0 / d) * s2d
            row_var = s2 / d
            __idx_denom_stack_10 = ((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1
            denom_stack_d[__idx_denom_stack_10] = denomd
            denom_stack[__idx_denom_stack_10] = denom
            __cse_55 = sqrt(row_var + eps)
            denomd = (1.0 / (2.0__cse_55)) * (row_vard + epsd)
            denom = __cse_55
            for j = 1:d
                kk = (i - 1) * d + j
                __idx_normed1_stack_1 = ((i_l - 1) * ((div(n - 1, 1) + 1) * (div(d - 1, 1) + 1)) + (i - 1) * (div(d - 1, 1) + 1) + (j - 1)) + 1
                normed1_stack_d[__idx_normed1_stack_1] = normed1d[kk]
                normed1_stack[__idx_normed1_stack_1] = normed1[kk]
                __cse_56 = ln1_gain[ln_offset + j]
                __cse_57 = resid1[kk] - row_mean
                __cse_58 = __cse_57 / denom
                normed1d[kk] = (__cse_56 * ((1.0 / denom) * (resid1d[kk] + -row_meand) + -(__cse_57 / denom ^ 2) * denomd) + __cse_58 * ln1_gaind[ln_offset + j]) + ln1_biasd[ln_offset + j]
                normed1[kk] = __cse_58 * __cse_56 + ln1_bias[ln_offset + j]
            end
            __idx_s_stack_14 = (((((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * dk - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + (((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1)
            s_stack_d[__idx_s_stack_14] = sd
            s_stack[__idx_s_stack_14] = s
            __idx_s2_stack_16 = ((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1
            s2_stack_d[__idx_s2_stack_16] = s2d
            s2_stack[__idx_s2_stack_16] = s2
        end
        for idx = 1:n_dff
            i = div(idx - 1, dff) + 1
            j = mod(idx - 1, dff) + 1
            sd = 0.0
            s = 0.0
            for i_p = 1:d
                __cse_59 = w1[w1_offset + (i_p - 1) * dff + j]
                __cse_60 = normed1[(i - 1) * d + i_p]
                sd = sd + (__cse_59 * normed1d[(i - 1) * d + i_p] + __cse_60 * w1d[w1_offset + (i_p - 1) * dff + j])
                s = s + __cse_60 * __cse_59
            end
            __idx_ff_hidden_stack_4 = ((i_l - 1) * (div(n_dff - 1, 1) + 1) + (idx - 1)) + 1
            ff_hidden_stack_d[__idx_ff_hidden_stack_4] = ff_hiddend[(i - 1) * dff + j]
            ff_hidden_stack[__idx_ff_hidden_stack_4] = ff_hidden[(i - 1) * dff + j]
            __cse_61 = s + b1[b1_offset + j]
            ff_hiddend[(i - 1) * dff + j] = (0.5 * (1.0 + sign(__cse_61))) * (sd + b1d[b1_offset + j])
            ff_hidden[(i - 1) * dff + j] = max(__cse_61, 0.0)
            __idx_s_stack_7 = ((((((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * dk - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + (((i_l - 1) * (div(n_dff - 1, 1) + 1) + (idx - 1)) + 1)
            s_stack_d[__idx_s_stack_7] = sd
            s_stack[__idx_s_stack_7] = s
        end
        for idx = 1:n_d
            i = div(idx - 1, d) + 1
            j = mod(idx - 1, d) + 1
            sd = 0.0
            s = 0.0
            for i_p = 1:dff
                __cse_62 = w2[w2_offset + (i_p - 1) * d + j]
                __cse_63 = ff_hidden[(i - 1) * dff + i_p]
                sd = sd + (__cse_62 * ff_hiddend[(i - 1) * dff + i_p] + __cse_63 * w2d[w2_offset + (i_p - 1) * d + j])
                s = s + __cse_63 * __cse_62
            end
            ff_outd[(i - 1) * d + j] = sd + b2d[b2_offset + j]
            ff_out[(i - 1) * d + j] = s + b2[b2_offset + j]
            __idx_s_stack_5 = (((((((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * dk - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_dff - 1, 1) + 1)) + (((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1)
            s_stack_d[__idx_s_stack_5] = sd
            s_stack[__idx_s_stack_5] = s
        end
        for idx = 1:n_d
            __idx_resid2_stack_0 = ((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1
            resid2_stack_d[__idx_resid2_stack_0] = resid2d[idx]
            resid2_stack[__idx_resid2_stack_0] = resid2[idx]
            resid2d[idx] = normed1d[idx] + ff_outd[idx]
            resid2[idx] = normed1[idx] + ff_out[idx]
        end
        for i = 1:n
            sd = 0.0
            s = 0.0
            for i_j = 1:d
                sd = sd + resid2d[(i - 1) * d + i_j]
                s = s + resid2[(i - 1) * d + i_j]
            end
            __idx_row_mean_stack_2 = max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + (((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1)
            row_mean_stack_d[__idx_row_mean_stack_2] = row_meand
            row_mean_stack[__idx_row_mean_stack_2] = row_mean
            row_meand = (1.0 / d) * sd
            row_mean = s / d
            s2d = 0.0
            s2 = 0.0
            for i_j = 1:d
                diffd = resid2d[(i - 1) * d + i_j] + -row_meand
                diff = resid2[(i - 1) * d + i_j] - row_mean
                __cse_64 = diff * diffd
                s2d = s2d + (__cse_64 + __cse_64)
                s2 = s2 + diff * diff
            end
            __idx_row_var_stack_7 = max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + (((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1)
            row_var_stack_d[__idx_row_var_stack_7] = row_vard
            row_var_stack[__idx_row_var_stack_7] = row_var
            row_vard = (1.0 / d) * s2d
            row_var = s2 / d
            __idx_denom_stack_10 = max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + (((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1)
            denom_stack_d[__idx_denom_stack_10] = denomd
            denom_stack[__idx_denom_stack_10] = denom
            __cse_65 = sqrt(row_var + eps)
            denomd = (1.0 / (2.0__cse_65)) * (row_vard + epsd)
            denom = __cse_65
            for j = 1:d
                kk = (i - 1) * d + j
                __cse_66 = ln2_gain[ln2_offset + j]
                __cse_67 = resid2[kk] - row_mean
                __cse_68 = __cse_67 / denom
                x_nextd[kk] = (__cse_66 * ((1.0 / denom) * (resid2d[kk] + -row_meand) + -(__cse_67 / denom ^ 2) * denomd) + __cse_68 * ln2_gaind[ln2_offset + j]) + ln2_biasd[ln2_offset + j]
                x_next[kk] = __cse_68 * __cse_66 + ln2_bias[ln2_offset + j]
            end
            __idx_s_stack_14 = ((((((((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * dk - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_dff - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + (((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1)
            s_stack_d[__idx_s_stack_14] = sd
            s_stack[__idx_s_stack_14] = s
            __idx_s2_stack_16 = max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + (((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1)
            s2_stack_d[__idx_s2_stack_16] = s2d
            s2_stack[__idx_s2_stack_16] = s2
        end
        for idx = 1:n_d
            __idx_x_stack_0 = ((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1
            x_stack_d[__idx_x_stack_0] = xd[idx]
            x_stack[__idx_x_stack_0] = x[idx]
            xd[idx] = x_nextd[idx]
            x[idx] = x_next[idx]
        end
        __idx_denom_stack_20 = (max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + ((i_l - 1) + 1)
        denom_stack_d[__idx_denom_stack_20] = denomd
        denom_stack[__idx_denom_stack_20] = denom
        __idx_row_mean_stack_22 = (max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + ((i_l - 1) + 1)
        row_mean_stack_d[__idx_row_mean_stack_22] = row_meand
        row_mean_stack[__idx_row_mean_stack_22] = row_mean
        __idx_row_var_stack_24 = (max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + ((i_l - 1) + 1)
        row_var_stack_d[__idx_row_var_stack_24] = row_vard
        row_var_stack[__idx_row_var_stack_24] = row_var
    end
    __idx_denom_stack_5 = ((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1)) + 1
    denom_stack_d[__idx_denom_stack_5] = denomd
    denom_stack[__idx_denom_stack_5] = denom
    __idx_row_mean_stack_7 = ((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1)) + 1
    row_mean_stack_d[__idx_row_mean_stack_7] = row_meand
    row_mean_stack[__idx_row_mean_stack_7] = row_mean
    __idx_row_var_stack_9 = ((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1)) + 1
    row_var_stack_d[__idx_row_var_stack_9] = row_vard
    row_var_stack[__idx_row_var_stack_9] = row_var
    __idx_denom_stack_0 = ((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1)) + 1
    denomd = denom_stack_d[__idx_denom_stack_0]
    denom = denom_stack[__idx_denom_stack_0]
    __idx_row_mean_stack_2 = ((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1)) + 1
    row_meand = row_mean_stack_d[__idx_row_mean_stack_2]
    row_mean = row_mean_stack[__idx_row_mean_stack_2]
    __idx_row_var_stack_4 = ((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1)) + 1
    row_vard = row_var_stack_d[__idx_row_var_stack_4]
    row_var = row_var_stack[__idx_row_var_stack_4]
    d = h * dk
    n_d = n * d
    n_dff = n * dff
    for i_l = n_layers:-1:1
        __idx_denom_stack_0 = (max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + ((i_l - 1) + 1)
        denomd = denom_stack_d[__idx_denom_stack_0]
        denom = denom_stack[__idx_denom_stack_0]
        __idx_row_mean_stack_2 = (max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + ((i_l - 1) + 1)
        row_meand = row_mean_stack_d[__idx_row_mean_stack_2]
        row_mean = row_mean_stack[__idx_row_mean_stack_2]
        __idx_row_var_stack_4 = (max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + ((i_l - 1) + 1)
        row_vard = row_var_stack_d[__idx_row_var_stack_4]
        row_var = row_var_stack[__idx_row_var_stack_4]
        w_offset = (i_l - 1) * d * d
        b_offset = (i_l - 1) * d
        ln_offset = (i_l - 1) * d
        w1_offset = (i_l - 1) * d * dff
        b1_offset = (i_l - 1) * dff
        w2_offset = (i_l - 1) * dff * d
        b2_offset = (i_l - 1) * d
        ln2_offset = (i_l - 1) * d
        for idx = n_d:-1:1
            __idx_x_stack_0 = ((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1
            xd[idx] = x_stack_d[__idx_x_stack_0]
            x[idx] = x_stack[__idx_x_stack_0]
            x_nextbd[idx] = x_nextbd[idx] + xbd[idx]
            x_nextb[idx] = x_nextb[idx] + xb[idx]
            xbd[idx] = 0.0
            xb[idx] = 0.0
        end
        for i = n:-1:1
            __idx_s_stack_0 = ((((((((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * dk - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_dff - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + (((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1)
            sd = s_stack_d[__idx_s_stack_0]
            s = s_stack[__idx_s_stack_0]
            __idx_s2_stack_2 = max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + (((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1)
            s2d = s2_stack_d[__idx_s2_stack_2]
            s2 = s2_stack[__idx_s2_stack_2]
            for j = d:-1:1
                kk = (i - 1) * d + j
                __cse_1d = x_nextbd[kk]
                __cse_1 = x_nextb[kk]
                __cse_69 = ln2_gain[ln2_offset + j]
                __cse_2d = __cse_1 * ln2_gaind[ln2_offset + j] + __cse_69 * __cse_1d
                __cse_2 = __cse_69 * __cse_1
                __cse_70 = denom ^ 2
                __cse_71 = 1.0 / __cse_70
                __cse_72 = 1.0 / denom
                __cse_3d = __cse_2 * (-__cse_71 * denomd) + __cse_72 * __cse_2d
                __cse_3 = __cse_72 * __cse_2
                resid2bd[kk] = resid2bd[kk] + __cse_3d
                resid2b[kk] = resid2b[kk] + __cse_3
                row_meanbd = row_meanbd + -__cse_3d
                row_meanb = row_meanb + -__cse_3
                __cse_4d = resid2d[kk] + -row_meand
                __cse_4 = resid2[kk] - row_mean
                __cse_73 = -(__cse_4 / __cse_70)
                denombd = denombd + (__cse_2 * -((__cse_71 * __cse_4d + -(__cse_4 / __cse_70 ^ 2) * ((2denom) * denomd))) + __cse_73 * __cse_2d)
                denomb = denomb + __cse_73 * __cse_2
                __cse_74 = __cse_4 / denom
                ln2_gainbd[ln2_offset + j] = ln2_gainbd[ln2_offset + j] + (__cse_1 * (__cse_72 * __cse_4d + __cse_73 * denomd) + __cse_74 * __cse_1d)
                ln2_gainb[ln2_offset + j] = ln2_gainb[ln2_offset + j] + __cse_74 * __cse_1
                ln2_biasbd[ln2_offset + j] = ln2_biasbd[ln2_offset + j] + __cse_1d
                ln2_biasb[ln2_offset + j] = ln2_biasb[ln2_offset + j] + __cse_1
                x_nextbd[kk] = 0.0
                x_nextb[kk] = 0.0
            end
            __idx_denom_stack_0 = max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + (((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1)
            denomd = denom_stack_d[__idx_denom_stack_0]
            denom = denom_stack[__idx_denom_stack_0]
            __cse_75 = 2.0 * sqrt(row_var + eps)
            __cse_76 = 1.0 / __cse_75
            __cse_5d = denomb * (-(1.0 / __cse_75 ^ 2) * (2.0 * (__cse_76 * (row_vard + epsd)))) + __cse_76 * denombd
            __cse_5 = __cse_76 * denomb
            row_varbd = row_varbd + __cse_5d
            row_varb = row_varb + __cse_5
            epsbd = epsbd + __cse_5d
            epsb = epsb + __cse_5
            denombd = 0.0
            denomb = 0.0
            __idx_row_var_stack_0 = max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + (((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1)
            row_vard = row_var_stack_d[__idx_row_var_stack_0]
            row_var = row_var_stack[__idx_row_var_stack_0]
            s2bd = s2bd + (1.0 / d) * row_varbd
            s2b = s2b + (1.0 / d) * row_varb
            row_varbd = 0.0
            row_varb = 0.0
            for i_j = 1:d
                diffd = resid2d[(i - 1) * d + i_j] + -row_meand
                diff = resid2[(i - 1) * d + i_j] - row_mean
                __cse_77 = diff * diffd
                s2d = s2d + (__cse_77 + __cse_77)
                s2 = s2 + diff * diff
                __cse_6d = s2b * diffd + diff * s2bd
                __cse_6 = diff * s2b
                diffbd = diffbd + __cse_6d
                diffb = diffb + __cse_6
                diffbd = diffbd + __cse_6d
                diffb = diffb + __cse_6
                resid2bd[(i - 1) * d + i_j] = resid2bd[(i - 1) * d + i_j] + diffbd
                resid2b[(i - 1) * d + i_j] = resid2b[(i - 1) * d + i_j] + diffb
                row_meanbd = row_meanbd + -diffbd
                row_meanb = row_meanb + -diffb
                diffbd = 0.0
                diffb = 0.0
            end
            s2bd = 0.0
            s2b = 0.0
            __idx_row_mean_stack_0 = max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + (((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1)
            row_meand = row_mean_stack_d[__idx_row_mean_stack_0]
            row_mean = row_mean_stack[__idx_row_mean_stack_0]
            sbd = sbd + (1.0 / d) * row_meanbd
            sb = sb + (1.0 / d) * row_meanb
            row_meanbd = 0.0
            row_meanb = 0.0
            for i_j = 1:d
                sd = sd + resid2d[(i - 1) * d + i_j]
                s = s + resid2[(i - 1) * d + i_j]
                resid2bd[(i - 1) * d + i_j] = resid2bd[(i - 1) * d + i_j] + sbd
                resid2b[(i - 1) * d + i_j] = resid2b[(i - 1) * d + i_j] + sb
            end
            sbd = 0.0
            sb = 0.0
        end
        for idx = n_d:-1:1
            __idx_resid2_stack_0 = ((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1
            resid2d[idx] = resid2_stack_d[__idx_resid2_stack_0]
            resid2[idx] = resid2_stack[__idx_resid2_stack_0]
            __cse_7d = resid2bd[idx]
            __cse_7 = resid2b[idx]
            normed1bd[idx] = normed1bd[idx] + __cse_7d
            normed1b[idx] = normed1b[idx] + __cse_7
            ff_outbd[idx] = ff_outbd[idx] + __cse_7d
            ff_outb[idx] = ff_outb[idx] + __cse_7
            resid2bd[idx] = 0.0
            resid2b[idx] = 0.0
        end
        for idx = n_d:-1:1
            __idx_s_stack_0 = (((((((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * dk - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_dff - 1, 1) + 1)) + (((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1)
            sd = s_stack_d[__idx_s_stack_0]
            s = s_stack[__idx_s_stack_0]
            i = div(idx - 1, d) + 1
            j = mod(idx - 1, d) + 1
            __cse_8d = ff_outbd[(i - 1) * d + j]
            __cse_8 = ff_outb[(i - 1) * d + j]
            sbd = sbd + __cse_8d
            sb = sb + __cse_8
            b2bd[b2_offset + j] = b2bd[b2_offset + j] + __cse_8d
            b2b[b2_offset + j] = b2b[b2_offset + j] + __cse_8
            ff_outbd[(i - 1) * d + j] = 0.0
            ff_outb[(i - 1) * d + j] = 0.0
            for i_p = 1:dff
                __cse_9d = ff_hiddend[(i - 1) * dff + i_p]
                __cse_9 = ff_hidden[(i - 1) * dff + i_p]
                __cse_10d = w2d[w2_offset + (i_p - 1) * d + j]
                __cse_10 = w2[w2_offset + (i_p - 1) * d + j]
                sd = sd + (__cse_10 * __cse_9d + __cse_9 * __cse_10d)
                s = s + __cse_9 * __cse_10
                ff_hiddenbd[(i - 1) * dff + i_p] = ff_hiddenbd[(i - 1) * dff + i_p] + (sb * __cse_10d + __cse_10 * sbd)
                ff_hiddenb[(i - 1) * dff + i_p] = ff_hiddenb[(i - 1) * dff + i_p] + __cse_10 * sb
                w2bd[w2_offset + (i_p - 1) * d + j] = w2bd[w2_offset + (i_p - 1) * d + j] + (sb * __cse_9d + __cse_9 * sbd)
                w2b[w2_offset + (i_p - 1) * d + j] = w2b[w2_offset + (i_p - 1) * d + j] + __cse_9 * sb
            end
            sbd = 0.0
            sb = 0.0
        end
        for idx = n_dff:-1:1
            __idx_s_stack_0 = ((((((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * dk - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n - 1, 1) + 1)) + (((i_l - 1) * (div(n_dff - 1, 1) + 1) + (idx - 1)) + 1)
            sd = s_stack_d[__idx_s_stack_0]
            s = s_stack[__idx_s_stack_0]
            i = div(idx - 1, dff) + 1
            j = mod(idx - 1, dff) + 1
            __idx_ff_hidden_stack_0 = ((i_l - 1) * (div(n_dff - 1, 1) + 1) + (idx - 1)) + 1
            ff_hiddend[(i - 1) * dff + j] = ff_hidden_stack_d[__idx_ff_hidden_stack_0]
            ff_hidden[(i - 1) * dff + j] = ff_hidden_stack[__idx_ff_hidden_stack_0]
            __cse_78 = 0.5 * (1.0 + sign(s + b1[b1_offset + j]))
            __cse_11d = __cse_78 * ff_hiddenbd[(i - 1) * dff + j]
            __cse_11 = __cse_78 * ff_hiddenb[(i - 1) * dff + j]
            sbd = sbd + __cse_11d
            sb = sb + __cse_11
            b1bd[b1_offset + j] = b1bd[b1_offset + j] + __cse_11d
            b1b[b1_offset + j] = b1b[b1_offset + j] + __cse_11
            ff_hiddenbd[(i - 1) * dff + j] = 0.0
            ff_hiddenb[(i - 1) * dff + j] = 0.0
            for i_p = 1:d
                __cse_12d = normed1d[(i - 1) * d + i_p]
                __cse_12 = normed1[(i - 1) * d + i_p]
                __cse_13d = w1d[w1_offset + (i_p - 1) * dff + j]
                __cse_13 = w1[w1_offset + (i_p - 1) * dff + j]
                sd = sd + (__cse_13 * __cse_12d + __cse_12 * __cse_13d)
                s = s + __cse_12 * __cse_13
                normed1bd[(i - 1) * d + i_p] = normed1bd[(i - 1) * d + i_p] + (sb * __cse_13d + __cse_13 * sbd)
                normed1b[(i - 1) * d + i_p] = normed1b[(i - 1) * d + i_p] + __cse_13 * sb
                w1bd[w1_offset + (i_p - 1) * dff + j] = w1bd[w1_offset + (i_p - 1) * dff + j] + (sb * __cse_12d + __cse_12 * sbd)
                w1b[w1_offset + (i_p - 1) * dff + j] = w1b[w1_offset + (i_p - 1) * dff + j] + __cse_12 * sb
            end
            sbd = 0.0
            sb = 0.0
        end
        for i = n:-1:1
            __idx_s_stack_0 = (((((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * dk - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + (((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1)
            sd = s_stack_d[__idx_s_stack_0]
            s = s_stack[__idx_s_stack_0]
            __idx_s2_stack_2 = ((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1
            s2d = s2_stack_d[__idx_s2_stack_2]
            s2 = s2_stack[__idx_s2_stack_2]
            for j = d:-1:1
                kk = (i - 1) * d + j
                __idx_normed1_stack_0 = ((i_l - 1) * ((div(n - 1, 1) + 1) * (div(d - 1, 1) + 1)) + (i - 1) * (div(d - 1, 1) + 1) + (j - 1)) + 1
                normed1d[kk] = normed1_stack_d[__idx_normed1_stack_0]
                normed1[kk] = normed1_stack[__idx_normed1_stack_0]
                __cse_14d = normed1bd[kk]
                __cse_14 = normed1b[kk]
                __cse_79 = ln1_gain[ln_offset + j]
                __cse_15d = __cse_14 * ln1_gaind[ln_offset + j] + __cse_79 * __cse_14d
                __cse_15 = __cse_79 * __cse_14
                __cse_80 = denom ^ 2
                __cse_81 = 1.0 / __cse_80
                __cse_82 = 1.0 / denom
                __cse_16d = __cse_15 * (-__cse_81 * denomd) + __cse_82 * __cse_15d
                __cse_16 = __cse_82 * __cse_15
                resid1bd[kk] = resid1bd[kk] + __cse_16d
                resid1b[kk] = resid1b[kk] + __cse_16
                row_meanbd = row_meanbd + -__cse_16d
                row_meanb = row_meanb + -__cse_16
                __cse_17d = resid1d[kk] + -row_meand
                __cse_17 = resid1[kk] - row_mean
                __cse_83 = -(__cse_17 / __cse_80)
                denombd = denombd + (__cse_15 * -((__cse_81 * __cse_17d + -(__cse_17 / __cse_80 ^ 2) * ((2denom) * denomd))) + __cse_83 * __cse_15d)
                denomb = denomb + __cse_83 * __cse_15
                __cse_84 = __cse_17 / denom
                ln1_gainbd[ln_offset + j] = ln1_gainbd[ln_offset + j] + (__cse_14 * (__cse_82 * __cse_17d + __cse_83 * denomd) + __cse_84 * __cse_14d)
                ln1_gainb[ln_offset + j] = ln1_gainb[ln_offset + j] + __cse_84 * __cse_14
                ln1_biasbd[ln_offset + j] = ln1_biasbd[ln_offset + j] + __cse_14d
                ln1_biasb[ln_offset + j] = ln1_biasb[ln_offset + j] + __cse_14
                normed1bd[kk] = 0.0
                normed1b[kk] = 0.0
            end
            __idx_denom_stack_0 = ((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1
            denomd = denom_stack_d[__idx_denom_stack_0]
            denom = denom_stack[__idx_denom_stack_0]
            __cse_85 = 2.0 * sqrt(row_var + eps)
            __cse_86 = 1.0 / __cse_85
            __cse_18d = denomb * (-(1.0 / __cse_85 ^ 2) * (2.0 * (__cse_86 * (row_vard + epsd)))) + __cse_86 * denombd
            __cse_18 = __cse_86 * denomb
            row_varbd = row_varbd + __cse_18d
            row_varb = row_varb + __cse_18
            epsbd = epsbd + __cse_18d
            epsb = epsb + __cse_18
            denombd = 0.0
            denomb = 0.0
            __idx_row_var_stack_0 = ((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1
            row_vard = row_var_stack_d[__idx_row_var_stack_0]
            row_var = row_var_stack[__idx_row_var_stack_0]
            s2bd = s2bd + (1.0 / d) * row_varbd
            s2b = s2b + (1.0 / d) * row_varb
            row_varbd = 0.0
            row_varb = 0.0
            for i_j = 1:d
                diffd = resid1d[(i - 1) * d + i_j] + -row_meand
                diff = resid1[(i - 1) * d + i_j] - row_mean
                __cse_87 = diff * diffd
                s2d = s2d + (__cse_87 + __cse_87)
                s2 = s2 + diff * diff
                __cse_19d = s2b * diffd + diff * s2bd
                __cse_19 = diff * s2b
                diffbd = diffbd + __cse_19d
                diffb = diffb + __cse_19
                diffbd = diffbd + __cse_19d
                diffb = diffb + __cse_19
                resid1bd[(i - 1) * d + i_j] = resid1bd[(i - 1) * d + i_j] + diffbd
                resid1b[(i - 1) * d + i_j] = resid1b[(i - 1) * d + i_j] + diffb
                row_meanbd = row_meanbd + -diffbd
                row_meanb = row_meanb + -diffb
                diffbd = 0.0
                diffb = 0.0
            end
            s2bd = 0.0
            s2b = 0.0
            __idx_row_mean_stack_0 = ((i_l - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1
            row_meand = row_mean_stack_d[__idx_row_mean_stack_0]
            row_mean = row_mean_stack[__idx_row_mean_stack_0]
            sbd = sbd + (1.0 / d) * row_meanbd
            sb = sb + (1.0 / d) * row_meanb
            row_meanbd = 0.0
            row_meanb = 0.0
            for i_j = 1:d
                sd = sd + resid1d[(i - 1) * d + i_j]
                s = s + resid1[(i - 1) * d + i_j]
                resid1bd[(i - 1) * d + i_j] = resid1bd[(i - 1) * d + i_j] + sbd
                resid1b[(i - 1) * d + i_j] = resid1b[(i - 1) * d + i_j] + sb
            end
            sbd = 0.0
            sb = 0.0
        end
        for idx = n_d:-1:1
            __idx_resid1_stack_0 = ((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1
            resid1d[idx] = resid1_stack_d[__idx_resid1_stack_0]
            resid1[idx] = resid1_stack[__idx_resid1_stack_0]
            __cse_20d = resid1bd[idx]
            __cse_20 = resid1b[idx]
            xbd[idx] = xbd[idx] + __cse_20d
            xb[idx] = xb[idx] + __cse_20
            attn_outbd[idx] = attn_outbd[idx] + __cse_20d
            attn_outb[idx] = attn_outb[idx] + __cse_20
            resid1bd[idx] = 0.0
            resid1b[idx] = 0.0
        end
        for idx = n_d:-1:1
            __idx_s_stack_0 = ((((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * n - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * dk - 1, 1) + 1)) + (((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1)
            sd = s_stack_d[__idx_s_stack_0]
            s = s_stack[__idx_s_stack_0]
            i = div(idx - 1, d) + 1
            j = mod(idx - 1, d) + 1
            __cse_21d = attn_outbd[(i - 1) * d + j]
            __cse_21 = attn_outb[(i - 1) * d + j]
            sbd = sbd + __cse_21d
            sb = sb + __cse_21
            bobd[b_offset + j] = bobd[b_offset + j] + __cse_21d
            bob[b_offset + j] = bob[b_offset + j] + __cse_21
            attn_outbd[(i - 1) * d + j] = 0.0
            attn_outb[(i - 1) * d + j] = 0.0
            for i_p = 1:d
                __cse_22d = ctxd[(i - 1) * d + i_p]
                __cse_22 = ctx[(i - 1) * d + i_p]
                __cse_23d = wod[w_offset + (i_p - 1) * d + j]
                __cse_23 = wo[w_offset + (i_p - 1) * d + j]
                sd = sd + (__cse_23 * __cse_22d + __cse_22 * __cse_23d)
                s = s + __cse_22 * __cse_23
                ctxbd[(i - 1) * d + i_p] = ctxbd[(i - 1) * d + i_p] + (sb * __cse_23d + __cse_23 * sbd)
                ctxb[(i - 1) * d + i_p] = ctxb[(i - 1) * d + i_p] + __cse_23 * sb
                wobd[w_offset + (i_p - 1) * d + j] = wobd[w_offset + (i_p - 1) * d + j] + (sb * __cse_22d + __cse_22 * sbd)
                wob[w_offset + (i_p - 1) * d + j] = wob[w_offset + (i_p - 1) * d + j] + __cse_22 * sb
            end
            sbd = 0.0
            sb = 0.0
        end
        for hh = h:-1:1
            head_offset = (hh - 1) * dk
            score_off = (hh - 1) * n * n
            for idx3 = n * dk:-1:1
                __idx_s_stack_0 = (((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n * n - 1, 1) + 1)) + (((i_l - 1) * ((div(h - 1, 1) + 1) * (div(n * dk - 1, 1) + 1)) + (hh - 1) * (div(n * dk - 1, 1) + 1) + (idx3 - 1)) + 1)
                sd = s_stack_d[__idx_s_stack_0]
                s = s_stack[__idx_s_stack_0]
                i = div(idx3 - 1, dk) + 1
                p = mod(idx3 - 1, dk) + 1
                __idx_ctx_stack_0 = ((i_l - 1) * ((div(h - 1, 1) + 1) * (div(n * dk - 1, 1) + 1)) + (hh - 1) * (div(n * dk - 1, 1) + 1) + (idx3 - 1)) + 1
                ctxd[(i - 1) * d + head_offset + p] = ctx_stack_d[__idx_ctx_stack_0]
                ctx[(i - 1) * d + head_offset + p] = ctx_stack[__idx_ctx_stack_0]
                sbd = sbd + ctxbd[(i - 1) * d + head_offset + p]
                sb = sb + ctxb[(i - 1) * d + head_offset + p]
                ctxbd[(i - 1) * d + head_offset + p] = 0.0
                ctxb[(i - 1) * d + head_offset + p] = 0.0
                for i_j = 1:n
                    __cse_24d = probsd[score_off + (i - 1) * n + i_j]
                    __cse_24 = probs[score_off + (i - 1) * n + i_j]
                    __cse_25d = vd[(i_j - 1) * d + head_offset + p]
                    __cse_25 = v[(i_j - 1) * d + head_offset + p]
                    sd = sd + (__cse_25 * __cse_24d + __cse_24 * __cse_25d)
                    s = s + __cse_24 * __cse_25
                    probsbd[score_off + (i - 1) * n + i_j] = probsbd[score_off + (i - 1) * n + i_j] + (sb * __cse_25d + __cse_25 * sbd)
                    probsb[score_off + (i - 1) * n + i_j] = probsb[score_off + (i - 1) * n + i_j] + __cse_25 * sb
                    vbd[(i_j - 1) * d + head_offset + p] = vbd[(i_j - 1) * d + head_offset + p] + (sb * __cse_24d + __cse_24 * sbd)
                    vb[(i_j - 1) * d + head_offset + p] = vb[(i_j - 1) * d + head_offset + p] + __cse_24 * sb
                end
                sbd = 0.0
                sb = 0.0
            end
            for i = n:-1:1
                __idx_row_max_stack_0 = max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) * max(0, div(n - 2, 1) + 1) + (((i_l - 1) * ((div(h - 1, 1) + 1) * (div(n - 1, 1) + 1)) + (hh - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1)
                row_maxd = row_max_stack_d[__idx_row_max_stack_0]
                row_max = row_max_stack[__idx_row_max_stack_0]
                __idx_row_sum_stack_2 = ((i_l - 1) * ((div(h - 1, 1) + 1) * (div(n - 1, 1) + 1)) + (hh - 1) * (div(n - 1, 1) + 1) + (i - 1)) + 1
                row_sumd = row_sum_stack_d[__idx_row_sum_stack_2]
                row_sum = row_sum_stack[__idx_row_sum_stack_2]
                for j = n:-1:1
                    kk = score_off + (i - 1) * n + j
                    __idx_probs_stack_0 = max(0, div(n_layers - 1, 1) + 1) * max(0, div(h - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) * max(0, div(n - 1, 1) + 1) + (((i_l - 1) * ((div(h - 1, 1) + 1) * (div(n - 1, 1) + 1) * (div(n - 1, 1) + 1)) + (hh - 1) * ((div(n - 1, 1) + 1) * (div(n - 1, 1) + 1)) + (i - 1) * (div(n - 1, 1) + 1) + (j - 1)) + 1)
                    probsd[kk] = probs_stack_d[__idx_probs_stack_0]
                    probs[kk] = probs_stack[__idx_probs_stack_0]
                    __cse_26d = probsbd[kk]
                    __cse_26 = probsb[kk]
                    __cse_88 = row_sum ^ 2
                    __cse_89 = 1.0 / __cse_88
                    __cse_90 = probs[kk]
                    __cse_91 = -(__cse_90 / __cse_88)
                    row_sumbd = row_sumbd + (__cse_26 * -((__cse_89 * probsd[kk] + -(__cse_90 / __cse_88 ^ 2) * ((2row_sum) * row_sumd))) + __cse_91 * __cse_26d)
                    row_sumb = row_sumb + __cse_91 * __cse_26
                    __cse_92 = 1.0 / row_sum
                    probsbd[kk] = __cse_26 * (-__cse_89 * row_sumd) + __cse_92 * __cse_26d
                    probsb[kk] = __cse_92 * __cse_26
                end
                for i_j = 1:n
                    row_sumd = row_sumd + probsd[score_off + (i - 1) * n + i_j]
                    row_sum = row_sum + probs[score_off + (i - 1) * n + i_j]
                    probsbd[score_off + (i - 1) * n + i_j] = probsbd[score_off + (i - 1) * n + i_j] + row_sumbd
                    probsb[score_off + (i - 1) * n + i_j] = probsb[score_off + (i - 1) * n + i_j] + row_sumb
                end
                row_sumbd = 0.0
                row_sumb = 0.0
                for j = n:-1:1
                    kk = score_off + (i - 1) * n + j
                    __idx_probs_stack_0 = ((i_l - 1) * ((div(h - 1, 1) + 1) * (div(n - 1, 1) + 1) * (div(n - 1, 1) + 1)) + (hh - 1) * ((div(n - 1, 1) + 1) * (div(n - 1, 1) + 1)) + (i - 1) * (div(n - 1, 1) + 1) + (j - 1)) + 1
                    probsd[kk] = probs_stack_d[__idx_probs_stack_0]
                    probs[kk] = probs_stack[__idx_probs_stack_0]
                    __cse_93 = probsb[kk]
                    __cse_94 = exp(scores[kk] - row_max)
                    __cse_27d = __cse_93 * (__cse_94 * (scoresd[kk] + -row_maxd)) + __cse_94 * probsbd[kk]
                    __cse_27 = __cse_94 * __cse_93
                    scoresbd[kk] = scoresbd[kk] + __cse_27d
                    scoresb[kk] = scoresb[kk] + __cse_27
                    row_maxbd = row_maxbd + -__cse_27d
                    row_maxb = row_maxb + -__cse_27
                    probsbd[kk] = 0.0
                    probsb[kk] = 0.0
                end
                for i_j = n:-1:2
                    __idx_row_max_stack_0 = ((i_l - 1) * ((div(h - 1, 1) + 1) * (div(n - 1, 1) + 1) * (div(n - 2, 1) + 1)) + (hh - 1) * ((div(n - 1, 1) + 1) * (div(n - 2, 1) + 1)) + (i - 1) * (div(n - 2, 1) + 1) + (i_j - 2)) + 1
                    row_maxd = row_max_stack_d[__idx_row_max_stack_0]
                    row_max = row_max_stack[__idx_row_max_stack_0]
                    __cse_28 = scores[score_off + (i - 1) * n + i_j]
                    __cse_95 = 0.5 * (1.0 + sign(__cse_28 - row_max))
                    scoresbd[score_off + (i - 1) * n + i_j] = scoresbd[score_off + (i - 1) * n + i_j] + __cse_95 * row_maxbd
                    scoresb[score_off + (i - 1) * n + i_j] = scoresb[score_off + (i - 1) * n + i_j] + __cse_95 * row_maxb
                    __cse_96 = 0.5 * (1.0 + sign(row_max - __cse_28))
                    row_maxbd = __cse_96 * row_maxbd
                    row_maxb = __cse_96 * row_maxb
                end
                scoresbd[score_off + (i - 1) * n + 1] = scoresbd[score_off + (i - 1) * n + 1] + row_maxbd
                scoresb[score_off + (i - 1) * n + 1] = scoresb[score_off + (i - 1) * n + 1] + row_maxb
                row_maxbd = 0.0
                row_maxb = 0.0
            end
            for idx2 = n * n:-1:1
                __idx_s_stack_0 = ((max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + (((i_l - 1) * ((div(h - 1, 1) + 1) * (div(n * n - 1, 1) + 1)) + (hh - 1) * (div(n * n - 1, 1) + 1) + (idx2 - 1)) + 1)
                sd = s_stack_d[__idx_s_stack_0]
                s = s_stack[__idx_s_stack_0]
                i = div(idx2 - 1, n) + 1
                j = mod(idx2 - 1, n) + 1
                __idx_scores_stack_0 = ((i_l - 1) * ((div(h - 1, 1) + 1) * (div(n * n - 1, 1) + 1)) + (hh - 1) * (div(n * n - 1, 1) + 1) + (idx2 - 1)) + 1
                scoresd[score_off + (i - 1) * n + j] = scores_stack_d[__idx_scores_stack_0]
                scores[score_off + (i - 1) * n + j] = scores_stack[__idx_scores_stack_0]
                __cse_97 = scoresb[score_off + (i - 1) * n + j]
                sbd = sbd + (__cse_97 * inv_sqrt_dkd + inv_sqrt_dk * scoresbd[score_off + (i - 1) * n + j])
                sb = sb + inv_sqrt_dk * __cse_97
                scoresbd[score_off + (i - 1) * n + j] = 0.0
                scoresb[score_off + (i - 1) * n + j] = 0.0
                for i_p = 1:dk
                    __cse_29d = qd[(i - 1) * d + head_offset + i_p]
                    __cse_29 = q[(i - 1) * d + head_offset + i_p]
                    __cse_30d = kd[(j - 1) * d + head_offset + i_p]
                    __cse_30 = k[(j - 1) * d + head_offset + i_p]
                    sd = sd + (__cse_30 * __cse_29d + __cse_29 * __cse_30d)
                    s = s + __cse_29 * __cse_30
                    qbd[(i - 1) * d + head_offset + i_p] = qbd[(i - 1) * d + head_offset + i_p] + (sb * __cse_30d + __cse_30 * sbd)
                    qb[(i - 1) * d + head_offset + i_p] = qb[(i - 1) * d + head_offset + i_p] + __cse_30 * sb
                    kbd[(j - 1) * d + head_offset + i_p] = kbd[(j - 1) * d + head_offset + i_p] + (sb * __cse_29d + __cse_29 * sbd)
                    kb[(j - 1) * d + head_offset + i_p] = kb[(j - 1) * d + head_offset + i_p] + __cse_29 * sb
                end
                sbd = 0.0
                sb = 0.0
            end
        end
        for idx = n_d:-1:1
            __idx_s_stack_0 = (max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1) + max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1)) + (((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1)
            sd = s_stack_d[__idx_s_stack_0]
            s = s_stack[__idx_s_stack_0]
            i = div(idx - 1, d) + 1
            j = mod(idx - 1, d) + 1
            __idx_v_stack_0 = ((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1
            vd[(i - 1) * d + j] = v_stack_d[__idx_v_stack_0]
            v[(i - 1) * d + j] = v_stack[__idx_v_stack_0]
            __cse_31d = vbd[(i - 1) * d + j]
            __cse_31 = vb[(i - 1) * d + j]
            sbd = sbd + __cse_31d
            sb = sb + __cse_31
            bvbd[b_offset + j] = bvbd[b_offset + j] + __cse_31d
            bvb[b_offset + j] = bvb[b_offset + j] + __cse_31
            vbd[(i - 1) * d + j] = 0.0
            vb[(i - 1) * d + j] = 0.0
            for i_p = 1:d
                __cse_32d = xd[(i - 1) * d + i_p]
                __cse_32 = x[(i - 1) * d + i_p]
                __cse_33d = wvd[w_offset + (i_p - 1) * d + j]
                __cse_33 = wv[w_offset + (i_p - 1) * d + j]
                sd = sd + (__cse_33 * __cse_32d + __cse_32 * __cse_33d)
                s = s + __cse_32 * __cse_33
                xbd[(i - 1) * d + i_p] = xbd[(i - 1) * d + i_p] + (sb * __cse_33d + __cse_33 * sbd)
                xb[(i - 1) * d + i_p] = xb[(i - 1) * d + i_p] + __cse_33 * sb
                wvbd[w_offset + (i_p - 1) * d + j] = wvbd[w_offset + (i_p - 1) * d + j] + (sb * __cse_32d + __cse_32 * sbd)
                wvb[w_offset + (i_p - 1) * d + j] = wvb[w_offset + (i_p - 1) * d + j] + __cse_32 * sb
            end
            sbd = 0.0
            sb = 0.0
        end
        for idx = n_d:-1:1
            __idx_s_stack_0 = max(0, div(n_layers - 1, 1) + 1) * max(0, div(n_d - 1, 1) + 1) + (((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1)
            sd = s_stack_d[__idx_s_stack_0]
            s = s_stack[__idx_s_stack_0]
            i = div(idx - 1, d) + 1
            j = mod(idx - 1, d) + 1
            __idx_k_stack_0 = ((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1
            kd[(i - 1) * d + j] = k_stack_d[__idx_k_stack_0]
            k[(i - 1) * d + j] = k_stack[__idx_k_stack_0]
            __cse_34d = kbd[(i - 1) * d + j]
            __cse_34 = kb[(i - 1) * d + j]
            sbd = sbd + __cse_34d
            sb = sb + __cse_34
            bkbd[b_offset + j] = bkbd[b_offset + j] + __cse_34d
            bkb[b_offset + j] = bkb[b_offset + j] + __cse_34
            kbd[(i - 1) * d + j] = 0.0
            kb[(i - 1) * d + j] = 0.0
            for i_p = 1:d
                __cse_35d = xd[(i - 1) * d + i_p]
                __cse_35 = x[(i - 1) * d + i_p]
                __cse_36d = wkd[w_offset + (i_p - 1) * d + j]
                __cse_36 = wk[w_offset + (i_p - 1) * d + j]
                sd = sd + (__cse_36 * __cse_35d + __cse_35 * __cse_36d)
                s = s + __cse_35 * __cse_36
                xbd[(i - 1) * d + i_p] = xbd[(i - 1) * d + i_p] + (sb * __cse_36d + __cse_36 * sbd)
                xb[(i - 1) * d + i_p] = xb[(i - 1) * d + i_p] + __cse_36 * sb
                wkbd[w_offset + (i_p - 1) * d + j] = wkbd[w_offset + (i_p - 1) * d + j] + (sb * __cse_35d + __cse_35 * sbd)
                wkb[w_offset + (i_p - 1) * d + j] = wkb[w_offset + (i_p - 1) * d + j] + __cse_35 * sb
            end
            sbd = 0.0
            sb = 0.0
        end
        for idx = n_d:-1:1
            __idx_s_stack_0 = ((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1
            sd = s_stack_d[__idx_s_stack_0]
            s = s_stack[__idx_s_stack_0]
            i = div(idx - 1, d) + 1
            j = mod(idx - 1, d) + 1
            __idx_q_stack_0 = ((i_l - 1) * (div(n_d - 1, 1) + 1) + (idx - 1)) + 1
            qd[(i - 1) * d + j] = q_stack_d[__idx_q_stack_0]
            q[(i - 1) * d + j] = q_stack[__idx_q_stack_0]
            __cse_37d = qbd[(i - 1) * d + j]
            __cse_37 = qb[(i - 1) * d + j]
            sbd = sbd + __cse_37d
            sb = sb + __cse_37
            bqbd[b_offset + j] = bqbd[b_offset + j] + __cse_37d
            bqb[b_offset + j] = bqb[b_offset + j] + __cse_37
            qbd[(i - 1) * d + j] = 0.0
            qb[(i - 1) * d + j] = 0.0
            for i_p = 1:d
                __cse_38d = xd[(i - 1) * d + i_p]
                __cse_38 = x[(i - 1) * d + i_p]
                __cse_39d = wqd[w_offset + (i_p - 1) * d + j]
                __cse_39 = wq[w_offset + (i_p - 1) * d + j]
                sd = sd + (__cse_39 * __cse_38d + __cse_38 * __cse_39d)
                s = s + __cse_38 * __cse_39
                xbd[(i - 1) * d + i_p] = xbd[(i - 1) * d + i_p] + (sb * __cse_39d + __cse_39 * sbd)
                xb[(i - 1) * d + i_p] = xb[(i - 1) * d + i_p] + __cse_39 * sb
                wqbd[w_offset + (i_p - 1) * d + j] = wqbd[w_offset + (i_p - 1) * d + j] + (sb * __cse_38d + __cse_38 * sbd)
                wqb[w_offset + (i_p - 1) * d + j] = wqb[w_offset + (i_p - 1) * d + j] + __cse_38 * sb
            end
            sbd = 0.0
            sb = 0.0
        end
    end
    inv_sqrt_dkbd = 0.0
    inv_sqrt_dkb = 0.0
    return (epsb, epsbd)
end

function transformer(x, wq, bq, wk, bk, wv, bv, wo, bo, ln1_gain, ln1_bias, w1, b1, w2, b2, ln2_gain, ln2_bias, q, k, v, scores, probs, ctx, attn_out, resid1, normed1, ff_hidden, ff_out, resid2, x_next, n, dk, h, dff, n_layers, eps)
    d = h * dk
    inv_sqrt_dk = 1.0 / sqrt(dk)
    n_d = n * d
    n_dff = n * dff
    for i_l = 1:n_layers
        w_offset = (i_l - 1) * d * d
        b_offset = (i_l - 1) * d
        ln_offset = (i_l - 1) * d
        w1_offset = (i_l - 1) * d * dff
        b1_offset = (i_l - 1) * dff
        w2_offset = (i_l - 1) * dff * d
        b2_offset = (i_l - 1) * d
        ln2_offset = (i_l - 1) * d
        for idx = 1:n_d
            i = div(idx - 1, d) + 1
            j = mod(idx - 1, d) + 1
            s = 0.0
            for i_p = 1:d
                s = s + x[(i - 1) * d + i_p] * wq[w_offset + (i_p - 1) * d + j]
            end
            q[(i - 1) * d + j] = s + bq[b_offset + j]
        end
        for idx = 1:n_d
            i = div(idx - 1, d) + 1
            j = mod(idx - 1, d) + 1
            s = 0.0
            for i_p = 1:d
                s = s + x[(i - 1) * d + i_p] * wk[w_offset + (i_p - 1) * d + j]
            end
            k[(i - 1) * d + j] = s + bk[b_offset + j]
        end
        for idx = 1:n_d
            i = div(idx - 1, d) + 1
            j = mod(idx - 1, d) + 1
            s = 0.0
            for i_p = 1:d
                s = s + x[(i - 1) * d + i_p] * wv[w_offset + (i_p - 1) * d + j]
            end
            v[(i - 1) * d + j] = s + bv[b_offset + j]
        end
        for hh = 1:h
            head_offset = (hh - 1) * dk
            score_off = (hh - 1) * n * n
            for idx2 = 1:n * n
                i = div(idx2 - 1, n) + 1
                j = mod(idx2 - 1, n) + 1
                s = 0.0
                for i_p = 1:dk
                    s = s + q[(i - 1) * d + head_offset + i_p] * k[(j - 1) * d + head_offset + i_p]
                end
                scores[score_off + (i - 1) * n + j] = s * inv_sqrt_dk
            end
            for i = 1:n
                row_max = scores[score_off + (i - 1) * n + 1]
                for i_j = 2:n
                    row_max = max(row_max, scores[score_off + (i - 1) * n + i_j])
                end
                for j = 1:n
                    kk = score_off + (i - 1) * n + j
                    probs[kk] = exp(scores[kk] - row_max)
                end
                row_sum = 0.0
                for i_j = 1:n
                    row_sum = row_sum + probs[score_off + (i - 1) * n + i_j]
                end
                for j = 1:n
                    kk = score_off + (i - 1) * n + j
                    probs[kk] = probs[kk] / row_sum
                end
            end
            for idx3 = 1:n * dk
                i = div(idx3 - 1, dk) + 1
                p = mod(idx3 - 1, dk) + 1
                s = 0.0
                for i_j = 1:n
                    s = s + probs[score_off + (i - 1) * n + i_j] * v[(i_j - 1) * d + head_offset + p]
                end
                ctx[(i - 1) * d + head_offset + p] = s
            end
        end
        for idx = 1:n_d
            i = div(idx - 1, d) + 1
            j = mod(idx - 1, d) + 1
            s = 0.0
            for i_p = 1:d
                s = s + ctx[(i - 1) * d + i_p] * wo[w_offset + (i_p - 1) * d + j]
            end
            attn_out[(i - 1) * d + j] = s + bo[b_offset + j]
        end
        for idx = 1:n_d
            resid1[idx] = x[idx] + attn_out[idx]
        end
        for i = 1:n
            s = 0.0
            for i_j = 1:d
                s = s + resid1[(i - 1) * d + i_j]
            end
            row_mean = s / d
            s2 = 0.0
            for i_j = 1:d
                diff = resid1[(i - 1) * d + i_j] - row_mean
                s2 = s2 + diff * diff
            end
            row_var = s2 / d
            denom = sqrt(row_var + eps)
            for j = 1:d
                kk = (i - 1) * d + j
                normed1[kk] = ((resid1[kk] - row_mean) / denom) * ln1_gain[ln_offset + j] + ln1_bias[ln_offset + j]
            end
        end
        for idx = 1:n_dff
            i = div(idx - 1, dff) + 1
            j = mod(idx - 1, dff) + 1
            s = 0.0
            for i_p = 1:d
                s = s + normed1[(i - 1) * d + i_p] * w1[w1_offset + (i_p - 1) * dff + j]
            end
            ff_hidden[(i - 1) * dff + j] = max(s + b1[b1_offset + j], 0.0)
        end
        for idx = 1:n_d
            i = div(idx - 1, d) + 1
            j = mod(idx - 1, d) + 1
            s = 0.0
            for i_p = 1:dff
                s = s + ff_hidden[(i - 1) * dff + i_p] * w2[w2_offset + (i_p - 1) * d + j]
            end
            ff_out[(i - 1) * d + j] = s + b2[b2_offset + j]
        end
        for idx = 1:n_d
            resid2[idx] = normed1[idx] + ff_out[idx]
        end
        for i = 1:n
            s = 0.0
            for i_j = 1:d
                s = s + resid2[(i - 1) * d + i_j]
            end
            row_mean = s / d
            s2 = 0.0
            for i_j = 1:d
                diff = resid2[(i - 1) * d + i_j] - row_mean
                s2 = s2 + diff * diff
            end
            row_var = s2 / d
            denom = sqrt(row_var + eps)
            for j = 1:d
                kk = (i - 1) * d + j
                x_next[kk] = ((resid2[kk] - row_mean) / denom) * ln2_gain[ln2_offset + j] + ln2_bias[ln2_offset + j]
            end
        end
        for idx = 1:n_d
            x[idx] = x_next[idx]
        end
    end
end
