function initstacks_ttgc_b(i_ncell, i_njac, i_nnode)
    vere_stack = Vector{Float64}(undef, ((max(0, div(i_ncell - 1, 1) + 1) * max(0, div(4 - 1, 1) + 1) + max(0, div(i_ncell - 1, 1) + 1)) + max(0, div(i_ncell - 1, 1) + 1) * max(0, div(4 - 1, 1) + 1)) + max(0, div(i_ncell - 1, 1) + 1))
    mup_stack = Vector{Float64}(undef, ((max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_nnode - 1, 1) + 1) + max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_ncell - 1, 1) + 1) * max(0, div(4 - 1, 1) + 1)) + max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_nnode - 1, 1) + 1)) + max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_ncell - 1, 1) + 1) * max(0, div(4 - 1, 1) + 1))
    up_stack = Vector{Float64}(undef, (max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_nnode - 1, 1) + 1) + max(0, div(i_nnode - 1, 1) + 1)) + max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_nnode - 1, 1) + 1))
    auxu_stack = Vector{Float64}(undef, max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_ncell - 1, 1) + 1) + max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_ncell - 1, 1) + 1))
    return (vere_stack, mup_stack, up_stack, auxu_stack)
end

function ttgc_hv(u, ub, uref, urefb, i_cell_to_node, cell_vol, cell_volb, node_vol, node_volb, skx, skxb, sky, skyb, skz, skzb, i_ncell, i_nnode, c, cb, dt, dtb, beta, betab, gamma, gammab, i_njac, res, resb, res2, res2b, up, upb, mup, mupb, loss, lossb, ud, ubd, urefd, urefbd, cell_vold, cell_volbd, node_vold, node_volbd, skxd, skxbd, skyd, skybd, skzd, skzbd, cd, cbd, dtd, dtbd, betad, betabd, gammad, gammabd, resd, resbd, res2d, res2bd, upd, upbd, mupd, mupbd, lossd, lossbd, vere_stack, mup_stack, up_stack, auxu_stack)
    vere_stack_d = Vector{Float64}(undef, length(vere_stack))
    mup_stack_d = Vector{Float64}(undef, length(mup_stack))
    up_stack_d = Vector{Float64}(undef, length(up_stack))
    auxu_stack_d = Vector{Float64}(undef, length(auxu_stack))
    aeresk = 0.0
    aerex = 0.0
    aerey = 0.0
    aerez = 0.0
    auxres = 0.0
    auxres2 = 0.0
    auxu = 0.0
    cavgx = 0.0
    cavgy = 0.0
    cavgz = 0.0
    factor = 0.0
    re = 0.0
    resi = 0.0
    vere = 0.0
    aereskb = 0.0
    aerexb = 0.0
    aereyb = 0.0
    aerezb = 0.0
    auxresb = 0.0
    auxres2b = 0.0
    auxub = 0.0
    cavgxb = 0.0
    cavgyb = 0.0
    cavgzb = 0.0
    factorb = 0.0
    reb = 0.0
    resib = 0.0
    vereb = 0.0
    aereskd = 0.0
    aereskbd = 0.0
    aerexd = 0.0
    aerexbd = 0.0
    aereyd = 0.0
    aereybd = 0.0
    aerezd = 0.0
    aerezbd = 0.0
    auxresd = 0.0
    auxresbd = 0.0
    auxres2d = 0.0
    auxres2bd = 0.0
    auxud = 0.0
    auxubd = 0.0
    cavgxd = 0.0
    cavgxbd = 0.0
    cavgyd = 0.0
    cavgybd = 0.0
    cavgzd = 0.0
    cavgzbd = 0.0
    factord = 0.0
    factorbd = 0.0
    red = 0.0
    rebd = 0.0
    resid = 0.0
    resibd = 0.0
    vered = 0.0
    verebd = 0.0
    for i_cell = 1:i_ncell
        aereskd = 0.0
        aeresk = 0.0
        aerexd = 0.0
        aerex = 0.0
        aereyd = 0.0
        aerey = 0.0
        aerezd = 0.0
        aerez = 0.0
        factord = 0.0
        factor = 0.0
        red = 0.0
        re = 0.0
        vered = 0.0
        vere = 0.0
        cavgxd = 0.0
        cavgx = 0.0
        cavgyd = 0.0
        cavgy = 0.0
        cavgzd = 0.0
        cavgz = 0.0
        for i_loc = 1:4
            i_node = i_cell_to_node[i_loc, i_cell]
            cavgxd = cavgxd + 0.25 * cd[1, i_node]
            cavgx = cavgx + c[1, i_node] / 4
            cavgyd = cavgyd + 0.25 * cd[2, i_node]
            cavgy = cavgy + c[2, i_node] / 4
            cavgzd = cavgzd + 0.25 * cd[3, i_node]
            cavgz = cavgz + c[3, i_node] / 4
        end
        for i_loc = 1:4
            aereskd = 0.0
            aeresk = 0.0
            factord = 0.0
            factor = 0.0
            i_node = i_cell_to_node[i_loc, i_cell]
            __cse_41 = c[1, i_node]
            __cse_42 = skx[i_loc, i_cell]
            __cse_43 = c[2, i_node]
            __cse_44 = sky[i_loc, i_cell]
            __cse_45 = c[3, i_node]
            __cse_46 = skz[i_loc, i_cell]
            __cse_47 = __cse_41 * __cse_42 + __cse_43 * __cse_44 + __cse_45 * __cse_46
            __cse_48 = u[i_node]
            vered = (-(1.0 / 3.0) * __cse_47) * ud[i_node] + (-(1.0 / 3.0) * __cse_48) * (((__cse_42 * cd[1, i_node] + __cse_41 * skxd[i_loc, i_cell]) + (__cse_44 * cd[2, i_node] + __cse_43 * skyd[i_loc, i_cell])) + (__cse_46 * cd[3, i_node] + __cse_45 * skzd[i_loc, i_cell]))
            vere = -(1.0 / 3.0) * __cse_48 * __cse_47
            __cse_49 = cell_vol[i_cell]
            red = (1.0 / __cse_49) * vered + -(vere / __cse_49 ^ 2) * cell_vold[i_cell]
            re = vere / __cse_49
            aerexd = re * cavgxd + cavgx * red
            aerex = cavgx * re
            aereyd = re * cavgyd + cavgy * red
            aerey = cavgy * re
            aerezd = re * cavgzd + cavgz * red
            aerez = cavgz * re
            __cse_50 = 0.5 - gamma[i_cell]
            __cse_51 = -(dt / 4)
            resid = ((__cse_50 * vere) * -(0.25dtd) + (__cse_51 * vere) * -(gammad[i_cell])) + (__cse_51 * __cse_50) * vered
            resi = __cse_51 * __cse_50 * vere
            for i_k = 1:4
                __cse_52 = skx[i_k, i_cell]
                __cse_53 = sky[i_k, i_cell]
                __cse_54 = skz[i_k, i_cell]
                aereskd = ((__cse_52 * aerexd + aerex * skxd[i_k, i_cell]) + (__cse_53 * aereyd + aerey * skyd[i_k, i_cell])) + (__cse_54 * aerezd + aerez * skzd[i_k, i_cell])
                aeresk = aerex * __cse_52 + aerey * __cse_53 + aerez * __cse_54
                __cse_55 = dt ^ 2 / 3
                factord = aeresk * (0.3333333333333333 * ((2dt) * dtd)) + __cse_55 * aereskd
                factor = __cse_55 * aeresk
                __cse_56 = beta[i_cell]
                auxresd = resid + (__cse_56 * factord + factor * betad[i_cell])
                auxres = resi + factor * __cse_56
                __cse_57 = gamma[i_cell]
                auxres2d = __cse_57 * factord + factor * gammad[i_cell]
                auxres2 = factor * __cse_57
                i_k_node = i_cell_to_node[i_k, i_cell]
                resd[i_k_node] = resd[i_k_node] + auxresd
                res[i_k_node] = res[i_k_node] + auxres
                res2d[i_k_node] = res2d[i_k_node] + auxres2d
                res2[i_k_node] = res2[i_k_node] + auxres2
            end
        end
    end
    for i_node = 1:i_nnode
        __cse_58 = node_vol[i_node]
        __cse_59 = res[i_node]
        upd[i_node] = (1.0 / __cse_58) * resd[i_node] + -(__cse_59 / __cse_58 ^ 2) * node_vold[i_node]
        up[i_node] = __cse_59 / __cse_58
    end
    for i_ = 1:i_njac
        for i_node = 1:i_nnode
            __idx_mup_stack_0 = ((i_ - 1) * (div(i_nnode - 1, 1) + 1) + (i_node - 1)) + 1
            mup_stack_d[__idx_mup_stack_0] = mupd[i_node]
            mup_stack[__idx_mup_stack_0] = mup[i_node]
            mupd[i_node] = 0.0
            mup[i_node] = 0.0
        end
        for i_cell = 1:i_ncell
            auxud = 0.0
            auxu = 0.0
            for i_loc = 1:4
                i_lnode = i_cell_to_node[i_loc, i_cell]
                auxud = auxud + upd[i_lnode]
                auxu = auxu + up[i_lnode]
            end
            for i_loc = 1:4
                i_lnode = i_cell_to_node[i_loc, i_cell]
                __idx_mup_stack_1 = max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_nnode - 1, 1) + 1) + (((i_ - 1) * ((div(i_ncell - 1, 1) + 1) * (div(4 - 1, 1) + 1)) + (i_cell - 1) * (div(4 - 1, 1) + 1) + (i_loc - 1)) + 1)
                __cse_0d = mupd[i_lnode]
                __cse_0 = mup[i_lnode]
                mup_stack_d[__idx_mup_stack_1] = __cse_0d
                mup_stack[__idx_mup_stack_1] = __cse_0
                __cse_60 = cell_vol[i_cell]
                __cse_61 = auxu + up[i_lnode]
                mupd[i_lnode] = __cse_0d + 0.05 * (__cse_60 * (auxud + upd[i_lnode]) + __cse_61 * cell_vold[i_cell])
                mup[i_lnode] = __cse_0 + (__cse_61 * __cse_60) / 20.0
            end
            __idx_auxu_stack_3 = ((i_ - 1) * (div(i_ncell - 1, 1) + 1) + (i_cell - 1)) + 1
            auxu_stack_d[__idx_auxu_stack_3] = auxud
            auxu_stack[__idx_auxu_stack_3] = auxu
        end
        for i_node = 1:i_nnode
            __idx_up_stack_0 = ((i_ - 1) * (div(i_nnode - 1, 1) + 1) + (i_node - 1)) + 1
            __cse_1d = upd[i_node]
            __cse_1 = up[i_node]
            up_stack_d[__idx_up_stack_0] = __cse_1d
            up_stack[__idx_up_stack_0] = __cse_1
            __cse_62 = node_vol[i_node]
            __cse_63 = res[i_node] - mup[i_node]
            upd[i_node] = __cse_1d + ((1.0 / __cse_62) * (resd[i_node] + -(mupd[i_node])) + -(__cse_63 / __cse_62 ^ 2) * node_vold[i_node])
            up[i_node] = __cse_1 + __cse_63 / __cse_62
        end
    end
    for i_cell = 1:i_ncell
        vered = 0.0
        vere = 0.0
        for i_loc = 1:4
            i_node = i_cell_to_node[i_loc, i_cell]
            __idx_vere_stack_1 = (max(0, div(i_ncell - 1, 1) + 1) * max(0, div(4 - 1, 1) + 1) + max(0, div(i_ncell - 1, 1) + 1)) + (((i_cell - 1) * (div(4 - 1, 1) + 1) + (i_loc - 1)) + 1)
            vere_stack_d[__idx_vere_stack_1] = vered
            vere_stack[__idx_vere_stack_1] = vere
            __cse_64 = c[1, i_node]
            __cse_65 = skx[i_loc, i_cell]
            __cse_66 = c[2, i_node]
            __cse_67 = sky[i_loc, i_cell]
            __cse_68 = __cse_64 * __cse_65 + __cse_66 * __cse_67
            __cse_69 = u[i_node] + up[i_node]
            vered = (-(1.0 / 3.0) * __cse_68) * (ud[i_node] + upd[i_node]) + (-(1.0 / 3.0) * __cse_69) * ((__cse_65 * cd[1, i_node] + __cse_64 * skxd[i_loc, i_cell]) + (__cse_67 * cd[2, i_node] + __cse_66 * skyd[i_loc, i_cell]))
            vere = -(1.0 / 3.0) * __cse_69 * __cse_68
            __cse_70 = -(dt / 4)
            resid = vere * -(0.25dtd) + __cse_70 * vered
            resi = __cse_70 * vere
            for i_k = 1:4
                i_k_node = i_cell_to_node[i_k, i_cell]
                res2d[i_k_node] = res2d[i_k_node] + resid
                res2[i_k_node] = res2[i_k_node] + resi
            end
        end
        __idx_vere_stack_2 = ((max(0, div(i_ncell - 1, 1) + 1) * max(0, div(4 - 1, 1) + 1) + max(0, div(i_ncell - 1, 1) + 1)) + max(0, div(i_ncell - 1, 1) + 1) * max(0, div(4 - 1, 1) + 1)) + ((i_cell - 1) + 1)
        vere_stack_d[__idx_vere_stack_2] = vered
        vere_stack[__idx_vere_stack_2] = vere
    end
    for i_node = 1:i_nnode
        __idx_up_stack_0 = max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_nnode - 1, 1) + 1) + ((i_node - 1) + 1)
        up_stack_d[__idx_up_stack_0] = upd[i_node]
        up_stack[__idx_up_stack_0] = up[i_node]
        __cse_71 = node_vol[i_node]
        __cse_72 = res2[i_node]
        upd[i_node] = (1.0 / __cse_71) * res2d[i_node] + -(__cse_72 / __cse_71 ^ 2) * node_vold[i_node]
        up[i_node] = __cse_72 / __cse_71
    end
    for i_ = 1:i_njac
        for i_node = 1:i_nnode
            __idx_mup_stack_0 = (max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_nnode - 1, 1) + 1) + max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_ncell - 1, 1) + 1) * max(0, div(4 - 1, 1) + 1)) + (((i_ - 1) * (div(i_nnode - 1, 1) + 1) + (i_node - 1)) + 1)
            mup_stack_d[__idx_mup_stack_0] = mupd[i_node]
            mup_stack[__idx_mup_stack_0] = mup[i_node]
            mupd[i_node] = 0.0
            mup[i_node] = 0.0
        end
        for i_cell = 1:i_ncell
            auxud = 0.0
            auxu = 0.0
            for i_loc = 1:4
                i_lnode = i_cell_to_node[i_loc, i_cell]
                auxud = auxud + upd[i_lnode]
                auxu = auxu + up[i_lnode]
            end
            for i_loc = 1:4
                i_lnode = i_cell_to_node[i_loc, i_cell]
                __idx_mup_stack_1 = ((max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_nnode - 1, 1) + 1) + max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_ncell - 1, 1) + 1) * max(0, div(4 - 1, 1) + 1)) + max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_nnode - 1, 1) + 1)) + (((i_ - 1) * ((div(i_ncell - 1, 1) + 1) * (div(4 - 1, 1) + 1)) + (i_cell - 1) * (div(4 - 1, 1) + 1) + (i_loc - 1)) + 1)
                __cse_2d = mupd[i_lnode]
                __cse_2 = mup[i_lnode]
                mup_stack_d[__idx_mup_stack_1] = __cse_2d
                mup_stack[__idx_mup_stack_1] = __cse_2
                __cse_73 = cell_vol[i_cell]
                __cse_74 = auxu + up[i_lnode]
                mupd[i_lnode] = __cse_2d + 0.05 * (__cse_73 * (auxud + upd[i_lnode]) + __cse_74 * cell_vold[i_cell])
                mup[i_lnode] = __cse_2 + (__cse_74 * __cse_73) / 20.0
            end
            __idx_auxu_stack_3 = max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_ncell - 1, 1) + 1) + (((i_ - 1) * (div(i_ncell - 1, 1) + 1) + (i_cell - 1)) + 1)
            auxu_stack_d[__idx_auxu_stack_3] = auxud
            auxu_stack[__idx_auxu_stack_3] = auxu
        end
        for i_node = 1:i_nnode
            __idx_up_stack_0 = (max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_nnode - 1, 1) + 1) + max(0, div(i_nnode - 1, 1) + 1)) + (((i_ - 1) * (div(i_nnode - 1, 1) + 1) + (i_node - 1)) + 1)
            __cse_3d = upd[i_node]
            __cse_3 = up[i_node]
            up_stack_d[__idx_up_stack_0] = __cse_3d
            up_stack[__idx_up_stack_0] = __cse_3
            __cse_75 = node_vol[i_node]
            __cse_76 = res2[i_node] - mup[i_node]
            upd[i_node] = __cse_3d + ((1.0 / __cse_75) * (res2d[i_node] + -(mupd[i_node])) + -(__cse_76 / __cse_75 ^ 2) * node_vold[i_node])
            up[i_node] = __cse_3 + __cse_76 / __cse_75
        end
    end
    for i_node2 = 1:i_nnode
        __cse_77 = (u[i_node2] + up[i_node2]) - uref[i_node2]
        lossd[1] = lossd[1] + (2__cse_77) * ((ud[i_node2] + upd[i_node2]) + -(urefd[i_node2]))
        loss[1] = loss[1] + __cse_77 ^ 2
    end
    for i_node2 = i_nnode:-1:1
        __cse_78 = lossb[1]
        __cse_79 = 2 * ((u[i_node2] + up[i_node2]) - uref[i_node2])
        __cse_4d = __cse_78 * (2 * ((ud[i_node2] + upd[i_node2]) + -(urefd[i_node2]))) + __cse_79 * lossbd[1]
        __cse_4 = __cse_79 * __cse_78
        ubd[i_node2] = ubd[i_node2] + __cse_4d
        ub[i_node2] = ub[i_node2] + __cse_4
        upbd[i_node2] = upbd[i_node2] + __cse_4d
        upb[i_node2] = upb[i_node2] + __cse_4
        urefbd[i_node2] = urefbd[i_node2] + -__cse_4d
        urefb[i_node2] = urefb[i_node2] + -__cse_4
    end
    for i_ = i_njac:-1:1
        for i_node = i_nnode:-1:1
            __idx_up_stack_0 = (max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_nnode - 1, 1) + 1) + max(0, div(i_nnode - 1, 1) + 1)) + (((i_ - 1) * (div(i_nnode - 1, 1) + 1) + (i_node - 1)) + 1)
            upd[i_node] = up_stack_d[__idx_up_stack_0]
            up[i_node] = up_stack[__idx_up_stack_0]
            __cse_5d = node_vold[i_node]
            __cse_5 = node_vol[i_node]
            __cse_6d = upbd[i_node]
            __cse_6 = upb[i_node]
            __cse_80 = __cse_5 ^ 2
            __cse_81 = 1.0 / __cse_80
            __cse_82 = 1.0 / __cse_5
            __cse_7d = __cse_6 * (-__cse_81 * __cse_5d) + __cse_82 * __cse_6d
            __cse_7 = __cse_82 * __cse_6
            res2bd[i_node] = res2bd[i_node] + __cse_7d
            res2b[i_node] = res2b[i_node] + __cse_7
            mupbd[i_node] = mupbd[i_node] + -__cse_7d
            mupb[i_node] = mupb[i_node] + -__cse_7
            __cse_83 = res2[i_node] - mup[i_node]
            __cse_84 = -(__cse_83 / __cse_80)
            node_volbd[i_node] = node_volbd[i_node] + (__cse_6 * -((__cse_81 * (res2d[i_node] + -(mupd[i_node])) + -(__cse_83 / __cse_80 ^ 2) * ((2__cse_5) * __cse_5d))) + __cse_84 * __cse_6d)
            node_volb[i_node] = node_volb[i_node] + __cse_84 * __cse_6
        end
        for i_cell = i_ncell:-1:1
            __idx_auxu_stack_0 = max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_ncell - 1, 1) + 1) + (((i_ - 1) * (div(i_ncell - 1, 1) + 1) + (i_cell - 1)) + 1)
            auxud = auxu_stack_d[__idx_auxu_stack_0]
            auxu = auxu_stack[__idx_auxu_stack_0]
            for i_loc = 4:-1:1
                i_lnode = i_cell_to_node[i_loc, i_cell]
                __idx_mup_stack_0 = ((max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_nnode - 1, 1) + 1) + max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_ncell - 1, 1) + 1) * max(0, div(4 - 1, 1) + 1)) + max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_nnode - 1, 1) + 1)) + (((i_ - 1) * ((div(i_ncell - 1, 1) + 1) * (div(4 - 1, 1) + 1)) + (i_cell - 1) * (div(4 - 1, 1) + 1) + (i_loc - 1)) + 1)
                mupd[i_lnode] = mup_stack_d[__idx_mup_stack_0]
                mup[i_lnode] = mup_stack[__idx_mup_stack_0]
                __cse_8d = 0.05 * mupbd[i_lnode]
                __cse_8 = 0.05 * mupb[i_lnode]
                __cse_85 = cell_vol[i_cell]
                __cse_9d = __cse_8 * cell_vold[i_cell] + __cse_85 * __cse_8d
                __cse_9 = __cse_85 * __cse_8
                auxubd = auxubd + __cse_9d
                auxub = auxub + __cse_9
                upbd[i_lnode] = upbd[i_lnode] + __cse_9d
                upb[i_lnode] = upb[i_lnode] + __cse_9
                __cse_86 = auxu + up[i_lnode]
                cell_volbd[i_cell] = cell_volbd[i_cell] + (__cse_8 * (auxud + upd[i_lnode]) + __cse_86 * __cse_8d)
                cell_volb[i_cell] = cell_volb[i_cell] + __cse_86 * __cse_8
            end
            for i_loc = 1:4
                i_lnode = i_cell_to_node[i_loc, i_cell]
                auxud = auxud + upd[i_lnode]
                auxu = auxu + up[i_lnode]
                i_lnode = i_cell_to_node[i_loc, i_cell]
                upbd[i_lnode] = upbd[i_lnode] + auxubd
                upb[i_lnode] = upb[i_lnode] + auxub
            end
            auxubd = 0.0
            auxub = 0.0
        end
        for i_node = i_nnode:-1:1
            __idx_mup_stack_0 = (max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_nnode - 1, 1) + 1) + max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_ncell - 1, 1) + 1) * max(0, div(4 - 1, 1) + 1)) + (((i_ - 1) * (div(i_nnode - 1, 1) + 1) + (i_node - 1)) + 1)
            mupd[i_node] = mup_stack_d[__idx_mup_stack_0]
            mup[i_node] = mup_stack[__idx_mup_stack_0]
            mupbd[i_node] = 0.0
            mupb[i_node] = 0.0
        end
    end
    for i_node = i_nnode:-1:1
        __idx_up_stack_0 = max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_nnode - 1, 1) + 1) + ((i_node - 1) + 1)
        upd[i_node] = up_stack_d[__idx_up_stack_0]
        up[i_node] = up_stack[__idx_up_stack_0]
        __cse_10d = node_vold[i_node]
        __cse_10 = node_vol[i_node]
        __cse_11d = upbd[i_node]
        __cse_11 = upb[i_node]
        __cse_87 = __cse_10 ^ 2
        __cse_88 = 1.0 / __cse_87
        __cse_89 = 1.0 / __cse_10
        res2bd[i_node] = res2bd[i_node] + (__cse_11 * (-__cse_88 * __cse_10d) + __cse_89 * __cse_11d)
        res2b[i_node] = res2b[i_node] + __cse_89 * __cse_11
        __cse_90 = res2[i_node]
        __cse_91 = -(__cse_90 / __cse_87)
        node_volbd[i_node] = node_volbd[i_node] + (__cse_11 * -((__cse_88 * res2d[i_node] + -(__cse_90 / __cse_87 ^ 2) * ((2__cse_10) * __cse_10d))) + __cse_91 * __cse_11d)
        node_volb[i_node] = node_volb[i_node] + __cse_91 * __cse_11
        upbd[i_node] = 0.0
        upb[i_node] = 0.0
    end
    for i_cell = i_ncell:-1:1
        __idx_vere_stack_0 = ((max(0, div(i_ncell - 1, 1) + 1) * max(0, div(4 - 1, 1) + 1) + max(0, div(i_ncell - 1, 1) + 1)) + max(0, div(i_ncell - 1, 1) + 1) * max(0, div(4 - 1, 1) + 1)) + ((i_cell - 1) + 1)
        vered = vere_stack_d[__idx_vere_stack_0]
        vere = vere_stack[__idx_vere_stack_0]
        for i_loc = 4:-1:1
            i_node = i_cell_to_node[i_loc, i_cell]
            for i_k = 4:-1:1
                i_k_node = i_cell_to_node[i_k, i_cell]
                resibd = resibd + res2bd[i_k_node]
                resib = resib + res2b[i_k_node]
            end
            dtbd = dtbd + 0.25 * -((resib * vered + vere * resibd))
            dtb = dtb + 0.25 * -(vere * resib)
            __cse_92 = -(dt / 4)
            verebd = verebd + (resib * -(0.25dtd) + __cse_92 * resibd)
            vereb = vereb + __cse_92 * resib
            resibd = 0.0
            resib = 0.0
            __idx_vere_stack_0 = (max(0, div(i_ncell - 1, 1) + 1) * max(0, div(4 - 1, 1) + 1) + max(0, div(i_ncell - 1, 1) + 1)) + (((i_cell - 1) * (div(4 - 1, 1) + 1) + (i_loc - 1)) + 1)
            vered = vere_stack_d[__idx_vere_stack_0]
            vere = vere_stack[__idx_vere_stack_0]
            __cse_12d = cd[1, i_node]
            __cse_12 = c[1, i_node]
            __cse_13d = skxd[i_loc, i_cell]
            __cse_13 = skx[i_loc, i_cell]
            __cse_14d = cd[2, i_node]
            __cse_14 = c[2, i_node]
            __cse_15d = skyd[i_loc, i_cell]
            __cse_15 = sky[i_loc, i_cell]
            __cse_93 = -(1.0 / 3.0) * (__cse_12 * __cse_13 + __cse_14 * __cse_15)
            __cse_16d = vereb * (-(1.0 / 3.0) * ((__cse_13 * __cse_12d + __cse_12 * __cse_13d) + (__cse_15 * __cse_14d + __cse_14 * __cse_15d))) + __cse_93 * verebd
            __cse_16 = __cse_93 * vereb
            ubd[i_node] = ubd[i_node] + __cse_16d
            ub[i_node] = ub[i_node] + __cse_16
            upbd[i_node] = upbd[i_node] + __cse_16d
            upb[i_node] = upb[i_node] + __cse_16
            __cse_94 = -(1.0 / 3.0) * (u[i_node] + up[i_node])
            __cse_17d = vereb * (-(1.0 / 3.0) * (ud[i_node] + upd[i_node])) + __cse_94 * verebd
            __cse_17 = __cse_94 * vereb
            cbd[1, i_node] = cbd[1, i_node] + (__cse_17 * __cse_13d + __cse_13 * __cse_17d)
            cb[1, i_node] = cb[1, i_node] + __cse_13 * __cse_17
            skxbd[i_loc, i_cell] = skxbd[i_loc, i_cell] + (__cse_17 * __cse_12d + __cse_12 * __cse_17d)
            skxb[i_loc, i_cell] = skxb[i_loc, i_cell] + __cse_12 * __cse_17
            cbd[2, i_node] = cbd[2, i_node] + (__cse_17 * __cse_15d + __cse_15 * __cse_17d)
            cb[2, i_node] = cb[2, i_node] + __cse_15 * __cse_17
            skybd[i_loc, i_cell] = skybd[i_loc, i_cell] + (__cse_17 * __cse_14d + __cse_14 * __cse_17d)
            skyb[i_loc, i_cell] = skyb[i_loc, i_cell] + __cse_14 * __cse_17
            verebd = 0.0
            vereb = 0.0
        end
        verebd = 0.0
        vereb = 0.0
    end
    for i_ = i_njac:-1:1
        for i_node = i_nnode:-1:1
            __idx_up_stack_0 = ((i_ - 1) * (div(i_nnode - 1, 1) + 1) + (i_node - 1)) + 1
            upd[i_node] = up_stack_d[__idx_up_stack_0]
            up[i_node] = up_stack[__idx_up_stack_0]
            __cse_18d = node_vold[i_node]
            __cse_18 = node_vol[i_node]
            __cse_19d = upbd[i_node]
            __cse_19 = upb[i_node]
            __cse_95 = __cse_18 ^ 2
            __cse_96 = 1.0 / __cse_95
            __cse_97 = 1.0 / __cse_18
            __cse_20d = __cse_19 * (-__cse_96 * __cse_18d) + __cse_97 * __cse_19d
            __cse_20 = __cse_97 * __cse_19
            resbd[i_node] = resbd[i_node] + __cse_20d
            resb[i_node] = resb[i_node] + __cse_20
            mupbd[i_node] = mupbd[i_node] + -__cse_20d
            mupb[i_node] = mupb[i_node] + -__cse_20
            __cse_98 = res[i_node] - mup[i_node]
            __cse_99 = -(__cse_98 / __cse_95)
            node_volbd[i_node] = node_volbd[i_node] + (__cse_19 * -((__cse_96 * (resd[i_node] + -(mupd[i_node])) + -(__cse_98 / __cse_95 ^ 2) * ((2__cse_18) * __cse_18d))) + __cse_99 * __cse_19d)
            node_volb[i_node] = node_volb[i_node] + __cse_99 * __cse_19
        end
        for i_cell = i_ncell:-1:1
            __idx_auxu_stack_0 = ((i_ - 1) * (div(i_ncell - 1, 1) + 1) + (i_cell - 1)) + 1
            auxud = auxu_stack_d[__idx_auxu_stack_0]
            auxu = auxu_stack[__idx_auxu_stack_0]
            for i_loc = 4:-1:1
                i_lnode = i_cell_to_node[i_loc, i_cell]
                __idx_mup_stack_0 = max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_nnode - 1, 1) + 1) + (((i_ - 1) * ((div(i_ncell - 1, 1) + 1) * (div(4 - 1, 1) + 1)) + (i_cell - 1) * (div(4 - 1, 1) + 1) + (i_loc - 1)) + 1)
                mupd[i_lnode] = mup_stack_d[__idx_mup_stack_0]
                mup[i_lnode] = mup_stack[__idx_mup_stack_0]
                __cse_21d = 0.05 * mupbd[i_lnode]
                __cse_21 = 0.05 * mupb[i_lnode]
                __cse_100 = cell_vol[i_cell]
                __cse_22d = __cse_21 * cell_vold[i_cell] + __cse_100 * __cse_21d
                __cse_22 = __cse_100 * __cse_21
                auxubd = auxubd + __cse_22d
                auxub = auxub + __cse_22
                upbd[i_lnode] = upbd[i_lnode] + __cse_22d
                upb[i_lnode] = upb[i_lnode] + __cse_22
                __cse_101 = auxu + up[i_lnode]
                cell_volbd[i_cell] = cell_volbd[i_cell] + (__cse_21 * (auxud + upd[i_lnode]) + __cse_101 * __cse_21d)
                cell_volb[i_cell] = cell_volb[i_cell] + __cse_101 * __cse_21
            end
            for i_loc = 1:4
                i_lnode = i_cell_to_node[i_loc, i_cell]
                auxud = auxud + upd[i_lnode]
                auxu = auxu + up[i_lnode]
                i_lnode = i_cell_to_node[i_loc, i_cell]
                upbd[i_lnode] = upbd[i_lnode] + auxubd
                upb[i_lnode] = upb[i_lnode] + auxub
            end
            auxubd = 0.0
            auxub = 0.0
        end
        for i_node = i_nnode:-1:1
            __idx_mup_stack_0 = ((i_ - 1) * (div(i_nnode - 1, 1) + 1) + (i_node - 1)) + 1
            mupd[i_node] = mup_stack_d[__idx_mup_stack_0]
            mup[i_node] = mup_stack[__idx_mup_stack_0]
            mupbd[i_node] = 0.0
            mupb[i_node] = 0.0
        end
    end
    for i_node = i_nnode:-1:1
        __cse_23d = node_vold[i_node]
        __cse_23 = node_vol[i_node]
        __cse_24d = upbd[i_node]
        __cse_24 = upb[i_node]
        __cse_102 = __cse_23 ^ 2
        __cse_103 = 1.0 / __cse_102
        __cse_104 = 1.0 / __cse_23
        resbd[i_node] = resbd[i_node] + (__cse_24 * (-__cse_103 * __cse_23d) + __cse_104 * __cse_24d)
        resb[i_node] = resb[i_node] + __cse_104 * __cse_24
        __cse_105 = res[i_node]
        __cse_106 = -(__cse_105 / __cse_102)
        node_volbd[i_node] = node_volbd[i_node] + (__cse_24 * -((__cse_103 * resd[i_node] + -(__cse_105 / __cse_102 ^ 2) * ((2__cse_23) * __cse_23d))) + __cse_106 * __cse_24d)
        node_volb[i_node] = node_volb[i_node] + __cse_106 * __cse_24
        upbd[i_node] = 0.0
        upb[i_node] = 0.0
    end
    for i_cell = 1:i_ncell
        aereskd = 0.0
        aeresk = 0.0
        aerexd = 0.0
        aerex = 0.0
        aereyd = 0.0
        aerey = 0.0
        aerezd = 0.0
        aerez = 0.0
        factord = 0.0
        factor = 0.0
        red = 0.0
        re = 0.0
        vered = 0.0
        vere = 0.0
        cavgxd = 0.0
        cavgx = 0.0
        cavgyd = 0.0
        cavgy = 0.0
        cavgzd = 0.0
        cavgz = 0.0
        for i_loc = 1:4
            i_node = i_cell_to_node[i_loc, i_cell]
            cavgxd = cavgxd + 0.25 * cd[1, i_node]
            cavgx = cavgx + c[1, i_node] / 4
            cavgyd = cavgyd + 0.25 * cd[2, i_node]
            cavgy = cavgy + c[2, i_node] / 4
            cavgzd = cavgzd + 0.25 * cd[3, i_node]
            cavgz = cavgz + c[3, i_node] / 4
        end
        for i_loc = 1:4
            aereskd = 0.0
            aeresk = 0.0
            factord = 0.0
            factor = 0.0
            i_node = i_cell_to_node[i_loc, i_cell]
            __cse_107 = c[1, i_node]
            __cse_108 = skx[i_loc, i_cell]
            __cse_109 = c[2, i_node]
            __cse_110 = sky[i_loc, i_cell]
            __cse_111 = c[3, i_node]
            __cse_112 = skz[i_loc, i_cell]
            __cse_113 = __cse_107 * __cse_108 + __cse_109 * __cse_110 + __cse_111 * __cse_112
            __cse_114 = u[i_node]
            vered = (-(1.0 / 3.0) * __cse_113) * ud[i_node] + (-(1.0 / 3.0) * __cse_114) * (((__cse_108 * cd[1, i_node] + __cse_107 * skxd[i_loc, i_cell]) + (__cse_110 * cd[2, i_node] + __cse_109 * skyd[i_loc, i_cell])) + (__cse_112 * cd[3, i_node] + __cse_111 * skzd[i_loc, i_cell]))
            vere = -(1.0 / 3.0) * __cse_114 * __cse_113
            __cse_115 = cell_vol[i_cell]
            red = (1.0 / __cse_115) * vered + -(vere / __cse_115 ^ 2) * cell_vold[i_cell]
            re = vere / __cse_115
            aerexd = re * cavgxd + cavgx * red
            aerex = cavgx * re
            aereyd = re * cavgyd + cavgy * red
            aerey = cavgy * re
            aerezd = re * cavgzd + cavgz * red
            aerez = cavgz * re
            __cse_116 = 0.5 - gamma[i_cell]
            __cse_117 = -(dt / 4)
            resid = ((__cse_116 * vere) * -(0.25dtd) + (__cse_117 * vere) * -(gammad[i_cell])) + (__cse_117 * __cse_116) * vered
            resi = __cse_117 * __cse_116 * vere
            for i_k = 1:4
                __cse_118 = skx[i_k, i_cell]
                __cse_119 = sky[i_k, i_cell]
                __cse_120 = skz[i_k, i_cell]
                aereskd = ((__cse_118 * aerexd + aerex * skxd[i_k, i_cell]) + (__cse_119 * aereyd + aerey * skyd[i_k, i_cell])) + (__cse_120 * aerezd + aerez * skzd[i_k, i_cell])
                aeresk = aerex * __cse_118 + aerey * __cse_119 + aerez * __cse_120
                __cse_121 = dt ^ 2 / 3
                factord = aeresk * (0.3333333333333333 * ((2dt) * dtd)) + __cse_121 * aereskd
                factor = __cse_121 * aeresk
                __cse_122 = beta[i_cell]
                auxresd = resid + (__cse_122 * factord + factor * betad[i_cell])
                auxres = resi + factor * __cse_122
                __cse_123 = gamma[i_cell]
                auxres2d = __cse_123 * factord + factor * gammad[i_cell]
                auxres2 = factor * __cse_123
                i_k_node = i_cell_to_node[i_k, i_cell]
            end
        end
        for i_loc = 1:4
            aereskd = 0.0
            aeresk = 0.0
            factord = 0.0
            factor = 0.0
            i_node = i_cell_to_node[i_loc, i_cell]
            __cse_124 = c[1, i_node]
            __cse_125 = skx[i_loc, i_cell]
            __cse_126 = c[2, i_node]
            __cse_127 = sky[i_loc, i_cell]
            __cse_128 = c[3, i_node]
            __cse_129 = skz[i_loc, i_cell]
            __cse_130 = __cse_124 * __cse_125 + __cse_126 * __cse_127 + __cse_128 * __cse_129
            __cse_131 = u[i_node]
            vered = (-(1.0 / 3.0) * __cse_130) * ud[i_node] + (-(1.0 / 3.0) * __cse_131) * (((__cse_125 * cd[1, i_node] + __cse_124 * skxd[i_loc, i_cell]) + (__cse_127 * cd[2, i_node] + __cse_126 * skyd[i_loc, i_cell])) + (__cse_129 * cd[3, i_node] + __cse_128 * skzd[i_loc, i_cell]))
            vere = -(1.0 / 3.0) * __cse_131 * __cse_130
            __cse_132 = cell_vol[i_cell]
            red = (1.0 / __cse_132) * vered + -(vere / __cse_132 ^ 2) * cell_vold[i_cell]
            re = vere / __cse_132
            aerexd = re * cavgxd + cavgx * red
            aerex = cavgx * re
            aereyd = re * cavgyd + cavgy * red
            aerey = cavgy * re
            aerezd = re * cavgzd + cavgz * red
            aerez = cavgz * re
            __cse_133 = 0.5 - gamma[i_cell]
            __cse_134 = -(dt / 4)
            resid = ((__cse_133 * vere) * -(0.25dtd) + (__cse_134 * vere) * -(gammad[i_cell])) + (__cse_134 * __cse_133) * vered
            resi = __cse_134 * __cse_133 * vere
            for i_k = 1:4
                __cse_135 = skx[i_k, i_cell]
                __cse_136 = sky[i_k, i_cell]
                __cse_137 = skz[i_k, i_cell]
                aereskd = ((__cse_135 * aerexd + aerex * skxd[i_k, i_cell]) + (__cse_136 * aereyd + aerey * skyd[i_k, i_cell])) + (__cse_137 * aerezd + aerez * skzd[i_k, i_cell])
                aeresk = aerex * __cse_135 + aerey * __cse_136 + aerez * __cse_137
                __cse_138 = dt ^ 2 / 3
                factord = aeresk * (0.3333333333333333 * ((2dt) * dtd)) + __cse_138 * aereskd
                factor = __cse_138 * aeresk
                __cse_139 = beta[i_cell]
                auxresd = resid + (__cse_139 * factord + factor * betad[i_cell])
                auxres = resi + factor * __cse_139
                __cse_140 = gamma[i_cell]
                auxres2d = __cse_140 * factord + factor * gammad[i_cell]
                auxres2 = factor * __cse_140
                i_k_node = i_cell_to_node[i_k, i_cell]
            end
            i_node = i_cell_to_node[i_loc, i_cell]
            for i_k = 1:4
                __cse_25d = skxd[i_k, i_cell]
                __cse_25 = skx[i_k, i_cell]
                __cse_26d = skyd[i_k, i_cell]
                __cse_26 = sky[i_k, i_cell]
                __cse_27d = skzd[i_k, i_cell]
                __cse_27 = skz[i_k, i_cell]
                aereskd = ((__cse_25 * aerexd + aerex * __cse_25d) + (__cse_26 * aereyd + aerey * __cse_26d)) + (__cse_27 * aerezd + aerez * __cse_27d)
                aeresk = aerex * __cse_25 + aerey * __cse_26 + aerez * __cse_27
                __cse_141 = 2dt
                __cse_28d = 0.3333333333333333 * (__cse_141 * dtd)
                __cse_28 = dt ^ 2 / 3
                factord = aeresk * __cse_28d + __cse_28 * aereskd
                factor = __cse_28 * aeresk
                __cse_29d = betad[i_cell]
                __cse_29 = beta[i_cell]
                auxresd = resid + (__cse_29 * factord + factor * __cse_29d)
                auxres = resi + factor * __cse_29
                __cse_30d = gammad[i_cell]
                __cse_30 = gamma[i_cell]
                auxres2d = __cse_30 * factord + factor * __cse_30d
                auxres2 = factor * __cse_30
                i_k_node = i_cell_to_node[i_k, i_cell]
                i_k_node = i_cell_to_node[i_k, i_cell]
                auxres2bd = auxres2bd + res2bd[i_k_node]
                auxres2b = auxres2b + res2b[i_k_node]
                auxresbd = auxresbd + resbd[i_k_node]
                auxresb = auxresb + resb[i_k_node]
                factorbd = factorbd + (auxres2b * __cse_30d + __cse_30 * auxres2bd)
                factorb = factorb + __cse_30 * auxres2b
                gammabd[i_cell] = gammabd[i_cell] + (auxres2b * factord + factor * auxres2bd)
                gammab[i_cell] = gammab[i_cell] + factor * auxres2b
                auxres2bd = 0.0
                auxres2b = 0.0
                resibd = resibd + auxresbd
                resib = resib + auxresb
                factorbd = factorbd + (auxresb * __cse_29d + __cse_29 * auxresbd)
                factorb = factorb + __cse_29 * auxresb
                betabd[i_cell] = betabd[i_cell] + (auxresb * factord + factor * auxresbd)
                betab[i_cell] = betab[i_cell] + factor * auxresb
                auxresbd = 0.0
                auxresb = 0.0
                __cse_142 = 0.3333333333333333 * (aeresk * factorb)
                dtbd = dtbd + (__cse_142 * (2dtd) + __cse_141 * (0.3333333333333333 * (factorb * aereskd + aeresk * factorbd)))
                dtb = dtb + __cse_141 * __cse_142
                aereskbd = aereskbd + (factorb * __cse_28d + __cse_28 * factorbd)
                aereskb = aereskb + __cse_28 * factorb
                factorbd = 0.0
                factorb = 0.0
                aerexbd = aerexbd + (aereskb * __cse_25d + __cse_25 * aereskbd)
                aerexb = aerexb + __cse_25 * aereskb
                skxbd[i_k, i_cell] = skxbd[i_k, i_cell] + (aereskb * aerexd + aerex * aereskbd)
                skxb[i_k, i_cell] = skxb[i_k, i_cell] + aerex * aereskb
                aereybd = aereybd + (aereskb * __cse_26d + __cse_26 * aereskbd)
                aereyb = aereyb + __cse_26 * aereskb
                skybd[i_k, i_cell] = skybd[i_k, i_cell] + (aereskb * aereyd + aerey * aereskbd)
                skyb[i_k, i_cell] = skyb[i_k, i_cell] + aerey * aereskb
                aerezbd = aerezbd + (aereskb * __cse_27d + __cse_27 * aereskbd)
                aerezb = aerezb + __cse_27 * aereskb
                skzbd[i_k, i_cell] = skzbd[i_k, i_cell] + (aereskb * aerezd + aerez * aereskbd)
                skzb[i_k, i_cell] = skzb[i_k, i_cell] + aerez * aereskb
                aereskbd = 0.0
                aereskb = 0.0
            end
            __cse_31d = -(gammad[i_cell])
            __cse_31 = 0.5 - gamma[i_cell]
            __cse_143 = __cse_31 * vere
            dtbd = dtbd + 0.25 * -((resib * (vere * __cse_31d + __cse_31 * vered) + __cse_143 * resibd))
            dtb = dtb + 0.25 * -(__cse_143 * resib)
            __cse_32d = -(0.25dtd)
            __cse_32 = -(dt / 4)
            __cse_144 = __cse_32 * vere
            gammabd[i_cell] = gammabd[i_cell] + -((resib * (vere * __cse_32d + __cse_32 * vered) + __cse_144 * resibd))
            gammab[i_cell] = gammab[i_cell] + -(__cse_144 * resib)
            __cse_145 = __cse_32 * __cse_31
            verebd = verebd + (resib * (__cse_31 * __cse_32d + __cse_32 * __cse_31d) + __cse_145 * resibd)
            vereb = vereb + __cse_145 * resib
            resibd = 0.0
            resib = 0.0
            cavgzbd = cavgzbd + (aerezb * red + re * aerezbd)
            cavgzb = cavgzb + re * aerezb
            rebd = rebd + (aerezb * cavgzd + cavgz * aerezbd)
            reb = reb + cavgz * aerezb
            aerezbd = 0.0
            aerezb = 0.0
            cavgybd = cavgybd + (aereyb * red + re * aereybd)
            cavgyb = cavgyb + re * aereyb
            rebd = rebd + (aereyb * cavgyd + cavgy * aereybd)
            reb = reb + cavgy * aereyb
            aereybd = 0.0
            aereyb = 0.0
            cavgxbd = cavgxbd + (aerexb * red + re * aerexbd)
            cavgxb = cavgxb + re * aerexb
            rebd = rebd + (aerexb * cavgxd + cavgx * aerexbd)
            reb = reb + cavgx * aerexb
            aerexbd = 0.0
            aerexb = 0.0
            __cse_33d = cell_vold[i_cell]
            __cse_33 = cell_vol[i_cell]
            __cse_146 = __cse_33 ^ 2
            __cse_147 = 1.0 / __cse_146
            __cse_148 = 1.0 / __cse_33
            verebd = verebd + (reb * (-__cse_147 * __cse_33d) + __cse_148 * rebd)
            vereb = vereb + __cse_148 * reb
            __cse_149 = -(vere / __cse_146)
            cell_volbd[i_cell] = cell_volbd[i_cell] + (reb * -((__cse_147 * vered + -(vere / __cse_146 ^ 2) * ((2__cse_33) * __cse_33d))) + __cse_149 * rebd)
            cell_volb[i_cell] = cell_volb[i_cell] + __cse_149 * reb
            rebd = 0.0
            reb = 0.0
            __cse_34d = cd[1, i_node]
            __cse_34 = c[1, i_node]
            __cse_35d = skxd[i_loc, i_cell]
            __cse_35 = skx[i_loc, i_cell]
            __cse_36d = cd[2, i_node]
            __cse_36 = c[2, i_node]
            __cse_37d = skyd[i_loc, i_cell]
            __cse_37 = sky[i_loc, i_cell]
            __cse_38d = cd[3, i_node]
            __cse_38 = c[3, i_node]
            __cse_39d = skzd[i_loc, i_cell]
            __cse_39 = skz[i_loc, i_cell]
            __cse_150 = -(1.0 / 3.0) * (__cse_34 * __cse_35 + __cse_36 * __cse_37 + __cse_38 * __cse_39)
            ubd[i_node] = ubd[i_node] + (vereb * (-(1.0 / 3.0) * (((__cse_35 * __cse_34d + __cse_34 * __cse_35d) + (__cse_37 * __cse_36d + __cse_36 * __cse_37d)) + (__cse_39 * __cse_38d + __cse_38 * __cse_39d))) + __cse_150 * verebd)
            ub[i_node] = ub[i_node] + __cse_150 * vereb
            __cse_151 = -(1.0 / 3.0) * u[i_node]
            __cse_40d = vereb * (-(1.0 / 3.0) * ud[i_node]) + __cse_151 * verebd
            __cse_40 = __cse_151 * vereb
            cbd[1, i_node] = cbd[1, i_node] + (__cse_40 * __cse_35d + __cse_35 * __cse_40d)
            cb[1, i_node] = cb[1, i_node] + __cse_35 * __cse_40
            skxbd[i_loc, i_cell] = skxbd[i_loc, i_cell] + (__cse_40 * __cse_34d + __cse_34 * __cse_40d)
            skxb[i_loc, i_cell] = skxb[i_loc, i_cell] + __cse_34 * __cse_40
            cbd[2, i_node] = cbd[2, i_node] + (__cse_40 * __cse_37d + __cse_37 * __cse_40d)
            cb[2, i_node] = cb[2, i_node] + __cse_37 * __cse_40
            skybd[i_loc, i_cell] = skybd[i_loc, i_cell] + (__cse_40 * __cse_36d + __cse_36 * __cse_40d)
            skyb[i_loc, i_cell] = skyb[i_loc, i_cell] + __cse_36 * __cse_40
            cbd[3, i_node] = cbd[3, i_node] + (__cse_40 * __cse_39d + __cse_39 * __cse_40d)
            cb[3, i_node] = cb[3, i_node] + __cse_39 * __cse_40
            skzbd[i_loc, i_cell] = skzbd[i_loc, i_cell] + (__cse_40 * __cse_38d + __cse_38 * __cse_40d)
            skzb[i_loc, i_cell] = skzb[i_loc, i_cell] + __cse_38 * __cse_40
            verebd = 0.0
            vereb = 0.0
            factorbd = 0.0
            factorb = 0.0
            aereskbd = 0.0
            aereskb = 0.0
        end
        for i_loc = 1:4
            i_node = i_cell_to_node[i_loc, i_cell]
            cavgxd = cavgxd + 0.25 * cd[1, i_node]
            cavgx = cavgx + c[1, i_node] / 4
            cavgyd = cavgyd + 0.25 * cd[2, i_node]
            cavgy = cavgy + c[2, i_node] / 4
            cavgzd = cavgzd + 0.25 * cd[3, i_node]
            cavgz = cavgz + c[3, i_node] / 4
            i_node = i_cell_to_node[i_loc, i_cell]
            cbd[3, i_node] = cbd[3, i_node] + 0.25cavgzbd
            cb[3, i_node] = cb[3, i_node] + 0.25cavgzb
            cbd[2, i_node] = cbd[2, i_node] + 0.25cavgybd
            cb[2, i_node] = cb[2, i_node] + 0.25cavgyb
            cbd[1, i_node] = cbd[1, i_node] + 0.25cavgxbd
            cb[1, i_node] = cb[1, i_node] + 0.25cavgxb
        end
        cavgzbd = 0.0
        cavgzb = 0.0
        cavgybd = 0.0
        cavgyb = 0.0
        cavgxbd = 0.0
        cavgxb = 0.0
        verebd = 0.0
        vereb = 0.0
        rebd = 0.0
        reb = 0.0
        factorbd = 0.0
        factorb = 0.0
        aerezbd = 0.0
        aerezb = 0.0
        aereybd = 0.0
        aereyb = 0.0
        aerexbd = 0.0
        aerexb = 0.0
        aereskbd = 0.0
        aereskb = 0.0
    end
    return (dtb, dtbd)
end

function ttgc(u, uref, i_cell_to_node, cell_vol, node_vol, skx, sky, skz, i_ncell, i_nnode, c, dt, beta, gamma, i_njac, res, res2, up, mup, loss)
    for i_cell = 1:i_ncell
        cavgx = 0.0
        cavgy = 0.0
        cavgz = 0.0
        for i_loc = 1:4
            i_node = i_cell_to_node[i_loc, i_cell]
            cavgx = cavgx + c[1, i_node] / 4
            cavgy = cavgy + c[2, i_node] / 4
            cavgz = cavgz + c[3, i_node] / 4
        end
        for i_loc = 1:4
            i_node = i_cell_to_node[i_loc, i_cell]
            vere = -(1.0 / 3.0) * u[i_node] * (c[1, i_node] * skx[i_loc, i_cell] + c[2, i_node] * sky[i_loc, i_cell] + c[3, i_node] * skz[i_loc, i_cell])
            re = vere / cell_vol[i_cell]
            aerex = cavgx * re
            aerey = cavgy * re
            aerez = cavgz * re
            resi = -(dt / 4) * (0.5 - gamma[i_cell]) * vere
            for i_k = 1:4
                aeresk = aerex * skx[i_k, i_cell] + aerey * sky[i_k, i_cell] + aerez * skz[i_k, i_cell]
                factor = (dt ^ 2 / 3) * aeresk
                auxres = resi + factor * beta[i_cell]
                auxres2 = factor * gamma[i_cell]
                i_k_node = i_cell_to_node[i_k, i_cell]
                res[i_k_node] = res[i_k_node] + auxres
                res2[i_k_node] = res2[i_k_node] + auxres2
            end
        end
    end
    for i_node = 1:i_nnode
        up[i_node] = res[i_node] / node_vol[i_node]
    end
    for i_ = 1:i_njac
        for i_node = 1:i_nnode
            mup[i_node] = 0.0
        end
        for i_cell = 1:i_ncell
            auxu = 0.0
            for i_loc = 1:4
                i_lnode = i_cell_to_node[i_loc, i_cell]
                auxu = auxu + up[i_lnode]
            end
            for i_loc = 1:4
                i_lnode = i_cell_to_node[i_loc, i_cell]
                mup[i_lnode] = mup[i_lnode] + ((auxu + up[i_lnode]) * cell_vol[i_cell]) / 20.0
            end
        end
        for i_node = 1:i_nnode
            up[i_node] = up[i_node] + (res[i_node] - mup[i_node]) / node_vol[i_node]
        end
    end
    for i_cell = 1:i_ncell
        for i_loc = 1:4
            i_node = i_cell_to_node[i_loc, i_cell]
            vere = -(1.0 / 3.0) * (u[i_node] + up[i_node]) * (c[1, i_node] * skx[i_loc, i_cell] + c[2, i_node] * sky[i_loc, i_cell])
            resi = -(dt / 4) * vere
            for i_k = 1:4
                i_k_node = i_cell_to_node[i_k, i_cell]
                res2[i_k_node] = res2[i_k_node] + resi
            end
        end
    end
    for i_node = 1:i_nnode
        up[i_node] = res2[i_node] / node_vol[i_node]
    end
    for i_ = 1:i_njac
        for i_node = 1:i_nnode
            mup[i_node] = 0.0
        end
        for i_cell = 1:i_ncell
            auxu = 0.0
            for i_loc = 1:4
                i_lnode = i_cell_to_node[i_loc, i_cell]
                auxu = auxu + up[i_lnode]
            end
            for i_loc = 1:4
                i_lnode = i_cell_to_node[i_loc, i_cell]
                mup[i_lnode] = mup[i_lnode] + ((auxu + up[i_lnode]) * cell_vol[i_cell]) / 20.0
            end
        end
        for i_node = 1:i_nnode
            up[i_node] = up[i_node] + (res2[i_node] - mup[i_node]) / node_vol[i_node]
        end
    end
    for i_node2 = 1:i_nnode
        loss[1] = loss[1] + ((u[i_node2] + up[i_node2]) - uref[i_node2]) ^ 2
    end
end
