function initstacks_ttgc_b(i_ncell, i_njac, i_nnode)
    vere_stack = Vector{Float64}(undef, ((max(0, div(i_ncell - 1, 1) + 1) * max(0, div(4 - 1, 1) + 1) + max(0, div(i_ncell - 1, 1) + 1)) + max(0, div(i_ncell - 1, 1) + 1) * max(0, div(4 - 1, 1) + 1)) + max(0, div(i_ncell - 1, 1) + 1))
    mup_stack = Vector{Float64}(undef, ((max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_nnode - 1, 1) + 1) + max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_ncell - 1, 1) + 1) * max(0, div(4 - 1, 1) + 1)) + max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_nnode - 1, 1) + 1)) + max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_ncell - 1, 1) + 1) * max(0, div(4 - 1, 1) + 1))
    up_stack = Vector{Float64}(undef, (max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_nnode - 1, 1) + 1) + max(0, div(i_nnode - 1, 1) + 1)) + max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_nnode - 1, 1) + 1))
    auxu_stack = Vector{Float64}(undef, max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_ncell - 1, 1) + 1) + max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_ncell - 1, 1) + 1))
    return (vere_stack, mup_stack, up_stack, auxu_stack)
end

function ttgc_hv(u, ub, uref, urefb, i_cell_to_node, cell_vol, cell_volb, node_vol, node_volb, skx, skxb, sky, skyb, skz, skzb, i_ncell, i_nnode, c, cb, dt, dtb, beta, betab, gamma, gammab, i_njac, res, resb, res2, res2b, up, upb, mup, mupb, loss, lossb, ud, ubd, urefd, urefbd, cell_vold, cell_volbd, node_vold, node_volbd, skxd, skxbd, skyd, skybd, skzd, skzbd, cd, cbd, dtd, dtbd, betad, betabd, gammad, gammabd, resd, resbd, res2d, res2bd, upd, upbd, mupd, mupbd, lossd, lossbd, vere_stack, mup_stack, up_stack, auxu_stack)
    vere_stack_d = Vector{Float64}(undef, length(vere_stack))
    mup_stack_d = Vector{Float64}(undef, length(mup_stack))
    up_stack_d = Vector{Float64}(undef, length(up_stack))
    auxu_stack_d = Vector{Float64}(undef, length(auxu_stack))
    aeresk = 0.0
    aerex = 0.0
    aerey = 0.0
    aerez = 0.0
    auxres = 0.0
    auxres2 = 0.0
    auxu = 0.0
    cavgx = 0.0
    cavgy = 0.0
    cavgz = 0.0
    factor = 0.0
    re = 0.0
    resi = 0.0
    vere = 0.0
    aereskb = 0.0
    aerexb = 0.0
    aereyb = 0.0
    aerezb = 0.0
    auxresb = 0.0
    auxres2b = 0.0
    auxub = 0.0
    cavgxb = 0.0
    cavgyb = 0.0
    cavgzb = 0.0
    factorb = 0.0
    reb = 0.0
    resib = 0.0
    vereb = 0.0
    aereskd = 0.0
    aereskbd = 0.0
    aerexd = 0.0
    aerexbd = 0.0
    aereyd = 0.0
    aereybd = 0.0
    aerezd = 0.0
    aerezbd = 0.0
    auxresd = 0.0
    auxresbd = 0.0
    auxres2d = 0.0
    auxres2bd = 0.0
    auxud = 0.0
    auxubd = 0.0
    cavgxd = 0.0
    cavgxbd = 0.0
    cavgyd = 0.0
    cavgybd = 0.0
    cavgzd = 0.0
    cavgzbd = 0.0
    factord = 0.0
    factorbd = 0.0
    red = 0.0
    rebd = 0.0
    resid = 0.0
    resibd = 0.0
    vered = 0.0
    verebd = 0.0
    for i_cell = 1:i_ncell
        aereskd = 0.0
        aeresk = 0.0
        aerexd = 0.0
        aerex = 0.0
        aereyd = 0.0
        aerey = 0.0
        aerezd = 0.0
        aerez = 0.0
        factord = 0.0
        factor = 0.0
        red = 0.0
        re = 0.0
        vered = 0.0
        vere = 0.0
        cavgxd = 0.0
        cavgx = 0.0
        cavgyd = 0.0
        cavgy = 0.0
        cavgzd = 0.0
        cavgz = 0.0
        for i_loc = 1:4
            i_node = i_cell_to_node[i_loc, i_cell]
            cavgxd = cavgxd + 0.25 * cd[1, i_node]
            cavgx = cavgx + c[1, i_node] / 4
            cavgyd = cavgyd + 0.25 * cd[2, i_node]
            cavgy = cavgy + c[2, i_node] / 4
            cavgzd = cavgzd + 0.25 * cd[3, i_node]
            cavgz = cavgz + c[3, i_node] / 4
        end
        for i_loc = 1:4
            aereskd = 0.0
            aeresk = 0.0
            factord = 0.0
            factor = 0.0
            i_node = i_cell_to_node[i_loc, i_cell]
            __ihcse_0 = -(1.0 / 3.0)
            __hcse_1 = c[1, i_node]
            __hcse_2 = skx[i_loc, i_cell]
            __hcse_3 = c[2, i_node]
            __hcse_4 = sky[i_loc, i_cell]
            __hcse_5 = c[3, i_node]
            __hcse_6 = skz[i_loc, i_cell]
            __hcse_7 = __hcse_1 * __hcse_2 + __hcse_3 * __hcse_4 + __hcse_5 * __hcse_6
            __hcse_8 = u[i_node]
            vered = (__ihcse_0 * __hcse_7) * ud[i_node] + (__ihcse_0 * __hcse_8) * (((__hcse_2 * cd[1, i_node] + __hcse_1 * skxd[i_loc, i_cell]) + (__hcse_4 * cd[2, i_node] + __hcse_3 * skyd[i_loc, i_cell])) + (__hcse_6 * cd[3, i_node] + __hcse_5 * skzd[i_loc, i_cell]))
            vere = __ihcse_0 * __hcse_8 * __hcse_7
            __hcse_9 = cell_vol[i_cell]
            red = (1.0 / __hcse_9) * vered + -(vere / __hcse_9 ^ 2) * cell_vold[i_cell]
            re = vere / __hcse_9
            aerexd = re * cavgxd + cavgx * red
            aerex = cavgx * re
            aereyd = re * cavgyd + cavgy * red
            aerey = cavgy * re
            aerezd = re * cavgzd + cavgz * red
            aerez = cavgz * re
            __hcse_10 = 0.5 - gamma[i_cell]
            __hcse_11 = -(dt / 4)
            resid = ((__hcse_10 * vere) * -(0.25dtd) + (__hcse_11 * vere) * -(gammad[i_cell])) + (__hcse_11 * __hcse_10) * vered
            resi = __hcse_11 * __hcse_10 * vere
            for i_k = 1:4
                __hcse_12 = skx[i_k, i_cell]
                __hcse_13 = sky[i_k, i_cell]
                __hcse_14 = skz[i_k, i_cell]
                aereskd = ((__hcse_12 * aerexd + aerex * skxd[i_k, i_cell]) + (__hcse_13 * aereyd + aerey * skyd[i_k, i_cell])) + (__hcse_14 * aerezd + aerez * skzd[i_k, i_cell])
                aeresk = aerex * __hcse_12 + aerey * __hcse_13 + aerez * __hcse_14
                __hcse_15 = dt ^ 2 / 3
                factord = aeresk * (0.3333333333333333 * ((2dt) * dtd)) + __hcse_15 * aereskd
                factor = __hcse_15 * aeresk
                __hcse_16 = beta[i_cell]
                auxresd = resid + (__hcse_16 * factord + factor * betad[i_cell])
                auxres = resi + factor * __hcse_16
                __hcse_17 = gamma[i_cell]
                auxres2d = __hcse_17 * factord + factor * gammad[i_cell]
                auxres2 = factor * __hcse_17
                i_k_node = i_cell_to_node[i_k, i_cell]
                resd[i_k_node] = resd[i_k_node] + auxresd
                res[i_k_node] = res[i_k_node] + auxres
                res2d[i_k_node] = res2d[i_k_node] + auxres2d
                res2[i_k_node] = res2[i_k_node] + auxres2
            end
        end
    end
    for i_node = 1:i_nnode
        __hcse_18 = node_vol[i_node]
        __hcse_19 = res[i_node]
        upd[i_node] = (1.0 / __hcse_18) * resd[i_node] + -(__hcse_19 / __hcse_18 ^ 2) * node_vold[i_node]
        up[i_node] = __hcse_19 / __hcse_18
    end
    for i_ = 1:i_njac
        for i_node = 1:i_nnode
            __idx_mup_stack_0 = ((i_ - 1) * (div(i_nnode - 1, 1) + 1) + (i_node - 1)) + 1
            mup_stack_d[__idx_mup_stack_0] = mupd[i_node]
            mup_stack[__idx_mup_stack_0] = mup[i_node]
            mupd[i_node] = 0.0
            mup[i_node] = 0.0
        end
        for i_cell = 1:i_ncell
            auxud = 0.0
            auxu = 0.0
            for i_loc = 1:4
                i_lnode = i_cell_to_node[i_loc, i_cell]
                auxud = auxud + upd[i_lnode]
                auxu = auxu + up[i_lnode]
            end
            for i_loc = 1:4
                i_lnode = i_cell_to_node[i_loc, i_cell]
                __icse_0 = div(4 - 1, 1) + 1
                __idx_mup_stack_1 = max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_nnode - 1, 1) + 1) + (((i_ - 1) * ((div(i_ncell - 1, 1) + 1) * __icse_0) + (i_cell - 1) * __icse_0 + (i_loc - 1)) + 1)
                __cse_1d = mupd[i_lnode]
                __cse_1 = mup[i_lnode]
                mup_stack_d[__idx_mup_stack_1] = __cse_1d
                mup_stack[__idx_mup_stack_1] = __cse_1
                __hcse_20 = cell_vol[i_cell]
                __hcse_21 = auxu + up[i_lnode]
                mupd[i_lnode] = __cse_1d + 0.05 * (__hcse_20 * (auxud + upd[i_lnode]) + __hcse_21 * cell_vold[i_cell])
                mup[i_lnode] = __cse_1 + (__hcse_21 * __hcse_20) / 20.0
            end
            __idx_auxu_stack_3 = ((i_ - 1) * (div(i_ncell - 1, 1) + 1) + (i_cell - 1)) + 1
            auxu_stack_d[__idx_auxu_stack_3] = auxud
            auxu_stack[__idx_auxu_stack_3] = auxu
        end
        for i_node = 1:i_nnode
            __idx_up_stack_0 = ((i_ - 1) * (div(i_nnode - 1, 1) + 1) + (i_node - 1)) + 1
            __cse_2d = upd[i_node]
            __cse_2 = up[i_node]
            up_stack_d[__idx_up_stack_0] = __cse_2d
            up_stack[__idx_up_stack_0] = __cse_2
            __hcse_22 = node_vol[i_node]
            __hcse_23 = res[i_node] - mup[i_node]
            upd[i_node] = __cse_2d + ((1.0 / __hcse_22) * (resd[i_node] + -(mupd[i_node])) + -(__hcse_23 / __hcse_22 ^ 2) * node_vold[i_node])
            up[i_node] = __cse_2 + __hcse_23 / __hcse_22
        end
    end
    for i_cell = 1:i_ncell
        vered = 0.0
        vere = 0.0
        for i_loc = 1:4
            i_node = i_cell_to_node[i_loc, i_cell]
            __icse_3 = max(0, div(i_ncell - 1, 1) + 1)
            __icse_4 = div(4 - 1, 1) + 1
            __idx_vere_stack_1 = (__icse_3 * max(0, __icse_4) + __icse_3) + (((i_cell - 1) * __icse_4 + (i_loc - 1)) + 1)
            vere_stack_d[__idx_vere_stack_1] = vered
            vere_stack[__idx_vere_stack_1] = vere
            __ihcse_24 = -(1.0 / 3.0)
            __hcse_25 = c[1, i_node]
            __hcse_26 = skx[i_loc, i_cell]
            __hcse_27 = c[2, i_node]
            __hcse_28 = sky[i_loc, i_cell]
            __hcse_29 = __hcse_25 * __hcse_26 + __hcse_27 * __hcse_28
            __hcse_30 = u[i_node] + up[i_node]
            vered = (__ihcse_24 * __hcse_29) * (ud[i_node] + upd[i_node]) + (__ihcse_24 * __hcse_30) * ((__hcse_26 * cd[1, i_node] + __hcse_25 * skxd[i_loc, i_cell]) + (__hcse_28 * cd[2, i_node] + __hcse_27 * skyd[i_loc, i_cell]))
            vere = __ihcse_24 * __hcse_30 * __hcse_29
            __hcse_31 = -(dt / 4)
            resid = vere * -(0.25dtd) + __hcse_31 * vered
            resi = __hcse_31 * vere
            for i_k = 1:4
                i_k_node = i_cell_to_node[i_k, i_cell]
                res2d[i_k_node] = res2d[i_k_node] + resid
                res2[i_k_node] = res2[i_k_node] + resi
            end
        end
        __icse_5 = max(0, div(i_ncell - 1, 1) + 1)
        __icse_6 = __icse_5 * max(0, div(4 - 1, 1) + 1)
        __idx_vere_stack_2 = ((__icse_6 + __icse_5) + __icse_6) + ((i_cell - 1) + 1)
        vere_stack_d[__idx_vere_stack_2] = vered
        vere_stack[__idx_vere_stack_2] = vere
    end
    for i_node = 1:i_nnode
        __idx_up_stack_0 = max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_nnode - 1, 1) + 1) + ((i_node - 1) + 1)
        up_stack_d[__idx_up_stack_0] = upd[i_node]
        up_stack[__idx_up_stack_0] = up[i_node]
        __hcse_32 = node_vol[i_node]
        __hcse_33 = res2[i_node]
        upd[i_node] = (1.0 / __hcse_32) * res2d[i_node] + -(__hcse_33 / __hcse_32 ^ 2) * node_vold[i_node]
        up[i_node] = __hcse_33 / __hcse_32
    end
    for i_ = 1:i_njac
        for i_node = 1:i_nnode
            __icse_7 = max(0, div(i_njac - 1, 1) + 1)
            __icse_8 = div(i_nnode - 1, 1) + 1
            __idx_mup_stack_0 = (__icse_7 * max(0, __icse_8) + __icse_7 * max(0, div(i_ncell - 1, 1) + 1) * max(0, div(4 - 1, 1) + 1)) + (((i_ - 1) * __icse_8 + (i_node - 1)) + 1)
            mup_stack_d[__idx_mup_stack_0] = mupd[i_node]
            mup_stack[__idx_mup_stack_0] = mup[i_node]
            mupd[i_node] = 0.0
            mup[i_node] = 0.0
        end
        for i_cell = 1:i_ncell
            auxud = 0.0
            auxu = 0.0
            for i_loc = 1:4
                i_lnode = i_cell_to_node[i_loc, i_cell]
                auxud = auxud + upd[i_lnode]
                auxu = auxu + up[i_lnode]
            end
            for i_loc = 1:4
                i_lnode = i_cell_to_node[i_loc, i_cell]
                __icse_9 = max(0, div(i_njac - 1, 1) + 1)
                __icse_10 = __icse_9 * max(0, div(i_nnode - 1, 1) + 1)
                __icse_11 = div(i_ncell - 1, 1) + 1
                __icse_12 = div(4 - 1, 1) + 1
                __idx_mup_stack_1 = ((__icse_10 + __icse_9 * max(0, __icse_11) * max(0, __icse_12)) + __icse_10) + (((i_ - 1) * (__icse_11 * __icse_12) + (i_cell - 1) * __icse_12 + (i_loc - 1)) + 1)
                __cse_13d = mupd[i_lnode]
                __cse_13 = mup[i_lnode]
                mup_stack_d[__idx_mup_stack_1] = __cse_13d
                mup_stack[__idx_mup_stack_1] = __cse_13
                __hcse_34 = cell_vol[i_cell]
                __hcse_35 = auxu + up[i_lnode]
                mupd[i_lnode] = __cse_13d + 0.05 * (__hcse_34 * (auxud + upd[i_lnode]) + __hcse_35 * cell_vold[i_cell])
                mup[i_lnode] = __cse_13 + (__hcse_35 * __hcse_34) / 20.0
            end
            __icse_14 = div(i_ncell - 1, 1) + 1
            __idx_auxu_stack_3 = max(0, div(i_njac - 1, 1) + 1) * max(0, __icse_14) + (((i_ - 1) * __icse_14 + (i_cell - 1)) + 1)
            auxu_stack_d[__idx_auxu_stack_3] = auxud
            auxu_stack[__idx_auxu_stack_3] = auxu
        end
        for i_node = 1:i_nnode
            __icse_15 = div(i_nnode - 1, 1) + 1
            __icse_16 = max(0, __icse_15)
            __idx_up_stack_0 = (max(0, div(i_njac - 1, 1) + 1) * __icse_16 + __icse_16) + (((i_ - 1) * __icse_15 + (i_node - 1)) + 1)
            __cse_17d = upd[i_node]
            __cse_17 = up[i_node]
            up_stack_d[__idx_up_stack_0] = __cse_17d
            up_stack[__idx_up_stack_0] = __cse_17
            __hcse_36 = node_vol[i_node]
            __hcse_37 = res2[i_node] - mup[i_node]
            upd[i_node] = __cse_17d + ((1.0 / __hcse_36) * (res2d[i_node] + -(mupd[i_node])) + -(__hcse_37 / __hcse_36 ^ 2) * node_vold[i_node])
            up[i_node] = __cse_17 + __hcse_37 / __hcse_36
        end
    end
    for i_node2 = 1:i_nnode
        __hcse_38 = (u[i_node2] + up[i_node2]) - uref[i_node2]
        lossd[1] = lossd[1] + (2__hcse_38) * ((ud[i_node2] + upd[i_node2]) + -(urefd[i_node2]))
        loss[1] = loss[1] + __hcse_38 ^ 2
    end
    for i_node2 = i_nnode:-1:1
        __hcse_39 = lossb[1]
        __hcse_40 = 2 * ((u[i_node2] + up[i_node2]) - uref[i_node2])
        __cse_18d = __hcse_39 * (2 * ((ud[i_node2] + upd[i_node2]) + -(urefd[i_node2]))) + __hcse_40 * lossbd[1]
        __cse_18 = __hcse_40 * __hcse_39
        ubd[i_node2] = ubd[i_node2] + __cse_18d
        ub[i_node2] = ub[i_node2] + __cse_18
        upbd[i_node2] = upbd[i_node2] + __cse_18d
        upb[i_node2] = upb[i_node2] + __cse_18
        urefbd[i_node2] = urefbd[i_node2] + -__cse_18d
        urefb[i_node2] = urefb[i_node2] + -__cse_18
    end
    for i_ = i_njac:-1:1
        for i_node = i_nnode:-1:1
            __icse_19 = div(i_nnode - 1, 1) + 1
            __icse_20 = max(0, __icse_19)
            __idx_up_stack_0 = (max(0, div(i_njac - 1, 1) + 1) * __icse_20 + __icse_20) + (((i_ - 1) * __icse_19 + (i_node - 1)) + 1)
            upd[i_node] = up_stack_d[__idx_up_stack_0]
            up[i_node] = up_stack[__idx_up_stack_0]
            __cse_21d = node_vold[i_node]
            __cse_21 = node_vol[i_node]
            __cse_22d = upbd[i_node]
            __cse_22 = upb[i_node]
            __hcse_41 = __cse_21 ^ 2
            __hcse_42 = 1.0 / __hcse_41
            __hcse_43 = 1.0 / __cse_21
            __cse_23d = __cse_22 * (-__hcse_42 * __cse_21d) + __hcse_43 * __cse_22d
            __cse_23 = __hcse_43 * __cse_22
            res2bd[i_node] = res2bd[i_node] + __cse_23d
            res2b[i_node] = res2b[i_node] + __cse_23
            mupbd[i_node] = mupbd[i_node] + -__cse_23d
            mupb[i_node] = mupb[i_node] + -__cse_23
            __hcse_44 = res2[i_node] - mup[i_node]
            __hcse_45 = -(__hcse_44 / __hcse_41)
            node_volbd[i_node] = node_volbd[i_node] + (__cse_22 * -((__hcse_42 * (res2d[i_node] + -(mupd[i_node])) + -(__hcse_44 / __hcse_41 ^ 2) * ((2__cse_21) * __cse_21d))) + __hcse_45 * __cse_22d)
            node_volb[i_node] = node_volb[i_node] + __hcse_45 * __cse_22
        end
        for i_cell = i_ncell:-1:1
            __icse_24 = div(i_ncell - 1, 1) + 1
            __idx_auxu_stack_0 = max(0, div(i_njac - 1, 1) + 1) * max(0, __icse_24) + (((i_ - 1) * __icse_24 + (i_cell - 1)) + 1)
            auxud = auxu_stack_d[__idx_auxu_stack_0]
            auxu = auxu_stack[__idx_auxu_stack_0]
            for i_loc = 4:-1:1
                i_lnode = i_cell_to_node[i_loc, i_cell]
                __icse_25 = max(0, div(i_njac - 1, 1) + 1)
                __icse_26 = __icse_25 * max(0, div(i_nnode - 1, 1) + 1)
                __icse_27 = div(i_ncell - 1, 1) + 1
                __icse_28 = div(4 - 1, 1) + 1
                __idx_mup_stack_0 = ((__icse_26 + __icse_25 * max(0, __icse_27) * max(0, __icse_28)) + __icse_26) + (((i_ - 1) * (__icse_27 * __icse_28) + (i_cell - 1) * __icse_28 + (i_loc - 1)) + 1)
                mupd[i_lnode] = mup_stack_d[__idx_mup_stack_0]
                mup[i_lnode] = mup_stack[__idx_mup_stack_0]
                __cse_29d = 0.05 * mupbd[i_lnode]
                __cse_29 = 0.05 * mupb[i_lnode]
                __hcse_46 = cell_vol[i_cell]
                __cse_30d = __cse_29 * cell_vold[i_cell] + __hcse_46 * __cse_29d
                __cse_30 = __hcse_46 * __cse_29
                auxubd = auxubd + __cse_30d
                auxub = auxub + __cse_30
                upbd[i_lnode] = upbd[i_lnode] + __cse_30d
                upb[i_lnode] = upb[i_lnode] + __cse_30
                __hcse_47 = auxu + up[i_lnode]
                cell_volbd[i_cell] = cell_volbd[i_cell] + (__cse_29 * (auxud + upd[i_lnode]) + __hcse_47 * __cse_29d)
                cell_volb[i_cell] = cell_volb[i_cell] + __hcse_47 * __cse_29
            end
            for i_loc = 1:4
                __icse_31 = i_cell_to_node[i_loc, i_cell]
                i_lnode = __icse_31
                auxud = auxud + upd[i_lnode]
                auxu = auxu + up[i_lnode]
                i_lnode = __icse_31
                upbd[i_lnode] = upbd[i_lnode] + auxubd
                upb[i_lnode] = upb[i_lnode] + auxub
            end
            auxubd = 0.0
            auxub = 0.0
        end
        for i_node = i_nnode:-1:1
            __icse_32 = max(0, div(i_njac - 1, 1) + 1)
            __icse_33 = div(i_nnode - 1, 1) + 1
            __idx_mup_stack_0 = (__icse_32 * max(0, __icse_33) + __icse_32 * max(0, div(i_ncell - 1, 1) + 1) * max(0, div(4 - 1, 1) + 1)) + (((i_ - 1) * __icse_33 + (i_node - 1)) + 1)
            mupd[i_node] = mup_stack_d[__idx_mup_stack_0]
            mup[i_node] = mup_stack[__idx_mup_stack_0]
            mupbd[i_node] = 0.0
            mupb[i_node] = 0.0
        end
    end
    for i_node = i_nnode:-1:1
        __idx_up_stack_0 = max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_nnode - 1, 1) + 1) + ((i_node - 1) + 1)
        upd[i_node] = up_stack_d[__idx_up_stack_0]
        up[i_node] = up_stack[__idx_up_stack_0]
        __oldb_2d = upbd[i_node]
        __oldb_2 = upb[i_node]
        upbd[i_node] = 0.0
        upb[i_node] = 0.0
        __cse_34d = node_vold[i_node]
        __cse_34 = node_vol[i_node]
        __hcse_48 = __cse_34 ^ 2
        __hcse_49 = 1.0 / __hcse_48
        __hcse_50 = 1.0 / __cse_34
        res2bd[i_node] = res2bd[i_node] + (__oldb_2 * (-__hcse_49 * __cse_34d) + __hcse_50 * __oldb_2d)
        res2b[i_node] = res2b[i_node] + __hcse_50 * __oldb_2
        __hcse_51 = res2[i_node]
        __hcse_52 = -(__hcse_51 / __hcse_48)
        node_volbd[i_node] = node_volbd[i_node] + (__oldb_2 * -((__hcse_49 * res2d[i_node] + -(__hcse_51 / __hcse_48 ^ 2) * ((2__cse_34) * __cse_34d))) + __hcse_52 * __oldb_2d)
        node_volb[i_node] = node_volb[i_node] + __hcse_52 * __oldb_2
    end
    for i_cell = i_ncell:-1:1
        __icse_35 = max(0, div(i_ncell - 1, 1) + 1)
        __icse_36 = __icse_35 * max(0, div(4 - 1, 1) + 1)
        __idx_vere_stack_0 = ((__icse_36 + __icse_35) + __icse_36) + ((i_cell - 1) + 1)
        vered = vere_stack_d[__idx_vere_stack_0]
        vere = vere_stack[__idx_vere_stack_0]
        for i_loc = 4:-1:1
            i_node = i_cell_to_node[i_loc, i_cell]
            for i_k = 4:-1:1
                i_k_node = i_cell_to_node[i_k, i_cell]
                resibd = resibd + res2bd[i_k_node]
                resib = resib + res2b[i_k_node]
            end
            __oldb_0d = resibd
            __oldb_0 = resib
            resibd = 0.0
            resib = 0.0
            dtbd = dtbd + 0.25 * -((__oldb_0 * vered + vere * __oldb_0d))
            dtb = dtb + 0.25 * -(vere * __oldb_0)
            __hcse_53 = -(dt / 4)
            verebd = verebd + (__oldb_0 * -(0.25dtd) + __hcse_53 * __oldb_0d)
            vereb = vereb + __hcse_53 * __oldb_0
            __icse_37 = max(0, div(i_ncell - 1, 1) + 1)
            __icse_38 = div(4 - 1, 1) + 1
            __idx_vere_stack_0 = (__icse_37 * max(0, __icse_38) + __icse_37) + (((i_cell - 1) * __icse_38 + (i_loc - 1)) + 1)
            vered = vere_stack_d[__idx_vere_stack_0]
            vere = vere_stack[__idx_vere_stack_0]
            __oldb_2d = verebd
            __oldb_2 = vereb
            verebd = 0.0
            vereb = 0.0
            __icse_39 = -(1.0 / 3.0)
            __cse_40d = cd[1, i_node]
            __cse_40 = c[1, i_node]
            __cse_41d = skxd[i_loc, i_cell]
            __cse_41 = skx[i_loc, i_cell]
            __cse_42d = cd[2, i_node]
            __cse_42 = c[2, i_node]
            __cse_43d = skyd[i_loc, i_cell]
            __cse_43 = sky[i_loc, i_cell]
            __hcse_54 = __icse_39 * (__cse_40 * __cse_41 + __cse_42 * __cse_43)
            __cse_44d = __oldb_2 * (__icse_39 * ((__cse_41 * __cse_40d + __cse_40 * __cse_41d) + (__cse_43 * __cse_42d + __cse_42 * __cse_43d))) + __hcse_54 * __oldb_2d
            __cse_44 = __hcse_54 * __oldb_2
            ubd[i_node] = ubd[i_node] + __cse_44d
            ub[i_node] = ub[i_node] + __cse_44
            upbd[i_node] = upbd[i_node] + __cse_44d
            upb[i_node] = upb[i_node] + __cse_44
            __hcse_55 = __icse_39 * (u[i_node] + up[i_node])
            __cse_45d = __oldb_2 * (__icse_39 * (ud[i_node] + upd[i_node])) + __hcse_55 * __oldb_2d
            __cse_45 = __hcse_55 * __oldb_2
            cbd[1, i_node] = cbd[1, i_node] + (__cse_45 * __cse_41d + __cse_41 * __cse_45d)
            cb[1, i_node] = cb[1, i_node] + __cse_41 * __cse_45
            skxbd[i_loc, i_cell] = skxbd[i_loc, i_cell] + (__cse_45 * __cse_40d + __cse_40 * __cse_45d)
            skxb[i_loc, i_cell] = skxb[i_loc, i_cell] + __cse_40 * __cse_45
            cbd[2, i_node] = cbd[2, i_node] + (__cse_45 * __cse_43d + __cse_43 * __cse_45d)
            cb[2, i_node] = cb[2, i_node] + __cse_43 * __cse_45
            skybd[i_loc, i_cell] = skybd[i_loc, i_cell] + (__cse_45 * __cse_42d + __cse_42 * __cse_45d)
            skyb[i_loc, i_cell] = skyb[i_loc, i_cell] + __cse_42 * __cse_45
        end
        verebd = 0.0
        vereb = 0.0
    end
    for i_ = i_njac:-1:1
        for i_node = i_nnode:-1:1
            __idx_up_stack_0 = ((i_ - 1) * (div(i_nnode - 1, 1) + 1) + (i_node - 1)) + 1
            upd[i_node] = up_stack_d[__idx_up_stack_0]
            up[i_node] = up_stack[__idx_up_stack_0]
            __cse_46d = node_vold[i_node]
            __cse_46 = node_vol[i_node]
            __cse_47d = upbd[i_node]
            __cse_47 = upb[i_node]
            __hcse_56 = __cse_46 ^ 2
            __hcse_57 = 1.0 / __hcse_56
            __hcse_58 = 1.0 / __cse_46
            __cse_48d = __cse_47 * (-__hcse_57 * __cse_46d) + __hcse_58 * __cse_47d
            __cse_48 = __hcse_58 * __cse_47
            resbd[i_node] = resbd[i_node] + __cse_48d
            resb[i_node] = resb[i_node] + __cse_48
            mupbd[i_node] = mupbd[i_node] + -__cse_48d
            mupb[i_node] = mupb[i_node] + -__cse_48
            __hcse_59 = res[i_node] - mup[i_node]
            __hcse_60 = -(__hcse_59 / __hcse_56)
            node_volbd[i_node] = node_volbd[i_node] + (__cse_47 * -((__hcse_57 * (resd[i_node] + -(mupd[i_node])) + -(__hcse_59 / __hcse_56 ^ 2) * ((2__cse_46) * __cse_46d))) + __hcse_60 * __cse_47d)
            node_volb[i_node] = node_volb[i_node] + __hcse_60 * __cse_47
        end
        for i_cell = i_ncell:-1:1
            __idx_auxu_stack_0 = ((i_ - 1) * (div(i_ncell - 1, 1) + 1) + (i_cell - 1)) + 1
            auxud = auxu_stack_d[__idx_auxu_stack_0]
            auxu = auxu_stack[__idx_auxu_stack_0]
            for i_loc = 4:-1:1
                i_lnode = i_cell_to_node[i_loc, i_cell]
                __icse_49 = div(4 - 1, 1) + 1
                __idx_mup_stack_0 = max(0, div(i_njac - 1, 1) + 1) * max(0, div(i_nnode - 1, 1) + 1) + (((i_ - 1) * ((div(i_ncell - 1, 1) + 1) * __icse_49) + (i_cell - 1) * __icse_49 + (i_loc - 1)) + 1)
                mupd[i_lnode] = mup_stack_d[__idx_mup_stack_0]
                mup[i_lnode] = mup_stack[__idx_mup_stack_0]
                __cse_50d = 0.05 * mupbd[i_lnode]
                __cse_50 = 0.05 * mupb[i_lnode]
                __hcse_61 = cell_vol[i_cell]
                __cse_51d = __cse_50 * cell_vold[i_cell] + __hcse_61 * __cse_50d
                __cse_51 = __hcse_61 * __cse_50
                auxubd = auxubd + __cse_51d
                auxub = auxub + __cse_51
                upbd[i_lnode] = upbd[i_lnode] + __cse_51d
                upb[i_lnode] = upb[i_lnode] + __cse_51
                __hcse_62 = auxu + up[i_lnode]
                cell_volbd[i_cell] = cell_volbd[i_cell] + (__cse_50 * (auxud + upd[i_lnode]) + __hcse_62 * __cse_50d)
                cell_volb[i_cell] = cell_volb[i_cell] + __hcse_62 * __cse_50
            end
            for i_loc = 1:4
                __icse_52 = i_cell_to_node[i_loc, i_cell]
                i_lnode = __icse_52
                auxud = auxud + upd[i_lnode]
                auxu = auxu + up[i_lnode]
                i_lnode = __icse_52
                upbd[i_lnode] = upbd[i_lnode] + auxubd
                upb[i_lnode] = upb[i_lnode] + auxub
            end
            auxubd = 0.0
            auxub = 0.0
        end
        for i_node = i_nnode:-1:1
            __idx_mup_stack_0 = ((i_ - 1) * (div(i_nnode - 1, 1) + 1) + (i_node - 1)) + 1
            mupd[i_node] = mup_stack_d[__idx_mup_stack_0]
            mup[i_node] = mup_stack[__idx_mup_stack_0]
            mupbd[i_node] = 0.0
            mupb[i_node] = 0.0
        end
    end
    for i_node = i_nnode:-1:1
        __oldb_0d = upbd[i_node]
        __oldb_0 = upb[i_node]
        upbd[i_node] = 0.0
        upb[i_node] = 0.0
        __cse_53d = node_vold[i_node]
        __cse_53 = node_vol[i_node]
        __hcse_63 = __cse_53 ^ 2
        __hcse_64 = 1.0 / __hcse_63
        __hcse_65 = 1.0 / __cse_53
        resbd[i_node] = resbd[i_node] + (__oldb_0 * (-__hcse_64 * __cse_53d) + __hcse_65 * __oldb_0d)
        resb[i_node] = resb[i_node] + __hcse_65 * __oldb_0
        __hcse_66 = res[i_node]
        __hcse_67 = -(__hcse_66 / __hcse_63)
        node_volbd[i_node] = node_volbd[i_node] + (__oldb_0 * -((__hcse_64 * resd[i_node] + -(__hcse_66 / __hcse_63 ^ 2) * ((2__cse_53) * __cse_53d))) + __hcse_67 * __oldb_0d)
        node_volb[i_node] = node_volb[i_node] + __hcse_67 * __oldb_0
    end
    for i_cell = 1:i_ncell
        aereskd = 0.0
        aeresk = 0.0
        aerexd = 0.0
        aerex = 0.0
        aereyd = 0.0
        aerey = 0.0
        aerezd = 0.0
        aerez = 0.0
        factord = 0.0
        factor = 0.0
        red = 0.0
        re = 0.0
        vered = 0.0
        vere = 0.0
        cavgxd = 0.0
        cavgx = 0.0
        cavgyd = 0.0
        cavgy = 0.0
        cavgzd = 0.0
        cavgz = 0.0
        for i_loc = 1:4
            i_node = i_cell_to_node[i_loc, i_cell]
            cavgxd = cavgxd + 0.25 * cd[1, i_node]
            cavgx = cavgx + c[1, i_node] / 4
            cavgyd = cavgyd + 0.25 * cd[2, i_node]
            cavgy = cavgy + c[2, i_node] / 4
            cavgzd = cavgzd + 0.25 * cd[3, i_node]
            cavgz = cavgz + c[3, i_node] / 4
        end
        for i_loc = 1:4
            aereskd = 0.0
            aeresk = 0.0
            factord = 0.0
            factor = 0.0
            i_node = i_cell_to_node[i_loc, i_cell]
            __ihcse_68 = -(1.0 / 3.0)
            __hcse_69 = c[1, i_node]
            __hcse_70 = skx[i_loc, i_cell]
            __hcse_71 = c[2, i_node]
            __hcse_72 = sky[i_loc, i_cell]
            __hcse_73 = c[3, i_node]
            __hcse_74 = skz[i_loc, i_cell]
            __hcse_75 = __hcse_69 * __hcse_70 + __hcse_71 * __hcse_72 + __hcse_73 * __hcse_74
            __hcse_76 = u[i_node]
            vered = (__ihcse_68 * __hcse_75) * ud[i_node] + (__ihcse_68 * __hcse_76) * (((__hcse_70 * cd[1, i_node] + __hcse_69 * skxd[i_loc, i_cell]) + (__hcse_72 * cd[2, i_node] + __hcse_71 * skyd[i_loc, i_cell])) + (__hcse_74 * cd[3, i_node] + __hcse_73 * skzd[i_loc, i_cell]))
            vere = __ihcse_68 * __hcse_76 * __hcse_75
            __hcse_77 = cell_vol[i_cell]
            red = (1.0 / __hcse_77) * vered + -(vere / __hcse_77 ^ 2) * cell_vold[i_cell]
            re = vere / __hcse_77
            aerexd = re * cavgxd + cavgx * red
            aerex = cavgx * re
            aereyd = re * cavgyd + cavgy * red
            aerey = cavgy * re
            aerezd = re * cavgzd + cavgz * red
            aerez = cavgz * re
            __hcse_78 = 0.5 - gamma[i_cell]
            __hcse_79 = -(dt / 4)
            resid = ((__hcse_78 * vere) * -(0.25dtd) + (__hcse_79 * vere) * -(gammad[i_cell])) + (__hcse_79 * __hcse_78) * vered
            resi = __hcse_79 * __hcse_78 * vere
            for i_k = 1:4
                __hcse_80 = skx[i_k, i_cell]
                __hcse_81 = sky[i_k, i_cell]
                __hcse_82 = skz[i_k, i_cell]
                aereskd = ((__hcse_80 * aerexd + aerex * skxd[i_k, i_cell]) + (__hcse_81 * aereyd + aerey * skyd[i_k, i_cell])) + (__hcse_82 * aerezd + aerez * skzd[i_k, i_cell])
                aeresk = aerex * __hcse_80 + aerey * __hcse_81 + aerez * __hcse_82
                __hcse_83 = dt ^ 2 / 3
                factord = aeresk * (0.3333333333333333 * ((2dt) * dtd)) + __hcse_83 * aereskd
                factor = __hcse_83 * aeresk
                __hcse_84 = beta[i_cell]
                auxresd = resid + (__hcse_84 * factord + factor * betad[i_cell])
                auxres = resi + factor * __hcse_84
                __hcse_85 = gamma[i_cell]
                auxres2d = __hcse_85 * factord + factor * gammad[i_cell]
                auxres2 = factor * __hcse_85
                i_k_node = i_cell_to_node[i_k, i_cell]
            end
        end
        for i_loc = 1:4
            aereskd = 0.0
            aeresk = 0.0
            factord = 0.0
            factor = 0.0
            i_node = i_cell_to_node[i_loc, i_cell]
            __ihcse_86 = -(1.0 / 3.0)
            __hcse_87 = c[1, i_node]
            __hcse_88 = skx[i_loc, i_cell]
            __hcse_89 = c[2, i_node]
            __hcse_90 = sky[i_loc, i_cell]
            __hcse_91 = c[3, i_node]
            __hcse_92 = skz[i_loc, i_cell]
            __hcse_93 = __hcse_87 * __hcse_88 + __hcse_89 * __hcse_90 + __hcse_91 * __hcse_92
            __hcse_94 = u[i_node]
            vered = (__ihcse_86 * __hcse_93) * ud[i_node] + (__ihcse_86 * __hcse_94) * (((__hcse_88 * cd[1, i_node] + __hcse_87 * skxd[i_loc, i_cell]) + (__hcse_90 * cd[2, i_node] + __hcse_89 * skyd[i_loc, i_cell])) + (__hcse_92 * cd[3, i_node] + __hcse_91 * skzd[i_loc, i_cell]))
            vere = __ihcse_86 * __hcse_94 * __hcse_93
            __hcse_95 = cell_vol[i_cell]
            red = (1.0 / __hcse_95) * vered + -(vere / __hcse_95 ^ 2) * cell_vold[i_cell]
            re = vere / __hcse_95
            aerexd = re * cavgxd + cavgx * red
            aerex = cavgx * re
            aereyd = re * cavgyd + cavgy * red
            aerey = cavgy * re
            aerezd = re * cavgzd + cavgz * red
            aerez = cavgz * re
            __hcse_96 = 0.5 - gamma[i_cell]
            __hcse_97 = -(dt / 4)
            resid = ((__hcse_96 * vere) * -(0.25dtd) + (__hcse_97 * vere) * -(gammad[i_cell])) + (__hcse_97 * __hcse_96) * vered
            resi = __hcse_97 * __hcse_96 * vere
            for i_k = 1:4
                __hcse_98 = skx[i_k, i_cell]
                __hcse_99 = sky[i_k, i_cell]
                __hcse_100 = skz[i_k, i_cell]
                aereskd = ((__hcse_98 * aerexd + aerex * skxd[i_k, i_cell]) + (__hcse_99 * aereyd + aerey * skyd[i_k, i_cell])) + (__hcse_100 * aerezd + aerez * skzd[i_k, i_cell])
                aeresk = aerex * __hcse_98 + aerey * __hcse_99 + aerez * __hcse_100
                __hcse_101 = dt ^ 2 / 3
                factord = aeresk * (0.3333333333333333 * ((2dt) * dtd)) + __hcse_101 * aereskd
                factor = __hcse_101 * aeresk
                __hcse_102 = beta[i_cell]
                auxresd = resid + (__hcse_102 * factord + factor * betad[i_cell])
                auxres = resi + factor * __hcse_102
                __hcse_103 = gamma[i_cell]
                auxres2d = __hcse_103 * factord + factor * gammad[i_cell]
                auxres2 = factor * __hcse_103
                i_k_node = i_cell_to_node[i_k, i_cell]
            end
            i_node = i_cell_to_node[i_loc, i_cell]
            for i_k = 1:4
                __cse_54d = skxd[i_k, i_cell]
                __cse_54 = skx[i_k, i_cell]
                __cse_55d = skyd[i_k, i_cell]
                __cse_55 = sky[i_k, i_cell]
                __cse_56d = skzd[i_k, i_cell]
                __cse_56 = skz[i_k, i_cell]
                aereskd = ((__cse_54 * aerexd + aerex * __cse_54d) + (__cse_55 * aereyd + aerey * __cse_55d)) + (__cse_56 * aerezd + aerez * __cse_56d)
                aeresk = aerex * __cse_54 + aerey * __cse_55 + aerez * __cse_56
                __hcse_104 = 2dt
                __cse_57d = 0.3333333333333333 * (__hcse_104 * dtd)
                __cse_57 = dt ^ 2 / 3
                factord = aeresk * __cse_57d + __cse_57 * aereskd
                factor = __cse_57 * aeresk
                __cse_58d = betad[i_cell]
                __cse_58 = beta[i_cell]
                auxresd = resid + (__cse_58 * factord + factor * __cse_58d)
                auxres = resi + factor * __cse_58
                __cse_59d = gammad[i_cell]
                __cse_59 = gamma[i_cell]
                auxres2d = __cse_59 * factord + factor * __cse_59d
                auxres2 = factor * __cse_59
                __icse_60 = i_cell_to_node[i_k, i_cell]
                i_k_node = __icse_60
                i_k_node = __icse_60
                auxres2bd = auxres2bd + res2bd[i_k_node]
                auxres2b = auxres2b + res2b[i_k_node]
                auxresbd = auxresbd + resbd[i_k_node]
                auxresb = auxresb + resb[i_k_node]
                __oldb_0d = auxres2bd
                __oldb_0 = auxres2b
                auxres2bd = 0.0
                auxres2b = 0.0
                factorbd = factorbd + (__oldb_0 * __cse_59d + __cse_59 * __oldb_0d)
                factorb = factorb + __cse_59 * __oldb_0
                gammabd[i_cell] = gammabd[i_cell] + (__oldb_0 * factord + factor * __oldb_0d)
                gammab[i_cell] = gammab[i_cell] + factor * __oldb_0
                __oldb_0d = auxresbd
                __oldb_0 = auxresb
                auxresbd = 0.0
                auxresb = 0.0
                resibd = resibd + __oldb_0d
                resib = resib + __oldb_0
                factorbd = factorbd + (__oldb_0 * __cse_58d + __cse_58 * __oldb_0d)
                factorb = factorb + __cse_58 * __oldb_0
                betabd[i_cell] = betabd[i_cell] + (__oldb_0 * factord + factor * __oldb_0d)
                betab[i_cell] = betab[i_cell] + factor * __oldb_0
                __oldb_0d = factorbd
                __oldb_0 = factorb
                factorbd = 0.0
                factorb = 0.0
                __hcse_105 = 0.3333333333333333 * (aeresk * __oldb_0)
                dtbd = dtbd + (__hcse_105 * (2dtd) + __hcse_104 * (0.3333333333333333 * (__oldb_0 * aereskd + aeresk * __oldb_0d)))
                dtb = dtb + __hcse_104 * __hcse_105
                aereskbd = aereskbd + (__oldb_0 * __cse_57d + __cse_57 * __oldb_0d)
                aereskb = aereskb + __cse_57 * __oldb_0
                __oldb_0d = aereskbd
                __oldb_0 = aereskb
                aereskbd = 0.0
                aereskb = 0.0
                aerexbd = aerexbd + (__oldb_0 * __cse_54d + __cse_54 * __oldb_0d)
                aerexb = aerexb + __cse_54 * __oldb_0
                skxbd[i_k, i_cell] = skxbd[i_k, i_cell] + (__oldb_0 * aerexd + aerex * __oldb_0d)
                skxb[i_k, i_cell] = skxb[i_k, i_cell] + aerex * __oldb_0
                aereybd = aereybd + (__oldb_0 * __cse_55d + __cse_55 * __oldb_0d)
                aereyb = aereyb + __cse_55 * __oldb_0
                skybd[i_k, i_cell] = skybd[i_k, i_cell] + (__oldb_0 * aereyd + aerey * __oldb_0d)
                skyb[i_k, i_cell] = skyb[i_k, i_cell] + aerey * __oldb_0
                aerezbd = aerezbd + (__oldb_0 * __cse_56d + __cse_56 * __oldb_0d)
                aerezb = aerezb + __cse_56 * __oldb_0
                skzbd[i_k, i_cell] = skzbd[i_k, i_cell] + (__oldb_0 * aerezd + aerez * __oldb_0d)
                skzb[i_k, i_cell] = skzb[i_k, i_cell] + aerez * __oldb_0
            end
            __oldb_0d = resibd
            __oldb_0 = resib
            resibd = 0.0
            resib = 0.0
            __cse_61d = -(gammad[i_cell])
            __cse_61 = 0.5 - gamma[i_cell]
            __hcse_106 = __cse_61 * vere
            dtbd = dtbd + 0.25 * -((__oldb_0 * (vere * __cse_61d + __cse_61 * vered) + __hcse_106 * __oldb_0d))
            dtb = dtb + 0.25 * -(__hcse_106 * __oldb_0)
            __cse_62d = -(0.25dtd)
            __cse_62 = -(dt / 4)
            __hcse_107 = __cse_62 * vere
            gammabd[i_cell] = gammabd[i_cell] + -((__oldb_0 * (vere * __cse_62d + __cse_62 * vered) + __hcse_107 * __oldb_0d))
            gammab[i_cell] = gammab[i_cell] + -(__hcse_107 * __oldb_0)
            __hcse_108 = __cse_62 * __cse_61
            verebd = verebd + (__oldb_0 * (__cse_61 * __cse_62d + __cse_62 * __cse_61d) + __hcse_108 * __oldb_0d)
            vereb = vereb + __hcse_108 * __oldb_0
            __oldb_0d = aerezbd
            __oldb_0 = aerezb
            aerezbd = 0.0
            aerezb = 0.0
            cavgzbd = cavgzbd + (__oldb_0 * red + re * __oldb_0d)
            cavgzb = cavgzb + re * __oldb_0
            rebd = rebd + (__oldb_0 * cavgzd + cavgz * __oldb_0d)
            reb = reb + cavgz * __oldb_0
            __oldb_0d = aereybd
            __oldb_0 = aereyb
            aereybd = 0.0
            aereyb = 0.0
            cavgybd = cavgybd + (__oldb_0 * red + re * __oldb_0d)
            cavgyb = cavgyb + re * __oldb_0
            rebd = rebd + (__oldb_0 * cavgyd + cavgy * __oldb_0d)
            reb = reb + cavgy * __oldb_0
            __oldb_0d = aerexbd
            __oldb_0 = aerexb
            aerexbd = 0.0
            aerexb = 0.0
            cavgxbd = cavgxbd + (__oldb_0 * red + re * __oldb_0d)
            cavgxb = cavgxb + re * __oldb_0
            rebd = rebd + (__oldb_0 * cavgxd + cavgx * __oldb_0d)
            reb = reb + cavgx * __oldb_0
            __oldb_0d = rebd
            __oldb_0 = reb
            rebd = 0.0
            reb = 0.0
            __cse_63d = cell_vold[i_cell]
            __cse_63 = cell_vol[i_cell]
            __hcse_109 = __cse_63 ^ 2
            __hcse_110 = 1.0 / __hcse_109
            __hcse_111 = 1.0 / __cse_63
            verebd = verebd + (__oldb_0 * (-__hcse_110 * __cse_63d) + __hcse_111 * __oldb_0d)
            vereb = vereb + __hcse_111 * __oldb_0
            __hcse_112 = -(vere / __hcse_109)
            cell_volbd[i_cell] = cell_volbd[i_cell] + (__oldb_0 * -((__hcse_110 * vered + -(vere / __hcse_109 ^ 2) * ((2__cse_63) * __cse_63d))) + __hcse_112 * __oldb_0d)
            cell_volb[i_cell] = cell_volb[i_cell] + __hcse_112 * __oldb_0
            __oldb_0d = verebd
            __oldb_0 = vereb
            verebd = 0.0
            vereb = 0.0
            __icse_64 = -(1.0 / 3.0)
            __cse_65d = cd[1, i_node]
            __cse_65 = c[1, i_node]
            __cse_66d = skxd[i_loc, i_cell]
            __cse_66 = skx[i_loc, i_cell]
            __cse_67d = cd[2, i_node]
            __cse_67 = c[2, i_node]
            __cse_68d = skyd[i_loc, i_cell]
            __cse_68 = sky[i_loc, i_cell]
            __cse_69d = cd[3, i_node]
            __cse_69 = c[3, i_node]
            __cse_70d = skzd[i_loc, i_cell]
            __cse_70 = skz[i_loc, i_cell]
            __hcse_113 = __icse_64 * (__cse_65 * __cse_66 + __cse_67 * __cse_68 + __cse_69 * __cse_70)
            ubd[i_node] = ubd[i_node] + (__oldb_0 * (__icse_64 * (((__cse_66 * __cse_65d + __cse_65 * __cse_66d) + (__cse_68 * __cse_67d + __cse_67 * __cse_68d)) + (__cse_70 * __cse_69d + __cse_69 * __cse_70d))) + __hcse_113 * __oldb_0d)
            ub[i_node] = ub[i_node] + __hcse_113 * __oldb_0
            __hcse_114 = __icse_64 * u[i_node]
            __cse_71d = __oldb_0 * (__icse_64 * ud[i_node]) + __hcse_114 * __oldb_0d
            __cse_71 = __hcse_114 * __oldb_0
            cbd[1, i_node] = cbd[1, i_node] + (__cse_71 * __cse_66d + __cse_66 * __cse_71d)
            cb[1, i_node] = cb[1, i_node] + __cse_66 * __cse_71
            skxbd[i_loc, i_cell] = skxbd[i_loc, i_cell] + (__cse_71 * __cse_65d + __cse_65 * __cse_71d)
            skxb[i_loc, i_cell] = skxb[i_loc, i_cell] + __cse_65 * __cse_71
            cbd[2, i_node] = cbd[2, i_node] + (__cse_71 * __cse_68d + __cse_68 * __cse_71d)
            cb[2, i_node] = cb[2, i_node] + __cse_68 * __cse_71
            skybd[i_loc, i_cell] = skybd[i_loc, i_cell] + (__cse_71 * __cse_67d + __cse_67 * __cse_71d)
            skyb[i_loc, i_cell] = skyb[i_loc, i_cell] + __cse_67 * __cse_71
            cbd[3, i_node] = cbd[3, i_node] + (__cse_71 * __cse_70d + __cse_70 * __cse_71d)
            cb[3, i_node] = cb[3, i_node] + __cse_70 * __cse_71
            skzbd[i_loc, i_cell] = skzbd[i_loc, i_cell] + (__cse_71 * __cse_69d + __cse_69 * __cse_71d)
            skzb[i_loc, i_cell] = skzb[i_loc, i_cell] + __cse_69 * __cse_71
            factorbd = 0.0
            factorb = 0.0
            aereskbd = 0.0
            aereskb = 0.0
        end
        for i_loc = 1:4
            __icse_72 = i_cell_to_node[i_loc, i_cell]
            i_node = __icse_72
            cavgxd = cavgxd + 0.25 * cd[1, i_node]
            cavgx = cavgx + c[1, i_node] / 4
            cavgyd = cavgyd + 0.25 * cd[2, i_node]
            cavgy = cavgy + c[2, i_node] / 4
            cavgzd = cavgzd + 0.25 * cd[3, i_node]
            cavgz = cavgz + c[3, i_node] / 4
            i_node = __icse_72
            cbd[3, i_node] = cbd[3, i_node] + 0.25cavgzbd
            cb[3, i_node] = cb[3, i_node] + 0.25cavgzb
            cbd[2, i_node] = cbd[2, i_node] + 0.25cavgybd
            cb[2, i_node] = cb[2, i_node] + 0.25cavgyb
            cbd[1, i_node] = cbd[1, i_node] + 0.25cavgxbd
            cb[1, i_node] = cb[1, i_node] + 0.25cavgxb
        end
        cavgzbd = 0.0
        cavgzb = 0.0
        cavgybd = 0.0
        cavgyb = 0.0
        cavgxbd = 0.0
        cavgxb = 0.0
        verebd = 0.0
        vereb = 0.0
        rebd = 0.0
        reb = 0.0
        factorbd = 0.0
        factorb = 0.0
        aerezbd = 0.0
        aerezb = 0.0
        aereybd = 0.0
        aereyb = 0.0
        aerexbd = 0.0
        aerexb = 0.0
        aereskbd = 0.0
        aereskb = 0.0
    end
    return (dtb, dtbd)
end

function ttgc(u, uref, i_cell_to_node, cell_vol, node_vol, skx, sky, skz, i_ncell, i_nnode, c, dt, beta, gamma, i_njac, res, res2, up, mup, loss)
    for i_cell = 1:i_ncell
        cavgx = 0.0
        cavgy = 0.0
        cavgz = 0.0
        for i_loc = 1:4
            i_node = i_cell_to_node[i_loc, i_cell]
            cavgx = cavgx + c[1, i_node] / 4
            cavgy = cavgy + c[2, i_node] / 4
            cavgz = cavgz + c[3, i_node] / 4
        end
        for i_loc = 1:4
            i_node = i_cell_to_node[i_loc, i_cell]
            vere = -(1.0 / 3.0) * u[i_node] * (c[1, i_node] * skx[i_loc, i_cell] + c[2, i_node] * sky[i_loc, i_cell] + c[3, i_node] * skz[i_loc, i_cell])
            re = vere / cell_vol[i_cell]
            aerex = cavgx * re
            aerey = cavgy * re
            aerez = cavgz * re
            resi = -(dt / 4) * (0.5 - gamma[i_cell]) * vere
            for i_k = 1:4
                aeresk = aerex * skx[i_k, i_cell] + aerey * sky[i_k, i_cell] + aerez * skz[i_k, i_cell]
                factor = (dt ^ 2 / 3) * aeresk
                auxres = resi + factor * beta[i_cell]
                auxres2 = factor * gamma[i_cell]
                i_k_node = i_cell_to_node[i_k, i_cell]
                res[i_k_node] = res[i_k_node] + auxres
                res2[i_k_node] = res2[i_k_node] + auxres2
            end
        end
    end
    for i_node = 1:i_nnode
        up[i_node] = res[i_node] / node_vol[i_node]
    end
    for i_ = 1:i_njac
        for i_node = 1:i_nnode
            mup[i_node] = 0.0
        end
        for i_cell = 1:i_ncell
            auxu = 0.0
            for i_loc = 1:4
                i_lnode = i_cell_to_node[i_loc, i_cell]
                auxu = auxu + up[i_lnode]
            end
            for i_loc = 1:4
                i_lnode = i_cell_to_node[i_loc, i_cell]
                mup[i_lnode] = mup[i_lnode] + ((auxu + up[i_lnode]) * cell_vol[i_cell]) / 20.0
            end
        end
        for i_node = 1:i_nnode
            up[i_node] = up[i_node] + (res[i_node] - mup[i_node]) / node_vol[i_node]
        end
    end
    for i_cell = 1:i_ncell
        for i_loc = 1:4
            i_node = i_cell_to_node[i_loc, i_cell]
            vere = -(1.0 / 3.0) * (u[i_node] + up[i_node]) * (c[1, i_node] * skx[i_loc, i_cell] + c[2, i_node] * sky[i_loc, i_cell])
            resi = -(dt / 4) * vere
            for i_k = 1:4
                i_k_node = i_cell_to_node[i_k, i_cell]
                res2[i_k_node] = res2[i_k_node] + resi
            end
        end
    end
    for i_node = 1:i_nnode
        up[i_node] = res2[i_node] / node_vol[i_node]
    end
    for i_ = 1:i_njac
        for i_node = 1:i_nnode
            mup[i_node] = 0.0
        end
        for i_cell = 1:i_ncell
            auxu = 0.0
            for i_loc = 1:4
                i_lnode = i_cell_to_node[i_loc, i_cell]
                auxu = auxu + up[i_lnode]
            end
            for i_loc = 1:4
                i_lnode = i_cell_to_node[i_loc, i_cell]
                mup[i_lnode] = mup[i_lnode] + ((auxu + up[i_lnode]) * cell_vol[i_cell]) / 20.0
            end
        end
        for i_node = 1:i_nnode
            up[i_node] = up[i_node] + (res2[i_node] - mup[i_node]) / node_vol[i_node]
        end
    end
    for i_node2 = 1:i_nnode
        loss[1] = loss[1] + ((u[i_node2] + up[i_node2]) - uref[i_node2]) ^ 2
    end
end
