function initstacks_unet_b(c1, c2, c3, h, w)
    two = 2
    h2 = div(h, two)
    w2 = div(w, two)
    hw2 = h2 * w2
    four = 4
    h4 = div(h, four)
    w4 = div(w, four)
    hw4 = h4 * w4
    n_b_mid = c3 * hw4
    n_b_out = c3 * hw4
    hw = h * w
    n_d1_mid = c1 * hw
    n_d1_out = c1 * hw
    n_d2_mid = c2 * hw2
    n_d2_out = c2 * hw2
    n_e1_mid = c1 * hw
    n_e1_out = c1 * hw
    n_e2_mid = c2 * hw2
    n_e2_out = c2 * hw2
    t_e1_stack = Vector{Float64}(undef, max(0, div(n_e1_mid - 1, 1) + 1))
    skip1_stack = Vector{Float64}(undef, max(0, div(n_e1_out - 1, 1) + 1))
    t_e2_stack = Vector{Float64}(undef, max(0, div(n_e2_mid - 1, 1) + 1))
    skip2_stack = Vector{Float64}(undef, max(0, div(n_e2_out - 1, 1) + 1))
    t_b_stack = Vector{Float64}(undef, max(0, div(n_b_mid - 1, 1) + 1))
    bott_stack = Vector{Float64}(undef, max(0, div(n_b_out - 1, 1) + 1))
    t_d2_stack = Vector{Float64}(undef, max(0, div(n_d2_mid - 1, 1) + 1))
    dec2out_stack = Vector{Float64}(undef, max(0, div(n_d2_out - 1, 1) + 1))
    t_d1_stack = Vector{Float64}(undef, max(0, div(n_d1_mid - 1, 1) + 1))
    dec1out_stack = Vector{Float64}(undef, max(0, div(n_d1_out - 1, 1) + 1))
    return (t_e1_stack, skip1_stack, t_e2_stack, skip2_stack, t_b_stack, bott_stack, t_d2_stack, dec2out_stack, t_d1_stack, dec1out_stack)
end

function unet_hv(x, xb, h, w, c_in, c1, c2, c3, c_out, w_e1a, w_e1ab, b_e1a, b_e1ab, w_e1b, w_e1bb, b_e1b, b_e1bb, w_e2a, w_e2ab, b_e2a, b_e2ab, w_e2b, w_e2bb, b_e2b, b_e2bb, w_ba, w_bab, b_ba, b_bab, w_bb, w_bbb, b_bb, b_bbb, w_d2a, w_d2ab, b_d2a, b_d2ab, w_d2b, w_d2bb, b_d2b, b_d2bb, w_d1a, w_d1ab, b_d1a, b_d1ab, w_d1b, w_d1bb, b_d1b, b_d1bb, w_out, w_outb, b_out, b_outb, xpad0, xpad0b, t_e1, t_e1b, t_e1pad, t_e1padb, skip1, skip1b, p1, p1b, p1pad, p1padb, t_e2, t_e2b, t_e2pad, t_e2padb, skip2, skip2b, p2, p2b, p2pad, p2padb, t_b, t_bb, t_bpad, t_bpadb, bott, bottb, u2, u2b, cat2, cat2b, cat2pad, cat2padb, t_d2, t_d2b, t_d2pad, t_d2padb, dec2out, dec2outb, u1, u1b, cat1, cat1b, cat1pad, cat1padb, t_d1, t_d1b, t_d1pad, t_d1padb, dec1out, dec1outb, y, yb, xd, xbd, w_e1ad, w_e1abd, b_e1ad, b_e1abd, w_e1bd, w_e1bbd, b_e1bd, b_e1bbd, w_e2ad, w_e2abd, b_e2ad, b_e2abd, w_e2bd, w_e2bbd, b_e2bd, b_e2bbd, w_bad, w_babd, b_bad, b_babd, w_bbd, w_bbbd, b_bbd, b_bbbd, w_d2ad, w_d2abd, b_d2ad, b_d2abd, w_d2bd, w_d2bbd, b_d2bd, b_d2bbd, w_d1ad, w_d1abd, b_d1ad, b_d1abd, w_d1bd, w_d1bbd, b_d1bd, b_d1bbd, w_outd, w_outbd, b_outd, b_outbd, xpad0d, xpad0bd, t_e1d, t_e1bd, t_e1padd, t_e1padbd, skip1d, skip1bd, p1d, p1bd, p1padd, p1padbd, t_e2d, t_e2bd, t_e2padd, t_e2padbd, skip2d, skip2bd, p2d, p2bd, p2padd, p2padbd, t_bd, t_bbd, t_bpadd, t_bpadbd, bottd, bottbd, u2d, u2bd, cat2d, cat2bd, cat2padd, cat2padbd, t_d2d, t_d2bd, t_d2padd, t_d2padbd, dec2outd, dec2outbd, u1d, u1bd, cat1d, cat1bd, cat1padd, cat1padbd, t_d1d, t_d1bd, t_d1padd, t_d1padbd, dec1outd, dec1outbd, yd, ybd, t_e1_stack, skip1_stack, t_e2_stack, skip2_stack, t_b_stack, bott_stack, t_d2_stack, dec2out_stack, t_d1_stack, dec1out_stack)
    t_e1_stack_d = Vector{Float64}(undef, length(t_e1_stack))
    skip1_stack_d = Vector{Float64}(undef, length(skip1_stack))
    t_e2_stack_d = Vector{Float64}(undef, length(t_e2_stack))
    skip2_stack_d = Vector{Float64}(undef, length(skip2_stack))
    t_b_stack_d = Vector{Float64}(undef, length(t_b_stack))
    bott_stack_d = Vector{Float64}(undef, length(bott_stack))
    t_d2_stack_d = Vector{Float64}(undef, length(t_d2_stack))
    dec2out_stack_d = Vector{Float64}(undef, length(dec2out_stack))
    t_d1_stack_d = Vector{Float64}(undef, length(t_d1_stack))
    dec1out_stack_d = Vector{Float64}(undef, length(dec1out_stack))
    a11 = 0.0
    a12 = 0.0
    a21 = 0.0
    a22 = 0.0
    m1 = 0.0
    m2 = 0.0
    s = 0.0
    a11b = 0.0
    a12b = 0.0
    a21b = 0.0
    a22b = 0.0
    m1b = 0.0
    m2b = 0.0
    sb = 0.0
    a11d = 0.0
    a11bd = 0.0
    a12d = 0.0
    a12bd = 0.0
    a21d = 0.0
    a21bd = 0.0
    a22d = 0.0
    a22bd = 0.0
    m1d = 0.0
    m1bd = 0.0
    m2d = 0.0
    m2bd = 0.0
    sd = 0.0
    sbd = 0.0
    zero_vald = 0.0
    zero_valbd = 0.0
    two = 2
    four = 4
    h2 = div(h, two)
    w2 = div(w, two)
    h4 = div(h, four)
    w4 = div(w, four)
    hp1 = h + 2
    wp1 = w + 2
    hp2 = h2 + 2
    wp2 = w2 + 2
    hp4 = h4 + 2
    wp4 = w4 + 2
    pad = 1
    kh = 3
    kw = 3
    khkw = kh * kw
    kh_out = 1
    kw_out = 1
    khkw_out = kh_out * kw_out
    scale = 2
    zero_vald = 0.0
    zero_val = 0.0
    c32 = c3 + c2
    c21 = c2 + c1
    hw = h * w
    hw2 = h2 * w2
    hw4 = h4 * w4
    n_xpad0 = c_in * hp1 * wp1
    n_e1_mid = c1 * hw
    n_e1_midpad = c1 * hp1 * wp1
    n_e1_out = c1 * hw
    n_p1pad = c1 * hp2 * wp2
    n_e2_mid = c2 * hw2
    n_e2_midpad = c2 * hp2 * wp2
    n_e2_out = c2 * hw2
    n_p2pad = c2 * hp4 * wp4
    n_b_mid = c3 * hw4
    n_b_midpad = c3 * hp4 * wp4
    n_b_out = c3 * hw4
    n_cat2pad = c32 * hp2 * wp2
    n_d2_mid = c2 * hw2
    n_d2_midpad = c2 * hp2 * wp2
    n_d2_out = c2 * hw2
    n_cat1pad = c21 * hp1 * wp1
    n_d1_mid = c1 * hw
    n_d1_midpad = c1 * hp1 * wp1
    n_d1_out = c1 * hw
    for i = 1:n_xpad0
        xpad0d[i] = zero_vald
        xpad0[i] = zero_val
    end
    for idx = 1:c_in * hw
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        yi = (ci - 1) * hp1 * wp1 + ((i + pad) - 1) * wp1 + (j + pad)
        xpad0d[yi] = xd[idx]
        xpad0[yi] = x[idx]
    end
    for idx = 1:c1 * hw
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        sd = 0.0
        s = 0.0
        for i_k = 1:c_in * khkw
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp1 * wp1 + (row - 1) * wp1 + col
            wi = (((co - 1) * c_in + (ci - 1)) * kh + (ki - 1)) * kw + kj
            __cse_23 = w_e1a[wi]
            __cse_24 = xpad0[xi]
            sd = sd + (__cse_23 * xpad0d[xi] + __cse_24 * w_e1ad[wi])
            s = s + __cse_24 * __cse_23
        end
        t_e1d[idx] = sd + b_e1ad[co]
        t_e1[idx] = s + b_e1a[co]
    end
    for i = 1:n_e1_mid
        __idx_t_e1_stack_0 = (i - 1) + 1
        __cse_0d = t_e1d[i]
        __cse_0 = t_e1[i]
        t_e1_stack_d[__idx_t_e1_stack_0] = __cse_0d
        t_e1_stack[__idx_t_e1_stack_0] = __cse_0
        t_e1d[i] = (0.5 * (1.0 + sign(__cse_0 - zero_val))) * __cse_0d + (0.5 * (1.0 + sign(zero_val - __cse_0))) * zero_vald
        t_e1[i] = max(__cse_0, zero_val)
    end
    for i = 1:n_e1_midpad
        t_e1padd[i] = zero_vald
        t_e1pad[i] = zero_val
    end
    for idx = 1:c1 * hw
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        yi = (ci - 1) * hp1 * wp1 + ((i + pad) - 1) * wp1 + (j + pad)
        t_e1padd[yi] = t_e1d[idx]
        t_e1pad[yi] = t_e1[idx]
    end
    for idx = 1:c1 * hw
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        sd = 0.0
        s = 0.0
        for i_k = 1:c1 * khkw
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp1 * wp1 + (row - 1) * wp1 + col
            wi = (((co - 1) * c1 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            __cse_25 = w_e1b[wi]
            __cse_26 = t_e1pad[xi]
            sd = sd + (__cse_25 * t_e1padd[xi] + __cse_26 * w_e1bd[wi])
            s = s + __cse_26 * __cse_25
        end
        skip1d[idx] = sd + b_e1bd[co]
        skip1[idx] = s + b_e1b[co]
    end
    for i = 1:n_e1_out
        __idx_skip1_stack_0 = (i - 1) + 1
        __cse_1d = skip1d[i]
        __cse_1 = skip1[i]
        skip1_stack_d[__idx_skip1_stack_0] = __cse_1d
        skip1_stack[__idx_skip1_stack_0] = __cse_1
        skip1d[i] = (0.5 * (1.0 + sign(__cse_1 - zero_val))) * __cse_1d + (0.5 * (1.0 + sign(zero_val - __cse_1))) * zero_vald
        skip1[i] = max(__cse_1, zero_val)
    end
    for idx = 1:c1 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        oi = div(rem, w2) + 1
        oj = mod(rem, w2) + 1
        i0 = 2oi - 1
        j0 = 2oj - 1
        a11d = skip1d[(ci - 1) * hw + (i0 - 1) * w + j0]
        a11 = skip1[(ci - 1) * hw + (i0 - 1) * w + j0]
        a12d = skip1d[(ci - 1) * hw + (i0 - 1) * w + j0 + 1]
        a12 = skip1[(ci - 1) * hw + (i0 - 1) * w + j0 + 1]
        a21d = skip1d[(ci - 1) * hw + i0 * w + j0]
        a21 = skip1[(ci - 1) * hw + i0 * w + j0]
        a22d = skip1d[(ci - 1) * hw + i0 * w + j0 + 1]
        a22 = skip1[(ci - 1) * hw + i0 * w + j0 + 1]
        m1d = (0.5 * (1.0 + sign(a11 - a12))) * a11d + (0.5 * (1.0 + sign(a12 - a11))) * a12d
        m1 = max(a11, a12)
        m2d = (0.5 * (1.0 + sign(a21 - a22))) * a21d + (0.5 * (1.0 + sign(a22 - a21))) * a22d
        m2 = max(a21, a22)
        p1d[idx] = (0.5 * (1.0 + sign(m1 - m2))) * m1d + (0.5 * (1.0 + sign(m2 - m1))) * m2d
        p1[idx] = max(m1, m2)
    end
    for i = 1:n_p1pad
        p1padd[i] = zero_vald
        p1pad[i] = zero_val
    end
    for idx = 1:c1 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        yi = (ci - 1) * hp2 * wp2 + ((i + pad) - 1) * wp2 + (j + pad)
        p1padd[yi] = p1d[idx]
        p1pad[yi] = p1[idx]
    end
    for idx = 1:c2 * hw2
        idxm1 = idx - 1
        co = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        sd = 0.0
        s = 0.0
        for i_k = 1:c1 * khkw
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp2 * wp2 + (row - 1) * wp2 + col
            wi = (((co - 1) * c1 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            __cse_27 = w_e2a[wi]
            __cse_28 = p1pad[xi]
            sd = sd + (__cse_27 * p1padd[xi] + __cse_28 * w_e2ad[wi])
            s = s + __cse_28 * __cse_27
        end
        t_e2d[idx] = sd + b_e2ad[co]
        t_e2[idx] = s + b_e2a[co]
    end
    for i = 1:n_e2_mid
        __idx_t_e2_stack_0 = (i - 1) + 1
        __cse_2d = t_e2d[i]
        __cse_2 = t_e2[i]
        t_e2_stack_d[__idx_t_e2_stack_0] = __cse_2d
        t_e2_stack[__idx_t_e2_stack_0] = __cse_2
        t_e2d[i] = (0.5 * (1.0 + sign(__cse_2 - zero_val))) * __cse_2d + (0.5 * (1.0 + sign(zero_val - __cse_2))) * zero_vald
        t_e2[i] = max(__cse_2, zero_val)
    end
    for i = 1:n_e2_midpad
        t_e2padd[i] = zero_vald
        t_e2pad[i] = zero_val
    end
    for idx = 1:c2 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        yi = (ci - 1) * hp2 * wp2 + ((i + pad) - 1) * wp2 + (j + pad)
        t_e2padd[yi] = t_e2d[idx]
        t_e2pad[yi] = t_e2[idx]
    end
    for idx = 1:c2 * hw2
        idxm1 = idx - 1
        co = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        sd = 0.0
        s = 0.0
        for i_k = 1:c2 * khkw
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp2 * wp2 + (row - 1) * wp2 + col
            wi = (((co - 1) * c2 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            __cse_29 = w_e2b[wi]
            __cse_30 = t_e2pad[xi]
            sd = sd + (__cse_29 * t_e2padd[xi] + __cse_30 * w_e2bd[wi])
            s = s + __cse_30 * __cse_29
        end
        skip2d[idx] = sd + b_e2bd[co]
        skip2[idx] = s + b_e2b[co]
    end
    for i = 1:n_e2_out
        __idx_skip2_stack_0 = (i - 1) + 1
        __cse_3d = skip2d[i]
        __cse_3 = skip2[i]
        skip2_stack_d[__idx_skip2_stack_0] = __cse_3d
        skip2_stack[__idx_skip2_stack_0] = __cse_3
        skip2d[i] = (0.5 * (1.0 + sign(__cse_3 - zero_val))) * __cse_3d + (0.5 * (1.0 + sign(zero_val - __cse_3))) * zero_vald
        skip2[i] = max(__cse_3, zero_val)
    end
    for idx = 1:c2 * hw4
        idxm1 = idx - 1
        ci = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        oi = div(rem, w4) + 1
        oj = mod(rem, w4) + 1
        i0 = 2oi - 1
        j0 = 2oj - 1
        a11d = skip2d[(ci - 1) * hw2 + (i0 - 1) * w2 + j0]
        a11 = skip2[(ci - 1) * hw2 + (i0 - 1) * w2 + j0]
        a12d = skip2d[(ci - 1) * hw2 + (i0 - 1) * w2 + j0 + 1]
        a12 = skip2[(ci - 1) * hw2 + (i0 - 1) * w2 + j0 + 1]
        a21d = skip2d[(ci - 1) * hw2 + i0 * w2 + j0]
        a21 = skip2[(ci - 1) * hw2 + i0 * w2 + j0]
        a22d = skip2d[(ci - 1) * hw2 + i0 * w2 + j0 + 1]
        a22 = skip2[(ci - 1) * hw2 + i0 * w2 + j0 + 1]
        m1d = (0.5 * (1.0 + sign(a11 - a12))) * a11d + (0.5 * (1.0 + sign(a12 - a11))) * a12d
        m1 = max(a11, a12)
        m2d = (0.5 * (1.0 + sign(a21 - a22))) * a21d + (0.5 * (1.0 + sign(a22 - a21))) * a22d
        m2 = max(a21, a22)
        p2d[idx] = (0.5 * (1.0 + sign(m1 - m2))) * m1d + (0.5 * (1.0 + sign(m2 - m1))) * m2d
        p2[idx] = max(m1, m2)
    end
    for i = 1:n_p2pad
        p2padd[i] = zero_vald
        p2pad[i] = zero_val
    end
    for idx = 1:c2 * hw4
        idxm1 = idx - 1
        ci = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        i = div(rem, w4) + 1
        j = mod(rem, w4) + 1
        yi = (ci - 1) * hp4 * wp4 + ((i + pad) - 1) * wp4 + (j + pad)
        p2padd[yi] = p2d[idx]
        p2pad[yi] = p2[idx]
    end
    for idx = 1:c3 * hw4
        idxm1 = idx - 1
        co = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        i = div(rem, w4) + 1
        j = mod(rem, w4) + 1
        sd = 0.0
        s = 0.0
        for i_k = 1:c2 * khkw
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp4 * wp4 + (row - 1) * wp4 + col
            wi = (((co - 1) * c2 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            __cse_31 = w_ba[wi]
            __cse_32 = p2pad[xi]
            sd = sd + (__cse_31 * p2padd[xi] + __cse_32 * w_bad[wi])
            s = s + __cse_32 * __cse_31
        end
        t_bd[idx] = sd + b_bad[co]
        t_b[idx] = s + b_ba[co]
    end
    for i = 1:n_b_mid
        __idx_t_b_stack_0 = (i - 1) + 1
        __cse_4d = t_bd[i]
        __cse_4 = t_b[i]
        t_b_stack_d[__idx_t_b_stack_0] = __cse_4d
        t_b_stack[__idx_t_b_stack_0] = __cse_4
        t_bd[i] = (0.5 * (1.0 + sign(__cse_4 - zero_val))) * __cse_4d + (0.5 * (1.0 + sign(zero_val - __cse_4))) * zero_vald
        t_b[i] = max(__cse_4, zero_val)
    end
    for i = 1:n_b_midpad
        t_bpadd[i] = zero_vald
        t_bpad[i] = zero_val
    end
    for idx = 1:c3 * hw4
        idxm1 = idx - 1
        ci = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        i = div(rem, w4) + 1
        j = mod(rem, w4) + 1
        yi = (ci - 1) * hp4 * wp4 + ((i + pad) - 1) * wp4 + (j + pad)
        t_bpadd[yi] = t_bd[idx]
        t_bpad[yi] = t_b[idx]
    end
    for idx = 1:c3 * hw4
        idxm1 = idx - 1
        co = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        i = div(rem, w4) + 1
        j = mod(rem, w4) + 1
        sd = 0.0
        s = 0.0
        for i_k = 1:c3 * khkw
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp4 * wp4 + (row - 1) * wp4 + col
            wi = (((co - 1) * c3 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            __cse_33 = w_bb[wi]
            __cse_34 = t_bpad[xi]
            sd = sd + (__cse_33 * t_bpadd[xi] + __cse_34 * w_bbd[wi])
            s = s + __cse_34 * __cse_33
        end
        bottd[idx] = sd + b_bbd[co]
        bott[idx] = s + b_bb[co]
    end
    for i = 1:n_b_out
        __idx_bott_stack_0 = (i - 1) + 1
        __cse_5d = bottd[i]
        __cse_5 = bott[i]
        bott_stack_d[__idx_bott_stack_0] = __cse_5d
        bott_stack[__idx_bott_stack_0] = __cse_5
        bottd[i] = (0.5 * (1.0 + sign(__cse_5 - zero_val))) * __cse_5d + (0.5 * (1.0 + sign(zero_val - __cse_5))) * zero_vald
        bott[i] = max(__cse_5, zero_val)
    end
    for idx = 1:c3 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        oi = div(rem, w2) + 1
        oj = mod(rem, w2) + 1
        oim1 = oi - 1
        ojm1 = oj - 1
        i = div(oim1, scale) + 1
        j = div(ojm1, scale) + 1
        xi = (ci - 1) * hw4 + (i - 1) * w4 + j
        u2d[idx] = bottd[xi]
        u2[idx] = bott[xi]
    end
    for idx = 1:c3 * hw2
        cat2d[idx] = u2d[idx]
        cat2[idx] = u2[idx]
    end
    for idx = 1:c2 * hw2
        cat2d[c3 * hw2 + idx] = skip2d[idx]
        cat2[c3 * hw2 + idx] = skip2[idx]
    end
    for i = 1:n_cat2pad
        cat2padd[i] = zero_vald
        cat2pad[i] = zero_val
    end
    for idx = 1:c32 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        yi = (ci - 1) * hp2 * wp2 + ((i + pad) - 1) * wp2 + (j + pad)
        cat2padd[yi] = cat2d[idx]
        cat2pad[yi] = cat2[idx]
    end
    for idx = 1:c2 * hw2
        idxm1 = idx - 1
        co = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        sd = 0.0
        s = 0.0
        for i_k = 1:c32 * khkw
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp2 * wp2 + (row - 1) * wp2 + col
            wi = (((co - 1) * c32 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            __cse_35 = w_d2a[wi]
            __cse_36 = cat2pad[xi]
            sd = sd + (__cse_35 * cat2padd[xi] + __cse_36 * w_d2ad[wi])
            s = s + __cse_36 * __cse_35
        end
        t_d2d[idx] = sd + b_d2ad[co]
        t_d2[idx] = s + b_d2a[co]
    end
    for i = 1:n_d2_mid
        __idx_t_d2_stack_0 = (i - 1) + 1
        __cse_6d = t_d2d[i]
        __cse_6 = t_d2[i]
        t_d2_stack_d[__idx_t_d2_stack_0] = __cse_6d
        t_d2_stack[__idx_t_d2_stack_0] = __cse_6
        t_d2d[i] = (0.5 * (1.0 + sign(__cse_6 - zero_val))) * __cse_6d + (0.5 * (1.0 + sign(zero_val - __cse_6))) * zero_vald
        t_d2[i] = max(__cse_6, zero_val)
    end
    for i = 1:n_d2_midpad
        t_d2padd[i] = zero_vald
        t_d2pad[i] = zero_val
    end
    for idx = 1:c2 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        yi = (ci - 1) * hp2 * wp2 + ((i + pad) - 1) * wp2 + (j + pad)
        t_d2padd[yi] = t_d2d[idx]
        t_d2pad[yi] = t_d2[idx]
    end
    for idx = 1:c2 * hw2
        idxm1 = idx - 1
        co = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        sd = 0.0
        s = 0.0
        for i_k = 1:c2 * khkw
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp2 * wp2 + (row - 1) * wp2 + col
            wi = (((co - 1) * c2 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            __cse_37 = w_d2b[wi]
            __cse_38 = t_d2pad[xi]
            sd = sd + (__cse_37 * t_d2padd[xi] + __cse_38 * w_d2bd[wi])
            s = s + __cse_38 * __cse_37
        end
        dec2outd[idx] = sd + b_d2bd[co]
        dec2out[idx] = s + b_d2b[co]
    end
    for i = 1:n_d2_out
        __idx_dec2out_stack_0 = (i - 1) + 1
        __cse_7d = dec2outd[i]
        __cse_7 = dec2out[i]
        dec2out_stack_d[__idx_dec2out_stack_0] = __cse_7d
        dec2out_stack[__idx_dec2out_stack_0] = __cse_7
        dec2outd[i] = (0.5 * (1.0 + sign(__cse_7 - zero_val))) * __cse_7d + (0.5 * (1.0 + sign(zero_val - __cse_7))) * zero_vald
        dec2out[i] = max(__cse_7, zero_val)
    end
    for idx = 1:c2 * hw
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        oi = div(rem, w) + 1
        oj = mod(rem, w) + 1
        oim1 = oi - 1
        ojm1 = oj - 1
        i = div(oim1, scale) + 1
        j = div(ojm1, scale) + 1
        xi = (ci - 1) * hw2 + (i - 1) * w2 + j
        u1d[idx] = dec2outd[xi]
        u1[idx] = dec2out[xi]
    end
    for idx = 1:c2 * hw
        cat1d[idx] = u1d[idx]
        cat1[idx] = u1[idx]
    end
    for idx = 1:c1 * hw
        cat1d[c2 * hw + idx] = skip1d[idx]
        cat1[c2 * hw + idx] = skip1[idx]
    end
    for i = 1:n_cat1pad
        cat1padd[i] = zero_vald
        cat1pad[i] = zero_val
    end
    for idx = 1:c21 * hw
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        yi = (ci - 1) * hp1 * wp1 + ((i + pad) - 1) * wp1 + (j + pad)
        cat1padd[yi] = cat1d[idx]
        cat1pad[yi] = cat1[idx]
    end
    for idx = 1:c1 * hw
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        sd = 0.0
        s = 0.0
        for i_k = 1:c21 * khkw
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp1 * wp1 + (row - 1) * wp1 + col
            wi = (((co - 1) * c21 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            __cse_39 = w_d1a[wi]
            __cse_40 = cat1pad[xi]
            sd = sd + (__cse_39 * cat1padd[xi] + __cse_40 * w_d1ad[wi])
            s = s + __cse_40 * __cse_39
        end
        t_d1d[idx] = sd + b_d1ad[co]
        t_d1[idx] = s + b_d1a[co]
    end
    for i = 1:n_d1_mid
        __idx_t_d1_stack_0 = (i - 1) + 1
        __cse_8d = t_d1d[i]
        __cse_8 = t_d1[i]
        t_d1_stack_d[__idx_t_d1_stack_0] = __cse_8d
        t_d1_stack[__idx_t_d1_stack_0] = __cse_8
        t_d1d[i] = (0.5 * (1.0 + sign(__cse_8 - zero_val))) * __cse_8d + (0.5 * (1.0 + sign(zero_val - __cse_8))) * zero_vald
        t_d1[i] = max(__cse_8, zero_val)
    end
    for i = 1:n_d1_midpad
        t_d1padd[i] = zero_vald
        t_d1pad[i] = zero_val
    end
    for idx = 1:c1 * hw
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        yi = (ci - 1) * hp1 * wp1 + ((i + pad) - 1) * wp1 + (j + pad)
        t_d1padd[yi] = t_d1d[idx]
        t_d1pad[yi] = t_d1[idx]
    end
    for idx = 1:c1 * hw
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        sd = 0.0
        s = 0.0
        for i_k = 1:c1 * khkw
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp1 * wp1 + (row - 1) * wp1 + col
            wi = (((co - 1) * c1 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            __cse_41 = w_d1b[wi]
            __cse_42 = t_d1pad[xi]
            sd = sd + (__cse_41 * t_d1padd[xi] + __cse_42 * w_d1bd[wi])
            s = s + __cse_42 * __cse_41
        end
        dec1outd[idx] = sd + b_d1bd[co]
        dec1out[idx] = s + b_d1b[co]
    end
    for i = 1:n_d1_out
        __idx_dec1out_stack_0 = (i - 1) + 1
        __cse_9d = dec1outd[i]
        __cse_9 = dec1out[i]
        dec1out_stack_d[__idx_dec1out_stack_0] = __cse_9d
        dec1out_stack[__idx_dec1out_stack_0] = __cse_9
        dec1outd[i] = (0.5 * (1.0 + sign(__cse_9 - zero_val))) * __cse_9d + (0.5 * (1.0 + sign(zero_val - __cse_9))) * zero_vald
        dec1out[i] = max(__cse_9, zero_val)
    end
    for idx = 1:c_out * hw
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        sd = 0.0
        s = 0.0
        for i_k = 1:c1 * khkw_out
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw_out) + 1
            rem2 = mod(kseqm1, khkw_out)
            ki = div(rem2, kw_out) + 1
            kj = mod(rem2, kw_out) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hw + (row - 1) * w + col
            wi = (((co - 1) * c1 + (ci - 1)) * kh_out + (ki - 1)) * kw_out + kj
            __cse_43 = w_out[wi]
            __cse_44 = dec1out[xi]
            sd = sd + (__cse_43 * dec1outd[xi] + __cse_44 * w_outd[wi])
            s = s + __cse_44 * __cse_43
        end
        yd[idx] = sd + b_outd[co]
        y[idx] = s + b_out[co]
    end
    two = 2
    four = 4
    h2 = div(h, two)
    w2 = div(w, two)
    h4 = div(h, four)
    w4 = div(w, four)
    hp1 = h + 2
    wp1 = w + 2
    hp2 = h2 + 2
    wp2 = w2 + 2
    hp4 = h4 + 2
    wp4 = w4 + 2
    pad = 1
    kh = 3
    kw = 3
    khkw = kh * kw
    kh_out = 1
    kw_out = 1
    khkw_out = kh_out * kw_out
    scale = 2
    c32 = c3 + c2
    c21 = c2 + c1
    hw = h * w
    hw2 = h2 * w2
    hw4 = h4 * w4
    n_xpad0 = c_in * hp1 * wp1
    n_e1_mid = c1 * hw
    n_e1_midpad = c1 * hp1 * wp1
    n_e1_out = c1 * hw
    n_p1pad = c1 * hp2 * wp2
    n_e2_mid = c2 * hw2
    n_e2_midpad = c2 * hp2 * wp2
    n_e2_out = c2 * hw2
    n_p2pad = c2 * hp4 * wp4
    n_b_mid = c3 * hw4
    n_b_midpad = c3 * hp4 * wp4
    n_b_out = c3 * hw4
    n_cat2pad = c32 * hp2 * wp2
    n_d2_mid = c2 * hw2
    n_d2_midpad = c2 * hp2 * wp2
    n_d2_out = c2 * hw2
    n_cat1pad = c21 * hp1 * wp1
    n_d1_mid = c1 * hw
    n_d1_midpad = c1 * hp1 * wp1
    n_d1_out = c1 * hw
    for idx = c_out * hw:-1:1
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        __cse_10d = ybd[idx]
        __cse_10 = yb[idx]
        sbd = sbd + __cse_10d
        sb = sb + __cse_10
        b_outbd[co] = b_outbd[co] + __cse_10d
        b_outb[co] = b_outb[co] + __cse_10
        ybd[idx] = 0.0
        yb[idx] = 0.0
        for i_k = c1 * khkw_out:-1:1
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw_out) + 1
            rem2 = mod(kseqm1, khkw_out)
            ki = div(rem2, kw_out) + 1
            kj = mod(rem2, kw_out) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hw + (row - 1) * w + col
            wi = (((co - 1) * c1 + (ci - 1)) * kh_out + (ki - 1)) * kw_out + kj
            __cse_45 = w_out[wi]
            dec1outbd[xi] = dec1outbd[xi] + (sb * w_outd[wi] + __cse_45 * sbd)
            dec1outb[xi] = dec1outb[xi] + __cse_45 * sb
            __cse_46 = dec1out[xi]
            w_outbd[wi] = w_outbd[wi] + (sb * dec1outd[xi] + __cse_46 * sbd)
            w_outb[wi] = w_outb[wi] + __cse_46 * sb
        end
        sbd = 0.0
        sb = 0.0
    end
    for i = n_d1_out:-1:1
        __idx_dec1out_stack_0 = (i - 1) + 1
        dec1outd[i] = dec1out_stack_d[__idx_dec1out_stack_0]
        dec1out[i] = dec1out_stack[__idx_dec1out_stack_0]
        __cse_47 = 0.5 * (1.0 + sign(dec1out[i] - zero_val))
        dec1outbd[i] = __cse_47 * dec1outbd[i]
        dec1outb[i] = __cse_47 * dec1outb[i]
    end
    for idx = c1 * hw:-1:1
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        __cse_11d = dec1outbd[idx]
        __cse_11 = dec1outb[idx]
        sbd = sbd + __cse_11d
        sb = sb + __cse_11
        b_d1bbd[co] = b_d1bbd[co] + __cse_11d
        b_d1bb[co] = b_d1bb[co] + __cse_11
        dec1outbd[idx] = 0.0
        dec1outb[idx] = 0.0
        for i_k = c1 * khkw:-1:1
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp1 * wp1 + (row - 1) * wp1 + col
            wi = (((co - 1) * c1 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            __cse_48 = w_d1b[wi]
            t_d1padbd[xi] = t_d1padbd[xi] + (sb * w_d1bd[wi] + __cse_48 * sbd)
            t_d1padb[xi] = t_d1padb[xi] + __cse_48 * sb
            __cse_49 = t_d1pad[xi]
            w_d1bbd[wi] = w_d1bbd[wi] + (sb * t_d1padd[xi] + __cse_49 * sbd)
            w_d1bb[wi] = w_d1bb[wi] + __cse_49 * sb
        end
        sbd = 0.0
        sb = 0.0
    end
    for idx = c1 * hw:-1:1
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        yi = (ci - 1) * hp1 * wp1 + ((i + pad) - 1) * wp1 + (j + pad)
        t_d1bd[idx] = t_d1bd[idx] + t_d1padbd[yi]
        t_d1b[idx] = t_d1b[idx] + t_d1padb[yi]
        t_d1padbd[yi] = 0.0
        t_d1padb[yi] = 0.0
    end
    for i = n_d1_midpad:-1:1
        t_d1padbd[i] = 0.0
        t_d1padb[i] = 0.0
    end
    for i = n_d1_mid:-1:1
        __idx_t_d1_stack_0 = (i - 1) + 1
        t_d1d[i] = t_d1_stack_d[__idx_t_d1_stack_0]
        t_d1[i] = t_d1_stack[__idx_t_d1_stack_0]
        __cse_50 = 0.5 * (1.0 + sign(t_d1[i] - zero_val))
        t_d1bd[i] = __cse_50 * t_d1bd[i]
        t_d1b[i] = __cse_50 * t_d1b[i]
    end
    for idx = c1 * hw:-1:1
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        __cse_12d = t_d1bd[idx]
        __cse_12 = t_d1b[idx]
        sbd = sbd + __cse_12d
        sb = sb + __cse_12
        b_d1abd[co] = b_d1abd[co] + __cse_12d
        b_d1ab[co] = b_d1ab[co] + __cse_12
        t_d1bd[idx] = 0.0
        t_d1b[idx] = 0.0
        for i_k = c21 * khkw:-1:1
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp1 * wp1 + (row - 1) * wp1 + col
            wi = (((co - 1) * c21 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            __cse_51 = w_d1a[wi]
            cat1padbd[xi] = cat1padbd[xi] + (sb * w_d1ad[wi] + __cse_51 * sbd)
            cat1padb[xi] = cat1padb[xi] + __cse_51 * sb
            __cse_52 = cat1pad[xi]
            w_d1abd[wi] = w_d1abd[wi] + (sb * cat1padd[xi] + __cse_52 * sbd)
            w_d1ab[wi] = w_d1ab[wi] + __cse_52 * sb
        end
        sbd = 0.0
        sb = 0.0
    end
    for idx = c21 * hw:-1:1
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        yi = (ci - 1) * hp1 * wp1 + ((i + pad) - 1) * wp1 + (j + pad)
        cat1bd[idx] = cat1bd[idx] + cat1padbd[yi]
        cat1b[idx] = cat1b[idx] + cat1padb[yi]
        cat1padbd[yi] = 0.0
        cat1padb[yi] = 0.0
    end
    for i = n_cat1pad:-1:1
        cat1padbd[i] = 0.0
        cat1padb[i] = 0.0
    end
    for idx = c1 * hw:-1:1
        skip1bd[idx] = skip1bd[idx] + cat1bd[c2 * hw + idx]
        skip1b[idx] = skip1b[idx] + cat1b[c2 * hw + idx]
        cat1bd[c2 * hw + idx] = 0.0
        cat1b[c2 * hw + idx] = 0.0
    end
    for idx = c2 * hw:-1:1
        u1bd[idx] = u1bd[idx] + cat1bd[idx]
        u1b[idx] = u1b[idx] + cat1b[idx]
        cat1bd[idx] = 0.0
        cat1b[idx] = 0.0
    end
    for idx = c2 * hw:-1:1
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        oi = div(rem, w) + 1
        oj = mod(rem, w) + 1
        oim1 = oi - 1
        ojm1 = oj - 1
        i = div(oim1, scale) + 1
        j = div(ojm1, scale) + 1
        xi = (ci - 1) * hw2 + (i - 1) * w2 + j
        dec2outbd[xi] = dec2outbd[xi] + u1bd[idx]
        dec2outb[xi] = dec2outb[xi] + u1b[idx]
        u1bd[idx] = 0.0
        u1b[idx] = 0.0
    end
    for i = n_d2_out:-1:1
        __idx_dec2out_stack_0 = (i - 1) + 1
        dec2outd[i] = dec2out_stack_d[__idx_dec2out_stack_0]
        dec2out[i] = dec2out_stack[__idx_dec2out_stack_0]
        __cse_53 = 0.5 * (1.0 + sign(dec2out[i] - zero_val))
        dec2outbd[i] = __cse_53 * dec2outbd[i]
        dec2outb[i] = __cse_53 * dec2outb[i]
    end
    for idx = c2 * hw2:-1:1
        idxm1 = idx - 1
        co = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        __cse_13d = dec2outbd[idx]
        __cse_13 = dec2outb[idx]
        sbd = sbd + __cse_13d
        sb = sb + __cse_13
        b_d2bbd[co] = b_d2bbd[co] + __cse_13d
        b_d2bb[co] = b_d2bb[co] + __cse_13
        dec2outbd[idx] = 0.0
        dec2outb[idx] = 0.0
        for i_k = c2 * khkw:-1:1
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp2 * wp2 + (row - 1) * wp2 + col
            wi = (((co - 1) * c2 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            __cse_54 = w_d2b[wi]
            t_d2padbd[xi] = t_d2padbd[xi] + (sb * w_d2bd[wi] + __cse_54 * sbd)
            t_d2padb[xi] = t_d2padb[xi] + __cse_54 * sb
            __cse_55 = t_d2pad[xi]
            w_d2bbd[wi] = w_d2bbd[wi] + (sb * t_d2padd[xi] + __cse_55 * sbd)
            w_d2bb[wi] = w_d2bb[wi] + __cse_55 * sb
        end
        sbd = 0.0
        sb = 0.0
    end
    for idx = c2 * hw2:-1:1
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        yi = (ci - 1) * hp2 * wp2 + ((i + pad) - 1) * wp2 + (j + pad)
        t_d2bd[idx] = t_d2bd[idx] + t_d2padbd[yi]
        t_d2b[idx] = t_d2b[idx] + t_d2padb[yi]
        t_d2padbd[yi] = 0.0
        t_d2padb[yi] = 0.0
    end
    for i = n_d2_midpad:-1:1
        t_d2padbd[i] = 0.0
        t_d2padb[i] = 0.0
    end
    for i = n_d2_mid:-1:1
        __idx_t_d2_stack_0 = (i - 1) + 1
        t_d2d[i] = t_d2_stack_d[__idx_t_d2_stack_0]
        t_d2[i] = t_d2_stack[__idx_t_d2_stack_0]
        __cse_56 = 0.5 * (1.0 + sign(t_d2[i] - zero_val))
        t_d2bd[i] = __cse_56 * t_d2bd[i]
        t_d2b[i] = __cse_56 * t_d2b[i]
    end
    for idx = c2 * hw2:-1:1
        idxm1 = idx - 1
        co = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        __cse_14d = t_d2bd[idx]
        __cse_14 = t_d2b[idx]
        sbd = sbd + __cse_14d
        sb = sb + __cse_14
        b_d2abd[co] = b_d2abd[co] + __cse_14d
        b_d2ab[co] = b_d2ab[co] + __cse_14
        t_d2bd[idx] = 0.0
        t_d2b[idx] = 0.0
        for i_k = c32 * khkw:-1:1
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp2 * wp2 + (row - 1) * wp2 + col
            wi = (((co - 1) * c32 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            __cse_57 = w_d2a[wi]
            cat2padbd[xi] = cat2padbd[xi] + (sb * w_d2ad[wi] + __cse_57 * sbd)
            cat2padb[xi] = cat2padb[xi] + __cse_57 * sb
            __cse_58 = cat2pad[xi]
            w_d2abd[wi] = w_d2abd[wi] + (sb * cat2padd[xi] + __cse_58 * sbd)
            w_d2ab[wi] = w_d2ab[wi] + __cse_58 * sb
        end
        sbd = 0.0
        sb = 0.0
    end
    for idx = c32 * hw2:-1:1
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        yi = (ci - 1) * hp2 * wp2 + ((i + pad) - 1) * wp2 + (j + pad)
        cat2bd[idx] = cat2bd[idx] + cat2padbd[yi]
        cat2b[idx] = cat2b[idx] + cat2padb[yi]
        cat2padbd[yi] = 0.0
        cat2padb[yi] = 0.0
    end
    for i = n_cat2pad:-1:1
        cat2padbd[i] = 0.0
        cat2padb[i] = 0.0
    end
    for idx = c2 * hw2:-1:1
        skip2bd[idx] = skip2bd[idx] + cat2bd[c3 * hw2 + idx]
        skip2b[idx] = skip2b[idx] + cat2b[c3 * hw2 + idx]
        cat2bd[c3 * hw2 + idx] = 0.0
        cat2b[c3 * hw2 + idx] = 0.0
    end
    for idx = c3 * hw2:-1:1
        u2bd[idx] = u2bd[idx] + cat2bd[idx]
        u2b[idx] = u2b[idx] + cat2b[idx]
        cat2bd[idx] = 0.0
        cat2b[idx] = 0.0
    end
    for idx = c3 * hw2:-1:1
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        oi = div(rem, w2) + 1
        oj = mod(rem, w2) + 1
        oim1 = oi - 1
        ojm1 = oj - 1
        i = div(oim1, scale) + 1
        j = div(ojm1, scale) + 1
        xi = (ci - 1) * hw4 + (i - 1) * w4 + j
        bottbd[xi] = bottbd[xi] + u2bd[idx]
        bottb[xi] = bottb[xi] + u2b[idx]
        u2bd[idx] = 0.0
        u2b[idx] = 0.0
    end
    for i = n_b_out:-1:1
        __idx_bott_stack_0 = (i - 1) + 1
        bottd[i] = bott_stack_d[__idx_bott_stack_0]
        bott[i] = bott_stack[__idx_bott_stack_0]
        __cse_59 = 0.5 * (1.0 + sign(bott[i] - zero_val))
        bottbd[i] = __cse_59 * bottbd[i]
        bottb[i] = __cse_59 * bottb[i]
    end
    for idx = c3 * hw4:-1:1
        idxm1 = idx - 1
        co = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        i = div(rem, w4) + 1
        j = mod(rem, w4) + 1
        __cse_15d = bottbd[idx]
        __cse_15 = bottb[idx]
        sbd = sbd + __cse_15d
        sb = sb + __cse_15
        b_bbbd[co] = b_bbbd[co] + __cse_15d
        b_bbb[co] = b_bbb[co] + __cse_15
        bottbd[idx] = 0.0
        bottb[idx] = 0.0
        for i_k = c3 * khkw:-1:1
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp4 * wp4 + (row - 1) * wp4 + col
            wi = (((co - 1) * c3 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            __cse_60 = w_bb[wi]
            t_bpadbd[xi] = t_bpadbd[xi] + (sb * w_bbd[wi] + __cse_60 * sbd)
            t_bpadb[xi] = t_bpadb[xi] + __cse_60 * sb
            __cse_61 = t_bpad[xi]
            w_bbbd[wi] = w_bbbd[wi] + (sb * t_bpadd[xi] + __cse_61 * sbd)
            w_bbb[wi] = w_bbb[wi] + __cse_61 * sb
        end
        sbd = 0.0
        sb = 0.0
    end
    for idx = c3 * hw4:-1:1
        idxm1 = idx - 1
        ci = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        i = div(rem, w4) + 1
        j = mod(rem, w4) + 1
        yi = (ci - 1) * hp4 * wp4 + ((i + pad) - 1) * wp4 + (j + pad)
        t_bbd[idx] = t_bbd[idx] + t_bpadbd[yi]
        t_bb[idx] = t_bb[idx] + t_bpadb[yi]
        t_bpadbd[yi] = 0.0
        t_bpadb[yi] = 0.0
    end
    for i = n_b_midpad:-1:1
        t_bpadbd[i] = 0.0
        t_bpadb[i] = 0.0
    end
    for i = n_b_mid:-1:1
        __idx_t_b_stack_0 = (i - 1) + 1
        t_bd[i] = t_b_stack_d[__idx_t_b_stack_0]
        t_b[i] = t_b_stack[__idx_t_b_stack_0]
        __cse_62 = 0.5 * (1.0 + sign(t_b[i] - zero_val))
        t_bbd[i] = __cse_62 * t_bbd[i]
        t_bb[i] = __cse_62 * t_bb[i]
    end
    for idx = c3 * hw4:-1:1
        idxm1 = idx - 1
        co = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        i = div(rem, w4) + 1
        j = mod(rem, w4) + 1
        __cse_16d = t_bbd[idx]
        __cse_16 = t_bb[idx]
        sbd = sbd + __cse_16d
        sb = sb + __cse_16
        b_babd[co] = b_babd[co] + __cse_16d
        b_bab[co] = b_bab[co] + __cse_16
        t_bbd[idx] = 0.0
        t_bb[idx] = 0.0
        for i_k = c2 * khkw:-1:1
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp4 * wp4 + (row - 1) * wp4 + col
            wi = (((co - 1) * c2 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            __cse_63 = w_ba[wi]
            p2padbd[xi] = p2padbd[xi] + (sb * w_bad[wi] + __cse_63 * sbd)
            p2padb[xi] = p2padb[xi] + __cse_63 * sb
            __cse_64 = p2pad[xi]
            w_babd[wi] = w_babd[wi] + (sb * p2padd[xi] + __cse_64 * sbd)
            w_bab[wi] = w_bab[wi] + __cse_64 * sb
        end
        sbd = 0.0
        sb = 0.0
    end
    for idx = c2 * hw4:-1:1
        idxm1 = idx - 1
        ci = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        i = div(rem, w4) + 1
        j = mod(rem, w4) + 1
        yi = (ci - 1) * hp4 * wp4 + ((i + pad) - 1) * wp4 + (j + pad)
        p2bd[idx] = p2bd[idx] + p2padbd[yi]
        p2b[idx] = p2b[idx] + p2padb[yi]
        p2padbd[yi] = 0.0
        p2padb[yi] = 0.0
    end
    for i = n_p2pad:-1:1
        p2padbd[i] = 0.0
        p2padb[i] = 0.0
    end
    for idx = 1:c2 * hw4
        idxm1 = idx - 1
        ci = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        oi = div(rem, w4) + 1
        oj = mod(rem, w4) + 1
        i0 = 2oi - 1
        j0 = 2oj - 1
        a11d = skip2d[(ci - 1) * hw2 + (i0 - 1) * w2 + j0]
        a11 = skip2[(ci - 1) * hw2 + (i0 - 1) * w2 + j0]
        a12d = skip2d[(ci - 1) * hw2 + (i0 - 1) * w2 + j0 + 1]
        a12 = skip2[(ci - 1) * hw2 + (i0 - 1) * w2 + j0 + 1]
        a21d = skip2d[(ci - 1) * hw2 + i0 * w2 + j0]
        a21 = skip2[(ci - 1) * hw2 + i0 * w2 + j0]
        a22d = skip2d[(ci - 1) * hw2 + i0 * w2 + j0 + 1]
        a22 = skip2[(ci - 1) * hw2 + i0 * w2 + j0 + 1]
        __cse_65 = 0.5 * (1.0 + sign(a11 - a12))
        __cse_66 = 0.5 * (1.0 + sign(a12 - a11))
        m1d = __cse_65 * a11d + __cse_66 * a12d
        m1 = max(a11, a12)
        __cse_67 = 0.5 * (1.0 + sign(a21 - a22))
        __cse_68 = 0.5 * (1.0 + sign(a22 - a21))
        m2d = __cse_67 * a21d + __cse_68 * a22d
        m2 = max(a21, a22)
        idxm1 = idx - 1
        ci = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        oi = div(rem, w4) + 1
        oj = mod(rem, w4) + 1
        i0 = 2oi - 1
        j0 = 2oj - 1
        __cse_17d = p2bd[idx]
        __cse_17 = p2b[idx]
        __cse_69 = 0.5 * (1.0 + sign(m1 - m2))
        m1bd = m1bd + __cse_69 * __cse_17d
        m1b = m1b + __cse_69 * __cse_17
        __cse_70 = 0.5 * (1.0 + sign(m2 - m1))
        m2bd = m2bd + __cse_70 * __cse_17d
        m2b = m2b + __cse_70 * __cse_17
        p2bd[idx] = 0.0
        p2b[idx] = 0.0
        a21bd = a21bd + __cse_67 * m2bd
        a21b = a21b + __cse_67 * m2b
        a22bd = a22bd + __cse_68 * m2bd
        a22b = a22b + __cse_68 * m2b
        m2bd = 0.0
        m2b = 0.0
        a11bd = a11bd + __cse_65 * m1bd
        a11b = a11b + __cse_65 * m1b
        a12bd = a12bd + __cse_66 * m1bd
        a12b = a12b + __cse_66 * m1b
        m1bd = 0.0
        m1b = 0.0
        skip2bd[(ci - 1) * hw2 + i0 * w2 + j0 + 1] = skip2bd[(ci - 1) * hw2 + i0 * w2 + j0 + 1] + a22bd
        skip2b[(ci - 1) * hw2 + i0 * w2 + j0 + 1] = skip2b[(ci - 1) * hw2 + i0 * w2 + j0 + 1] + a22b
        a22bd = 0.0
        a22b = 0.0
        skip2bd[(ci - 1) * hw2 + i0 * w2 + j0] = skip2bd[(ci - 1) * hw2 + i0 * w2 + j0] + a21bd
        skip2b[(ci - 1) * hw2 + i0 * w2 + j0] = skip2b[(ci - 1) * hw2 + i0 * w2 + j0] + a21b
        a21bd = 0.0
        a21b = 0.0
        skip2bd[(ci - 1) * hw2 + (i0 - 1) * w2 + j0 + 1] = skip2bd[(ci - 1) * hw2 + (i0 - 1) * w2 + j0 + 1] + a12bd
        skip2b[(ci - 1) * hw2 + (i0 - 1) * w2 + j0 + 1] = skip2b[(ci - 1) * hw2 + (i0 - 1) * w2 + j0 + 1] + a12b
        a12bd = 0.0
        a12b = 0.0
        skip2bd[(ci - 1) * hw2 + (i0 - 1) * w2 + j0] = skip2bd[(ci - 1) * hw2 + (i0 - 1) * w2 + j0] + a11bd
        skip2b[(ci - 1) * hw2 + (i0 - 1) * w2 + j0] = skip2b[(ci - 1) * hw2 + (i0 - 1) * w2 + j0] + a11b
        a11bd = 0.0
        a11b = 0.0
    end
    for i = n_e2_out:-1:1
        __idx_skip2_stack_0 = (i - 1) + 1
        skip2d[i] = skip2_stack_d[__idx_skip2_stack_0]
        skip2[i] = skip2_stack[__idx_skip2_stack_0]
        __cse_71 = 0.5 * (1.0 + sign(skip2[i] - zero_val))
        skip2bd[i] = __cse_71 * skip2bd[i]
        skip2b[i] = __cse_71 * skip2b[i]
    end
    for idx = c2 * hw2:-1:1
        idxm1 = idx - 1
        co = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        __cse_18d = skip2bd[idx]
        __cse_18 = skip2b[idx]
        sbd = sbd + __cse_18d
        sb = sb + __cse_18
        b_e2bbd[co] = b_e2bbd[co] + __cse_18d
        b_e2bb[co] = b_e2bb[co] + __cse_18
        skip2bd[idx] = 0.0
        skip2b[idx] = 0.0
        for i_k = c2 * khkw:-1:1
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp2 * wp2 + (row - 1) * wp2 + col
            wi = (((co - 1) * c2 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            __cse_72 = w_e2b[wi]
            t_e2padbd[xi] = t_e2padbd[xi] + (sb * w_e2bd[wi] + __cse_72 * sbd)
            t_e2padb[xi] = t_e2padb[xi] + __cse_72 * sb
            __cse_73 = t_e2pad[xi]
            w_e2bbd[wi] = w_e2bbd[wi] + (sb * t_e2padd[xi] + __cse_73 * sbd)
            w_e2bb[wi] = w_e2bb[wi] + __cse_73 * sb
        end
        sbd = 0.0
        sb = 0.0
    end
    for idx = c2 * hw2:-1:1
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        yi = (ci - 1) * hp2 * wp2 + ((i + pad) - 1) * wp2 + (j + pad)
        t_e2bd[idx] = t_e2bd[idx] + t_e2padbd[yi]
        t_e2b[idx] = t_e2b[idx] + t_e2padb[yi]
        t_e2padbd[yi] = 0.0
        t_e2padb[yi] = 0.0
    end
    for i = n_e2_midpad:-1:1
        t_e2padbd[i] = 0.0
        t_e2padb[i] = 0.0
    end
    for i = n_e2_mid:-1:1
        __idx_t_e2_stack_0 = (i - 1) + 1
        t_e2d[i] = t_e2_stack_d[__idx_t_e2_stack_0]
        t_e2[i] = t_e2_stack[__idx_t_e2_stack_0]
        __cse_74 = 0.5 * (1.0 + sign(t_e2[i] - zero_val))
        t_e2bd[i] = __cse_74 * t_e2bd[i]
        t_e2b[i] = __cse_74 * t_e2b[i]
    end
    for idx = c2 * hw2:-1:1
        idxm1 = idx - 1
        co = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        __cse_19d = t_e2bd[idx]
        __cse_19 = t_e2b[idx]
        sbd = sbd + __cse_19d
        sb = sb + __cse_19
        b_e2abd[co] = b_e2abd[co] + __cse_19d
        b_e2ab[co] = b_e2ab[co] + __cse_19
        t_e2bd[idx] = 0.0
        t_e2b[idx] = 0.0
        for i_k = c1 * khkw:-1:1
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp2 * wp2 + (row - 1) * wp2 + col
            wi = (((co - 1) * c1 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            __cse_75 = w_e2a[wi]
            p1padbd[xi] = p1padbd[xi] + (sb * w_e2ad[wi] + __cse_75 * sbd)
            p1padb[xi] = p1padb[xi] + __cse_75 * sb
            __cse_76 = p1pad[xi]
            w_e2abd[wi] = w_e2abd[wi] + (sb * p1padd[xi] + __cse_76 * sbd)
            w_e2ab[wi] = w_e2ab[wi] + __cse_76 * sb
        end
        sbd = 0.0
        sb = 0.0
    end
    for idx = c1 * hw2:-1:1
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        yi = (ci - 1) * hp2 * wp2 + ((i + pad) - 1) * wp2 + (j + pad)
        p1bd[idx] = p1bd[idx] + p1padbd[yi]
        p1b[idx] = p1b[idx] + p1padb[yi]
        p1padbd[yi] = 0.0
        p1padb[yi] = 0.0
    end
    for i = n_p1pad:-1:1
        p1padbd[i] = 0.0
        p1padb[i] = 0.0
    end
    for idx = 1:c1 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        oi = div(rem, w2) + 1
        oj = mod(rem, w2) + 1
        i0 = 2oi - 1
        j0 = 2oj - 1
        a11d = skip1d[(ci - 1) * hw + (i0 - 1) * w + j0]
        a11 = skip1[(ci - 1) * hw + (i0 - 1) * w + j0]
        a12d = skip1d[(ci - 1) * hw + (i0 - 1) * w + j0 + 1]
        a12 = skip1[(ci - 1) * hw + (i0 - 1) * w + j0 + 1]
        a21d = skip1d[(ci - 1) * hw + i0 * w + j0]
        a21 = skip1[(ci - 1) * hw + i0 * w + j0]
        a22d = skip1d[(ci - 1) * hw + i0 * w + j0 + 1]
        a22 = skip1[(ci - 1) * hw + i0 * w + j0 + 1]
        __cse_77 = 0.5 * (1.0 + sign(a11 - a12))
        __cse_78 = 0.5 * (1.0 + sign(a12 - a11))
        m1d = __cse_77 * a11d + __cse_78 * a12d
        m1 = max(a11, a12)
        __cse_79 = 0.5 * (1.0 + sign(a21 - a22))
        __cse_80 = 0.5 * (1.0 + sign(a22 - a21))
        m2d = __cse_79 * a21d + __cse_80 * a22d
        m2 = max(a21, a22)
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        oi = div(rem, w2) + 1
        oj = mod(rem, w2) + 1
        i0 = 2oi - 1
        j0 = 2oj - 1
        __cse_20d = p1bd[idx]
        __cse_20 = p1b[idx]
        __cse_81 = 0.5 * (1.0 + sign(m1 - m2))
        m1bd = m1bd + __cse_81 * __cse_20d
        m1b = m1b + __cse_81 * __cse_20
        __cse_82 = 0.5 * (1.0 + sign(m2 - m1))
        m2bd = m2bd + __cse_82 * __cse_20d
        m2b = m2b + __cse_82 * __cse_20
        p1bd[idx] = 0.0
        p1b[idx] = 0.0
        a21bd = a21bd + __cse_79 * m2bd
        a21b = a21b + __cse_79 * m2b
        a22bd = a22bd + __cse_80 * m2bd
        a22b = a22b + __cse_80 * m2b
        m2bd = 0.0
        m2b = 0.0
        a11bd = a11bd + __cse_77 * m1bd
        a11b = a11b + __cse_77 * m1b
        a12bd = a12bd + __cse_78 * m1bd
        a12b = a12b + __cse_78 * m1b
        m1bd = 0.0
        m1b = 0.0
        skip1bd[(ci - 1) * hw + i0 * w + j0 + 1] = skip1bd[(ci - 1) * hw + i0 * w + j0 + 1] + a22bd
        skip1b[(ci - 1) * hw + i0 * w + j0 + 1] = skip1b[(ci - 1) * hw + i0 * w + j0 + 1] + a22b
        a22bd = 0.0
        a22b = 0.0
        skip1bd[(ci - 1) * hw + i0 * w + j0] = skip1bd[(ci - 1) * hw + i0 * w + j0] + a21bd
        skip1b[(ci - 1) * hw + i0 * w + j0] = skip1b[(ci - 1) * hw + i0 * w + j0] + a21b
        a21bd = 0.0
        a21b = 0.0
        skip1bd[(ci - 1) * hw + (i0 - 1) * w + j0 + 1] = skip1bd[(ci - 1) * hw + (i0 - 1) * w + j0 + 1] + a12bd
        skip1b[(ci - 1) * hw + (i0 - 1) * w + j0 + 1] = skip1b[(ci - 1) * hw + (i0 - 1) * w + j0 + 1] + a12b
        a12bd = 0.0
        a12b = 0.0
        skip1bd[(ci - 1) * hw + (i0 - 1) * w + j0] = skip1bd[(ci - 1) * hw + (i0 - 1) * w + j0] + a11bd
        skip1b[(ci - 1) * hw + (i0 - 1) * w + j0] = skip1b[(ci - 1) * hw + (i0 - 1) * w + j0] + a11b
        a11bd = 0.0
        a11b = 0.0
    end
    for i = n_e1_out:-1:1
        __idx_skip1_stack_0 = (i - 1) + 1
        skip1d[i] = skip1_stack_d[__idx_skip1_stack_0]
        skip1[i] = skip1_stack[__idx_skip1_stack_0]
        __cse_83 = 0.5 * (1.0 + sign(skip1[i] - zero_val))
        skip1bd[i] = __cse_83 * skip1bd[i]
        skip1b[i] = __cse_83 * skip1b[i]
    end
    for idx = c1 * hw:-1:1
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        __cse_21d = skip1bd[idx]
        __cse_21 = skip1b[idx]
        sbd = sbd + __cse_21d
        sb = sb + __cse_21
        b_e1bbd[co] = b_e1bbd[co] + __cse_21d
        b_e1bb[co] = b_e1bb[co] + __cse_21
        skip1bd[idx] = 0.0
        skip1b[idx] = 0.0
        for i_k = c1 * khkw:-1:1
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp1 * wp1 + (row - 1) * wp1 + col
            wi = (((co - 1) * c1 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            __cse_84 = w_e1b[wi]
            t_e1padbd[xi] = t_e1padbd[xi] + (sb * w_e1bd[wi] + __cse_84 * sbd)
            t_e1padb[xi] = t_e1padb[xi] + __cse_84 * sb
            __cse_85 = t_e1pad[xi]
            w_e1bbd[wi] = w_e1bbd[wi] + (sb * t_e1padd[xi] + __cse_85 * sbd)
            w_e1bb[wi] = w_e1bb[wi] + __cse_85 * sb
        end
        sbd = 0.0
        sb = 0.0
    end
    for idx = c1 * hw:-1:1
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        yi = (ci - 1) * hp1 * wp1 + ((i + pad) - 1) * wp1 + (j + pad)
        t_e1bd[idx] = t_e1bd[idx] + t_e1padbd[yi]
        t_e1b[idx] = t_e1b[idx] + t_e1padb[yi]
        t_e1padbd[yi] = 0.0
        t_e1padb[yi] = 0.0
    end
    for i = n_e1_midpad:-1:1
        t_e1padbd[i] = 0.0
        t_e1padb[i] = 0.0
    end
    for i = n_e1_mid:-1:1
        __idx_t_e1_stack_0 = (i - 1) + 1
        t_e1d[i] = t_e1_stack_d[__idx_t_e1_stack_0]
        t_e1[i] = t_e1_stack[__idx_t_e1_stack_0]
        __cse_86 = 0.5 * (1.0 + sign(t_e1[i] - zero_val))
        t_e1bd[i] = __cse_86 * t_e1bd[i]
        t_e1b[i] = __cse_86 * t_e1b[i]
    end
    for idx = c1 * hw:-1:1
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        __cse_22d = t_e1bd[idx]
        __cse_22 = t_e1b[idx]
        sbd = sbd + __cse_22d
        sb = sb + __cse_22
        b_e1abd[co] = b_e1abd[co] + __cse_22d
        b_e1ab[co] = b_e1ab[co] + __cse_22
        t_e1bd[idx] = 0.0
        t_e1b[idx] = 0.0
        for i_k = c_in * khkw:-1:1
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp1 * wp1 + (row - 1) * wp1 + col
            wi = (((co - 1) * c_in + (ci - 1)) * kh + (ki - 1)) * kw + kj
            __cse_87 = w_e1a[wi]
            xpad0bd[xi] = xpad0bd[xi] + (sb * w_e1ad[wi] + __cse_87 * sbd)
            xpad0b[xi] = xpad0b[xi] + __cse_87 * sb
            __cse_88 = xpad0[xi]
            w_e1abd[wi] = w_e1abd[wi] + (sb * xpad0d[xi] + __cse_88 * sbd)
            w_e1ab[wi] = w_e1ab[wi] + __cse_88 * sb
        end
        sbd = 0.0
        sb = 0.0
    end
    for idx = c_in * hw:-1:1
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        yi = (ci - 1) * hp1 * wp1 + ((i + pad) - 1) * wp1 + (j + pad)
        xbd[idx] = xbd[idx] + xpad0bd[yi]
        xb[idx] = xb[idx] + xpad0b[yi]
        xpad0bd[yi] = 0.0
        xpad0b[yi] = 0.0
    end
    for i = n_xpad0:-1:1
        xpad0bd[i] = 0.0
        xpad0b[i] = 0.0
    end
    zero_valbd = 0.0
    zero_valb = 0.0
    return nothing
end

function unet(x, h, w, c_in, c1, c2, c3, c_out, w_e1a, b_e1a, w_e1b, b_e1b, w_e2a, b_e2a, w_e2b, b_e2b, w_ba, b_ba, w_bb, b_bb, w_d2a, b_d2a, w_d2b, b_d2b, w_d1a, b_d1a, w_d1b, b_d1b, w_out, b_out, xpad0, t_e1, t_e1pad, skip1, p1, p1pad, t_e2, t_e2pad, skip2, p2, p2pad, t_b, t_bpad, bott, u2, cat2, cat2pad, t_d2, t_d2pad, dec2out, u1, cat1, cat1pad, t_d1, t_d1pad, dec1out, y)
    two = 2
    four = 4
    h2 = div(h, two)
    w2 = div(w, two)
    h4 = div(h, four)
    w4 = div(w, four)
    hp1 = h + 2
    wp1 = w + 2
    hp2 = h2 + 2
    wp2 = w2 + 2
    hp4 = h4 + 2
    wp4 = w4 + 2
    pad = 1
    kh = 3
    kw = 3
    khkw = kh * kw
    kh_out = 1
    kw_out = 1
    khkw_out = kh_out * kw_out
    scale = 2
    zero_val = 0.0
    c32 = c3 + c2
    c21 = c2 + c1
    hw = h * w
    hw2 = h2 * w2
    hw4 = h4 * w4
    n_xpad0 = c_in * hp1 * wp1
    n_e1_mid = c1 * hw
    n_e1_midpad = c1 * hp1 * wp1
    n_e1_out = c1 * hw
    n_p1pad = c1 * hp2 * wp2
    n_e2_mid = c2 * hw2
    n_e2_midpad = c2 * hp2 * wp2
    n_e2_out = c2 * hw2
    n_p2pad = c2 * hp4 * wp4
    n_b_mid = c3 * hw4
    n_b_midpad = c3 * hp4 * wp4
    n_b_out = c3 * hw4
    n_cat2pad = c32 * hp2 * wp2
    n_d2_mid = c2 * hw2
    n_d2_midpad = c2 * hp2 * wp2
    n_d2_out = c2 * hw2
    n_cat1pad = c21 * hp1 * wp1
    n_d1_mid = c1 * hw
    n_d1_midpad = c1 * hp1 * wp1
    n_d1_out = c1 * hw
    for i = 1:n_xpad0
        xpad0[i] = zero_val
    end
    for idx = 1:c_in * hw
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        yi = (ci - 1) * hp1 * wp1 + ((i + pad) - 1) * wp1 + (j + pad)
        xpad0[yi] = x[idx]
    end
    for idx = 1:c1 * hw
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        s = 0.0
        for i_k = 1:c_in * khkw
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp1 * wp1 + (row - 1) * wp1 + col
            wi = (((co - 1) * c_in + (ci - 1)) * kh + (ki - 1)) * kw + kj
            s = s + xpad0[xi] * w_e1a[wi]
        end
        t_e1[idx] = s + b_e1a[co]
    end
    for i = 1:n_e1_mid
        t_e1[i] = max(t_e1[i], zero_val)
    end
    for i = 1:n_e1_midpad
        t_e1pad[i] = zero_val
    end
    for idx = 1:c1 * hw
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        yi = (ci - 1) * hp1 * wp1 + ((i + pad) - 1) * wp1 + (j + pad)
        t_e1pad[yi] = t_e1[idx]
    end
    for idx = 1:c1 * hw
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        s = 0.0
        for i_k = 1:c1 * khkw
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp1 * wp1 + (row - 1) * wp1 + col
            wi = (((co - 1) * c1 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            s = s + t_e1pad[xi] * w_e1b[wi]
        end
        skip1[idx] = s + b_e1b[co]
    end
    for i = 1:n_e1_out
        skip1[i] = max(skip1[i], zero_val)
    end
    for idx = 1:c1 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        oi = div(rem, w2) + 1
        oj = mod(rem, w2) + 1
        i0 = 2oi - 1
        j0 = 2oj - 1
        a11 = skip1[(ci - 1) * hw + (i0 - 1) * w + j0]
        a12 = skip1[(ci - 1) * hw + (i0 - 1) * w + j0 + 1]
        a21 = skip1[(ci - 1) * hw + i0 * w + j0]
        a22 = skip1[(ci - 1) * hw + i0 * w + j0 + 1]
        m1 = max(a11, a12)
        m2 = max(a21, a22)
        p1[idx] = max(m1, m2)
    end
    for i = 1:n_p1pad
        p1pad[i] = zero_val
    end
    for idx = 1:c1 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        yi = (ci - 1) * hp2 * wp2 + ((i + pad) - 1) * wp2 + (j + pad)
        p1pad[yi] = p1[idx]
    end
    for idx = 1:c2 * hw2
        idxm1 = idx - 1
        co = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        s = 0.0
        for i_k = 1:c1 * khkw
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp2 * wp2 + (row - 1) * wp2 + col
            wi = (((co - 1) * c1 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            s = s + p1pad[xi] * w_e2a[wi]
        end
        t_e2[idx] = s + b_e2a[co]
    end
    for i = 1:n_e2_mid
        t_e2[i] = max(t_e2[i], zero_val)
    end
    for i = 1:n_e2_midpad
        t_e2pad[i] = zero_val
    end
    for idx = 1:c2 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        yi = (ci - 1) * hp2 * wp2 + ((i + pad) - 1) * wp2 + (j + pad)
        t_e2pad[yi] = t_e2[idx]
    end
    for idx = 1:c2 * hw2
        idxm1 = idx - 1
        co = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        s = 0.0
        for i_k = 1:c2 * khkw
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp2 * wp2 + (row - 1) * wp2 + col
            wi = (((co - 1) * c2 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            s = s + t_e2pad[xi] * w_e2b[wi]
        end
        skip2[idx] = s + b_e2b[co]
    end
    for i = 1:n_e2_out
        skip2[i] = max(skip2[i], zero_val)
    end
    for idx = 1:c2 * hw4
        idxm1 = idx - 1
        ci = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        oi = div(rem, w4) + 1
        oj = mod(rem, w4) + 1
        i0 = 2oi - 1
        j0 = 2oj - 1
        a11 = skip2[(ci - 1) * hw2 + (i0 - 1) * w2 + j0]
        a12 = skip2[(ci - 1) * hw2 + (i0 - 1) * w2 + j0 + 1]
        a21 = skip2[(ci - 1) * hw2 + i0 * w2 + j0]
        a22 = skip2[(ci - 1) * hw2 + i0 * w2 + j0 + 1]
        m1 = max(a11, a12)
        m2 = max(a21, a22)
        p2[idx] = max(m1, m2)
    end
    for i = 1:n_p2pad
        p2pad[i] = zero_val
    end
    for idx = 1:c2 * hw4
        idxm1 = idx - 1
        ci = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        i = div(rem, w4) + 1
        j = mod(rem, w4) + 1
        yi = (ci - 1) * hp4 * wp4 + ((i + pad) - 1) * wp4 + (j + pad)
        p2pad[yi] = p2[idx]
    end
    for idx = 1:c3 * hw4
        idxm1 = idx - 1
        co = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        i = div(rem, w4) + 1
        j = mod(rem, w4) + 1
        s = 0.0
        for i_k = 1:c2 * khkw
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp4 * wp4 + (row - 1) * wp4 + col
            wi = (((co - 1) * c2 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            s = s + p2pad[xi] * w_ba[wi]
        end
        t_b[idx] = s + b_ba[co]
    end
    for i = 1:n_b_mid
        t_b[i] = max(t_b[i], zero_val)
    end
    for i = 1:n_b_midpad
        t_bpad[i] = zero_val
    end
    for idx = 1:c3 * hw4
        idxm1 = idx - 1
        ci = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        i = div(rem, w4) + 1
        j = mod(rem, w4) + 1
        yi = (ci - 1) * hp4 * wp4 + ((i + pad) - 1) * wp4 + (j + pad)
        t_bpad[yi] = t_b[idx]
    end
    for idx = 1:c3 * hw4
        idxm1 = idx - 1
        co = div(idxm1, hw4) + 1
        rem = mod(idxm1, hw4)
        i = div(rem, w4) + 1
        j = mod(rem, w4) + 1
        s = 0.0
        for i_k = 1:c3 * khkw
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp4 * wp4 + (row - 1) * wp4 + col
            wi = (((co - 1) * c3 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            s = s + t_bpad[xi] * w_bb[wi]
        end
        bott[idx] = s + b_bb[co]
    end
    for i = 1:n_b_out
        bott[i] = max(bott[i], zero_val)
    end
    for idx = 1:c3 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        oi = div(rem, w2) + 1
        oj = mod(rem, w2) + 1
        oim1 = oi - 1
        ojm1 = oj - 1
        i = div(oim1, scale) + 1
        j = div(ojm1, scale) + 1
        xi = (ci - 1) * hw4 + (i - 1) * w4 + j
        u2[idx] = bott[xi]
    end
    for idx = 1:c3 * hw2
        cat2[idx] = u2[idx]
    end
    for idx = 1:c2 * hw2
        cat2[c3 * hw2 + idx] = skip2[idx]
    end
    for i = 1:n_cat2pad
        cat2pad[i] = zero_val
    end
    for idx = 1:c32 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        yi = (ci - 1) * hp2 * wp2 + ((i + pad) - 1) * wp2 + (j + pad)
        cat2pad[yi] = cat2[idx]
    end
    for idx = 1:c2 * hw2
        idxm1 = idx - 1
        co = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        s = 0.0
        for i_k = 1:c32 * khkw
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp2 * wp2 + (row - 1) * wp2 + col
            wi = (((co - 1) * c32 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            s = s + cat2pad[xi] * w_d2a[wi]
        end
        t_d2[idx] = s + b_d2a[co]
    end
    for i = 1:n_d2_mid
        t_d2[i] = max(t_d2[i], zero_val)
    end
    for i = 1:n_d2_midpad
        t_d2pad[i] = zero_val
    end
    for idx = 1:c2 * hw2
        idxm1 = idx - 1
        ci = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        yi = (ci - 1) * hp2 * wp2 + ((i + pad) - 1) * wp2 + (j + pad)
        t_d2pad[yi] = t_d2[idx]
    end
    for idx = 1:c2 * hw2
        idxm1 = idx - 1
        co = div(idxm1, hw2) + 1
        rem = mod(idxm1, hw2)
        i = div(rem, w2) + 1
        j = mod(rem, w2) + 1
        s = 0.0
        for i_k = 1:c2 * khkw
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp2 * wp2 + (row - 1) * wp2 + col
            wi = (((co - 1) * c2 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            s = s + t_d2pad[xi] * w_d2b[wi]
        end
        dec2out[idx] = s + b_d2b[co]
    end
    for i = 1:n_d2_out
        dec2out[i] = max(dec2out[i], zero_val)
    end
    for idx = 1:c2 * hw
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        oi = div(rem, w) + 1
        oj = mod(rem, w) + 1
        oim1 = oi - 1
        ojm1 = oj - 1
        i = div(oim1, scale) + 1
        j = div(ojm1, scale) + 1
        xi = (ci - 1) * hw2 + (i - 1) * w2 + j
        u1[idx] = dec2out[xi]
    end
    for idx = 1:c2 * hw
        cat1[idx] = u1[idx]
    end
    for idx = 1:c1 * hw
        cat1[c2 * hw + idx] = skip1[idx]
    end
    for i = 1:n_cat1pad
        cat1pad[i] = zero_val
    end
    for idx = 1:c21 * hw
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        yi = (ci - 1) * hp1 * wp1 + ((i + pad) - 1) * wp1 + (j + pad)
        cat1pad[yi] = cat1[idx]
    end
    for idx = 1:c1 * hw
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        s = 0.0
        for i_k = 1:c21 * khkw
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp1 * wp1 + (row - 1) * wp1 + col
            wi = (((co - 1) * c21 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            s = s + cat1pad[xi] * w_d1a[wi]
        end
        t_d1[idx] = s + b_d1a[co]
    end
    for i = 1:n_d1_mid
        t_d1[i] = max(t_d1[i], zero_val)
    end
    for i = 1:n_d1_midpad
        t_d1pad[i] = zero_val
    end
    for idx = 1:c1 * hw
        idxm1 = idx - 1
        ci = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        yi = (ci - 1) * hp1 * wp1 + ((i + pad) - 1) * wp1 + (j + pad)
        t_d1pad[yi] = t_d1[idx]
    end
    for idx = 1:c1 * hw
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        s = 0.0
        for i_k = 1:c1 * khkw
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw) + 1
            rem2 = mod(kseqm1, khkw)
            ki = div(rem2, kw) + 1
            kj = mod(rem2, kw) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hp1 * wp1 + (row - 1) * wp1 + col
            wi = (((co - 1) * c1 + (ci - 1)) * kh + (ki - 1)) * kw + kj
            s = s + t_d1pad[xi] * w_d1b[wi]
        end
        dec1out[idx] = s + b_d1b[co]
    end
    for i = 1:n_d1_out
        dec1out[i] = max(dec1out[i], zero_val)
    end
    for idx = 1:c_out * hw
        idxm1 = idx - 1
        co = div(idxm1, hw) + 1
        rem = mod(idxm1, hw)
        i = div(rem, w) + 1
        j = mod(rem, w) + 1
        s = 0.0
        for i_k = 1:c1 * khkw_out
            kseqm1 = i_k - 1
            ci = div(kseqm1, khkw_out) + 1
            rem2 = mod(kseqm1, khkw_out)
            ki = div(rem2, kw_out) + 1
            kj = mod(rem2, kw_out) + 1
            row = (i + ki) - 1
            col = (j + kj) - 1
            xi = (ci - 1) * hw + (row - 1) * w + col
            wi = (((co - 1) * c1 + (ci - 1)) * kh_out + (ki - 1)) * kw_out + kj
            s = s + dec1out[xi] * w_out[wi]
        end
        y[idx] = s + b_out[co]
    end
end
